### ISSUE TITLE
memory leak after repeating "record and stop" several times

### ISSUE THREAD

**Issue by shenchenxh** [rrweb-io/rrweb#100]
Code

```
const test = () => {
  const stopFn = rrweb.record({
    emit() {
      stopFn!();
    }
  });
};

setInterval(() => {
  test();
}, 500);
```

执行上面的代码会产生内存泄漏

Chrome memory 的 timeline, 展示如下，可以看到momory一直没有释放
<img width="1680" alt="屏幕快照 2019-07-24 下午7 13 09" src="https://user-images.githubusercontent.com/3212000/61789408-37960380-ae47-11e9-92dc-c19ea8884a16.png">

**Comment by Yuyz0112** [comment]
@shenchenxh Thanks for the report and patch.
