### ISSUE TITLE
[Bug]: 使用console插件，无法播放数据

### ISSUE THREAD

**Issue by Huhui-coder** [rrweb-io/rrweb#1019]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/rrweb-io/rrweb/issues) for a bug report that matches the one I want to file, without success.

### What package is this bug report for?

rrweb

### Version

^2.0.0-alpha.2

### Expected Behavior

控制台播放数据

### Actual Behavior

控制台未正常播放数据

### Steps to Reproduce

使用配置代码为：
录制：
rrweb.record({
  emit: function emit(event) {
    // 如果要使用console来输出信息，请使用如下的写法
    const defaultLog = console.log['__rrweb_original__']
      ? console.log['__rrweb_original__']
      : console.log;
    defaultLog(event);
  },
  // 使用默认的配置选项
  plugins: [rrweb.getRecordConsolePlugin()],
});
播放：
const replayer = new rrweb.Replayer(events, {
  plugins: [
    rrweb.getReplayConsolePlugin({
      level: ['info', 'log', 'warn', 'error'],
    }),
  ],
});
replayer.play();

### Additional Information

使用的依赖包版本号为：
    "rrweb": "^2.0.0-alpha.2",
    "rrweb-player": "^1.0.0-alpha.3",
    
    通过打印播放的 events, 发现是 有 console 数据的。
    
![image](https://user-images.githubusercontent.com/37322200/194813701-b129b34d-6bd5-465d-92db-fdd006af910c.png)

**Comment by Mark-Fenng** [comment]
能否够提供一下出问题的events
