### ISSUE TITLE
base64 导致数据庞大

### ISSUE THREAD

**Issue by moweng** [rrweb-io/rrweb#103]
你们有没有遇到过如果项目图片链接用 base64 或者样式引用了 字体文件，序列化之后 数据会很庞大，这种情况可以怎么解决  @Yuyz0112

**Comment by Yuyz0112** [comment]
@moweng HTML 内的 base64 目前没有太好的方法，样式内的话可以试一下这个 option https://github.com/rrweb-io/rrweb/blob/master/src/record/index.ts#L44
```
inlineStylesheet: false
```

这样不会把 remote CSS 样式 inline 化，不过需要自行保证 remote CSS 在回放时可访问（跨域、相对路径等问题）。

后续可能会提供 assets URL 替换功能。

**Comment by moweng** [comment]
assets URL 是指将这些文件上传到你们的服务器或者七牛云之类的，在回放时通过外联的方式引用吗
