### ISSUE TITLE
[Bug]: issue with webgl record & replay

### ISSUE THREAD

**Issue by JasonBoy** [rrweb-io/rrweb#1030]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/rrweb-io/rrweb/issues) for a bug report that matches the one I want to file, without success.

### What package is this bug report for?

rrweb

### Version

v1.1.3

### Expected Behavior

record and replay the webgl(with three.js demo), start recording when page loaded or some time later in page, should replay webgl correctly

### Actual Behavior

- [ok]: start record immediately when page loading, which is ok when replaying the webgl
- [not ok]: start record after some time in page, the replay canvas shows white canvas when replay(other normal canvas replay is ok, only the canvas using webgl), and console shows some errors when replay, the demo is using the [three.js demo in readme](https://github.com/mrdoob/three.js#usage)
![image](https://user-images.githubusercontent.com/2911620/196408027-683257b4-d938-4b1e-8b94-bd62e9b4ab39.png)

### Steps to Reproduce

manually trigger record after some time(after webgl initialized in page ui) in the page

**Comment by vlazdimir** [comment]
Same issue with newest   `2.0.0-alpha.3` rrweb version.

**Comment by Juice10** [comment]
This is unfortunately a limitation of webgl recording, once we miss the first couple webgl events replays are broken. To get around this there is another recording strategy you can use which does work on canvas elements already in the DOM at recording time, and that is using the sample config.

```js
rrweb.record({
  emit(event) {},
  recordCanvas: true,
  sampling: {
    canvas: 15,
  },
});
```
See https://github.com/rrweb-io/rrweb/blob/master/docs/recipes/canvas.md for more info
