### ISSUE TITLE
[Observer] Observer doesn't watch for CSSStyleSheet.insertRule

### ISSUE THREAD

**Issue by VladimirMilenko** [rrweb-io/rrweb#104]
Currently, it is impossible to track calls to insertRule(which is used in CSS-in-JS libraries).
With this, it's impossible to get the styles, which are added dynamically during render phase.

I believe this can be solved by proxying calls  to `styleElement.sheet.addRule/insertRule`

**Comment by VladimirMilenko** [comment]
I was able to do this in following way:

```
  handleStyleRoot = styleRoot => {
    const handler = {
      apply: function apply(target, thisArg, argumentsList) {
        const result = target.apply(thisArg, argumentsList);
        styleRoot.innerHTML = Array.from(thisArg.rules, x => x.cssText).join('\n');

        styleRoot.sheet.insertRule = new Proxy(styleRoot.sheet.insertRule, handler);

        return result;
      }
    };
    const proxy = new Proxy(styleRoot.sheet.insertRule, handler);
    styleRoot.sheet.insertRule = proxy;
    styleRoot.sheet.insertRule('.rr_track_on {}');
  };
```

**Comment by jperl** [comment]
@VladimirMilenko where did you put this code?

**Comment by jperl** [comment]
@Yuyz0112 @VladimirMilenko If you have guidance on how to add support for this, I would be happy to work on submitting a PR.

**Comment by dacort** [comment]
Is this the same as #58 ?
