### ISSUE TITLE
[Bug]: ReferenceError: exports is not defined in ES module scope

### ISSUE THREAD

**Issue by hosamChung** [rrweb-io/rrweb#1056]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/rrweb-io/rrweb/issues) for a bug report that matches the one I want to file, without success.

### What package is this bug report for?

rrweb

### Version

"rrweb": "^2.0.0-alpha.4",

### Expected Behavior

To start recording when the page is loaded.

### Actual Behavior

![image](https://user-images.githubusercontent.com/107183787/203896615-e9c78764-d554-41e6-908b-c964d024b52a.png)

### Steps to Reproduce

https://stackblitz.com/edit/next-typescript-nfhzmu?file=pages%2Findex.tsx

### Additional Information

    "next": "^12.3.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "rrweb": "^2.0.0-alpha.4",

**Comment by fbiere** [comment]
Same issue here, just with Vue 3 / Nuxt instead.

@hosamChung did you end up figuring anything out?

**Comment by hosamChung** [comment]
Hi @fbiere, I ended up using "rrweb": "^1.1.3" and updated the rrweb-player to the latest version. Because all I wanted for now is to get access to the player destroyer function. So this is my current workaround and "rrweb": "^1.1.3" does not cause any error.

**Comment by fbiere** [comment]
Works for me. Thank you! 🚀

**Comment by Mark-Fenng** [comment]
Thanks for your report. This will be fixed in the next publish.
