### ISSUE TITLE
[Feature Request]: Changelog for v2?

### ISSUE THREAD

**Issue by mydea** [rrweb-io/rrweb#1059]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/rrweb-io/rrweb/issues) for a feature request that matches the one I want to file, without success.

### What package is this feature request for?

rrweb

### Problem Description

It would be great to have some kind of changelog for v2 (alpha.X). I'd love to try it out, but as of now it is very hard to know what to look out for, what is breaking, ...

### Proposed Solution

Add v2 alpha releases to CHANGELOG.md or add Release in Github with some information on what changed.

### Alternatives Considered

I am of course aware that v2 is still alpha, and thus it's up to myself to update. It's just that I'd love to try it and give feedback on v2, but that's a bit hard to do without any type of changelog.

Figuring out what changed by looking at the git history is also extremely hard, as _so many_ things have been touched: https://github.com/rrweb-io/rrweb/compare/rrweb%401.1.3..rrweb%402.0.0-alpha.4

**Comment by Juice10** [comment]
Totally agree we are missing a changelog, I went ahead and marked all of the merged pull requests for 2.0: https://github.com/rrweb-io/rrweb/pulls?q=is%3Apr+is%3Aclosed+label%3A2.0

**Comment by YunFeng0817** [comment]
Completed by https://github.com/rrweb-io/rrweb/pull/1119
