### ISSUE TITLE
单页页面切换页面，回放异常

### ISSUE THREAD

**Issue by moweng** [rrweb-io/rrweb#106]
The node before which the new node is to be inserted is not a child of this node

![image](https://user-images.githubusercontent.com/8938428/62354637-f0db9400-b53f-11e9-8656-73b011a89b94.png)

这种情况有遇到过？
@Yuyz0112

**Comment by Yuyz0112** [comment]
需要提供 events debug 一下。另外用的 rrweb 版本是 0.7.18 吗？

**Comment by Yuyz0112** [comment]
Please feel free to reopen this with any further debug info.
