### ISSUE TITLE
请问rrweb可以实现插件的形式吗，输入网址进行录制[Bug]: 

### ISSUE THREAD

**Issue by zhangqingrui-creater** [rrweb-io/rrweb#1061]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/rrweb-io/rrweb/issues) for a bug report that matches the one I want to file, without success.

### What package is this bug report for?

rrweb

### Version

v1.1

### Expected Behavior

请问rrweb可以实现插件的形式吗，输入网址进行录制

### Actual Behavior

请问rrweb可以实现插件的形式吗，输入网址进行录制

### Steps to Reproduce

请问rrweb可以实现插件的形式吗，输入网址进行录制

### Additional Information

请问rrweb可以实现插件的形式吗，输入网址进行录制

**Comment by Juice10** [comment]
Could you provide us with some more information on what you are trying to accomplish?
