### ISSUE TITLE
[Bug]: iframe can't load

### ISSUE THREAD

**Issue by zhaobosky** [rrweb-io/rrweb#1064]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/rrweb-io/rrweb/issues) for a bug report that matches the one I want to file, without success.

### What package is this bug report for?

rrweb

### Version

v.2.0.0

### Expected Behavior

iframe can load

### Actual Behavior

open a page has iframe inside, iframe load failed

### Steps to Reproduce

1、live mode 
2、open page http://gjkj.mwr.gov.cn/jsjd1/bzcx/
3、<img width="972" alt="image" src="https://user-images.githubusercontent.com/22151144/205274178-2f90ff00-aa4a-41e5-9674-f4cb663c6dfb.png">

iframe is empty

**Comment by Mark-Fenng** [comment]
This iframe is actually a cross-origin iframe so its recording is not built in. @Juice10 You are right about this issue. This website seems not to be available beyond the mainland area and I made some effort to load it.
![image](https://user-images.githubusercontent.com/27533910/205295939-6d816afb-0da0-4a93-a014-65fc5860bc21.png)
