### ISSUE TITLE
[Bug]: Replayer Exception - mutation Failed to execute 'insertBefore' on 'Node': Only one doctype on document allowed

### ISSUE THREAD

**Issue by pdwittig** [rrweb-io/rrweb#1065]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/rrweb-io/rrweb/issues) for a bug report that matches the one I want to file, without success.

### What package is this bug report for?

rrweb

### Version

2.0.0-alpha.4

### Expected Behavior

The recording should replay as recorded without erroring out

### Actual Behavior

**Important** This session recording contains an rrweb player in it. Everything works as expected until I rewind the player and re-play. I susepect the rewind (and thus the rebuild to seek to that point) causes this issue.

This error is thrown:
[replayer] Exception in mutation Failed to execute 'insertBefore' on 'Node': Only one doctype on document allowed. 

And it is following by many of these (for various nodes):
[replayer] Node with id '1542' not found. 

### Steps to Reproduce

If you load these events in a player and play, the exceptions should be visible in the console.

Events: https://gist.github.com/pdwittig/2f6134ca10c5e19c0b888ff9912a8d77

I tried loading these events into https://rrwebdebug.com, but it sits in a perpetual loading state.

Let me know if I can provide any additional info to help out!

### Testcase Gist URL

https://rrwebdebug.com/play/index.html?url=https%3A%2F%2Fgist.github.com%2Fpdwittig%2F2f6134ca10c5e19c0b888ff9912a8d77&version=1.0.0-alpha.4&play=on

**Comment by bhavitsharma** [comment]
Yeah, this is our fix as well and additionally we've also resetted the virtual dom

**Comment by pdwittig** [comment]
Yes. @alexfullview + @bhavitsharma. That is helpful. This might be a stupid question, but as these issues sit unmerged, do you just use your own updated forks?

**Comment by bhavitsharma** [comment]
Yep, there are quite a lot of fixes that we've made that we'd like to contribute here but haven't found the time. Maybe we should open source our fork soon

**Comment by pdwittig** [comment]
Thanks, @bhavitsharma. And ya, that would be great, if you found the time.
