### ISSUE TITLE
[Bug]: recordCrossOriginIframes: true does not work with pack/unpack fn

### ISSUE THREAD

**Issue by thatsnotright** [rrweb-io/rrweb#1077]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/rrweb-io/rrweb/issues) for a bug report that matches the one I want to file, without success.

### What package is this bug report for?

rrweb

### Version

latest from master

### Expected Behavior

I expect recordCrossOriginIframes will show iframe content when injected in to all iframes, with a pack/unpackfn specified.

### Actual Behavior

The mutations are captured for iframes but not processed unless I remove the packFn.  If I specify a packFn for only the top-level rrweb this also works, so it's just in the child to parent messaging that the packFn causes this behavior.

### Steps to Reproduce

Use the repl to get an IFrame site, and then add a packFn and see that it no longer renders cross-domain IFrame content.

I have an idea where to fix this that I'm looking at locally and I can submit a PR if I fix this behavior before anyone else does.

**Comment by Juice10** [comment]
Looks like rrweb should disable packing out of the box for inter-iframe communication, then you wouldn't bump into this issue
