### ISSUE TITLE
[Bug]: rrweb 2.0.0 not compatible with 1.x ?

### ISSUE THREAD

**Issue by krneticz** [rrweb-io/rrweb#1082]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/rrweb-io/rrweb/issues) for a bug report that matches the one I want to file, without success.

### What package is this bug report for?

rrweb

### Version

2.0.0 - alpha

### Expected Behavior

In our project, we are using syncit and rrweb (latest 1.x) to enable remote control (live mode) of the website. We have updated rrweb to the latest 2.0.0-alpha4, and expected it to work as it was with 1.x, but it's not. 

### Actual Behavior

Since the update to 2.x we are noticing that remote viewing and control sessions are starting as usual and original content is properly mirrored, but scrolling does not reflect on the viewing side, and none of the remote actions is working. 

**So, my question is: is rrweb 2.x supposed to be compatible with 1.x without code changes?**

I understand that 2.x is is still alpha so that might be the reason for the described behaviour.

### Steps to Reproduce

Update rrweb from 1.x to the latest 2.x alpha.

**Comment by Juice10** [comment]
Hi @krneticz thanks for opening the issue.
rrweb 2.0.0 is supposed to be backwards compatible with 1.x with regards to event playback. However there are some exposed APIs which have changed including the Mirror, currently syncit is still using the deprecated `mirror`: https://github.com/Yuyz0112/syncit/blob/16213b732f67923597439c8a6446519d57462800/packages/ui/src/Embed.svelte#L217

This should be switched to the new `getMirror` api and then it should start working again

**Comment by krneticz** [comment]
@Juice10 thanks for replying! Can you please elaborate bit more about what exactly need to be changed, or point me to the documentation where it's described. Beside "Mirror" change, what else needs change? Thanks!

**Comment by Juice10** [comment]
@krneticz check out this commit, https://github.com/rrweb-io/rrweb/commit/52cbbdaf5669740cc7d417db3551502c25b22b36
It replaces the old mirror api with the new getMirror api. Which is what also needs to happen in syncit

**Comment by krneticz** [comment]
@Juice10 I see in that commit "rrweb 1.0 use new getMirror API" that new API was already in use in 1.x. We are on 1.0.4 and upgrading to 2.x. When trying to upgrade syncit to rrweb 2.0 beta from 1.0.4 I got a reported problem in common.ts "Module '"rrweb/typings/types"' declares 'listenerHandler' locally, but it is not exported."

**Comment by Juice10** [comment]
That is indeed also something that changes in 2.0. Imports from “rrweb/typings/types” need to be replaced by “@rrweb/types” or in some cases “rrweb-snapshot”
