### ISSUE TITLE
使用rrwebPlayer播放非常卡顿，甚至无法播放

### ISSUE THREAD

**Issue by qiaoyixuan** [rrweb-io/rrweb#109]
提供一个由repl录制的视频
[replay_2019_08_05T03_38_47.txt](https://github.com/rrweb-io/rrweb/files/3465864/replay_2019_08_05T03_38_47.txt)

由于html无法上传，改为txt了，请切换注释的不同播放器查看效果

**Comment by qiaoyixuan** [comment]
提供一个由repl录制的视频
[replay_2019_08_05T03_38_47.txt](https://github.com/rrweb-io/rrweb/files/3465862/replay_2019_08_05T03_38_47.txt)
由于html无法上传，改为txt了，请切换注释的不同播放器查看效果

**Comment by qiaoyixuan** [comment]
使用默认的rrweb.Replayer播放没什么问题
使用rrwebPlayer有问题：加载时间非常长，无法点击播放按钮

**Comment by Yuyz0112** [comment]
@qiaoyixuan 应该是因为 rrweb-player 还没有更新 0.7.19 版本的 rrweb（包含了 CSS parser 的性能优化）

我刚刚 release 了 rrweb-player@0.3.15，问题应该解决了。
