### ISSUE TITLE
[Bug]: Recorder initializes very late in page load lifecycle

### ISSUE THREAD

**Issue by lazyvab** [rrweb-io/rrweb#1090]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/rrweb-io/rrweb/issues) for a bug report that matches the one I want to file, without success.

### What package is this bug report for?

rrweb

### Version

v1.1.3

### Expected Behavior

I am using RRWeb in a Chrome extension to record activity on a website. 
I inject RRWeb library in the webpage on `document_start` and call the `record()` function as soon as possible, so recording may start earliest in page load lifecycle and should not wait for complete page to load (like images). To start capturing DOM state, it should only wait for `DOMContentLoaded` event.

Along with DOM state, it should also start capturing console logs as early as possible.

### Actual Behavior

The RRWeb recorder seems to initialize only when window `load` event is fired which means the webpage has loaded completely including resources like images.

I was looking at the [source code](https://github.com/rrweb-io/rrweb/blob/master/packages/rrweb/src/record/index.ts#L578), according to which if the webpage is still in `loading` state, that is, `document.readyState="loading"`, it would wait for window `load` event which is fired after all resources have been loaded.
In my case, the whole website loads except for few images which are delayed for almost a minute and recording could not start until then.
IMHO, it should rather wait for `DOMContentLoaded` event and start observing DOM as soon as it is ready.

### Steps to Reproduce

Covered above.

**Comment by Mark-Fenng** [comment]
Thanks for your report. Could you please have a look at my fix?

**Comment by lazyvab** [comment]
@Juice10 @Mark-Fenng Thanks for working on it. Really appreciate!
To get this fix, which rrweb version I should upgrade to?

**Comment by Mark-Fenng** [comment]
The next publish possibly 2.0.0-alpha.5 will have the fix.

**Comment by lazyvab** [comment]
@Mark-Fenng Any expected timeline for 2.0.0-alpha.5? We would like to consume as soon as it is available.

**Comment by Juice10** [comment]
@lazyvab keep an eye on the pr https://github.com/rrweb-io/rrweb/pull/1119#issue-1578271194 shortly after it is merged we can do a .5 release
