### ISSUE TITLE
[Bug]: 用rrweb录制的脚本用rrvideo转成视频，时长44s的脚本转出来只有11秒，请问是啥原因？

### ISSUE THREAD

**Issue by pittQ** [rrweb-io/rrweb#1102]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/rrweb-io/rrweb/issues) for a bug report that matches the one I want to file, without success.

### What package is this bug report for?

rrweb

### Version

^2.0.0-alpha.4

### Expected Behavior

环境：
     "rrweb": "^2.0.0-alpha.4",
     "rrweb-player": "^1.0.0-alpha.4",
先用rrweb进行脚本录制，录制的脚本可以正常播放：
然后通过rrvideo命令转成视频：
命令如下： rrvideo --input F:\xxxxxx\test\data.json
结果视频区域没有转换出来，请问是怎么回事？
视频的时长也不对，只有11s
![image](https://user-images.githubusercontent.com/65379888/215635074-842a89b8-da42-45d1-b2ae-7dc5f0945825.png)

**Comment by xujiujiu** [comment]
https://github.com/rrweb-io/rrvideo/pull/26

需要修改下rrvideo
