### ISSUE TITLE
在我们的页面中通过IFrame打开三方页面，要录制和回放三方页面必须要为三方页面注入脚本吗？

### ISSUE THREAD

**Issue by ichenglixue** [rrweb-io/rrweb#1113]
在我们的页面中通过IFrame打开三方页面，要录制和回放三方页面必须要为三方页面注入脚本吗？
但三方页面在三方站点上，域名不同，我们应该是无法为三方页面所在的IFrame注入脚本的吧，rrweb还有其它解决方法吗？

大家有没有好的思路，感谢大家~~

**Comment by Mark-Fenng** [comment]
目前没有，必须给跨域页面注入脚本
