### ISSUE TITLE
[Feature Request]: npm release via GitHub actions

### ISSUE THREAD

**Issue by Juice10** [rrweb-io/rrweb#1117]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/rrweb-io/rrweb/issues) for a feature request that matches the one I want to file, without success.

### What package is this feature request for?

Other (specify below)

### Problem Description

Releases take lots of time to do and are infrequent because of it

### Proposed Solution

Automate creation of changelog
Automate publishing to npm
 - https://github.com/marketplace/actions/npm-publish

### Alternatives Considered

None yet, happy to get suggestions

**Comment by YunFeng0817** [comment]
done in #1119
