### ISSUE TITLE
[Bug]: record failed

### ISSUE THREAD

**Issue by zhaobosky** [rrweb-io/rrweb#1118]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/rrweb-io/rrweb/issues) for a bug report that matches the one I want to file, without success.

### What package is this bug report for?

rrweb

### Version

v.2.0.0 alpha4

### Expected Behavior

record.emit send correct dom data,when page load complete

### Actual Behavior

1. record.emit don't send dom data,when page load complete
2. rebuild failed in some pages

### Steps to Reproduce

1.open page ,record.emit don't send data
https://www.gmgitc.com/Bid/BidList

**Comment by zhaobosky** [comment]
https://www.gmgitc.com/Bid/BidList
https://bd.ispacechina.com/retrieve.do?typflag=1

use try catch in snapshot.ts ,the page can snapshot success

<img width="594" alt="image" src="https://user-images.githubusercontent.com/22151144/218902652-84d18105-cf89-49d3-8dab-abd526c25a3e.png">

<img width="946" alt="image" src="https://user-images.githubusercontent.com/22151144/218903030-57433677-2a55-49b4-b3d8-cd89b9f19e96.png">
<img width="561" alt="image" src="https://user-images.githubusercontent.com/22151144/218901300-19fa2298-f73b-4ed8-b37f-ac804b24073c.png">

**Comment by YunFeng0817** [comment]
After some debug, the reason is that in your demo page,  you polyfill the classList method for all HTML elements but the implementation seems to be not right. 
<img width="978" alt="image" src="https://user-images.githubusercontent.com/27533910/220096605-5c2f6325-05c3-4253-82da-678495f4b034.png">

**Comment by zhaobosky** [comment]
> After some debug, the reason is that in your demo page, you polyfill the classList method for all HTML elements but the implementation seems to be not right. <img alt="image" width="978" src="https://user-images.githubusercontent.com/27533910/220096605-5c2f6325-05c3-4253-82da-678495f4b034.png">

https://www.gmgitc.com/Bid/BidList

<img width="1277" alt="image" src="https://user-images.githubusercontent.com/22151144/220301637-874d0686-3f74-42c4-a6ff-d19e20f1b05a.png">


The list data is fetched by ajax，but rrweb don't monitor the dom changes
<img width="955" alt="image" src="https://user-images.githubusercontent.com/22151144/220303634-0161ce73-01ae-4300-ba40-8cd4ed717f95.png">
