### ISSUE TITLE
textarea标签的默认文本在播放时翻倍出现

### ISSUE THREAD

**Issue by ZITnew** [rrweb-io/rrweb#112]
页面中存在textarea标签，若是标签中有默认的文本，不改动这些默认的文本，在播放时，这些未改动的文本会翻倍出现，比如，默认文本是hello，播放时就是hellohello

**Comment by YanJie-001** [comment]
这bug也没解决啊，怎么就完成了

**Comment by eoghanmurray** [comment]
I've a new fix and test for this as part of #1351 
either [this fix](https://github.com/rrweb-io/rrweb/commit/0efe23f04acde1cdd523337eb4d8f9352387d35d) never worked, or else there was a regression since.
