### ISSUE TITLE
[Question] rrweb-player是否能够将两段视频拼接到一起？

### ISSUE THREAD

**Issue by ccchen1213** [rrweb-io/rrweb#1142]
例如：我在11:20-11:22录制了2分钟的视频，退出页面。12:20-12:23又录制了一段3分钟的视频，退出页面。
目前结果：在第一段2分钟播放完成之后静止在最后一个页面1小时，之后再播放第二段3分钟的视频，**总时长：1小时5分钟**
期望结果：播放完第一段2分钟后，继续播放第二段3分钟的视频。**总时长：5分钟**

请问大家目前有这种实现方式吗？能否做到通过rrweb-player渲染出来**总时长为5分钟**的视频，不在中间等待1小时。
或者有其他替代方式也欢迎告知我！
谢谢！

**Comment by YunFeng0817** [comment]
是可以做得到的，只需要把第一段视频的所有timestamp增加一个小时，或者把第二段视频的timestamp全部减少一个小时就可以了

**Comment by plwdxiiu** [comment]
> 是可以做得到的，只需要把第一段视频的所有timestamp增加一个小时，或者把第二段视频的timestamp全部减少一个小时就可以了

好的，了解了，感谢～ 😊

**Comment by rzechen** [comment]
实现了吗？

**Comment by ccchen1213** [comment]
> 

实现了

**Comment by ccchen1213** [comment]
> 实现了吗？

实现了！
