### ISSUE TITLE
[Bug]: Event already exists, but error cannot be played.   Uncaught (in promise) TypeError: Cannot read properties of null (reading 'timestamp') 

### ISSUE THREAD

**Issue by zhuimingdongma** [rrweb-io/rrweb#1147]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/rrweb-io/rrweb/issues) for a bug report that matches the one I want to file, without success.

### What package is this bug report for?

rrweb

### Version

2.0.0-alpha.4

### Expected Behavior

.

### Actual Behavior

.

### Steps to Reproduce

.

### Testcase Gist URL

https://cdc.testsaas.ins-box.com/#/cdc/policyVideo?recallKey=094da43a-b215-4bd0-86fe-94191e85e077

### Additional Information

.

**Comment by YunFeng0817** [comment]
I think the reason for the reason is that your events were compressed with packFn while recording.
<img width="1291" alt="image" src="https://user-images.githubusercontent.com/27533910/220000841-d527006f-1d07-4d28-a85c-2ad74eccabbe.png">
So you may also need to use unpackFn in your replayer.
<img width="1141" alt="image" src="https://user-images.githubusercontent.com/27533910/220000952-73747cad-dc19-4620-9236-bd10c20f4c08.png">
https://github.com/rrweb-io/rrweb/blob/master/guide.md

**Comment by zhuimingdongma** [comment]
> I think the reason for the reason is that your events were compressed with packFn while recording. <img alt="image" width="1291" src="https://user-images.githubusercontent.com/27533910/220000841-d527006f-1d07-4d28-a85c-2ad74eccabbe.png"> So you may also need to use unpackFn in your replayer. 

Thank you very much, but I have decompressed it, this is the source code and the txt file generated by recording during playback
https://dev-img.ins-box.com/rrweb/test/saas_347umjuh8dihh112s717ug7f8rt.txt
const genaPlayer = (data) => {
  const playEvents = data || events;
  if (playEvents.length < 2) {
    alert("请先录制");
  }

  replayer = new RrwebPlayer({
    target: document.getElementById("replaycontent"), // 可以自定义 DOM 元素
    unpackFn: rrweb.unpack, //解压数据
    // 配置项
    props: {
      events: playEvents,
      mouseTail: true,
      autoPlay: false,
    },
  });

**Comment by YunFeng0817** [comment]
I find one null value in your recorded data, I guess this is the reason of the error.
<img width="547" alt="image" src="https://user-images.githubusercontent.com/27533910/220086662-8f4448d0-9865-417b-b4f9-493217ee4cbf.png">

**Comment by zhuimingdongma** [comment]
> I find one null value in your recorded data, I guess this is the reason for the error. <img alt="image" width="547" src="https://user-images.githubusercontent.com/27533910/220086662-8f4448d0-9865-417b-b4f9-493217ee4cbf.png">

thank you very much indeed!
