### ISSUE TITLE
[Bug]: Unable to record sidebar that's injected by another chrome extension in a tab

### ISSUE THREAD

**Issue by VikramTiwari** [rrweb-io/rrweb#1151]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/rrweb-io/rrweb/issues) for a bug report that matches the one I want to file, without success.

### What package is this bug report for?

rrweb

### Version

2.0.0-alpha.5

### Expected Behavior

I am using `web-extension` from https://chrome.google.com/webstore/detail/rrweb/pdaldeopoccdhlkabbkcjmecmmoninhe?hl=en with the published extension version being 2.0.0-alpha.5.

I have another chrome extension installed: https://chrome.google.com/webstore/detail/zoominfo-reachout-b2b-con/fofjcndophjadilglgimelemjkjblgpf which injects sidebar on all the pages. You don't need an account on the extension. Go to google.com and click on the extension icon to open the sidebar.

Now start recording from the rrweb extension and do some actions on google.com and the sidebar page. Stop and replay the recording. You will see that the area of the sidebar is missing from the recording and it just has a while area instead.

This issue was originally reported on slack https://rrweb.slack.com/archives/C01BYDC5C93/p1677017450858169?thread_ts=1677015759.609419&cid=C01BYDC5C93

### Actual Behavior

I was expecting to see the sidebar's content as well as the events happening on that sidebar but I don't see anything inside that sidebar in the recorded session at all.

### Steps to Reproduce

- Ensure you have both rrweb extension as well as zoominfo extension.
- Go to google.com and click on the zoominfo extension so that it's sidebar is in the page
- Now record a new session and replay it to see the behaviour.

Replay screenshot with missing sidebar content and events:
<img width="1268" alt="Screenshot 2023-02-21 at 2 10 25 PM" src="https://user-images.githubusercontent.com/1330677/220479624-93b53a0d-c5bd-48ba-8b50-204caeb03f82.png">

**Comment by YunFeng0817** [comment]
I looked into this carefully. I find that iframes created by other extensions are different from those in normal web pages. Chrome doesn't allow to inject content scripts into these iframes . So I think it's impossible to record elements created by other extensions.
