### ISSUE TITLE
[Bug]: Seeking repeatedly crashes chrome tab (when using virtual dom)

### ISSUE THREAD

**Issue by pdwittig** [rrweb-io/rrweb#1160]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/rrweb-io/rrweb/issues) for a bug report that matches the one I want to file, without success.

### What package is this bug report for?

rrweb

### Version

2.0.0-alpha.5

### Expected Behavior

I am able to seek without chrome tab crashing

### Actual Behavior

Using the latest alpha version, with `useVirtualDom: true`, when I scrub around (drag progress bar or click seek forward or backward repeatedly, which calls `player.play(time)`) my chrome tab crashes with error code 5.

If I set `useVirtualDom: false` and scrub the tab **does not** crash.

Additionally, if I bump down to `2.0.0-alpha.4` I am **not able** to reproduce the bug with or without virtual DOM enabled.

This happens for every recording I play in my player, so I have not included a test set of events.

Additionally, I'm not really great at debugging these sort of issues, but I did run the chrome profiler, and it looks like it could be some sort of memory leak?
<img width="751" alt="image" src="https://user-images.githubusercontent.com/2209014/221988221-f09b777c-387e-4068-80bd-1cccd9f8f0a3.png">

Let me know if I can provide any additional information to help debug. Thanks!

### Steps to Reproduce

See above

**Comment by Code-Crash** [comment]
I'm also facing this issue in `2.0.0-alpha.5`. 

The attached image shows its `CPU usage` is at 100% and `JS heap size` is more than 1GB.

<img width="721" alt="Screenshot 2023-03-08 at 12 13 31 PM" src="https://user-images.githubusercontent.com/5871757/223638919-5bf4c4a9-6257-406a-b5bd-45fed066799f.png">

**Comment by YunFeng0817** [comment]
I've fixed this bug in #1139, @Juice10  could you please review my code these days? This issue is urgent I think.

**Comment by YunFeng0817** [comment]
2.0.0-alpha.6 is available with the fix.

**Comment by Code-Crash** [comment]
Thank @YunFeng0817, it's working now.
