### ISSUE TITLE
Something Wrong in 0.7.20

### ISSUE THREAD

**Issue by shawandshaw** [rrweb-io/rrweb#117]
some errors occur when doing as the demo in the guide with version 0.7.20, when I change it back to 0.7.19, everything turns ok

![image](https://user-images.githubusercontent.com/32030495/62830399-f53f3580-bc40-11e9-9755-140eb6f378b7.png)
![image](https://user-images.githubusercontent.com/32030495/62830403-fbcdad00-bc40-11e9-9950-8c2ccac20b70.png)
![image](https://user-images.githubusercontent.com/32030495/62830404-00926100-bc41-11e9-9be6-dc242d646e30.png)

**Comment by Yuyz0112** [comment]
@shawandshaw sorry about that. Just released `0.7.21` to hotfix the problem.
