### ISSUE TITLE
rrwebRecord seems unusable since 0.7.19

### ISSUE THREAD

**Issue by xavier-heysch** [rrweb-io/rrweb#118]
Since the release [0.7.19](https://github.com/rrweb-io/rrweb/releases/tag/0.7.19), It seems that the function rrwebRecord is unusable.

I was using the 0.7.17 for few months, and I have tried to use the last release. Neither the 0.7.19, 0.7.20 and 0.7.21, are working.

I have tried to find a cause and a workaround, without success for now.

In the builded / minified files, there is a notable difference:

0.7.17:
<img width="1396" alt="Screen Shot 2019-08-12 at 14 12 56" src="https://user-images.githubusercontent.com/7370867/62864207-60553e80-bd0b-11e9-9ee5-955006b2bef3.png">

0.7.21:
<img width="1415" alt="Screen Shot 2019-08-12 at 14 13 05" src="https://user-images.githubusercontent.com/7370867/62864213-6519f280-bd0b-11e9-9d99-5d2bd5af5b68.png">

As you can see, the old file is starting with `var rrwebRecord=function(){` and the new file is starting with `var rrwebRecord=function(e){`. 

I don't know how to bypass this problem and use the last rrwebRecord function.

Is someone have an idea?

**Comment by Yuyz0112** [comment]
That's my fault, feeling sad for that:(

The custom event feature introduces a breaking change to the rrwebRecord bundle. I have reverted the patch and will release it in 0.8.0.

**Comment by Yuyz0112** [comment]
I think 0.7.22 fixed it.
