### ISSUE TITLE
[Question]: Do I need to Remove events in liveMode?

### ISSUE THREAD

**Issue by hzq8147** [rrweb-io/rrweb#1195]
In livemode, i always do addevents(),i watch getMetaData().totalTime is always been bigger.
is there any api to remove events?or need i remove ？

**Comment by Juice10** [comment]
As far as I know there isn't a way to remove events in live mode (or in general), if you're running into performance issues you could wait for a new full snapshot and drop the whole player and start a new one, that should clean up most memory issues if you're having any.

**Comment by hzq8147** [comment]
thx for u help ,i'll try it if i have a memory issue.

> As far as I know there isn't a way to remove events in live mode (or in general), if you're running into performance issues you could wait for a new full snapshot and drop the whole player and start a new one, that should clean up most memory issues if you're having any.
