### ISSUE TITLE
rrweb replay error

### ISSUE THREAD

**Issue by lamtungthien** [rrweb-io/rrweb#121]
Hello , when I record I have some problem.
![image](https://user-images.githubusercontent.com/29231119/63146095-f8149e80-c023-11e9-81d6-a0ac4c175d64.png)
![image](https://user-images.githubusercontent.com/29231119/63146130-15e20380-c024-11e9-942a-b2abb26df99d.png)

**Comment by Yuyz0112** [comment]
Could you provide the events log?

**Comment by lamtungthien** [comment]
this is my events log 
[367.zip](https://github.com/rrweb-io/rrweb/files/3509690/367.zip)
![image](https://user-images.githubusercontent.com/29231119/63169615-7c394700-c061-11e9-97a5-c9a6a54472ce.png)

**Comment by Yuyz0112** [comment]
@lamtungthien Sorry I could not reproduce the problem. Are you using version `0.7.23`？

**Comment by lamtungthien** [comment]
@Yuyz0112  hello
In record side, I use:
<script  src="https://cdn.jsdelivr.net/npm/rrweb@latest/dist/rrweb.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/rrweb@latest/dist/rrweb.min.css" />
In replay side, I use:
<script src="https://cdn.jsdelivr.net/npm/rrweb@latest/dist/rrweb.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/rrweb-player@latest/dist/index.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/rrweb@latest/dist/rrweb.min.css" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/rrweb-player@latest/dist/style.css

**Comment by lamtungthien** [comment]
Hello @Yuyz0112 
In record side, I use:
<script src="https://cdn.jsdelivr.net/npm/rrweb@latest/dist/rrweb.min.js"></script> 
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/rrweb@latest/dist/rrweb.min.css" />
In replay side, I use: 
<script src="https://cdn.jsdelivr.net/npm/rrweb@latest/dist/rrweb.min.js"></script> 
<script src="https://cdn.jsdelivr.net/npm/rrweb-player@latest/dist/index.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/rrweb-player@latest/dist/style.css
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/rrweb@latest/dist/rrweb.min.css

**Comment by lamtungthien** [comment]
@Yuyz0112  , sorry for this annoyed, I found this problem. In the Replay  side, I changed version **0.3.14** instead of lastest for rrweb-player. So, I thought problem #67 should change version. Thank for watching my error ^^
