### ISSUE TITLE
[Bug]: rrweb-player实例对象里没有destroy这个方法啊?!

### ISSUE THREAD

**Issue by yaoyuanrong** [rrweb-io/rrweb#1213]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/rrweb-io/rrweb/issues) for a bug report that matches the one I want to file, without success.

### What package is this bug report for?

rrweb-player

### Version

 "rrweb-player": "^0.7.14",

### Expected Behavior

我感觉应该是有destroy这个方法的

### Actual Behavior

![image](https://user-images.githubusercontent.com/46862208/235031486-2f31fd34-c888-4ffe-a0b2-7672be83abbc.png)

### Steps to Reproduce

按最新包直接就能重现

**Comment by YunFeng0817** [comment]
[rrweb-player@2.0.0-alpha.8](https://github.com/rrweb-io/rrweb/releases/tag/rrweb-player%402.0.0-alpha.8)
在这个版本中会有destroy方法
