### ISSUE TITLE
[Question] How to implement voice recording?

### ISSUE THREAD

**Issue by buremba** [rrweb-io/rrweb#122]
We're looking for a way to use rrweb for recording the screencast of our app but since it doesn't support voice recording (or synchronizing a pre-recorded mp3 with the player) we probably implement it on our own or find a workaround.

What would be the easiest way to use rrweb for this use-case? Can someone point some of the parts in the codebase so that we can start playing with it?

**Comment by Yuyz0112** [comment]
Do not have experience in this usage case but I think "synchronizing a pre-recorded mp3 with the player" is possible.

Currently, the player exposes some [events](https://github.com/rrweb-io/rrweb/blob/master/guide.md#events), maybe you can control the audio to sync with these events.

**Comment by remisharrock** [comment]
Hi, I would love to have this feature implemented. Here are some details.
Asciinema had the same kind of issue here https://github.com/asciinema/asciinema/issues/256 
https://github.com/asciinema/asciinema-server/issues/63 
Also our team developped Codecast that has an audio recorder synchronized with an online code editor here https://github.com/France-ioi/codecast 
Looks like the solution they found for asciinema is to mimick HTMLVideoElement, as explained here https://github.com/asciinema/asciinema-player#controlling-the-player-programmatically

**Comment by buremba** [comment]
I would love to implement this feature but since I don't have enough time, I just went with the easy way which is basically recording the screen as a video. I don't have plans to work on it in a near time so feel free to take it if you wish. Sorry. :(

**Comment by remisharrock** [comment]
Any news on that ?
Mimicking or doing the same interface as HTMLVideoElement would be really nice, what do you think ? (See above)

**Comment by buremba** [comment]
I'm not working on this issue since I don't have enough time but I still think that the idea is cool. :)

**Comment by lucked** [comment]
hey any update about this? can u share the code? @buremba

**Comment by buremba** [comment]
@lucked Unfortunately I don't have any prototype or snippet.

**Comment by Yuyz0112** [comment]
Please reopen this if anyone would like to work on this all share some prototype.

**Comment by remisharrock** [comment]
dear @Yuyz0112 we are working on that with @lubenard and will suggest a prototype soon

**Comment by data-harmonization** [comment]
Hi @remisharrock, I was wondering you could share an update. Looking very much forward to this feature

**Comment by kasperkamperman** [comment]
I'm interested in this. Is it possible to record and replay with an "external timer"? In this case the audiorecorder/player (playhead position) can provided the timing. You could than pause/play with the audiorecorder and rrweb stays in sync. 

Would this be something to do with a plugin? Or to implement with the snapshot part of rrweb? 

Any thoughts or pointers would be welcome.
