### ISSUE TITLE
webssh可以录制，但回放时无内容

### ISSUE THREAD

**Issue by leffss** [rrweb-io/rrweb#123]
### 录制：
![1](https://user-images.githubusercontent.com/49055524/63243131-37ddbf00-c28c-11e9-94a1-68c84d5eaa0e.PNG)

### 回放：
![2](https://user-images.githubusercontent.com/49055524/63243133-38765580-c28c-11e9-9f25-65dbe24d6612.PNG)

我的项目： https://github.com/leffss/devops

**Comment by Yuyz0112** [comment]
xterm 的 DOM 模式应该可以正常支持了，canvas 模式不建议用 rrweb 录制，最好直接录制 xterm 的输入输出

**Comment by Huhui-coder** [comment]
> xterm 的 DOM 模式应该可以正常支持了，canvas 模式不建议用 rrweb 录制，最好直接录制 xterm 的输入输出

 怎么录制 xterm 的输入输出呀
