### ISSUE TITLE
canvas in iframe not recorded correctly

### ISSUE THREAD

**Issue by davidleon** [rrweb-io/rrweb#1233]
the iframe is recorded. though the iframe canvas doesn't inherit the setting from main frame. the iframe canvas is not recorded as expecte. it's not cross origin content.

**Comment by davidleon** [comment]
the issue is actually the canvas in iframe not correctly recorded corresponding to the sampling setting. e.g. 15/sec, while the replay canvas doesn't change

**Comment by PasserbyFluid** [comment]
may I Copy your code？
