### ISSUE TITLE
Docker Container 中运行时出现中文乱码

### ISSUE THREAD

**Issue by dusty-cjh** [rrweb-io/rrweb#1240]
## 环境
* 本地 MacOS 2020 M1 chip
* Docker Container node:19

## 问题描述
* 在本地编译安装 rrweb，然后使用 rrvideo 导出视频，没有任何问题。
* 在 docker container 中安装 rrweb，然后使用 rrvideo 导出视频，发现中文乱码。

## Dockerfile

```dockerfile
FROM node:19

WORKDIR /app

# install browser
RUN apt-get update && apt install chromium -y

# clone rrweb
RUN git clone https://github.com/rrweb-io/rrweb.git
WORKDIR /app/rrweb
RUN yarn install
RUN npm run build:all
RUN chmod +x /app/rrweb/packages/rrvideo/build/cli.js

CMD ["/app/rrweb/packages/rrvideo/build/cli.js", "--input",  "/data/event.json", "--output", "/data/output.mp4"]
```

## 导出视频

注意⚠️： 图中并没有中文，可见的中文其实都是图片

![image](https://github.com/rrweb-io/rrweb/assets/45847340/6d73a528-5459-4282-8ded-3518f9ef6607)

## 问题

想请问下大佬们：

* 这个错误一般是由什么引起的呢？
* 如何优雅地进行排错？目前我没有 debug 的思路了😂，而且因为是在 docker container 中运行，所以也没法看到具体浏览器的报错

**Comment by YunFeng0817** [comment]
这个错误应该是由于在container中的chromium 缺失了一些font库，你可能需要在dockerfile中安装更多的依赖，例如可以参考 https://dev.to/cloudx/how-to-use-puppeteer-inside-a-docker-container-568c
