### ISSUE TITLE
[Question] Release schedule

### ISSUE THREAD

**Issue by shivam-thatch** [rrweb-io/rrweb#1244]
Hi there! Is there a release cadence for rrweb? I'd like to bump the version in my application to include #846, but I see that 2.0.0-alpha.9 hasn't yet been released so I'm not yet able to. Thanks!

**Comment by Juice10** [comment]
Hey @shivam-thatch, alpha.9 was released: https://github.com/rrweb-io/rrweb/releases/tag/rrweb%402.0.0-alpha.9

We currently don't have an official release schedule unfortunately
