### ISSUE TITLE
[Bug]:使用了原生HTML的select标签在回放过程中option选项为什么是看不到的

### ISSUE THREAD

**Issue by shenjianzch** [rrweb-io/rrweb#1245]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/rrweb-io/rrweb/issues) for a bug report that matches the one I want to file, without success.

### What package is this bug report for?

rrweb

### Version

2.0.0-alpha.8

### Expected Behavior

应该在回放中也能看到select的option选项，然后使用了element-ui库的组件，比如我使用了el-checkbox，在录制过程中我选择了它，但是在回放中并不存在

### Actual Behavior

回放过程中都无显示

### Steps to Reproduce

使用element-ui库的el-checkbox组件尝试或者使用select+option原生html元素也是不能在回放中显示

### Additional Information

![WX20230629-193749](https://github.com/rrweb-io/rrweb/assets/7286498/39604916-afb9-4412-a61e-8e26bd2cb83f)

**Comment by Juice10** [comment]
Thanks for submitting, this is a duplicate of https://github.com/rrweb-io/rrweb/issues/457
