### ISSUE TITLE
Sentry potentially violating copyright license

### ISSUE THREAD

**Issue by LewisW** [rrweb-io/rrweb#1248]
Hi, I'm not sure if you have a special agreement with Sentry but [it looks like they have forked your work, removed your license and then are claiming your work as their own copyright](https://github.com/getsentry/rrweb/pull/18/files).

Sorry if I've missed some kind of special agreement between you two, but I figured I would bring it to your attention in case they are indeed violating your license.

**Comment by Juice10** [comment]
Thanks for reporting this @LewisW, and thanks to @chadwhitacre and @lms24 for fixing the issue so quickly!
