### ISSUE TITLE
[Bug]: Missing opacity transition in recording

### ISSUE THREAD

**Issue by handoppler37** [rrweb-io/rrweb#1261]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/rrweb-io/rrweb/issues) for a bug report that matches the one I want to file, without success.

### What package is this bug report for?

rrweb

### Version

latest

### Expected Behavior

opacity transition from 1 to 0 cannot be recorded correctly

### Actual Behavior

opacity transition from 1 to 0 cannot be recorded correctly

### Steps to Reproduce

.test {
  opacity: 1,
  transition: opacity 1s
}
.after_1_second{
  opacity: 0
}

**Comment by handoppler37** [comment]
animating by animation api

**Comment by handoppler37** [comment]
close

**Comment by Muhammad-Taif-Khan** [comment]
did you find any solution?
