### ISSUE TITLE
[Feature Request]: 可以支持主动触发制作快照吗

### ISSUE THREAD

**Issue by houyj404** [rrweb-io/rrweb#1263]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/rrweb-io/rrweb/issues) for a feature request that matches the one I want to file, without success.

### What package is this feature request for?

rrweb

### Problem Description

现在可以通过checkoutEveryNms、checkoutEveryNth触发重新制作快照，请问可以通过特定事件手动触发制作快照吗？

### Proposed Solution

暴露制作快照属性，使调用方可以更加灵活的选择重新制作快照的时机

### Alternatives Considered

保持使用现有checkoutEveryNms、checkoutEveryNth属性触发，但在相关场景选择上不够灵活

**Comment by Juice10** [comment]
Hi @houyj404, thanks for submitting this feature request.
Instead of using `checkoutEveryNms` or `checkoutEveryNth` you can already call `record.takeFullSnapshot` whenever you'd like to take a full snapshot.

**Comment by houyj404** [comment]
Thank you very much for your reply, I have found it in the source code 
API `record.takeFullSnapshot(true)` for proactive snapshot generation
