### ISSUE TITLE
Replace numeric-enums with string-based enums

### ISSUE THREAD

**Issue by marcospassos** [rrweb-io/rrweb#127]
Numeric-enums have the disadvantage of being position-sensitive, which may [bring issues while evolving the project](https://github.com/rrweb-io/rrweb/blob/56c025fde3eed6251f7bbdff2d23b51b2da5fa9a/src/types.ts#L201).

That's why I want to propose replacing numeric-enums with string-based enums. We can keep a mapping in the replay side to provide BC-compatibility with previous versions and remove it in the next major version release.

**Comment by Yuyz0112** [comment]
I think another advantage of numeric-enum is the transport size.

The position-sensitive problem could be solved like this:
```ts
export enum MouseInteractions {
  MouseUp = 0,
  MouseDown = 1,
  Click = 100,
}
```
