### ISSUE TITLE
How can i handle on scroll?

### ISSUE THREAD

**Issue by mustafa-colakoglu** [rrweb-io/rrweb#128]
Hi

How can i on scroll playing web page?

Thanks

**Comment by Yuyz0112** [comment]
Could you provide some further info on the question?

**Comment by mustafa220** [comment]
@Yuyz0112 

i want to hadle scrool when rrwebplayer playing my record

**Comment by Yuyz0112** [comment]
Now you can listen to the `event-cast` event which has a payload of the current event.
