### ISSUE TITLE
同主机css引用data url翻译问题

### ISSUE THREAD

**Issue by futurepaycc** [rrweb-io/rrweb#129]
同主机的css文件引用，会变成inline的style标签，但会把形如：
>src: url(data:application/font-woff;base64,d09GMgABAAAAAAm.......

转换成带主机名的全路径url：
>src: url(http://localhost:8080/dist/data:application/font-woff;base64,d09GMgABAAAAAAm.......

影响web_font图标展示

rrweb版本：
0.7.23

**Comment by Yuyz0112** [comment]
Thanks for the report!
