### ISSUE TITLE
[Bug]:  页面中出现 frameset和frame录制失败 页面中出现 frameset和frame录制失败 Frameset and frame recording failure appear on the page

### ISSUE THREAD

**Issue by xdfeg** [rrweb-io/rrweb#1299]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/rrweb-io/rrweb/issues) for a bug report that matches the one I want to file, without success.

### What package is this bug report for?

rrweb

### Version

2.0.0

### Expected Behavior

![Uploading image.png…]()

### Actual Behavior

![image](https://github.com/rrweb-io/rrweb/assets/86296433/555bfea8-d16f-4371-bf8f-289b98024fb0)

### Steps to Reproduce

frameset + frame

**Comment by skitterm** [comment]
@xdfeg can you share how you resolved this? I'm running into the same issue. 

I see the issue was marked as `completed`, was this fixed with a PR?
