### ISSUE TITLE
Uncaught TypeError: Cannot read property 'blur' of null

### ISSUE THREAD

**Issue by ChuckJonas** [rrweb-io/rrweb#13]
I captured events on an react app (using the `antd` component library) and if I change an input text, I get the error during playback (using cdn `rr-webplayer@latest` with basically just the example code from the guide).

```
Uncaught TypeError: Cannot read property 'blur' of null
    at e.applyIncremental (index.js:1)
    at i (index.js:1)
    at Object.doAction (index.js:1)
    at r (index.js:1)
```

It stops the playback, but if I click play again, it will continue (although after I can't replay it again).

The code base is for a private client so I can't share for replay events (will try to reproduce with sharable code alter)... Just wondering if you have any ideas why this might happen?

**Comment by DvdGiessen** [comment]
Note: also applies to the `target.focus()` call a few lines below.

**Comment by ChuckJonas** [comment]
Just curious... Does the fix here just ignore the error?  IOW, information loss in the replay?

**Comment by Yuyz0112** [comment]
@ChuckJonas Yes, you are right.
Because we can not find what cause this without a reproducible events log, so the best thing we can do is to add some safe check and prevent an exception stop the whole world.
Previously I do not do this because I want to see whether there is some corner case rrweb does not cover, and a not handled error may encourage users to report the bug. But now more people are trying to use rrweb in production, so safe check and warning messages are more suitable.

**Comment by Sh1d0w** [comment]
I've experienced the same error.

It is reproducible every time with the following steps:

1. Open a page and start recording
2. Loose the focus of the page for several seconds, e.g. switch the browser window with another application window, e.g. Mail, Sublime etc.
3. Regain the browser window focus and continue to interact with the page

After that when you replay the saved events, it will show the correct session length, however when the player reaches the place where the browser window looses the focus it will throw this error in the console and will stop to play

```
index.js:1 Uncaught TypeError: s.blur is not a function
```

**Comment by Sh1d0w** [comment]
@Yuyz0112 Thanks for your quick replay. I've opened https://github.com/rrweb-io/rrweb/issues/48 and added little bit more info I was able to collect and sample json events I've recorded.
