### ISSUE TITLE
[Bug]: Textarea shows default value twice in replay

### ISSUE THREAD

**Issue by josephmathew900** [rrweb-io/rrweb#1301]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/rrweb-io/rrweb/issues) for a bug report that matches the one I want to file, without success.

### What package is this bug report for?

rrweb

### Version

latest

### Expected Behavior

Textarea shows default value twice in replay

### Actual Behavior

Textarea default value should not be duplicated.

### Steps to Reproduce

https://vimeo.com/862640906/5ee922b408

### Additional Information

I found a similar issue https://github.com/rrweb-io/rrweb/issues/745, and in that issue, it is mentioned that the bug has been fixed, but the issue still exists.

**Comment by YanJie-001** [comment]
I also encountered this bug and I didn't find that this bug was fixed.

**Comment by YanJie-001** [comment]
This problem still exists. You can use rrweb-player and remember not to use the default version.To use 2.0.0-alpha.11.

**Comment by eoghanmurray** [comment]
Thank you for putting together a great bug report.
In your video at 01:15 there is a screenshot of an event.
Is the textare node there part of a FullSnapshot or of a Mutation?

It seems to me that we should be addressing the problem on the _record_ side, in that we shouldn't be producing textarea nodes which contain both a value attribute and a child with the same value in it.  Would it be possible to look into that, and then see whether your fix in #1326 is still needed?

**Comment by eoghanmurray** [comment]
I'm just checking in case the record side can produce all variants of textareas:
 - attribute value and child text node set (as you witnessed)
 - only attribute value set
 - only child text node set
If that is the case, then #1326 might break one of the latter two above

**Comment by josephmathew900** [comment]
@eoghanmurray 
```
In your video at 01:15 there is a screenshot of an event.
Is the textare node there part of a FullSnapshot or of a Mutation?
```

It is part of a FullSnapshot.

**Comment by eoghanmurray** [comment]
#1351 is ready for review; you can execute the code to check that it fixes your use case and let me know if not

**Comment by josephmathew900** [comment]
I tested my use case with the code changes, and it is working perfectly fine.
