### ISSUE TITLE
React Native compatibility

### ISSUE THREAD

**Issue by itsezc** [rrweb-io/rrweb#131]
Is RRWeb React (and React Native) compatible, if not are there any plans to incorporate this?

Also would be interested on use cases with web view

**Comment by itsezc** [comment]
I see, however I have done some research and full well know that it is possible (atleast to a decent extent). UXCam is very popular in the RN market (https://uxcam.com/) and its RN lib can be found here: https://www.npmjs.com/package/react-native-ux-cam and another alternative.

And another competitor of UXCam (https://www.appsee.com/features), however I do see your point about rrnative (:

**Comment by Yuyz0112** [comment]
These links look really interesting! However I am afraid I do not have enough knowledge on the native side to implement this, but any open discussion is welcomed.

**Comment by itsezc** [comment]
@Yuyz0112 React Native support would be absolutely mind blowing for RRWeb!

Here are some similar (yet, basic) projects:
https://github.com/ycswaves/react-native-screen-recorder
https://www.npmjs.com/package/react-native-screen-recorder

While this would mean a lot of work, it also would boost RRWeb's awareness and usage, I'm currently researching into various implementations. 

For those who want a short term solution, you can wrap your React project inside a WebView and use RRWeb.
