### ISSUE TITLE
React

### ISSUE THREAD

**Issue by M3talen** [rrweb-io/rrweb#133]
Hello,
How to initialize the player in react ?

**Comment by Yuyz0112** [comment]
you can init the player in the component did mount hook and use the ref to access a DOM

**Comment by M3talen** [comment]
Do you by any chance have a example ?

**Comment by M3talen** [comment]
Also i can't even import rrweb-player 
both `import  * as rrwebPlayer from 'rrweb-player';` and `import rrwebPlayer from 'rrweb-player'` dont work

**Comment by Yuyz0112** [comment]
@M3talen This is a working example:https://github.com/Yuyz0112/project-r/blob/master/src/components/Player.tsx#L2

**Comment by M3talen** [comment]
Thanks, works like a charm
