### ISSUE TITLE
Player not updating the "captured content"

### ISSUE THREAD

**Issue by ptfly** [rrweb-io/rrweb#134]
On play, it will show only the first screen without updating the "video" and the captured mouse is not moving. If I click on the slider (playhead) to go to a certain time position, the screen gets updated with the proper stuff and freezes again while the playhead is still going. 

Any suggestions are welcome. Thanks!

**Comment by Yuyz0112** [comment]
Did you call the play method like this?
const replayer = new rrweb.Replayer(events);
replayer.play();

**Comment by ptfly** [comment]
Yes, like that. Also tried the rrweb-playerr, same result

**Comment by ptfly** [comment]
Even with this simple code, I have the same problem. Again, if I seek through/click on the timeline of the player, the content gets updated but wont continue to update, just staying on where I clicked.

`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>rrWeb Player</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/rrweb-player@latest/dist/style.css"/>
    <script src="https://cdn.jsdelivr.net/npm/rrweb-player@latest/dist/index.js"></script>

    <script>

        const options = {
            method: 'POST',
            credentials:'include',
            headers: {'Content-Type': 'application/json'},
            body: JSON.stringify({session_id:'1d059b1b-eeeb-4c5a-b9e9-12717041d7fe'})
        };

        fetch('http://localhost:4001/api/dt/rrwebStorageGet', options)
            .then((response) => response.json())
            .then((result) => {

                let events = [];

                result[1].data.map((e) => {
                    if(e) events = [...events, ...e.data];
                });

                new rrwebPlayer({
                    target: document.body,
                    data: {
                        events,
                        autoPlay: true,
                    },
                });

            });
    </script>
</head>
<body>

</body>
</html>
`

**Comment by ptfly** [comment]
Looks like the data we stored is corrupted when we compress/decompress it. This issue is not relevant. I've tested recording/playing with a data stored in a simple `json-server` instance and everything is fine. 
Sorry for wasting your time!

**Comment by Yuyz0112** [comment]
Never mind! Feel free to append further info since other users may go into the same problem.

**Comment by Serendipity0429** [comment]
I tried delaying my recording to 500ms after document "load" event and everything works well. I found that one possible reason of this problem is because the rrweb starts recording before some dynamic content is loaded from the script.
