### ISSUE TITLE
start/stop recording on click

### ISSUE THREAD

**Issue by Dewilas** [rrweb-io/rrweb#137]
Hello,

maybe you can write a code example like clicking on a button to start a new event recording and on press another button to stop and send them.

If I hit start again, I would have to start recording again. ty

**Comment by Yuyz0112** [comment]
Sure

```js
let events = [];
let stopFn;

function onClickStart() {
  stopFn = rrweb.record({
    emit(event) {
      events.push(event)
    }
  });
}

function onClickStop() {
  stopFn()
  yourSendFunction(events)
  events = []
}
```

**Comment by Dewilas** [comment]
@Yuyz0112 thanks, it helped
