### ISSUE TITLE
Autoplay flag seem to not work, I chose to set autoplay to false but replay still keeps playing

### ISSUE THREAD

**Issue by Ramu-Narsinga** [rrweb-io/rrweb#139]
Although 
new rrwebPlayer({
  target: document.body, // customizable root element
  data: {
    events,
    autoPlay: false,
  },
});
I set autoplay to false, replay events were still playing on page load. is this a known issue?

**Comment by Ramu-Narsinga** [comment]
> Although
> new rrwebPlayer({
> target: document.body, // customizable root element
> data: {
> events,
> autoPlay: false,
> },
> });
> I set autoplay to false, replay events were still playing on page load. is this a known issue?

PS: there is no consistency with the autoplay flag, sometimes it won't replay on page reload and sometimes it does

**Comment by Yuyz0112** [comment]
Yes I find the bug in rrweb-player. Going to fix it.

**Comment by Yuyz0112** [comment]
I think this has already been fixed, going to release a new rrweb player version.

**Comment by Ramu-Narsinga** [comment]
Awesome, Thanks.

**Comment by romain130492** [comment]
still not working?
