### ISSUE TITLE
Is it possible to truncate start of events and still watch the replay?

### ISSUE THREAD

**Issue by ChuckJonas** [rrweb-io/rrweb#14]
I'd like to include this library in my error capture handler for an internal sales tool. 

However, users might be on this page for quite some time, so I was hoping it would be possible to implement a "[circular buffer](https://en.wikipedia.org/wiki/Circular_buffer)" so I could capture just the last x events from when an error is logged.

Due to platform limitations, this would be more ideal than just saving every x seconds as your example shows.

Is it possible to start a replay for any point?  I've done some quick testing and it doesn't seem to work, but maybe I'm just missing something?

**Comment by ChuckJonas** [comment]
Looking at my truncated attempts I think the problem is that my event are all `EventType. IncrementalSnapshot`.

So maybe this would be possible if I somehow was able to incrementally restart with `EventType. FullSnapshot`?

Seems like I could achieve something similar by just having 2-3 offset & refreshing `rrweb.record` instances running at once, but since there is no way to stop recording (#16), I'm sure this is not a good idea.

**Comment by ChuckJonas** [comment]
The latter solution you proposed could work well for my use case.  My only concern is that there may be some performance impact corresponding to high user activity (if the user was generating lots of events)?  

I feel it would almost be safer to say  

> take a full snapshot after 10 seconds

This gets a little more complicated as you would only want to take a snapshot if the user is actually active on the page.

A more robust solution might be someway to trigger full snapshot event emit yourself.  This would require changing the return of the `record` to an object:

```
let recorder = rrweb.record({
  emit(event) {
    if (events.length > 100) {
      // stop after 100 events
      recorder.stop();
    }
  },
});

setTimeout(10000, recorder.captureFullSnapshot);
```

**Comment by Yuyz0112** [comment]
@ChuckJonas how about provides two modes?
`take one full snapshot after N incremental snapshot` and `take one full snapshot after N ms`?
Expose something like `captureFullsnapshot` may look too low-level for most of the developers.

**Comment by Yuyz0112** [comment]
@ChuckJonas Added this in #36, please let me know if you like it or not:)
