### ISSUE TITLE
Lazy-loading relative img src 

### ISSUE THREAD

**Issue by sumbatx15** [rrweb-io/rrweb#140]
Hey guys, first of all big respect, you are awsome, and this project is crazy :D 
I had some issue with the player, the collector is awsome, but when there are imgs with relative path, like so "assets/img/characters/robot.png"
then the event looks like this
"attributes": {
**"data-src": "assets/img/characters/robot.png",**
},
instead of **"data-src": "https://example.com/assets/img/characters/robot.png",**
and then we get no img :(
Well thank you for your awsome project, have fun :) Bye

**Comment by Yuyz0112** [comment]
@sumbatx15 I think you are having some code that read the `data-src` attribute as the image path right?
rrweb change relative paths to absolute paths when it knows it is a URL, like the `src` attribute for `<img/>` tag or the background value in a CSS rule.

But something like `data-src` is just like `<div data-id="1" />` which rrweb has no clue it should be treated as URL.

Actually I have merged an experimental feature, [hooks](https://github.com/rrweb-io/rrweb/blob/master/src/record/observer.ts#L522), which let the user modify the event if they need to. But it was not documented yet and the API is a little low-level.

**Comment by Yuyz0112** [comment]
Ok, this looks like a bug. I will do a test later, thanks for the report.

**Comment by Yuyz0112** [comment]
@sumbatx15 
I have written a unit test but it looks like the attribute was handled correctly.
https://github.com/rrweb-io/rrweb-snapshot/commit/cd9de42b6dc0013bec188b4517170d097a451f25

**Comment by sumbatx15** [comment]
@Yuyz0112 
Thank you, it seems that the snapshot doing great
my bad didn't notice its a lazy loading

so first when you enter the website, the elements look like this
they have no `src` attribute

```html
<picture>
<source class="lozad image-to-load-first w-200" type="image/webp" data-srcset="assets/img/characters/robot.webp">
<img class="lozad image-to-load-first w-200" data-src="assets/img/characters/robot.png" alt="robot">
</picture>
```

then when they became visible,
the lazyloading puts `src` on them

and then we get an event that looks like this 
```js
"attributes": {
    "src": "assets/img/characters/robot.png",
}
```

**Comment by Yuyz0112** [comment]
@sumbatx15 I believe this was fixed in the latest release, you can have a check:)

Please let me know if there is still some corner case not covered by us, thanks a lot.
