### ISSUE TITLE
Uncaught DOMException: Failed to execute 'insertBefore' on 'Node'

### ISSUE THREAD

**Issue by PaulAik** [rrweb-io/rrweb#141]
For infor this is rrweb 0.7.25 on latest Chrome (mac) and playing back using rrweb-player.

Full exception is: 

> DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

This looks to be happening for instance with a sample capture of the Github homepage when it loads in new content via AJAX. The error seems to happen just as the new content from the AJAX request is about to be loaded in?

![image](https://user-images.githubusercontent.com/99102/66435616-29568d00-ea1d-11e9-89e2-3469b48bddff.png)

Player is frozen after this point unfortunately.

**Comment by Yuyz0112** [comment]
@PaulAik Could you provide the events log for debugging?

**Comment by PaulAik** [comment]
Sure, here's a codepen with the events running (falls over at 0:14): https://codepen.io/PaulAik/pen/JjjdxeB

Full log here: https://www.lab25.co.uk/temp/data.js

**Comment by PaulAik** [comment]
The node the code is trying to add is as follows:

```
       {
          "parentId": 1172,
          "previousId": 71,
          "nextId": 1476,
          "node": {
            "type": 3,
            "textContent": "\n",
            "id": 7035
          }
        }
```

There are two nodes in the missing node map at this point, I think one of them contains the HTML content loaded in via AJAX. Id's of the missing nodes are 70 and 71.

The strange thing I guess is it's found another node entirely as the parent and/or next node, e.g. it's found the incorrect node in this instance. 

Looking at them in inspector, the parent and the next nodes's parent are indeed different. Not sure why there are multiple nodes in the data with the same ID, are they unique within a certain context/closure? 

Main code I was looking at was lines 397-407 in index.ts (rrweb/src/replay/index.ts).

**Comment by Yuyz0112** [comment]
Thanks for the information!

I found there are two full-snapshots in your log, and the second one is a little strange. Could you show your record code for debugging?

**Comment by PaulAik** [comment]
No worries! The first snapshot will be the initial page load, then the second would be the refresh so I could catch the AJAX load in time. I'm using a slightly modified version of the chrome plugin (background worker) to inject the script.

Record is just:

```
record({
  emit(event) {
    logEvent("if.recording.event", event);
  }
});
```

Where logEvent basically stringifies the data, adds it into an event queue and sends it to the server to be persisted every second or so:

```
export function logEvent(name, data) {
  events.push({ name, data: JSON.stringify(data) });
}

// Send code using fetch, every second (if the events queue has something in it)
```

The part I was looking at last was trying to figure out why three nodes had an id in the data of 1172 when the page was only refreshed once (I'd maybe expect two of the same ID, one per each full snapshot?). 

I'm still a bit of a newbie to the rrweb project, but from what I could see that should only happen if the ID was being re-used? In this situation, the nodes appear to be different, but have the same ID.

**Comment by Yuyz0112** [comment]
The id should not be re-used. The real problem at here is there are a set of duplicate add nodes record after the second full-snapshot.

So I am wondering wether there are two recorder emitting events at that moment.

**Comment by PaulAik** [comment]
Yeah it could be the script had been added too many times because of the way it's being injected in the chrome plugin (bit of a hack I guess).

I've just tried a couple more recordings of the same page and they seem to have worked ok, think this one is ok to close?

**Comment by PaulAik** [comment]
Ahh, yeah that nailed it - I had a look at your "repl.ts" and noticed you had a "window.__IS_RECORDING__" check. 

I added that in and everything started working a bit better! Thanks for the pointers, appreciate it.
