### ISSUE TITLE
[Bug]: Types are not exported

### ISSUE THREAD

**Issue by Nomango** [rrweb-io/rrweb#1424]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/rrweb-io/rrweb/issues) for a bug report that matches the one I want to file, without success.

### What package is this bug report for?

rrweb

### Version

2.0.0-alpha.11

### Expected Behavior

Code suggestions should work.

### Actual Behavior

```
There are types at '@rrweb/types/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The '@rrweb/types' library may need to update its package.json or typings.
```

### Steps to Reproduce

https://codesandbox.io/p/devbox/rrweb-issue-f4g9sp?file=%2Fsrc%2FApp.vue

**Comment by Juice10** [comment]
This was fixed by https://github.com/rrweb-io/rrweb/pull/1369
