### ISSUE TITLE
[Feature Request]: Setting name as data.payload.name instead of data.tag

### ISSUE THREAD

**Issue by Archish27** [rrweb-io/rrweb#1425]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/rrweb-io/rrweb/issues) for a feature request that matches the one I want to file, without success.

### What package is this feature request for?

rrweb

### Problem Description

Idea is to have two multiple custom names under same tag.

Example: 
tag name as `error` & event name as `Some error occurred in application` 

Why what is the idea behind this?
Currently there is no way to group event names under same tag. By doing so we can define same color to specific tag.

### Proposed Solution

instead of this
```javascript
const customEvent = {
          name: event.data.tag,
          background: tags[event.data.tag] || 'rgb(73, 80, 246)',
          position: `${position(start, end, event.timestamp)}%`,
        };
customEvents.push(customEvent);
```

to 
```javascript
const customEvent = {
          name: event.data.name,
          background: tags[event.data.tag] || 'rgb(73, 80, 246)',
          position: `${position(start, end, event.timestamp)}%`,
 };
customEvents.push(customEvent);
```

### Alternatives Considered

N/A

**Comment by eoghanmurray** [comment]
see #1426
