### ISSUE TITLE
Some Nodes are not getting added to the snapshot

### ISSUE THREAD

**Issue by IMFIL** [rrweb-io/rrweb#143]
When recording this page: [https://www.slaters.co.uk/checkout/onepage](url) the recording will show missing DOM nodes.

**This is what it looks like on the website:**
<img width="1069" alt="Screen Shot 2019-11-05 at 10 20 48 AM" src="https://user-images.githubusercontent.com/16093847/68220558-f2d94700-ffb5-11e9-91a1-68087e6f97e0.png">

**This is what it looks like in the recording:**
<img width="1026" alt="Screen Shot 2019-11-05 at 10 21 42 AM" src="https://user-images.githubusercontent.com/16093847/68220622-113f4280-ffb6-11e9-9d33-74d163e0f8ee.png">

**These are the warnings thrown during the replay:**
<img width="953" alt="Screen Shot 2019-11-05 at 10 22 28 AM" src="https://user-images.githubusercontent.com/16093847/68220695-2e741100-ffb6-11e9-9589-1d8c8eb3541e.png">

**My env**
- Mac book pro, Catalina
- Google Chrome
- latest version of RRweb

**Comment by Yuyz0112** [comment]
Hi @IMFIL , I cannot open the page you are recording since it needs sign up.

Could you check the payment part's DOM in the browser dev-tool? Is the DOM in an iframe or shadow DOM?

**Comment by IMFIL** [comment]
Hey @Yuyz0112 , you can checkout as guest, as done here:

**Comment by Yuyz0112** [comment]
Could you provide some logged events? I have tried the checkout as a guest feature but it is a little hard for me to debug.

**Comment by IMFIL** [comment]
Here is the events recorded on that page
[event.txt](https://github.com/rrweb-io/rrweb/files/3817924/event.txt)

**Comment by IMFIL** [comment]
@Yuyz0112  This was fixed by using the traditional for loop over the iterator.
