### ISSUE TITLE
[Bug]: Node Parent casting of undefined

### ISSUE THREAD

**Issue by yimejky** [rrweb-io/rrweb#1443]
### Preflight Checklist
* [x]  I have searched the [issue tracker](https://www.github.com/rrweb-io/rrweb/issues) for a bug report that matches the one I want to file, without success.

### What package is this bug report for?
rrweb

### Version
2.0.0-alpha.12

### Expected Behavior
The library shouldn't crash and spam the web and its performance.

### Actual Behavior
We have an angular web, where we use Posthog monitoring, and the problematic part seems to be this lib. One of our forms starts to spam the console and the performance with an error after rendering.
 
<img width="1048" alt="image" src="https://github.com/rrweb-io/rrweb/assets/22467644/252e3caa-a0c0-4685-aeae-28640237691a">

I backtracked the code to 

https://github.com/rrweb-io/rrweb/blob/3d1877cff83d9a018630674fb6e730050ceef812/packages/rrweb/src/record/mutation.ts#L444

where the casting pretends the node always has a parent, and it's connected to the DOM. 

### Steps to Reproduce
Unfortunately, I have no idea why is it happening. My suspect is race condition of too many updates or something like that. The problematic node simply doesn't have a parent at the time of execution.

**Comment by eoghanmurray** [comment]
Is this fixed in #1445 ?

**Comment by yimejky** [comment]
> Is this fixed in #1445 ?

Probably yes. I will update our FE this week.
