### ISSUE TITLE
[Bug]: Cannot use 'in' operator to search for 'xmlns' in undefined

### ISSUE THREAD

**Issue by w3villa-harsh-yadav** [rrweb-io/rrweb#1446]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/rrweb-io/rrweb/issues) for a bug report that matches the one I want to file, without success.

### What package is this bug report for?

rrweb-player

### Version

^1.0.0-alpha.4

### Expected Behavior

I want the video to be played which is recorded using rrweb package

### Actual Behavior

The video recorded using rrweb package is showing blank screen during its playtime, and throwing this error.

### Steps to Reproduce

Try Recording for this website [https://research-laundry.github.io/test.html]() 

### Additional Information

rrweb-snapshot.js:1728 Uncaught TypeError: Cannot use 'in' operator to search for 'xmlns' in undefined
    at ra (rrweb-snapshot.js:1728:17)
    at rrweb-snapshot.js:1801:16
    at ol.rebuildFullSnapshot (index.js:515:9)
    at index.js:340:22

**Comment by eoghanmurray** [comment]
This would be a fix btw, but don't think it's needed in trunk, but I may be wrong;

```--- a/packages/rrweb-snapshot/src/rebuild.ts
+++ b/packages/rrweb-snapshot/src/rebuild.ts
@@ -439,6 +439,7 @@ export function buildNodeWithSN(
       // this is needed as document.createElement('iframe') otherwise inherits a CSS1Compat mode from the parent replayer environment
       if (
         n.childNodes[0].type === NodeType.Element &&
+        n.childNodes[0].attributes &&
         'xmlns' in n.childNodes[0].attributes &&
         n.childNodes[0].attributes.xmlns === 'http://www.w3.org/1999/xhtml'
       ) {
```

**Comment by w3villa-harsh-yadav** [comment]
@eoghanmurray Thank you for your response. I haven't encountered any errors while recording and saving the DOM structure to my backend. However, I'm experiencing issues with playback using rrweb-player. I'll also attempt playback using the trunk version. Regarding post-processing, I'm not currently performing any post-processing on the data.

**Comment by eoghanmurray** [comment]
Could you let me know what the resolution on this was?  Did the current version of trunk fix it?
