### ISSUE TITLE
Does this support AJAX content?

### ISSUE THREAD

**Issue by Pinchanzee** [rrweb-io/rrweb#146]
I'm finding this consistently fails to display content that is loaded by AJAX, is this just an area that isn't implemented?
The DOM elements the AJAX content is loaded into simply remain empty.

**Comment by Yuyz0112** [comment]
could you provide your events log for debugging？

**Comment by Pinchanzee** [comment]
It's fine, I seen in the roadmap that AJAX isn't supported yet so I used a different project, cheers

**Comment by Yuyz0112** [comment]
@Pinchanzee nope, the AJAX things on the roadmap just means recording the content of http response. Any kind of DOM change should be supported out of box.

**Comment by Pinchanzee** [comment]
I no longer have access to the events unfortunately, but it was a simple case of ajax receiving a response and putting part of it (the HTML) into a pre-existing popup.
There were a host of other styling issues (margins all over the place, heights not expanding correctly, hidden overflow being shown, etc) that made this a non-option for us anyway

**Comment by hkmsadek** [comment]
does ajax content still support or not? Anyone has a solution?
