### ISSUE TITLE
[Bug]: Injected styles are cleared when node is added to a `<style>` element

### ISSUE THREAD

**Issue by billyvg** [rrweb-io/rrweb#1460]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/rrweb-io/rrweb/issues) for a bug report that matches the one I want to file, without success.

### What package is this bug report for?

rrweb

### Version

v2.0.0-alpha.13

### Expected Behavior

Injected styles (block styles, `noscript`) should remain on the document during playback.

### Actual Behavior

Injected styles are being lost when we have a mutation that adds a node to a `style` element and there is a fast forward event.

### Steps to Reproduce

I've wrote up a test case here: https://github.com/rrweb-io/rrweb/pull/1459

**Comment by jaj1014** [comment]
This sounds like the bug I reported and have a PR up for. https://github.com/rrweb-io/rrweb/pull/1357
