### ISSUE TITLE
Record A Specified Tag Only

### ISSUE THREAD

**Issue by erfanpp** [rrweb-io/rrweb#149]
Hi, I was trying to create some sort of playback for user interactions and my only purpose is to record the area of my action, not navbar not a sidebar only specified tag with proper height and weight, is there a solution? if not please guide me on how to change the source.

**Comment by Yuyz0112** [comment]
Similar to https://github.com/rrweb-io/rrweb/issues/111.

Currently, you can add the class name `.rr-block` to the DOM you do not want to record.

**Comment by erfanpp** [comment]
well `.rr-block` will ruin the rest of my visual, I browsed the code and find 
`  observer.observe(document, {
        attributes: true,
        attributeOldValue: true,
        characterData: true,
        characterDataOldValue: true,
        childList: true,
        subtree: true
    });` 
when i give an element instedof whole document it loses some style even when i give the body

**Comment by erfanpp** [comment]
Anyone who reads this you should use the iframe and partial views
