### ISSUE TITLE
Typescript File ../node_modules/rrweb/index.d.ts' is not a module.

### ISSUE THREAD

**Issue by ChuckJonas** [rrweb-io/rrweb#15]
If you try to `import rrweb from 'rrweb';` in a typescript project, you get an error:

> File '.../node_modules/rrweb/index.d.ts' is not a module.ts(2306)

**Comment by ChuckJonas** [comment]
I'm slammed right now, but if this hasn't been picked up in a couple weeks i'll take a stab

**Comment by Yuyz0112** [comment]
Sorry for this, won't take so much time to finish it.

**Comment by lidong081824** [comment]
node_modules/rrweb/index.d.ts' is not a module.ts  Has the problem been solved？

**Comment by Yuyz0112** [comment]
@ChuckJonas @lidong081824 
Definition files were shipped in `0.7.6`.

**Comment by GabiAxel** [comment]
I still get this error with 0.7.9 . Can you please provide example import statement and tsconfig.json of a working case so I can see if I'm missing anything?

**Comment by davibe** [comment]
same problem herewith 0.7.9

```
examples/rrweb-player.ts:2:26 - error TS2306: File 'node_modules/rrweb/index.d.ts' is not a module.

2 import { Replayer } from 'rrweb'
                           ~~~~~~~

node_modules/rrweb/index.d.ts:4:35 - error TS2304: Cannot find name 'Handler'.

4     (all?: { [key: string]: Array<Handler> }): Emitter;
                                    ~~~~~~~

node_modules/rrweb/index.d.ts:4:48 - error TS2304: Cannot find name 'Emitter'.

4     (all?: { [key: string]: Array<Handler> }): Emitter;
                                                 ~~~~~~~

src/RRWebRecorder.ts:2:42 - error TS2306: File 'node_modules/rrweb/index.d.ts' is not a module.

2 import { Replayer, mirror, record } from 'rrweb'
                                           ~~~~~~~

src/example.ts:1:24 - error TS2306: File ' node_modules/rrweb/index.d.ts' is not a module.

1 import { record } from 'rrweb'
```

**Comment by davibe** [comment]
If i transpile with no checks it works but this breaks typechecking of the project so it's very bad for a typescript project.

**Comment by Yuyz0112** [comment]
@davibe Could you have a try with the latest version?
