### ISSUE TITLE
Recorder creating tags that do not exist.

### ISSUE THREAD

**Issue by IMFIL** [rrweb-io/rrweb#150]
**The recorder seems to be creating invalid tags**

<img width="330" alt="Screen Shot 2019-11-24 at 6 08 35 PM" src="https://user-images.githubusercontent.com/16093847/69503203-73200780-0ee5-11ea-9fad-9249dfa00b50.png">

**And the replayer  throws this error**

<img width="455" alt="69491315-82f60800-0e61-11ea-81e3-d4ab8d52fe03" src="https://user-images.githubusercontent.com/16093847/69503239-a06cb580-0ee5-11ea-8334-65522c9f13b2.png">

**Here is the full log**

[event.txt](https://github.com/rrweb-io/rrweb/files/3884260/event.txt)

Upon replacing alt="" by p, the replayer works as expected.

**EDIT**
The tag is genuinly called alt="" as seen in the actual DOM here.

<img width="469" alt="Screen Shot 2019-11-24 at 6 17 27 PM" src="https://user-images.githubusercontent.com/16093847/69503330-c0e93f80-0ee6-11ea-8239-b438226a21d3.png">

Here is the web page : [https://www.surlatable.com/checkout-start](url)

**Comment by Yuyz0112** [comment]
Yes, I have a test on the tag name.
`CreateElement` prevent create an element with an invalid tag name, but `parent.innerHTML = '<alt=""></alt="">'` do the trick.

I'm thinking of how to adapt this in rrweb.

**Comment by IMFIL** [comment]
In this situation the DOM is not added by any javascript and present by default. I think a solution would be to process each tagname to remove any numerical or symbol characters from them. CreateElement only fails if the tag name contains number or symbols. So alt="" would become alt. I'm going to have a PR soon.

**Comment by Yuyz0112** [comment]
@IMFIL 
Yep, this may cover most of the cases I think.
