### ISSUE TITLE
how to handle custom event when l was replaying.

### ISSUE THREAD

**Issue by 0x30** [rrweb-io/rrweb#153]
maybe we can send  `event-action-start` with Emitter when l start event action.  

like this. [feat: add evnt start for replayevent,to know event start action.](https://github.com/0x30/rrweb/commit/dc927725a98f161d6d6838d39fe5cf30f729c2a3)

**Comment by Yuyz0112** [comment]
Hi @0x30, the purposed API looks good to me.

The only thing I'm thinking is which timing is more important for users:
1. Emit when the event was wrapped(the way your code does).
2. Emit when the event was cast (because event replay is an async process).

**Comment by 0x30** [comment]
好吧，我之前也考虑过过要不要自定义`自定义事件`的执行，因为那样子可能会更好..

目前咱们关于`自定义事件`的重播，是以类似于空过的方式，进行的[break](https://github.com/rrweb-io/rrweb/blob/master/src/replay/index.ts#L266).  所以想要自定义事件执行的话，我最开始想的是在 `playerConfig` 增加一个 关于 `自定义事件`类型的 castFn 构造方法... 但是参考 `getCastFn ` 以及 `applyIncremental ` 方法，貌似需要很多似有属性..

 所以我考虑是不是只是知道事件开始执行就够了，事实上，我只是想实现 [logrocket](http://logrocket.com/) 额外的关于网络或者VUEX 日志的事件重播，我只是需要一个事件运行到哪里的通知，所以我需要的只是我`自定义事件`的开始就足够了，剩下数据会在 `payload` 中存在

我读代码的时间并没有太久... 也许有什么更好的解决办法...

**Comment by Yuyz0112** [comment]
嗯，我的想法是在[这里](https://github.com/rrweb-io/rrweb/blob/master/src/replay/timer.ts#L43) emit 是不是更合理（event action 实际执行的时机）。

**Comment by 0x30** [comment]
嗯，当然会好，但是这样的话，我有些疑问...

因为 这个时候，action 执行的是[这里](https://github.com/rrweb-io/rrweb/blob/master/src/replay/index.ts#L134)  的 `actionWithDelay `对象中的 `castFn` 方法 ， 如果我想获取具体是哪个 `event` 开始执行，就需要自己完成 `getCastFn` 关于 自定义事件的动作执行？在这里，我没看到有比较好的一个办法可以获取到这个事件对象(这是我最开始的痛点)？也许扩展 `actionWithDelay` ?

而且不知道是不是我的理解问题，我感觉  [这里](https://github.com/rrweb-io/rrweb/blob/master/src/replay/index.ts#L132) 如果我是同步执行的话，也许我就有一些事件遗漏通知了吧？我没有去看咱们的`isSync` 这个参数的具体的含义，以及产生原因...

**Comment by Yuyz0112** [comment]
`isSync` 是应对“跳转”的场景，目前 rrweb replay 跳转的实现时同步 apply 跳转时间点前的 event，这部分对于使用者来说可以理解为“no cast”，所以不触发好像更合理。

**Comment by 0x30** [comment]
其实想解决的问题，大概是说比如页面跳转了或者一些其中日志的打印这类事件，这种不应该一下子全部列出来，而是应该事件执行的时候才会出现的记录行为。

**Comment by Yuyz0112** [comment]
目前的实现是这样的，可以试一下

**Comment by 0x30** [comment]
嗯，咱们的播放器是如此做的。

但是针对自定义事件，我目前是没有找到什么方式可以知道，该轮到某一个自定义事件执行了，不知道这样子表述会不会更清楚些...

![WX20191209-111100](https://user-images.githubusercontent.com/6121524/70404318-9fef2580-1a74-11ea-9a37-805fb6ef3a4a.png)

**Comment by Yuyz0112** [comment]
我上面 reference 的 commit 现在就在 event cast 的时候了emit，应该可以用来判断 custom event？

**Comment by 0x30** [comment]
OK 刚才没看到... 不好意思
