### ISSUE TITLE
页面样式太多，我用的layui，存储到数据库中json字符串的长度，小的20万，大的110万了

### ISSUE THREAD

**Issue by hulang** [rrweb-io/rrweb#155]
能否转换成mp4格式啊，我就存个路径了，json字符串太长，崩溃了几次了，搞的我有几个页面都不敢保存记录了。

**Comment by Yuyz0112** [comment]
可以在 record 的时候 options 设置 `inlineStylesheet` 为 false，就不会将样式表中的 CSS inline 化。

```
rrweb.record({
  emit(event) {
  },
  inlineStylesheet: false
});
```

**Comment by hulang** [comment]
@Yuyz0112 会影响回放么？

**Comment by Yuyz0112** [comment]
会在回放的时候去访问外部 CSS。如果录制和回访时 CSS 地址对应的内容没有变化就不影响。

**Comment by hulang** [comment]
@Yuyz0112 刚试了下，还是不行。。直接来个json长度：10457884
我PHP页面直接：Allowed memory size of 134217728 bytes exhausted (tried to allocate 4198400 bytes)
当然了。这是一个特殊的页面，页面有614条数据。

**Comment by Yuyz0112** [comment]
可以吧 events log 发出来看一下吗？

**Comment by hulang** [comment]
@Yuyz0112 怎么发，不是很懂，我才用额。

**Comment by Yuyz0112** [comment]
如果是可以公开访问的页面可以提供 URL，如果不能访问的话可以把录制后的 JSON 压缩上传到这个 issue，或者发到我的邮箱

**Comment by hulang** [comment]
@Yuyz0112 已发送。。tp.的

**Comment by hulang** [comment]
@Yuyz0112 回放的时候，可以右键查看源码。

**Comment by hulang** [comment]
10457884长度的文件，已发送给你，你能在这里回复我下，你收到邮件了么？

**Comment by Yuyz0112** [comment]
已收到

**Comment by hulang** [comment]
@Yuyz0112 什么个情况额。。

**Comment by hulang** [comment]
@Yuyz0112 什么个情况，回复下啊。。

**Comment by Yuyz0112** [comment]
@hulang https://github.com/rrweb-io/rrweb/issues/151

可以关注一下这个优化尺寸的 issue

**Comment by hulang** [comment]
@Yuyz0112 具体的怎么做，你能写个demo么？我不懂英语额。。。
我的网站就是普通的那种，不是vue等等高级工具写的。

**Comment by hulang** [comment]
@Yuyz0112 我进行翻译了你发的
I believe there is a huge potential to reduce the size of the recorded events(I always seeing 90% size reduction when I gzip the events).
--
我相信有一个巨大的潜力可以减少记录的事件的大小（当我对事件进行gzip操作时，我总是看到大小减少了90%）。
--
减少了90%，急需要demo。哈哈
