### ISSUE TITLE
录制数据与使用录制是参数不同导致回访效果不一致问题

### ISSUE THREAD

**Issue by betweens** [rrweb-io/rrweb#156]
使用checkoutEveryNth 或checkoutEveryNms 记录数据 和 不是用这这两个参数，录制数据回访的时候，使用参数回放的正确的。相反，10s中发送一次数据，在后端管理组合数据时候，回放的效果不实用参数的时候，和实际不一致，使用参数的时候是一致的

**Comment by Yuyz0112** [comment]
可以提供一下录制和回放的代码吗？

**Comment by Yuyz0112** [comment]
Please re-open the issue if there is any further information.
