### ISSUE TITLE
Replay with clicks

### ISSUE THREAD

**Issue by alexiskattan** [rrweb-io/rrweb#157]
I'd like to be able to replay but have the clicks take place on the page.  I'm trying to make a tool to automate certain tasks.  So I want to record the mouse moving and clicking buttons.  Then during the replay, I'd like the buttons to be clicked instead of just having the red circle appear. 

Is there a way to do this using the library?

**Comment by gimme4free** [comment]
I think you can come up with a very hacky solution using this library.

A better option would be to use either selenium or puppeteer. They're made for the purpose you're talking about.

There's even a chrome extension that converts your interactions into puppeteer code
https://chrome.google.com/webstore/detail/puppeteer-recorder/djeegiggegleadkkbgopoonhjimgehda?hl=en

**Comment by Yuyz0112** [comment]
Yep, the replayer is a sandbox which will not fire click events.

I think you can just use the recorder to collect events and cast events in something like puppeteer.

The puppeteer-recorder project mentioned above works in many scenarios. Personally I have an interaction codegen project do the similar things but have no limitation on the target platform. Hope I have time to open source it:)

**Comment by alexiskattan** [comment]
That plugin is amazing.  Thank you so much for the link!  Am playing around with it and puppeteer right now.
