### ISSUE TITLE
Recording user interactions on iFrame/video tags

### ISSUE THREAD

**Issue by praneetnadkar** [rrweb-io/rrweb#159]
Hi,

I have tried to use a iframe and a video tag. The rrweb doesnt track the interactions on those. It just shows a grey area instead in the replay. Could you please help me out here to understand why that happens?

iFrame :
```
<iframe width="560" height="315" src="" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
</iframe>

```

Video tag:
```
<video width="320" height="240" controls>
    <source src="movie.mp4" type="video/mp4">
    <source src="movie.ogg" type="video/ogg">
    Your browser does not support the video tag.
  </video>
```
Is it that the interactions on the iframe or a video cannot be tracked?

Thanks in advance.

**Comment by Yuyz0112** [comment]
Iframes are complex because of cross-origin stuff. There are draft PRs about support nested recording but not finished.

The video part looks like a bug.

**Comment by praneetnadkar** [comment]
Thanks for looking into this.
For the video part, could you please take it up as a bug?

Thanks

**Comment by Yuyz0112** [comment]
Sure.

BTW, the expected result of interactions in the `video` tag means when user click the play/pause, the replayer should do the same at the same time right?

**Comment by praneetnadkar** [comment]
Yes. Certainly.

Thanks again for looking into this.

This is a great tool. Great job !

**Comment by Yuyz0112** [comment]
@praneetnadkar I believe this has been fixed in the latest release. Since the media may load asynchronously, the replay of the `play` events may not be perfectly accurate in timing but it should work.

**Comment by shivamtomar96** [comment]
is this issue resolved ?
