### ISSUE TITLE
[Question] Streaming/Paginating events while replaying

### ISSUE THREAD

**Issue by praneetnadkar** [rrweb-io/rrweb#161]
If the events data to be replayed is huge, then it will affect the performance. Any way we can stream the events while replay or paginate them?

**Comment by pnadkar** [comment]
Can someone help me on this:?

**Comment by bugwheels94** [comment]
Hi, Any way to achieve this?

**Comment by Yuyz0112** [comment]
Now you can simply use `addEvent` to do this.

```
const replayer = new rrweb.Replayer(events)

for (const newEvent of newEvents) {
  replayer.addEvent(newEvent)
}
```

**Comment by tamilvendhank-helptap** [comment]
@Yuyz0112, how to know I need new set of events? Could you give a full example that includes initializing the player, fetching the data based on some event & adding it to the player?

**Comment by ShayMalchi** [comment]
@Yuyz0112 Hi, using `addEvent` works but the progress bar remains out of date (inactive time in particular) and does not update dynamically like the duration. On hard reload it draws correctly. How can I force it to update as well?
