### ISSUE TITLE
Failed to execute 'insertBefore' on 'Node'...by use checkoutEveryNth

### ISSUE THREAD

**Issue by liwangying55555** [rrweb-io/rrweb#164]
When i use checkoutEveryNth(events to 50) to checkout , the first events set is can replay, but then second events set is show this:
Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node 

and the 3th,4th...events set all cannot replay
Do you konw what's wrong？
Can the checkout evnets set cannot replay unattached？

**Comment by Yuyz0112** [comment]
A related bug has been fixed in the latest version.
