### ISSUE TITLE
node with id 'xxx' not found in 

### ISSUE THREAD

**Issue by jwentao** [rrweb-io/rrweb#166]
![image](https://user-images.githubusercontent.com/21285362/73130560-47c8ae80-4035-11ea-8d14-3b69a20ce7c8.png)
请问这种情况要怎么解决呢，可以回放，但是进度条没有时间

**Comment by jwentao** [comment]
进度条是这样的
![Uploading image.png…]()

**Comment by jwentao** [comment]
进度条是这样的
![image](https://user-images.githubusercontent.com/21285362/73130568-8199b500-4035-11ea-81a9-2f757136fdd1.png)

**Comment by Yuyz0112** [comment]
可以提供一下 events 用于 debug 吗？

**Comment by saqing** [comment]
@Yuyz0112 作者你好，我也遇到了这个问题。这是我的events
https://study-api.testbay.cn/api/v1/web-record/5e6aee2324f32000e50b64b3
可以在 https://saqing.github.io/rrweb-player/ 播放，播放 session 6 出现 了 node with id  166 not found

**Comment by saqing** [comment]
借楼再问一个问题 同上 events ，在播放session1 时出现了这个错误   err DOMException: Failed to execute 'insertRule' on 'CSSStyleSheet': The index provided (6) is larger than the maximum index (5).感觉像是录制端录制出的问题，望解答，谢谢

**Comment by jwentao** [comment]
抱歉未即时关注提过的issue，这个问题已经解决，原因是播放时组装event产生了时序问题

**Comment by Yuyz0112** [comment]
@saqing 你的问题是因为录制多个 fullsnapshot 的一个 bug 导致的，我得想一下修复的方案

**Comment by SummerCreazy** [comment]
您好我也出现了这样的问题，但貌似不是是时序的问题

**Comment by wbcs** [comment]
inlineStylesheet:true
