### ISSUE TITLE
Crash once a http request ist send in Angular

### ISSUE THREAD

**Issue by florianfelgentraeger** [rrweb-io/rrweb#167]
I've been trying to get it to run in Angular and the events are coming but once its recording and im sending a web request Chrome just crashes the request never finishes and i cant do anything anymore.
Any suggestions?

**Comment by Yuyz0112** [comment]
Could you provide the code to reproduce this issus?

**Comment by florianfelgentraeger** [comment]
Sadly no. I cant provide my code because its not a public project.
So far i tried it via a button in my navigation as well as in the app.component.ts (so once my Application starts up I start recording). Once a request occurs it Crashes. Cpu usage goes up to absurd levels and I can only close the window via task manager.

**Comment by 24601** [comment]
I am also experiencing this, Angular 9. 

Totally locks Chrome tab.

**Comment by 24601** [comment]
> I've been trying to get it to run in Angular and the events are coming but once its recording and im sending a web request Chrome just crashes the request never finishes and i cant do anything anymore.
> Any suggestions?

Are you using the npm module install or script?

**Comment by Yuyz0112** [comment]
@24601 Do you have a reproducible code for this?

**Comment by 24601** [comment]
Yes but I cannot share it publicly, so I will be happy to screen share
until I can pull out enough into a generic public example.

The issue seems related to http activity after recording begins so it’s not
as simple as making an angular template and just inserting record, as one
of our other background http proceeded causes it and I can’t just share
those.

**Comment by kubadospial** [comment]
have the same issue with record function. Implementation:
![image](https://user-images.githubusercontent.com/24934035/88804597-7410e380-d1ae-11ea-815e-1a1c877fb569.png)

result:
tab crashes
![image](https://user-images.githubusercontent.com/24934035/88804739-a3bfeb80-d1ae-11ea-83b5-8f9de1347417.png)

**Comment by Yuyz0112** [comment]
@kubadospial Do you have any reproducible code for me to debug?

**Comment by kubadospial** [comment]
unfortunately I tried to reproduce the issue on new, clear angular 9 project and I wasn't able to. If I'll figure what was the issue in my company project I will follow up with it.

**Comment by Yuyz0112** [comment]
@kubadospial  I remember someone has reported they are having this issue with a tooltip component, are you using something like that in your project too?

**Comment by kubadospial** [comment]
@Yuyz0112 yes we use a tooltip component in the app. In the free time I will remove this component and test if it helps. I will let you know

**Comment by Yuyz0112** [comment]
https://github.com/rrweb-io/rrweb/pull/284 may relate to this issue. It's appreciated if anyone can help verify whether the issue still happen with v0.9.1.

**Comment by Yuyz0112** [comment]
Please reopen this if there is any further information.

**Comment by MitsuhideA** [comment]
Hello @kubadospial,
Did you fix your problem?
I have a similar crash when I hover a element that displays a tooltip.
Your help would be appreciated if you managed to fix your problem.

**Comment by aserec** [comment]
It says was fixed in the commit rrweb-io/rrweb@13f1a61. I've tried with angular 9, then upgraded to 10 and finally to 11. They all face the same result. Screen gets frozen. I've used the example code readme for the recording. I'm using ngx-bootstrap.

This was done in Feb, was it truly fixed?

**Comment by Yuyz0112** [comment]
@aserec Could you open a new issue and provide a reproducible code?
