### ISSUE TITLE
node project rrweb Error in recording window is not defined unale to record

### ISSUE THREAD

**Issue by shivafreelancin3** [rrweb-io/rrweb#168]
step 1 : installed rrweb

E:\nodejs_projects\self practise\rrweb_try_tutorials\download>npm i --save rrweb
npm WARN download@1.0.0 No description
npm WARN download@1.0.0 No repository field.

+ rrweb@0.7.27
added 2 packages from 1 contributor and audited 36 packages in 7.717s
found 0 vulnerabilities

step 2: written a js file. below is the code of record.js
const rrweb = require('rrweb');

let events = [];

rrweb.record({
  emit(event) {
    // push event into the events array
    events.push(event);
    console.log("no of events recorded so far : " + events.length);
    if(events.length > 100) events = [];
  },
});

step 3: try to run the js file using node command.

E:\nodejs_projects\self practise\rrweb_try_tutorials\download>node record.js
E:\nodejs_projects\self practise\rrweb_try_tutorials\download\node_modules\rrweb\lib\rrweb.js:1109
    if ('NodeList' in window && !NodeList.prototype.forEach) {
                      ^

ReferenceError: window is not defined
    at polyfill (E:\nodejs_projects\self practise\rrweb_try_tutorials\download\node_modules\←[4mrrweb←[24m\lib\rrweb.js:1109:23)
    at Object.record (E:\nodejs_projects\self practise\rrweb_try_tutorials\download\node_modules\←[4mrrweb←[24m\lib\rrweb.js:1654:5)
    at Object.<anonymous> (E:\nodejs_projects\self practise\rrweb_try_tutorials\download\record.js:5:7)
←[90m    at Module._compile (internal/modules/cjs/loader.js:959:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:815:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:727:14)←[39m
←[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)←[39m
←[90m    at internal/main/run_main_module.js:17:11←[39m

E:\nodejs_projects\self practise\rrweb_try_tutorials\download>

Issue, is not clear how to remove this error.
how to define window here.
rrweb does not have any other method, by which somehow, need to set this value.

**Comment by Yuyz0112** [comment]
rrweb needs to be executed in a browser environment.
