### ISSUE TITLE
Failed to execute dispatch event

### ISSUE THREAD

**Issue by jonaslund** [rrweb-io/rrweb#169]
Hi,

Having issues with replayer, after capturing a short recording, it fails to execute clicks. Any ideas or API reference?

```
Uncaught TypeError: Failed to execute 'dispatchEvent' on 'EventTarget': parameter 1 is not of type 'Event'.
    at t.applyIncremental (index.ts:241)
    at o (index.ts:234)
    at Object.doAction (index.ts:241)
    at o (timer.ts:43)
```

**Comment by Yuyz0112** [comment]
Could you provide the events log for debugging?

**Comment by Yuyz0112** [comment]
Close due to inactivity. Feel free to reopen it if there is any further feedback.
