### ISSUE TITLE
Certain DOM nodes are not serialized  in Safari but are being serialized in Chrome.

### ISSUE THREAD

**Issue by IMFIL** [rrweb-io/rrweb#173]
How to reproduce:

1. Go to this URL:  https://www.skiny.com/pant-2er-pack-white-086835-080500.html
2. Follow steps in video: 
![steps](https://user-images.githubusercontent.com/16093847/74781607-c3ea9680-526f-11ea-98aa-4f2bbf89c775.gif)

Do the exact same steps on Safari and Chrome and the session replay on the: [https://www.skiny.com/checkout/#shipping](https://www.skiny.com/checkout/#shipping) page will be broken on safari and not on chrome.

This is the error message received while replaying the session in Safari. There is no such error during replay time for the session recorded in Chrome.

<img width="723" alt="Screen Shot 2020-02-18 at 4 58 59 PM" src="https://user-images.githubusercontent.com/16093847/74781700-f85e5280-526f-11ea-977d-d056e2522555.png">

Running the latest code for both the player as well as the recorder.

Here are the events for the safari recording:
[safari.txt](https://github.com/rrweb-io/rrweb/files/4221860/safari.txt)

Here are the events for the chrome recording:
[chrome.txt](https://github.com/rrweb-io/rrweb/files/4221862/chrome.txt)

**Comment by Yuyz0112** [comment]
Thanks for the report @IMFIL 

Since my laptop OS is Linux, I think I need some more time to find a safari env to reproduce and fix the issue.

**Comment by IMFIL** [comment]
This PR will prevent the re-player from breaking when this happens. It should buy us more time to fix it at it's core.

https://github.com/rrweb-io/rrweb/pull/174
