### ISSUE TITLE
Can you communicate with iframe from parent page?

### ISSUE THREAD

**Issue by universalconsciousness** [rrweb-io/rrweb#175]
Can I communicate with the iframe that is playing the recording from the parent page?

For example, using something like Postmessage()?

I wanted to pull some text values from the recording every time the recording is paused.

**Comment by Yuyz0112** [comment]
I think you can access the replayer's iframe like this

```js
const replayer = new Replayer(...)
replayer.iframe.contentDocument
```

**Comment by universalconsciousness** [comment]
Hey @Yuyz0112 

Thanks for the suggestion!

I added this
`console.log(replayer.iframe.contentDocument);`
and when I run it, it prints this to the console https://imgur.com/a/C2q0159


However, when I do this
`console.log(replayer.iframe.contentDocument.getElementsByClassName('view-lines')[0].textContent);`
I get this error https://imgur.com/a/91f9XrD
Error in text form: 
> Uncaught TypeError: Cannot read property 'textContent' of undefined

I kept playing around with it but couldn't come to any solution. Do you know why the second one might not be working?

**Comment by universalconsciousness** [comment]
Found the solution

My JS code was running before the DOM was being loaded so I put my JS in a setTimeout function
