### ISSUE TITLE
Ignore certain elements through record options

### ISSUE THREAD

**Issue by fizerkhan** [rrweb-io/rrweb#179]
I understand that we can ignore and block elements by adding "rb-ignore" and "rb-block" class in the tag.

Instead, we want to ignore and block certain classes through record options. We want to ignore the "headway" classes(this tool we used for notification) for all our projects. 

    rrweb.record({
        emit(event) {
        },
        ignoreClasses: [ "HW_animated", "olark-popup" ]
        blockClasses: [ "token", "apiKeys" ]
    });

This will give better control to us for blocking elements instead of changing the tags.

**Comment by Yuyz0112** [comment]
Hi @fizerkhan , I believe this feature is already in the options: https://github.com/rrweb-io/rrweb/blob/master/src/record/index.ts#L33. Sorry for not updating the doc.

Currently, the `blockClass` accepts a string or Regexp to match elements' class names, do you think it fits your usage? If so I would love to add the same option for the `ignoreClass`.

**Comment by fizerkhan** [comment]
@Yuyz0112 Thanks. Yes I saw the regex option inside the code. But configuring with regex with multiple classes seems to be error prone. 

If you also support Array of class names along with string and regex, that will be great.

**Comment by Yuyz0112** [comment]
I don't think `new RegExp(blockClass.join('|'), 'gi')` has the same sematic with Array of class names.

For example, `['a', 'b']` usually means match exactly with these two class names, but `/a|b/` matches many other things.

Personally I would not like to provide too many forms of options, but PR for that is acceptable.

**Comment by fizerkhan** [comment]
@Yuyz0112 Thanks for the update. Can I give the Pull request with this changes?

**Comment by Yuyz0112** [comment]
@fizerkhan Sure, feel free to ping me if you need any help.
