### ISSUE TITLE
Option to pause at certain time offset

### ISSUE THREAD

**Issue by fizerkhan** [rrweb-io/rrweb#181]
We have option to play from certain offset. 

Can you provide same option for `pause(timeOffset)`.

**Comment by Yuyz0112** [comment]
Could you explain a bit more about the use case for this?

And does this works?
```js
play(offset)
pause()
```

**Comment by fizerkhan** [comment]
@Yuyz0112 I add notes to particular recording at certain offset (might be some UI bugs that i want to report) . Then I share the note in slack channel which has note text, video URL (which has start offset in query params),  recording info such as browser, os, user agent, etc.

When user clicks on the video URL, it will take the user to the video and pause at the offset. Then highlight the notes in the side pan.

**Comment by buremba** [comment]
I'm also looking for this feature. We're planning to use rrweb for our product demos and rrweb seems to be a great alternative for this. 

We plan to add notes pausing the player at a certain time and resume it afterwards. We can do it using `setInterval` but it would be great if rrweb can support it out of the box.

**Comment by randy-johnson** [comment]
@ Yuyz0112 can you confirm if this is supposed to work?
```
play(offset)
pause()

```

**Comment by Yuyz0112** [comment]
@randy-johnson Yes

**Comment by Yuyz0112** [comment]
v0.9 has a straight-forward API `pause(offset)` for this.
