### ISSUE TITLE
Node  id xxx is not found.

### ISSUE THREAD

**Issue by arun477** [rrweb-io/rrweb#182]
hey, great tool man, I'm facing some issue with replaying my recorded events. when I try to replay the recorded events, I can see a lot of warning messages "Node with id xxx not found" like this but my video somehow playing but not properly( it happens if a number of event increase for example: if total event size is 1k it playing well but when it increased to more than 1k it started playing improperly).  my application is react based and I'm using styled-components("CSS in js library) and I'm storing every event as a string(JSON.stringify(event)) in DB. at playing time query it from DB parse it using JSON.parse(event) and trying to play. 

thanks.

**Comment by arun477** [comment]
and I have two more questions.
1. is the order of events important or we can provide events in any order to the player.
2. is it ok to use JSON.stringify and JSON.parse (it won't corrupt event data?)

**Comment by Yuyz0112** [comment]
Hi @arun477 , could you provide a sample events log for debugging?

For your questions:
1. Yes, we need the events being ordered by timestamp.
2. Yes, the events are serializable.

**Comment by arun477** [comment]
hey, thank for the quick reply.  my logs are sensitive to share, so I can't share could you tell me what causes this  issue "Nodeid xxx is not found" I try to debug myself( if not I will simulate sample env and email you but it will take some time for me to generate that sample log)

**Comment by Yuyz0112** [comment]
Feel free to re-open this issue if I can help.

**Comment by eoghanmurray** [comment]
@arun477 were you using `player.addEvent` to add events?

**Comment by jackiehamchen** [comment]
Hello @arun477 
are you able to solve the issue? could you please share with me as i'm experiencing the same error message while replaying?

**Comment by wbcs** [comment]
inlineStylesheet:true
