### ISSUE TITLE
Is there some options we can config when record?  Where can i see them?

### ISSUE THREAD

**Issue by ZiqiWill** [rrweb-io/rrweb#183]
hi 请问在Record的时候是否有一些options可以自己定义或者修改，在文档中没有发现关于这方面的内容

**Comment by Yuyz0112** [comment]
https://github.com/rrweb-io/rrweb/blob/master/src/types.ts#L128

这个是的 record options。抱歉文档有点过期

**Comment by ZiqiWill** [comment]
Thanks Man, I'am going to close this
