### ISSUE TITLE
Usage example

### ISSUE THREAD

**Issue by lucked** [rrweb-io/rrweb#185]
Hi can someone share with me a DEMO project? with recording and playing?
i cant make this work :/
thanks

**Comment by nikhilrayaprolu** [comment]
Some of the examples I found online:
https://github.com/getsentry/sentry-rrweb/tree/master/demo
https://github.com/corcd/rrweb-server

https://github.com/AdamSD1/rrwebTest

https://github.com/kharybdys/RRServer
https://github.com/kharybdys/RRWeb

https://github.com/getsentry/sentry-rrweb
https://github.com/getsentry/rrweb-json-player

https://github.com/brendanbernas/rrweb-test
