### ISSUE TITLE
Node with id 'xxx' not found in [object]

### ISSUE THREAD

**Issue by jwentao** [rrweb-io/rrweb#190]
我的代码
```
export function initWebReplay () {
  console.log('initWebReplay');
  const instance = require('rrweb');
  instance.record({
    emit (event, isCheckout) {
      if (isCheckout) {
        eventsMatrix.push({
          id: eventsMatrix[eventsMatrix.length - 1].id + 1,
          events: []
        });
      }
      eventsMatrix[eventsMatrix.length - 1].events.push(event);
    },
    checkoutEveryNms: 60 * 1000
  });
  // 定时清除冗余的数据
  setInterval(() => {
      while (eventsMatrix.length > 4) {
        eventsMatrix.shift();
      }
  }, 5000);
}
```
使用了checkoutEveryNms，在回放时出现了Node with id 'xxx' not found in [object] 警告，但是播放看着没什么问题
![image](https://user-images.githubusercontent.com/21285362/77989162-b20d1080-7350-11ea-98e4-c93439ac192a.png)

**Comment by yogendra3236** [comment]
Hi, could anyone find, how to resolve this issue?
I got this issue while trying to play the Events with Replayer.

**Comment by Yuyz0112** [comment]
Hi @yogendra3236 
Did you use the `checkout` config?

**Comment by yogendra3236** [comment]
Hi, I don't know about it. Could you pls suggest me with some reference to it? Thanks.

**Comment by Yuyz0112** [comment]
Maybe you can provide your events log for debugging? @yogendra3236

**Comment by yogendra3236** [comment]
Yes, this is the error response in browser's console, and I'm getting blank screen with cursor. @Yuyz0112 

```
[replayer] Node with id '4486' not found in {…}

adds: Array []
attributes: Array [ {…} ]
removes: Array(3) [ {…}, {…}, {…} ]
source: 0
texts: Array []
<prototype>: Object { … }
```

**Comment by yogendra3236** [comment]
Any update on this? @Yuyz0112

**Comment by yogendra3236** [comment]
Hi @Yuyz0112 , Sorry for bothering you so much, but I found the `delay` key in the Events' each object when logging in the browser, however, this key is not present anywhere in the Events array.
And, I guess, due to this particular key, it happens to not play the proper recording. Could you help me, please?

Example-
```
[{
   data: {source: 3, id: 1, x: 0, y: 8847.7783203125}
   delay: 8435
   timestamp: 1589276648869
   type: 3
}]
```

**Comment by yogendra3236** [comment]
Hi @Yuyz0112 , I've generated an Events log which is not playing using Replayer. 
Visit [here](https://meandyoubucket.s3.ap-south-1.amazonaws.com/records.json)

Could you pls have a look? Thanks!

**Comment by Yuyz0112** [comment]
Hi @yogendra3236 

The events log above is missing a full snapshot. This usually caused by a size limit in your backend(Nginx body, etc).

**Comment by yogendra3236** [comment]
Hi @Yuyz0112 , thanks! But, I've noticed that whenever I'm storing events from localhost to the remote server, it works fine, but causes issue when I try to apply it in the server itself.
I get this error- 
`uncaught DOMException: Failed to execute 'deleteRule' on 'CSSStyleSheet': The index provided (xx) is larger than the maximum index (xx)`

Could you pls help me if you know how to resolve it?

**Comment by Yuyz0112** [comment]
What do you mean apply in the server? Are you using something like JSDOM
 in the server side? Since server env does
 not have browser APIs.

**Comment by yogendra3236** [comment]
Nope, I'm not using JSDOM or anything like this. I'm getting the above error in React-Frontend while playing the events with Replayer. Could you tell me what this error is about and why does it appear?
@Yuyz0112

**Comment by Yuyz0112** [comment]
@yogendra3236 Maybe share the events for debugging?

**Comment by zissop** [comment]
> Hi @yogendra3236
> 
> The events log above is missing a full snapshot. This usually caused by a size limit in your backend(Nginx body, etc).

Hello

What is a full snapshot and how can we locate it? I'm having the same issue. Is it the first event?

**Comment by Yuyz0112** [comment]
@zissop It's a snapshot with `type` equals to `2`

You can upload your events log if possible, and I will help you to debug it.

**Comment by Yuyz0112** [comment]
Please reopen this if there is any further information.

**Comment by omairnabiel** [comment]
Is there a solution to this? I'm facing the same issue. I also think that this might be the reason why some parts of my DOM Recording does replay properly. The dom seems out of place. See the image

<img width="1439" alt="Screenshot 2021-06-28 at 2 09 36 PM" src="https://user-images.githubusercontent.com/13148988/123677391-7ff1a380-d85e-11eb-87aa-d403be0b69e6.png">

**Comment by wbcs** [comment]
inlineStylesheet:true
