### ISSUE TITLE
Mouse pointer position is not replayed correctly

### ISSUE THREAD

**Issue by dpnishant** [rrweb-io/rrweb#192]
I attempted recording multiple pages with the recorder client while everything else seems to work fine, I see that the mouse pointer position and the click co-ordinates are not represented correctly in the replay. The mouse hover and click positions are always appear to be somewhere away from the actual elements. Any way to debug/fix this?

**Comment by Yuyz0112** [comment]
@dpnishant Could you provide an URL or some recorded events for debugging?

**Comment by dpnishant** [comment]
@Yuyz0112 You can download the events array as a JS file from this link. This is a demo/test application. http://www.mediafire.com/file/5x7uewvhpn63b54/events-test.js.zip

**Comment by dpnishant** [comment]
@Yuyz0112 Is that useful to you?

**Comment by Yuyz0112** [comment]
Hi @dpnishant 

I've merged a patch fix some initial offset problem. Could you provide a public URL to a site can reproduce the problem, or if you can help verify whether the patch works?

**Comment by dpnishant** [comment]
Hey @Yuyz0112 It works perfectly now. Thanks for the quick fix. 👍

**Comment by yousefalaqra** [comment]
@dpnishant 
Could you please describe what you did to solve the issue?
