### ISSUE TITLE
能否由用户强制触发checkout

### ISSUE THREAD

**Issue by shmilyoo** [rrweb-io/rrweb#194]
checkoutEveryNms: 1000 * 60 * 10 // 我这里checkout时间范围是10分钟
由于我这边系统录屏数据非常大，所以在存储到mongodb的时候，采用的是一天的数据存到一个collection中。
这样就导致了在0点时候，之后的数据会存储到新的collection中，那在当天的第一个分片，如果是从0点开始连接着前一天的连续数据，就会白屏无法播放。
rrweb可否提供用户强制checkout的功能，这样我在跨越0点的时候，强制checkout一下，避免此类问题。

**Comment by Yuyz0112** [comment]
停止录制再重新录制可以做到预期的效果吗？

**Comment by shmilyoo** [comment]
> 停止录制再重新录制可以做到预期的效果吗？

感谢，有效。贴出代码。 我这里是本地存入indexedDB，缓存发送， 每个发送的请求中为10条数据，进行 pako压缩。
后台是golang， 每天的数据存入单独的mongodb collection，在golang中还需要对 每个请求的10条数据的时间进行判断，在0点的跨度时间时，10条数据很有可能需要存入两个collection。 
这样就可以比较好的避免每天第一个录制时间段的白屏情况。
```
// 用来判断是否到了新的一天，服务端需要存入新的mongodb collection（golang服务端是东八区，这里的时间需要转换为东八区的时间判断）
let day = getServerDay();
let stopFunc;

async function startRecord() {
    stopFunc = record({
      emit(event, checkout) {
        if (checkout) setNewSession();
        const newDay = getServerDay();
        if (newDay !== day) {
          // console.log('日期不同，停止重启录制', newDay, day);
          day = newDay;
          rrwebSessionSet();
          // console.log('stopfn is restart ', stopFunc);
          if (stopFunc) {
            stopFunc();
            startRecord();
          }
        } else {
          storagePush(event);
        }
      },
      checkoutEveryNms: 1000 * 60 * 10
    });
}

startRecord();
check();
```

**Comment by Yuyz0112** [comment]
在 0.8 的版本里预计会提供更强大、可控的”编辑模式“，例如把一段五分钟的 session ”编辑"为 03:30 - 04:45 的片段，可能会比 checkout 的适用场景更广。
