### ISSUE TITLE
Pack/Unpack turning array of events into object

### ISSUE THREAD

**Issue by alexcroox** [rrweb-io/rrweb#201]
Using cdn.jsdelivr.net/npm/rrweb@0.7.33/dist/rrweb.min.js

I have the following being sent to my server:

`window.rrweb.pack(arrayOfEvents)`

arrayOfEvents looks like this:

![ss1](https://p193.p3.n0.cdn.getcloudapp.com/items/ApujNpg1/Screenshot%202020-04-19%20at%2020.15.02.png?v=6d6c003f14349bebd08796d374365de2)

Then when it comes to playback:

```
let unpackedEvents = window.rrweb.unpack(this.modalData.events)

console.log(unpackedEvents)
```

![ss2](https://p193.p3.n0.cdn.getcloudapp.com/items/Z4uLZ0Gn/Screenshot%202020-04-19%20at%2020.16.09.png?v=377838dbc400c3c0c8165577e072a6d9)

The number of items seems to be less and also notice the v: "v1" key it adds to the object, when this is supposed to be an array of objects.

Am I missing a step here?

**Comment by Yuyz0112** [comment]
Hi @alexcroox 

Both pack and unpack use single event as the parameter, so you need to change code to this:
```js
arrayOfEvents.forEach(event => window.rrweb.pack(event))

```

**Comment by alexcroox** [comment]
Ah that makes sense, thanks!

**Comment by lazyvab** [comment]
@alexcroox, @Yuyz0112 
No, it is not recommended to compress each event individually.

Read what [documentation](https://github.com/rrweb-io/rrweb/blob/master/docs/recipes/optimize-storage.md#compress-the-whole-session) says:

> Use packFn to compress every event may not get the best result.
> It's recommended to compress the whole session in the backend, which will have a more efficient compression ratio for some algorithms like deflate.

When we compress whole events object, the compression algorithm has more probability to find similarities between different events objects and thus can reduce the overall size dramatically.

To avoid conversion of array to object, you should wrap events array inside an object like this:
```javascript
const packedData = rrweb.pack({ events });

const unpackedData = rrweb.unpack(packedData);
const eventsAfterUnpack = unpackedData.events;
```

Notice that `v: v1` property is still added by the compression library but this time it would be on the wrapping object and not impact events object.

Hope this is still useful for you and others. :)
