### ISSUE TITLE
这个没有记录请求及console的日志内容吗

### ISSUE THREAD

**Issue by trtrtr6** [rrweb-io/rrweb#204]
这个没有记录请求及console的日志内容吗，如果有这些就可以完美复现当时环境的问题了，fullstory和logrocket我看都有记录这些，不过是收费的😂😂😂

**Comment by Yuyz0112** [comment]
没有，因为不是还原 Web 视图必要的信息，所以不在 rrweb 的核心代码。

后续可以作为插件加入进来，也可以在 user-land 结合 custom event 自行实现。
