### ISSUE TITLE
'Null' after each node

### ISSUE THREAD

**Issue by zhanseitaliev** [rrweb-io/rrweb#208]
Hello everyone. I am just mastering this library. 
Did everything as written in the instructions. But when replay, null is inserted after each element. What could it be?
Urgently need a solution!

![download](https://user-images.githubusercontent.com/36212648/81059341-13954180-8ef2-11ea-9d22-2518fee36957.png)

![Untitled](https://user-images.githubusercontent.com/36212648/81059386-2445b780-8ef2-11ea-942f-1b7adaf47be3.png)

**Comment by Yuyz0112** [comment]
Could you please provide the events log for debugging?

**Comment by zhanseitaliev** [comment]
@Yuyz0112 Created a demo for verification

An array of events:  [Link](https://webvisor.shopter.tech/api/record)
Player page: [Link](https://webvisor.shopter.tech/test)
Recording page: [Link](https://allwatches1.myshopify.com/)

**Comment by Yuyz0112** [comment]
Hi @zhanseitaliev, thanks for the details.

I think maybe your backend code has done some wrong transformation on the data.

I can see the recorded page emit events like this in the network panel:
![image](https://user-images.githubusercontent.com/13651389/81066186-4e59a280-8f0f-11ea-90d1-893131aa3de2.png)

But the text content becomes `null` when getting them from backend again

![image](https://user-images.githubusercontent.com/13651389/81066231-60d3dc00-8f0f-11ea-8846-836ac199684b.png)

**Comment by zhanseitaliev** [comment]
@Yuyz0112 Thank you so much! You really helped me out. 
I used Laravel framework in the backend. ORM Attribute Casting incorrectly converted character escapes.
