### ISSUE TITLE
There is an error when moving to the next page

### ISSUE THREAD

**Issue by zhanseitaliev** [rrweb-io/rrweb#209]
An error appears while playing back actions in the player.
When the visitor moves to the next page, the player stops, and an error appears in the console.

Error in console:  `Uncaught TypeError: t.setAttribute is not a function`

Events are sent to the server for storage every second.

**Comment by Yuyz0112** [comment]
Close due to un-reproducible. Feel free to reopen if the problem still happens.

**Comment by juancruzgardey** [comment]
@Yuyz0112 I have the same problem when I replay the interactions in the eBay website. I attach the events that I'm trying to replay. [events_ebay.zip](https://github.com/rrweb-io/rrweb/files/5034928/events_ebay.zip)

It's an error that use to happen in other websites also, especially in the highly dynamic ones.

I use the recorder as a web-extension, starting the capture whenever each page is loaded.

**Comment by Yuyz0112** [comment]
@juancruzgardey Looks like you are using the chrome extension to record across multiple pages, but the DOM map are not reset correctly.

Could you share your record code for debugging?

**Comment by juancruzgardey** [comment]
@Yuyz0112 sorry for the delay. I attach a zip that contains the web-extension.

Thanks!

[ScreenRecorderDebugging.zip](https://github.com/rrweb-io/rrweb/files/5226469/ScreenRecorderDebugging.zip)
