### ISSUE TITLE
Sending large array of Events using Fetch API throws error!

### ISSUE THREAD

**Issue by yogendra3236** [rrweb-io/rrweb#210]
Hi, thanks for this amazing tool. But, there are certain issues that I've been facing using it.

1. When I send a small array of events of up to 100 lengths through the node-fetch to store them in elastic search, it works fine, but beyond the limit, it throws error like 'Failed to fetch'.

2. Could you provide a better alternative to store & manage events, as storing a large array of about the length of 1K+ and size more than 100+ MBs, really takes time and may corrupt the DB.

Any help would be highly appreciated. Thanks!

**Comment by Yuyz0112** [comment]
Could you provide the error message about the storage?

**Comment by yogendra3236** [comment]
Thanks for the quick response. This is what I'm getting- `TypeError: Failed to fetch`

**Comment by rifaideen** [comment]
I think this is the issue in your server-side when you send bulk data. However, you can occasionally save the new data every 15 to 30 secs to resolve this error.

**Comment by yogendra3236** [comment]
Yes, this issue gets resolved. I'm sending the array of new events only from the client to the server at the regular interval and pushing it to the array in the backend only. Thanks!

Closing now!
