### ISSUE TITLE
chrome disable cache 后，添加了custom event  播放时 event 缺失

### ISSUE THREAD

**Issue by trtrtr6** [rrweb-io/rrweb#211]
在 chrome 设置 disable cache 的环境下，我添加了custom event，  记录进去的event有40多个，播放时通过 event-cast 监听所有event，发现只有20多个，缺失了很多，去掉disable cache之后刷新又正常了，看了下代码是disable cache环境下触发了resume导致的

**Comment by Yuyz0112** [comment]
可以发一下 events log 用于 debug 吗？

**Comment by trtrtr6** [comment]
见附件，你们看看，也可能是我哪里操作有问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"yz-yu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月8日(星期五) 下午4:51
收件人:&nbsp;"rrweb-io/rrweb"<rrweb@noreply.github.com&gt;;
抄送:&nbsp;"000000000"<2450260012@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [rrweb-io/rrweb] chrome disable cache 后，添加了custom event  播放时 event 缺失 (#211)





 
可以发一下 events log 用于 debug 吗？

**Comment by Yuyz0112** [comment]
@trtrtr6 邮件回复的 github comments 好像不会把附件也上传到 issue 里

**Comment by trtrtr6** [comment]
[events2.js.zip](https://github.com/rrweb-io/rrweb/files/4598189/events2.js.zip)

**Comment by Yuyz0112** [comment]
目前没有更多的线索和复现思路。如果问题仍然存在，可以提供一个可复现代码继续调查。
