### ISSUE TITLE
Render Frame 0

### ISSUE THREAD

**Issue by jwbrew** [rrweb-io/rrweb#216]
When initalising a new Replayer, if `play()` is not called, there is just a blank screen with a cursor position available. Should it be possible to show the first frame of the recording?

**Comment by Yuyz0112** [comment]
Good idea, going to add this

**Comment by Yuyz0112** [comment]
Good idea, going to add this

**Comment by eoghanmurray** [comment]
One problem with this is that you don't get a chance to attach a handler for the `fullsnapshot-rebuilded` event.

I see that there is special `setTimeout` treatment for the `Resize` event, but maybe that's for a different purpose?
