### ISSUE TITLE
can not record dynamic canvas

### ISSUE THREAD

**Issue by lxm** [rrweb-io/rrweb#218]
can not record dynamic canvas in page

**Comment by Yuyz0112** [comment]
Same to #60

**Comment by FrankRoc** [comment]
为什么我下载了最新版(0.9.7)的rrweb 还是不能录制canvas呢

**Comment by linweiboy** [comment]
> 为什么我下载了最新版(0.9.7)的rrweb 还是不能录制canvas呢
动态的canvas不能录制，请问有好的解决方案吗

**Comment by Yuyz0112** [comment]
https://github.com/rrweb-io/rrweb/blob/master/docs/recipes/canvas.zh_CN.md

请参照 canvas 场景示例
