### ISSUE TITLE
How about a chat channel?

### ISSUE THREAD

**Issue by Yuyz0112** [rrweb-io/rrweb#22]
I think GitHub is better for tracking feature requests and reproducible bugs. But as a new project, rrweb's users may have many ideas in early stage or meeting some small bugs which need help.

So how about a chatting room, like:
- slack
- discord
- gitter

Of course, we will only choose **one** so any suggestion is welcome.

**Comment by pd4d10** [comment]
How about Spectrum? It is acquired by GitHub recently.

Not an expert of this topic... Just add another possible option.

**Comment by TimoSta** [comment]
I second the suggestion to use Spectrum.

I'm actively using the Zeit Spectrum channel. I feel like it's a great middle ground between chat tool and forum/thread style support platform.

**Comment by Yuyz0112** [comment]
I've already tried slack/discord/gitter/spectrum and will choose one this weekend.

Thanks for all suggestions:)

**Comment by Yuyz0112** [comment]
https://gitter.im/rrweb-io/community?utm_source=share-link&utm_medium=link&utm_campaign=share-link

Our gitter community has launched!

**Comment by eoghanmurray** [comment]
We are moving to Slack from gitter now I think. 
@Yuyz0112 is there a link for people to join Slack?

**Comment by Yuyz0112** [comment]
@eoghanmurray I've update the slack channel in README, here is the link: https://join.slack.com/t/rrweb/shared_invite/zt-siwoc6hx-uWay3s2wyG8t5GpZVb8rWg
