### ISSUE TITLE
Emit event after stopping recording

### ISSUE THREAD

**Issue by mpstv** [rrweb-io/rrweb#227]
Hello everyone, I found some strange behavior when recording. 
Sometimes (this does not always happen) after stopping recording (calling the stop function) rrweb emit another event:

![image](https://user-images.githubusercontent.com/54762420/83434019-63f4b600-a442-11ea-8b17-244d122a9010.png)

It seems that this event should be included in the list of events that occurred before the stop, but for some reason this does not happen. 

Perhaps the stop function should be asynchronous? The problem can be reproduced using this [repository](https://github.com/mpstv/rrweb-event-after-stop-recording-problem).

**Comment by Yuyz0112** [comment]
Thanks for the report, this may happen since the observers are async. Maybe we can add a `stopped` flag to stop further emit.

**Comment by mpstv** [comment]
I'm not sure, but it seems to me that this event really happened before the stop, but it was emitted later. To make sure, need to debug this problem more. I think it's worth considering the option with an asynchronous stop function too.

**Comment by randy-johnson** [comment]
One of my concerns: will all the events get sent after the moderator stops the recording. I do not see a problem if it needs to finish sending the events after stop has been issued.

**Comment by Yuyz0112** [comment]
After thinking about this issue, I feel ok to have the stop function with a semantic of "stop observer".

It's also possible to make the stop function become async and the semantic of resolved is "observer already stopped", but need introduce some breaking changes on the interface.

So it may be good to do this in version 0.9. @mpstv Please let me know if you need this feature in a very soon time, and we can schedule a release earlier.
