### ISSUE TITLE
Replay Error: Uncaught TypeError: Cannot read property 'querySelectorAll' of null

### ISSUE THREAD

**Issue by mpstv** [rrweb-io/rrweb#228]
Hi.
Sometimes when replay record, i getting an error:
```
Uncaught TypeError: Cannot read property 'querySelectorAll' of null
``` 
I did not reveal the pattern of error, but at a high level of review, this happens on this [line](https://github.com/rrweb-io/rrweb/blob/ee73bd4919b5db1d380981fd9249a7452cdef474/src/replay/index.ts#L747).

**Comment by Yuyz0112** [comment]
Hi @mpstv, could you provide the events for debugging?

**Comment by mpstv** [comment]
I introduced some changes to [repository](https://github.com/mpstv/angular-components-rrweb-problem) and now you can use it to reproduce this error.

![querySelectorAll_reproduce](https://user-images.githubusercontent.com/54762420/83517236-36127e80-a4e1-11ea-9b31-00165d34c0b1.gif)

For using this app you should clone repository and run command:
```
npm i && ng serve
``` 

After it app will be available on `localhost:4200`
