### ISSUE TITLE
Compiling RRweb from master gives Uncaught TypeError

### ISSUE THREAD

**Issue by nikhilrayaprolu** [rrweb-io/rrweb#229]
Uncaught TypeError: Cannot read property 'appendChild' of null
Specifically at:
![image](https://user-images.githubusercontent.com/15216503/84079708-a5640300-a9f8-11ea-87a8-7721c5b1cb04.png)

**Comment by Yuyz0112** [comment]
Hi @nikhilrayaprolu 

Could you confirm the version of the typescript you are using to compile the project?

**Comment by nikhilrayaprolu** [comment]
![image](https://user-images.githubusercontent.com/15216503/84122167-a4ad8a00-aa55-11ea-9177-3beddeba8f82.png)


also, I checked by compiling the 0.7.33 version of the release, it worked without errors.

**Comment by Yuyz0112** [comment]
Please try the latest master
