### ISSUE TITLE
Allow custom privacy selectors

### ISSUE THREAD

**Issue by samjbmason** [rrweb-io/rrweb#23]
Currently there are two-class names that can be added to hide data being input into them. It would be great if we could configure these class names

**Comment by Yuyz0112** [comment]
#1 Described why we use this strategy in the issue, and feedback and discussion are welcomed.

**Comment by samjbmason** [comment]
Yeah that’s correct.

**Comment by Yuyz0112** [comment]
It should not be hard to implement, I could add this when I'm free. And if anyone is interested in doing this, I would be glad to help.

**Comment by samjbmason** [comment]
I would be happy to give it a go tonight. From my understanding I would need a PR to implement in the snapshot repo and this one

**Comment by Yuyz0112** [comment]
Yes you are right, maybe export two functions like `getIgnoreClass` and `getBlockClass` from the snapshot repo will make the code cleaner.
