### ISSUE TITLE
How to map Js line errors to Typescript files

### ISSUE THREAD

**Issue by nikhilrayaprolu** [rrweb-io/rrweb#230]
![image](https://user-images.githubusercontent.com/15216503/84126735-ef320500-aa5b-11ea-8a9b-d1bd475a4b6e.png)

Currently, if I make modifications to the rrweb source code, I could only see where the error is in the generated Js codes but there is no mapping to the original ts files. How to map the errors to the respective ts files?

**Comment by Yuyz0112** [comment]
Run `npm run bundle` to compile rrweb will generate the source map aside from the bundled files. And the browser will use the source map to show the original LOC of code.
