### ISSUE TITLE
Recording a Replay - Record doesn't emit any events

### ISSUE THREAD

**Issue by nikhilrayaprolu** [rrweb-io/rrweb#231]
I am trying to build co-browsing feature, I thought that a replay would emit events if the atrributes on iframe are removed - (removing sandbox) but even after I removed the sandbox attribute, there were no events being triggered!

Is there any restriction applied for not recording the events in a replay?

I am doing this so that I can build the co-browsing feature similar to  https://upscope.io/ using rrweb!

**Comment by Yuyz0112** [comment]
The sandbox strategy makes it safe to replay things: https://github.com/rrweb-io/rrweb/blob/master/docs/sandbox.md

But I think it's reasonable to add a method to remove the sandbox attribute if the user really has the use case.

BTW, I've already built a co-browsing tool like this, and I scheduled to open-source it in the coming two weeks.

**Comment by nikhilrayaprolu** [comment]
Thanks for the update @Yuyz0112 , I thought of building an open-source co-browsing app built on top of rrweb. But anyway, will be waiting for your co-browsing tool!

**Comment by FeSeason** [comment]
@nikhilrayaprolu  I also have the same scenario. Do you have any solution in using rrweb?
