### ISSUE TITLE
Is there a way to not show a section in the player?

### ISSUE THREAD

**Issue by randy-johnson** [rrweb-io/rrweb#232]
I saw this in the docs:  

`An element with the class name .rr-block will not be recorded. Instead, it will replay as a placeholder with the same dimension.`

The screen that is recording has a div at the top and a div on the left and the large view div area in the middle.  We were hoping to only record the big div area and not the other 2 divs and not have the placeholders either

Is this possible?

**Comment by Yuyz0112** [comment]
Similar to #111. I will update comments about why this is a little hard to implement.
