### ISSUE TITLE
hijack the console API and record corresponding events

### ISSUE THREAD

**Issue by Luiz-N** [rrweb-io/rrweb#234]
i'm looking to be able to capture events in the console while using rrweb. Specifically error events so this feature would be perfect. Any suggestions or examples I could look at for "hijacking the console" so that i could give this a try?

**Comment by Yuyz0112** [comment]
Hi @Luiz-N 

I would suggest dividing the development of this feature into two parts:
1. capture console calls as rrweb events
2. display rrweb console events during replaying

For the first part, you can check some existing implementation like [this](https://github.com/getsentry/sentry-javascript/blob/a257a8aa1b46b8f3f3a48eb4d1b4bf89f9893095/packages/integrations/src/captureconsole.ts).

And for the second part, I'm not quite sure what's the best way to do it. I mean maybe we can call the console API during replaying to show the events we captured, or we can display them in part of the replayer. Any suggestions are welcomed and it should not block the first part.

**Comment by alexcroox** [comment]
This is how LogRocket handles it, showing both the console output and network calls in sync with the playback video.

It's incredibly handy for debugging errors while watching the playback

![image](https://user-images.githubusercontent.com/1065835/87186258-19891380-c2e3-11ea-9590-8659877669c4.jpg)

**Comment by Yuyz0112** [comment]
https://github.com/rrweb-io/rrweb/blob/master/docs/recipes/console.md

**Comment by alexcroox** [comment]
Amazing work thank you!!
