### ISSUE TITLE
Standardize support for non-attribute properties in protocol

### ISSUE THREAD

**Issue by DvdGiessen** [rrweb-io/rrweb#24]
Right now, the protocol doesn't have a standardized way for storing non-attribute data directly linked to an element. One example of this is the `isSVG` property, which is [stored separately in the element object](https://github.com/rrweb-io/rrweb-snapshot/blob/master/src/snapshot.ts#L160). Another example is element widths and heights, which are instead [stored in a few internal attributes](https://github.com/rrweb-io/rrweb-snapshot/blob/master/src/snapshot.ts#L150-L154).

Now, conceivably as we extend rrweb, we'll have a need to add additional properties. In fact, I've been working on supporting transmitting of media state (whether a video is playing, paused, when the user seeks to another point in the video, etc) and I've ran into the same issue. (See [here](https://github.com/DvdGiessen/rrweb/tree/media-elements) and [here](https://github.com/DvdGiessen/rrweb-snapshot/tree/media-elements) for that work-in-progress implementation.) Right now I've opted to add an additional property and store my data there, but it'd be nice to have a standardized way for storing such data.

I think using a structure similar to how currently events are modelled might be nice (using a object with a `type` property referring to an enum). This will allow future extensions / support for additional properties without breaking existing implementations, which can just skip non-supported types.

We can then also move existing data such as the `isSVG` flag or the `width` and `height` data to this new structure.

However, this approach might also introduce some overhead, and I'm not sure how much of a problem that is going to be.

@Yuyz0112 What do you think is the best way to deal with this?

**Comment by Yuyz0112** [comment]
Just read the description and the commits about media support, it looks nice. I Still need some time to think about this carefully, but the following points may be considered as a design principle:
1. It will be nice if the data structure is similar to the node's original data interface, so the serializer is will be more transparent to the developer.
2. It is important to have a data structure with less overhead, I know there is a trade-off about namespace or abstraction, but still need to be careful here.

Currently, the special cases you've mentioned are following these rules, like only add a flag when it really needs, or re-use the attributes object to store some internal attributes. However, there are absolutely some spaces to improve, but if there is a breaking change, we need to do that ASAP before someone use rrweb in production heavily:)

**Comment by Yuyz0112** [comment]
How about use a `properties` key to store these states?

**Comment by DvdGiessen** [comment]
A `properties` key would be similar to the `mediaState` object I used, reusable for properties from all types of DOM objects. I think keeping it typed would be nice to have.

However, I'm not entirely sure that provides the extensibility I meant. A bit like the `width` and `height`: While storing them as strings in custom-named attributes works, it feels like a bit of a hack. So, I meant, if we're going to add new arbitrary values in the future, what is the preferred way to store them? A `properties` key only addresses DOM object properties.

I think "we add new keys" is a acceptable answer to that question. But I want to make sure that we agree that is the way to do it, since in the README you mentioned wanting to have a stable data structure for v1.0, and it also implies we'll from now on have to deal with new/missing keys for compatibility between different versions and cannot make any of these keys required in the typedef.

**Comment by DvdGiessen** [comment]
Alright, I'll update and my media branch to include this.
