### ISSUE TITLE
javascript Timer on the page

### ISSUE THREAD

**Issue by randy-johnson** [rrweb-io/rrweb#240]
I  have another issue.

We recently added a Javascript counter on the page that we are recording and it is generating an event every second. 

Is there anyway to stop rrweb from recording event being generated every second?  I tried .rr-ignore and rr-block which hides the timer in the player but the events are still generated

**Comment by Yuyz0112** [comment]
Could you produce a demo code for this?
`.rr-block` is designed for this usage, and I would like to check whether it works correctly.

**Comment by randy-johnson** [comment]
I had a thought.  I put the class on the parent div instead of the div itself and it seemed to take care of the issue.  I will work on getting a demo.

**Comment by Yuyz0112** [comment]
@randy-johnson I think this issue has been fixed with the latest patch.
