### ISSUE TITLE
Both rrweb-record-pack and rrweb-record declare same global variable

### ISSUE THREAD

**Issue by alexcroox** [rrweb-io/rrweb#243]
Unless I'm missing something it's not possible to use the record and pack functions together from the CDN:

https://cdn.jsdelivr.net/npm/rrweb@0.8.2/dist/record/

Since they both declare the same global variable `rrwebRecord` the last script to load overwrites the other.

**Comment by Yuyz0112** [comment]
@alexcroox you are right, but what's the scenario to use both of them? rrweb-record-pack is a combination of record and pack.

**Comment by alexcroox** [comment]
Ah I tried that initially and it didn’t seem to contain both. I will try again

**Comment by Yuyz0112** [comment]
Yes, the interface should works like this:

```
rrwebRecord() // <- the record function

rrwebRecord.pack() // <- the pack function
```
