### ISSUE TITLE
按钮被点击时只需要截屏一次的API吗？

### ISSUE THREAD

**Issue by zhaoxm2016** [rrweb-io/rrweb#245]
按钮被点击时只需要截屏一次的API吗？

**Comment by Yuyz0112** [comment]
@zhaoxm2016 没太理解问题。是说想要实现点击一次按钮，把当前视图保存下来，并且可以重建吗？

**Comment by zhaoxm2016** [comment]
嗯是的，可以认为是点击按钮，截屏一次保存起来，然后重建

**Comment by zhaoxm2016** [comment]
大神是在北京吗~

**Comment by zhaoxm2016** [comment]
大神是在北京吗







		 	     
 赵向明 
信美人寿相互保险社  
 电话：01086398282-8518 
 邮箱：mike.zhao@trustlife.com 
 地址：北京 
   

	 访问企业主页         
 信息安全声明：本邮件包含信息归发件人所在组织所有，发件人所在组织对该邮件拥有所有权利。
请接收者注意保密，未经发件人书面许可，不得向任何第三方组织和个人透露本邮件所含信息的全部或部分。以上声明仅适用于工作邮件。
Information Security Notice: The information contained in this mail is solely property of the sender's organization. 
This mail communication is confidential. Recipients named above are obligated to maintain secrecy and are not permitted to disclose the contents of this communication to others.  ------------------------------------------------------------------
发件人：yz-yu<notifications@github.com>
日　期：2020年07月15日 14:23:24
收件人：rrweb-io/rrweb<rrweb@noreply.github.com>
抄　送：zhaoxm2016<mike.zhao@trustlife.com>; Mention<mention@noreply.github.com>
主　题：Re: [rrweb-io/rrweb] 按钮被点击时只需要截屏一次的API吗？ (#245)

@zhaoxm2016 没太理解问题。是说想要实现点击一次按钮，把当前视图保存下来，并且可以重建吗？

**Comment by Yuyz0112** [comment]
@zhaoxm2016 

如果不需要持续的 session，用 [rrweb-snapshot](https://github.com/rrweb-io/rrweb-snapshot) 就可以了

```
const [snap] = rrweb.snapshot(document);
rrweb.rebuild(snap, document)[0]; -> 重建后的 DOM
```

**Comment by Yuyz0112** [comment]
先关闭 issue 了，如果还有问题可以随时 reopen。
