### ISSUE TITLE
why does resume take a `timeOffset`?

### ISSUE THREAD

**Issue by eoghanmurray** [rrweb-io/rrweb#248]
I'm trying to understand something with the API.

Why can we pass in a timeOffset to the resume() function?

 - Is it true that resume should not apply any of the events leading up to the current paused time?
 - Is it an error if the replayer is paused at time X and resume() is called with time Y?

Thanks!

**Comment by Yuyz0112** [comment]
The resume API will be departed in v1.0, and use `play` under the hood in v0.9.

More details: https://github.com/rrweb-io/rrweb/issues/274
