### ISSUE TITLE
previousSibling and nextSibling is exist in document but have never serialized

### ISSUE THREAD

**Issue by wsq547ak** [rrweb-io/rrweb#251]
in some scene, previousSibling and nextSibling is exist in document but have never serialized. so   in observer function of pushAdd,  just set parentId and serialized curNode , shouldnt set previousId and nextId. after all added node in adds array ,in payloadCallback function ,set adds  node previousId and nextId.

**Comment by Yuyz0112** [comment]
@wsq547ak Which version are you using? And could provide a reproducible URL for me to debug?

**Comment by wsq547ak** [comment]
an old version, sry, i check it in a new one

**Comment by Yuyz0112** [comment]
Feel free to reopen this if you still find issues with the latest version.
