### ISSUE TITLE
Flush is never emitted in applyIncremental

### ISSUE THREAD

**Issue by movrdx** [rrweb-io/rrweb#254]
Ever since https://github.com/rrweb-io/rrweb/commit/4bf533a675c8a4430ef4718fa8f55cb0984be5ad, incremental changes involving node additions have been broken during playback. It seems like this completely breaks the 0.8.3 release.

Here is an event JSON: https://gist.githubusercontent.com/movrdx/39c9647bbe83b2b44aef8ad03d950a30/raw/e9e5d972437a7569d45320311cd16ae2e0ae0b2e/events.json

Here is the appearance is in 0.8.2 at finish playback:

![image](https://user-images.githubusercontent.com/30243474/87863704-b0bd1f00-c912-11ea-997e-b17c1f306c20.png)

In 0.8.3:

![image](https://user-images.githubusercontent.com/30243474/87863718-e4984480-c912-11ea-919a-b99f2878b75b.png)

**Comment by Yuyz0112** [comment]
Thanks @movrdx 

Just fixed in 0.8.4
