### ISSUE TITLE
求助：我在录制y页面中将信息保存中localstarge中，取出信息有错误，显示“Replayer need at least 2 events”？

### ISSUE THREAD

**Issue by aiwenForGit** [rrweb-io/rrweb#255]
我也录制页面中添加了如下的代码：
let events = [];
localStorage.setItem("abcd", "");
rrweb.record({
  emit(event) {
    // 将 event 存入 events 数组中
    events.push(event);
	var body = JSON.stringify(events);
	var str = events.toString();
	console.log(body);
    localStorage.setItem("abcd", body);
  },
});

中回放按钮中写了如下代码：

msgs = JSON.parse(localStorage.getItem("abcd")); 
new rrwebPlayer({
  target: document.body, // 可以自定义 DOM 元素
  data: {
   msgs,
  },
});

一直回放不成功，console台显示错误**“Replayer need at least 2 events”**

**Comment by aiwenForGit** [comment]
页面上一直空白状态，不知道是否跟浏览器有关，我是在360chrome中调试的。

**Comment by Yuyz0112** [comment]
```diff
msgs = JSON.parse(localStorage.getItem("abcd"));
new rrwebPlayer({
  target: document.body, // 可以自定义 DOM 元素
  data: {
-    msgs,
+    events: msgs
  },
});

```

试一下

**Comment by aiwenForGit** [comment]
@Yuyz0112 非常感谢大神的帮忙，确实可以了，另外我问下如果我采用json文件的方式存储，如果碰到转义字符，还需要转换回来么

**Comment by Yuyz0112** [comment]
@aiwenForGit 比如什么样的转义？

**Comment by aiwenForGit** [comment]
比如“\”,"\\"","\n"，引号，回车，换行，斜杠等等。

**Comment by Yuyz0112** [comment]
如果你的存储过程是类似 `JSON.parse(JSON.stringify(events))` 这样的标准 API，应该是不需要做额外的操作的。

**Comment by aiwenForGit** [comment]
好的，非常感谢大神的答复。我关闭下。
