### ISSUE TITLE
!#en: more info about "TraceKit" in roadmap? !#zh: 想了解下 roadmap 中TraceKit的更多信息

### ISSUE THREAD

**Issue by ly525** [rrweb-io/rrweb#256]
!#en: more info about "TraceKit" in roadmap? 
I want to upload the related events when the error occured, so we can reproduce the problem. Can you please give more info or idea about the TraceKit? or Can we integrate rrweb with sentry

!#zh: 想了解下 roadmap 中TraceKit的更多信息?
首先感谢作者以及team，贡献了这么棒的项目！

是这样的，我先交代下背景：
我看了作者在知乎写的文章，我们也有类似的困境：因为某些原因，我们的Web 产品（B端）的用户不在本市，而是在其它城市，因此有时候用户抛出了一些问题，我们无法快速定位、复现问题，特别是线上问题，有时候需要和用户远程来复现问题，成本比较高。

我看到 roadmap中有一个 TraceKit，应该是错误追踪套件，想请教下作者这方面的思路，我目前的想法是，在错误发生的时候，上报该错误发生前的 60s 左右的 events，还原用户用户的操作，来定位问题。

想请教下您在结合rrweb + 错误追踪、错误定位方面的一些思路，是否可以结合sentry 来做这样，非常感谢！

**Comment by Yuyz0112** [comment]
@ly525 

分为两个部分：
1. 收集错误信息
2. 收集错误过程中的操作

TraceKit 用于解决第一部分，也可以用其它的异常收集工具。

第二部分 rrweb 在处理的时候有一个问题，就是受限于目前实现里 op-log 的实现，没法“获取过去 60s 的 events”，而是需要从最近的一个全量快照开始的完整数据链。
目前的解决方式是提供了一个 [checkout](https://github.com/rrweb-io/rrweb/blob/master/guide.zh_CN.md#%E9%87%8D%E6%96%B0%E5%88%B6%E4%BD%9C%E5%BF%AB%E7%85%A7) 的配置，但是不够精确。目前在设计新的 editor mode API，希望能够实现对任意数据链进行裁剪。

和 sentry 官方有一个合作，在实验 sentry + rrweb 的集成（https://github.com/getsentry/sentry-rrweb），也可以参考一下。

**Comment by ly525** [comment]
@Yuyz0112 非常感谢您的解答

1. 我先了解下 checkout 相关的配置信息，目前来看，可能不需要太精确，我先试一下。期待新的 editor mode API 
2. 同时去看下 sentry + rrweb 的项目

PS：方便透露下 TraceKit 这个是否会开源吗？

**Comment by Yuyz0112** [comment]
Tracekit 指的是这个 https://github.com/csnover/TraceKit

**Comment by ly525** [comment]
😂😂
