### ISSUE TITLE
录制之后样式失效

### ISSUE THREAD

**Issue by ty997021381** [rrweb-io/rrweb#260]
在录制之后。把event放到项目外的文件展示，样式失效

**Comment by Yuyz0112** [comment]
可以提供一下 events 和回放的代码用于 debug 吗？

**Comment by ty997021381** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rrweb-io/rrweb"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月22日(星期三) 下午4:53
收件人:&nbsp;"rrweb-io/rrweb"<rrweb@noreply.github.com&gt;;
抄送:&nbsp;"小 ン輄 輥ミ"<997021381@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [rrweb-io/rrweb] 录制之后样式失效 (#260)





 
可以提供一下 events 和回放的代码用于 debug 吗？
