### ISSUE TITLE
Adding an hours worth of events to the player

### ISSUE THREAD

**Issue by randy-johnson** [rrweb-io/rrweb#262]
When using the rrweb-player:

```
new rrwebPlayer({
  target: document.body, // customizable root element
  data: {
    events,
    autoPlay: true,
  },
});

```

What is the preferred way to add the events when you have an hours worth of events that need to be added to the player?

Outputting the events above the player does work but kinda freezes the browser (waiting for loading) because of the size of the size of the events that need to be queried and written to the page

**Comment by randy-johnson** [comment]
ok, I have decided that I'll need to make several ajax calls to the server to grab the events and add them to the player.  What I am not sure of is how to add the events to the player  after the initial code above runs.  Any ideas?

**Comment by zjsen668** [comment]
> ok, I have decided that I'll need to make several ajax calls to the server to grab the events and add them to the player. What I am not sure of is how to add the events to the player after the initial code above runs. Any ideas?

You can consider using live model.

**Comment by randy-johnson** [comment]
@zjsen668, we do use live mode for realtime as the session is going on, but what I am talking about here is after the fact.

**Comment by Yuyz0112** [comment]
https://github.com/rrweb-io/rrweb/issues/161#issuecomment-687972345

I think the new `addEvent` API solves this.
