### ISSUE TITLE
JS errors in rrweb@latest

### ISSUE THREAD

**Issue by randy-johnson** [rrweb-io/rrweb#263]
Hello,

I am getting these types of errors when recording using 

```
<link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/rrweb@latest/dist/rrweb.min.css"
/>
<script src="https://cdn.jsdelivr.net/npm/rrweb@latest/dist/rrweb.min.js"></script>

```

https://www.dropbox.com/s/ipacewy3bidef6g/2020-07-23_10-04-44.png?dl=0

Things still seem to work from what I can see.

Any idea what the issue could be?

**Comment by Yuyz0112** [comment]
@randy-johnson is there a public URL I can reproduce this errors?

**Comment by Yuyz0112** [comment]
BTW, does rrweb@0.8.2 do not have this problem?

**Comment by randy-johnson** [comment]
@Yuyz0112 ,  no public version at this time.  I can confirm though when I was setting up a basic demo to make public I am not seeing the error.  I am checking on the previous version and will report back.

**Comment by randy-johnson** [comment]
@Yuyz0112 I can confirm that when I use 
`<script src="https://cdn.jsdelivr.net/npm/rrweb@0.8.2/dist/rrweb.min.js"></script>`

the error goes away.

**Comment by Yuyz0112** [comment]
@randy-johnson Thanks for the feedback. Are you using blockClass?

**Comment by randy-johnson** [comment]
@Yuyz0112 , if you are referring to rr-block and rr-ignore, yes  I am.

**Comment by Yuyz0112** [comment]
[rrweb.min.zip](https://github/rrweb-io/rrweb/files/4967135/rrweb.min.zip)

@randy-johnson Could you try to use the js bundle in this zip file to replace the online version and see whether it fixes the bug?

**Comment by randy-johnson** [comment]
Sure.  I will report back shortly

**Comment by randy-johnson** [comment]
@Yuyz0112 , There are no errors using the zipped rrweb.min.js you provided.

**Comment by Yuyz0112** [comment]
I think I find the root cause, going to release a new version.

**Comment by randy-johnson** [comment]
Thank You @Yuyz0112
