### ISSUE TITLE
Setup CI for pull requests

### ISSUE THREAD

**Issue by Juice10** [rrweb-io/rrweb#265]
It would be great to have all tests run in CI whenever someone submits a pull request.
That way we don't have any breaking code accidentally merged into the project.

Some suggestions:
- Travis-CI is free for Open Source projects and might be a good candidate.
- GitHub actions are also free for Open Source projects. I have no personal experience running puppeteer on Github Actions but since there are a couple actions dedicated towards puppeteer, it seems doable. eg. https://github.com/marketplace/actions/puppeteer-headful

**Comment by Yuyz0112** [comment]
I already setup Travis-CI https://github.com/rrweb-io/rrweb/blob/master/.travis.yml, going to check why it does not run on PRs.

**Comment by Yuyz0112** [comment]
Just finished the `travis org` to `travis com` migration, I believe it should work again.

**Comment by Juice10** [comment]
Thank you @Yuyz0112! Confirmed it working on https://github.com/rrweb-io/rrweb/pull/264
