### ISSUE TITLE
replayer is not interactive during replay

### ISSUE THREAD

**Issue by wanzheng2019** [rrweb-io/rrweb#267]
when I run the rrweb's sample code in my local computer, I found that the replay works well, but the dom elements are not interactive any more, I can't key in any word in the "input", the  button can't be clicked either. If I try it on the offical website: https://www.rrweb.io/#demos, I can input text , click the button while the replay is ongoging.

**Comment by Yuyz0112** [comment]
Because we add `pointer-events: none` by default to prevent interacting with the replayer.

There are methods `enableInteract` and `disableInteract` you can use to toggle this.

```js
const replayer = new Replayer(...)

replayer.enableInteract()
```

**Comment by Yuyz0112** [comment]
code here: https://github.com/rrweb-io/rrweb/blob/master/src/replay/index.ts#L253

**Comment by randy-johnson** [comment]
@wanzheng2019 , I am curious as to why you would want type in the input field while replaying?

**Comment by wanzheng2019** [comment]
@Yuyz0112 Thanks, it sloved my problem.
@randy-johnson , it comes from the customer's requreiment:)
