### ISSUE TITLE
BUG: waitForStylesheetLoad resumes playing of video when paused

### ISSUE THREAD

**Issue by Juice10** [rrweb-io/rrweb#268]
In some cases I've experienced that `waitForStylesheetLoad` will trigger a resume when the player should be paused.

```javascript
      const { Replayer } = rrweb;
      const replayer = new Replayer(events);
      replayer.play(15000); // <-- setTimeout in waitForStylesheetLoad called
      replayer.pause(); // <-- should pause
// <-- setTimeout ends and triggers resume
```

Current contents of `waitForStylesheetLoad`:
https://github.com/rrweb-io/rrweb/blob/6cf3253d9458e1d05441d45a27200d31e5af13a3/src/replay/index.ts#L394-L434

**Comment by Juice10** [comment]
What might fix this is a different strategy that does not depend on `replayer.play(number); replayer.pause()` to seek and pause. Maybe we could allow people to use `replayer.pause(number)` to move the player to the point in time they need to pause at.

Alternatively we could also implement `replayer.seek(number)` if we are afraid changing `pause` is might break things.

**Comment by Yuyz0112** [comment]
I believe the root cause is it only checks the `beforeLoadState` after the load.

So if we have these action sequence, it fails:
```
play
wait style load <- beforeLoadState is 'playing'
pause
loaded <- check beforeLoadState, do resume
```

pause at time offset only fix some use case, but users can still trigger this action sequence with the API.

**Comment by Yuyz0112** [comment]
Please let me know if the fix does not work.

**Comment by Juice10** [comment]
> Please let me know if the fix does not work.

Apologies that it took me a while to verify this.
Unfortunately the fix doesn't work. [Here is an `events.json` file that can be used to verify](https://gist.github.com/Juice10/74c74e96be356988dcb2feba2064926e) this issue.

Code to trigger the issue:

```js
replayer.pause(2829);
```

**Comment by Juice10** [comment]
Since we have simplified the state machine I think the following if statements in `waitForStylesheetLoad` always going to match.
```js
               if (beforeLoadState.matches('playing')) {
...
         if (beforeLoadState.matches('playing')) { 
```
