### ISSUE TITLE
Uncaught DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.

### ISSUE THREAD

**Issue by jasonbarry** [rrweb-io/rrweb#271]
I am receiving this exception in my console:

```
Uncaught DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
```

The exception points to the code `parent.appendChild(target);` at this line: https://github.com/rrweb-io/rrweb/blob/master/src/replay/index.ts#L701

In my case, `parent` is a #text node. Its `__sn` value is 

```
{ type: 3, textContent: "      ", id: 42 }
```

Meanwhile, `target` is a `div`.

**Comment by Yuyz0112** [comment]
Thanks for the feedback. Is it possible to provide the whole events for debugging?

**Comment by jasonbarry** [comment]
@Yuyz0112 replaying these events should reproduce the exception: https://gist.githubusercontent.com/jasonbarry/3a7338bb8172eb7fc88f597a891bcb7e/raw/5641608f11567fc856570300f822e2e9eea94150/debug-events-rrweb-271

**Comment by chenkaikevin** [comment]
The same mistake happened            The first page starts recording, and the second page reports an error            If the second page starts recording, the third page will play an error
第一个页面开始录制，第二个页面播放报错
如果第二个页面开始录制，第三个页面播放报错

**Comment by Yuyz0112** [comment]
@chenkaikevin 可以提供 events 用于 debug 吗？

**Comment by chenkaikevin** [comment]
> @chenkaikevin 我把文件放附加了，错误截图也发了一下。

[events.txt](https://github.com/rrweb-io/rrweb/files/4994142/events.txt)
![截图](https://user-images.githubusercontent.com/35229805/88786636-54d18080-d1c5-11ea-920d-e39469236ba0.png)

**Comment by jasonbarry** [comment]
Interesting, the above screenshot happens on `removeChild` – so it looks like this occurs on both additions and removals.

**Comment by Yuyz0112** [comment]
> @Yuyz0112 replaying these events should reproduce the exception: https://gist.githubusercontent.com/jasonbarry/3a7338bb8172eb7fc88f597a891bcb7e/raw/5641608f11567fc856570300f822e2e9eea94150/debug-events-rrweb-271

@jasonbarry In your events, the id looks strange because there are two DOM that has the same id.

Is this the initial event of a recording? And is there only one record function call during the recording?

**Comment by Yuyz0112** [comment]
@chenkaikevin 你的 events 看上去也是类似的问题，缺失了一些数据。

录制代码大概是什么样的，会出现同时录制多次的情况吗？以及是否使用 block class 的功能？

**Comment by 18865522675** [comment]
@Yuyz0112 你好，我也遇到了这样子的问题。之前好像还好好的，目前这功能要上线，今天会顾一看，发现出现了这样子的问题，请问下如何解决呀

**Comment by Yuyz0112** [comment]
@18865522675 提供 events 用于 debug 吧，同样的报错不一定是同样的原因

**Comment by sunzhixun001** [comment]
一个组件里(vue)同时回放2个视频就会报这个错 @Yuyz0112

**Comment by heyitsnovi** [comment]
Any updates on this. facing the same issue too

**Comment by amitpareek49** [comment]
@Yuyz0112 - Is there a way to avoid this kind of issue? I am too facing the same issue. The recording works fine if I play the replay sequentially but it fails to play when I jump to different timestamps on the replay.

**Comment by endypark** [comment]
@Yuyz0112 @Juice10 , could you help to debug this events, thanks.

https://github.com/rrweb-io/rrweb/issues/617#issuecomment-1175889687

**Comment by endypark** [comment]
[trace-video-data.txt](https://github.com/rrweb-io/rrweb/files/9052662/trace-video-data.txt)

same issue, please help to debug, thanks.
@Yuyz0112 @Juice10

**Comment by endypark** [comment]
> [trace-video-data.txt](https://github.com/rrweb-io/rrweb/files/9052662/trace-video-data.txt)
> 
> same issue, please help to debug, thanks. @Yuyz0112 @Juice10

And how to avoid that issue?
such as , if the recording-data has some error, the rrweb-player skip that statment(1 -2 seconds), running the video continously;
or , if the webpage-html data has some error, render the webpage normally with some element-missing，one or two elements do not influence the overall.

**Comment by endypark** [comment]
@chenkaikevin , 你知道该怎么避免这个问题吗？ 现在Safari浏览器，尤其是iPhone，出这个问题的概率很高， 用户要求我们必须解决。
我没有深入研究，预计问题就是： 比如某个流程有5个页面，那么当 重新渲染 某个页面（例如第3个页面）时，无法渲染这个页面，就会直接中断并抛出异常。
我想的方法是：rrweb-player 遇到这种情况，跳过一些问题，比如 node.appendChild 出问题，就跳过这段，只要用户可以看到相对完成的视频，那么 1）页面上少一两个元素 2）整个视频少1-2秒 ，应该都是可以接受的；
 而从 录制方面去解决问题，我想到的是会更难，因为一般不能完全保证某个程序完全不出错误，所以录制时，一定会有一定的概率出现错误数据的，只是 多还是少的问题。
能力、精力有限，我也没办法去解决这个基础问题。
所以还得请教各位大侠，有没有什么解决办法。
谢谢

**Comment by endypark** [comment]
@chenkaikevin , 你知道该怎么避免这个问题吗？ 现在Safari浏览器，尤其是iPhone，出这个问题的概率很高， 用户要求我们必须解决。
我没有深入研究，预计问题就是： 比如某个流程有5个页面，那么当 重新渲染 某个页面（例如第3个页面）时，无法渲染这个页面，就会直接中断并抛出异常。
我想的方法是：rrweb-player 遇到这种情况，跳过一些问题，比如 node.appendChild 出问题，就跳过这段，只要用户可以看到相对完成的视频，那么 1）页面上少一两个元素 2）整个视频少1-2秒 ，应该都是可以接受的；
 而从 录制方面去解决问题，我想到的是会更难，因为一般不能完全保证某个程序完全不出错误，所以录制时，一定会有一定的概率出现错误数据的，只是 多还是少的问题。
能力、精力有限，我也没办法去解决这个基础问题。
所以还得请教各位大侠，有没有什么解决办法。
谢谢

**Comment by endypark** [comment]
@jasonbarry , do you know how to fix or avoid this issue ?

**Comment by endypark** [comment]
@Yuyz0112 @Juice10 , upgrade the rrweb-player to latest version,  could it avoid or resolve this issue ?

**Comment by endypark** [comment]
@sunzhixun001 , 您好，这个问题，你解决了吗？

**Comment by endypark** [comment]
解决方法分享： Failed to execute 'appendChild' on 'Node'
1. 通过debug找到报这个错误的代码，一般是 t.appendChild 或 t.removeChild，或者是被压缩过的 s(e) 这种；
2. 使用try catch 对这行代码进行包裹，catch打个日志就行了。
这样就能跳过这个坏点，视频继续运行。。。

**Comment by Mark-Fenng** [comment]
If you are facing the same error, please feel free to open a new issue and upload the events for debugging.
