### ISSUE TITLE
拉取到本地的rrweb-player,如何使用呢

### ISSUE THREAD

**Issue by zhaoxm2016** [rrweb-io/rrweb#272]
TypeError: __WEBPACK_IMPORTED_MODULE_1_rrweb_player__ is not a constructor

**Comment by zhaoxm2016** [comment]
@Yuyz0112 npm 安装的，一直报上面的错误

**Comment by Yuyz0112** [comment]
可以看一下你启动 replayer 的代码吗？

**Comment by zhaoxm2016** [comment]
import rrwebPlayer from 'rrweb-player';
const PlayView = (props)=>{
	const myRef = React.createRef();
	let records = JSON.parse(localStorage.getItem("Records")) || {};
	let events = records['0c469565-c160-4748-b350-7df5d7df278c|0.1.0|PC|A']
	let player = new rrwebPlayer({
	  target: document.getElementById("rrweb"),
	  data: {
	    events
	  },
	});
	useEffect(()=>{
		
	})
	return <div id="rrweb">
		
	</div>
}

export default PlayView;

**Comment by zhaoxm2016** [comment]
之前是用的CDN上的，没有问题，npm install到本地之后就一直报上面的错

**Comment by Yuyz0112** [comment]
看起来是 webpack 配置的问题，我在一个 `create-react-app` 的项目里这样使用没有遇到问题。


https://codesandbox.io/s/rough-mountain-y8b8k?file=/src/App.js

**Comment by zhaoxm2016** [comment]
现在的工程就是基于create-react-app改造的，有建议查找的方向吗

**Comment by Yuyz0112** [comment]
`console.log(rrwebPlayer)` 看一下 import 进来的是什么？

**Comment by zhaoxm2016** [comment]
RRWEB /static/media/index.de8e958b.mjs

**Comment by Yuyz0112** [comment]
可以参考一下这个问题：

https://github.com/rrweb-io/rrweb-player/issues/11

**Comment by zhaoxm2016** [comment]
使用0.4.6版本吗

**Comment by zhaoxm2016** [comment]
没看出来如何解决。。。。

**Comment by Yuyz0112** [comment]
`import rrwebPlayer from 'rrweb-player/lib/index.js'` 试一下？

**Comment by zhaoxm2016** [comment]
尝试了，结果报了一堆错 。。

**Comment by Yuyz0112** [comment]
那只能再自行调查一下 webpack 的配置了，和 https://codesandbox.io/s/rough-mountain-y8b8k?file=/src/App.js 对比一下

**Comment by zhaoxm2016** [comment]
我先用CDN的把，不过是不是可以支持一下导入js啊

**Comment by Yuyz0112** [comment]
导入 JS 是指什么？

**Comment by Yuyz0112** [comment]
Feel free to reopen this issue if there any updates.
