### ISSUE TITLE
播放完后无法重新播放

### ISSUE THREAD

**Issue by Rxdey** [rrweb-io/rrweb#273]
使用`0.8+`版本 `rrweb.Replayer`来自定义播放器
播放完毕后再次调用`replayer.play(0)`无法重新播放。`timeOffset`直接变成了结尾
但是使用`0.7.33`版本同样的方式可以重新播放
代码就普通的播放，播放完成后再次调用播放
请问是什么问题呢？或者该如何重置状态？

**Comment by Yuyz0112** [comment]
用最新的 master 试一下？

v0.8 版本里进行了一些重构，保证状态正确的情况下引入了一些问题（主要是 API 易用性方面），我们正在讨论和重构这部分代码，希望这周末能够有一个新的版本。

**Comment by Yuyz0112** [comment]
或者可以暂时使用 0.7.x

**Comment by Rxdey** [comment]
> 用最新的 master 试一下？
> 
> v0.8 版本里进行了一些重构，保证状态正确的情况下引入了一些问题（主要是 API 易用性方面），我们正在讨论和重构这部分代码，希望这周末能够有一个新的版本。
好嘞， 使用的确实是最新的master手动打包的，还是有问题，那就先使用之前的版本了。

**Comment by Rxdey** [comment]
嗯嗯，现在使用的是最新的master手动打包的，还是存在问题
那就暂时使用之前版本了。
