### ISSUE TITLE
Proposal: improve state management in the player

### ISSUE THREAD

**Issue by Yuyz0112** [rrweb-io/rrweb#274]
After building the first(< 0.8) and the second(0.8.x) version of rrweb's replayer, I found we need to improve the state management in the replayer for two goals:

1. Keep states and actions explicit. It should be straight forward to know the state of the replayer and the valid actions it can do.
2. Keep public APIs intuitive, simple, and easy to use. Users should not see unexpected behaviors after calling the APIs.

In the old version, the replayer did not do a good job on the first point. We are using multiple boolean flags to describe the states which make these codes:
```
if A && B
  -> playing
else if C1 && !C2 && D
  -> skipping
...
```
And these states are hard to be re-used in the rrweb-player, which is a UI for the replayer.
Then I introduce the state machine to solve the first problem, which is good at strictly handling states.
But the refactoring ruined the second point. Users lost in the new APIs and facing many regressions.
The main problem here is I'm exposing the state machine to the public APIs which means users should be aware of the states and handle it.

So in this proposal, I suggest refining the state machine and improve the public APIs to achieve both goals.

## Refining the state machine

We will have two simple state machines instead of a complex one, and remove some context from the machine.

First, we will have a simple state machine with `paused`, `playing`, and `live` states.
The transitions look like this:
![image](https://user-images.githubusercontent.com/13651389/88823709-f83b8900-d1f7-11ea-9c5c-83d7aa248c53.png)

The `live` state looks not quite useful at this moment, but I believe it was needed for future development.

Then we will have another state machine with `normal` and `skipping` states.
The transitions look like this:
![image](https://user-images.githubusercontent.com/13651389/88823823-1dc89280-d1f8-11ea-80fc-1163ef16e431.png)

This machine responsible for calculating the fast-forward speed and restore to previous normal speed.

## Improve the public APIs
Since we are not going to expose the state machine concepts to the users, we still provide APIs look similar to the actions but easier to use.

### play
Play accepts an optional time offset number as the params.
In the implementation, it will do the following things:
1. if the replayer is paused, send the PLAY event to the machine
2. if the replayer is playing, send PAUSE and PLAY event to the machine in a sequence.
3. if the replayer is skipping, send the BACK_TO_NORMAL event to the machine.
We will depart the resume API.

### pause
Pause now accept an optional time offset number too.
In the implementation, it will do the following things:
1. if no time offset number is passed in, and the replayer is playing, send the PAUSE event to the machine
2. if time offset number is passed in, call the play API with the time offset number, then call PAUSE to stop at that time offset.

### startLive
Currently, it will only send the TO_LIVE event when the replayer is paused.

**Comment by Yuyz0112** [comment]
Invite @eoghanmurray  @Juice10 to review this.

**Comment by Juice10** [comment]
Thanks for this @Yuyz0112, I like the way you have this structured, and I love that this cleans up the api quite a bit!

A couple questions for you, hope you don't mind.

When implementing #269 I wasn't sure if `FAST_FORWARD`/`skipping` was meant to indicate that the player was playing at a faster speed, or if it was seeking (jumping to a moment in time). I'm still not 100% sure which one it is meant for, judging by your proposal above I'm guessing it might be for playing at a faster speed. Could you clarify that for me? That would be super helpful!

I didn't see the `ended` state in here, are we removing it? I noticed a couple potential issues with it (eg. calling `play(timeOffset)` when in `ended` state, currently ignores the timeOffset and effectively does `play(0)`). Not hard to fix but if you'd like to remove `ended` I like that we have one less state to worry about. 

> __Pause__
> if time offset number is passed in, call the play API with the time offset number, then call PAUSE to stop at that time offset.

If this would also trigger the second state machine to go into `FAST_FORWARD`/`skipping` mode we could add a second check in `waitForStylesheetLoad` to easily fix #268. Would that be the case in your proposal? (Guess it depends on the answer to my earlier question about FF/skipping)

**Comment by Juice10** [comment]
> **Play**
> if the replayer is skipping, send the BACK_TO_NORMAL event to the machine.

Could there be a situation where the `play` could trigger another FAST_FORWARD when the replayer is already skipping?

**Comment by Yuyz0112** [comment]
@Juice10 

> When implementing #269 I wasn't sure if FAST_FORWARD/skipping was meant to indicate that the replayer was playing at a faster speed, or if it was seeking (jumping to a moment in time). I'm still not 100% sure which one it is meant for, judging by your proposal above I'm guessing it might be for playing at a faster speed. Could you clarify that for me? That would be super helpful!

After rethinking the states, I believe `skipping` is something could be separate from the main state. It refers to the `skip inactive` feature, which means the replayer keeps detecting events to see whether there are some user interactions and try to fast forward.

> I didn't see the ended state in here, are we removing it? I noticed a couple potential issues with it (eg. calling play(timeOffset) when in ended state, currently ignores the timeOffset and effectively does play(0)). Not hard to fix but if you'd like to remove ended I like that we have one less state to worry about.

`ended` and `inited` has been removed.

**Comment by Juice10** [comment]
@Yuyz0112

Thank you for clearing that up for me, I didn't realize `skipping` had to do with the `skip inactive` feature. That was super helpful, thank you! 

It would be great if we could add something to your proposal. Below are two alternative strategies that would both accomplish the same thing. I'm curious to see what you think. And see if it would be possible to potentially add one of these to your proposal.

## More states
### Add seeking state & renaming skipping state

Maybe we could rename `skipping` to `skipping-inactive` or something else a little more verbose?
Then we could add a third state to the play/skipping state machine, one called something like `seeking`. While `seeking` we could turn off the wait for stylesheets which would allow us to fix #268. 

## Less states
### Multi-purpose skipping state

We could re-use `skipping` for more than just skipping inactive. We could also use it when moving the playhead to a later (or earlier) point in time. While doing `skipping` we can turn off all the waits for stylesheets and such which would fix #268.

Would love to see what you think. (And also feel free to reach out to me via Gitter.im if that makes things easier.)

**Comment by Yuyz0112** [comment]
@Juice10 By design, the `seeking` process should be a sync process. Could you explain more about how would it help to solve this(https://github.com/rrweb-io/rrweb/issues/268#issuecomment-665759413)?

**Comment by Juice10** [comment]
@Yuyz0112 I'd be happy to!

To understand how it would be helpful we have to look at how `waitForStylesheetLoad` works. 
`waitForStylesheetLoad()` has three steps:

1. Trigger `this.service.send({ type: 'PAUSE' });` 
2. Waits for stylesheet to load
3. Triggers resume (`this.resume(this.getCurrentTime());`) if it was playing before the PAUSE was called

This disrupts any seeking because `resume()` overrides `timeOffset` set on `play()`.

#### Proposed solution
If we have a seeking/skipping state `waitForStylesheetLoad()` could check if that state is active and then it could continue seeking afterwards instead of `resume()`ing and overriding the specified `timeOffset` with `this.getCurrentTime()`.

**Comment by Juice10** [comment]
@Yuyz0112 I'm not super familiar with sync. Would it be possible for `waitForStylesheetLoad` to check if we are running a sync process? That could potentially also fix this (without the extra needed state).

**Comment by eoghanmurray** [comment]
Thanks @Yuyz0112 I appreciate your creation of this separate proposal and explanation as to the introduction of the state machine.

> Keep states and actions explicit. It should be straight forward to know the state of the replayer and the valid actions it can do.

My personal approach would be different.  I believe it is possible to design software such that there is no such thing as an 'invalid' action... applying any action to the software should not result in an error state, along the lines of the https://en.wikipedia.org/wiki/Robustness_principle. 

From that point of view, the sets of booleans that were tracking state were just fine, but I'm not aware of the problems they were causing so maybe things are over simplified in my head.
E.g. you could have:

```
isPlaying: boolean => { return A && B; }
isSkipping: boolean => { return !self.isPlaying() &&  C1 && !C2 && D; }
```

I'm happy to see that the problems I've raised look set to be addressed with the new simplified state machines.
