### ISSUE TITLE
采集事件回放

### ISSUE THREAD

**Issue by zhaoxm2016** [rrweb-io/rrweb#276]
![image](https://user-images.githubusercontent.com/51771541/88995901-65e1d500-d31e-11ea-91d3-eecc73ff464a.png)

在实际业务流程中，我采集了3部分的数据，A/B/C
将A/B/C三组数据事件合并之后，整个流程可以正常播放
但是如果三组事件独立播放的话，只有A节点的数据可以正常播放，
B/C的时间都是白屏，会报出如下警告信息
index.js:1 [replayer] Node with id '177' not found in {source: 0, texts: Array(0), attributes: Array(2), removes: Array(2), adds: Array(22)}

@Yuyz0112 指点一下哈

**Comment by zhaoxm2016** [comment]
![29B347DB-4F0C-4AC1-A873-FD0E3864F703](https://user-images.githubusercontent.com/51771541/88996243-59aa4780-d31f-11ea-92a9-f215bd7c0e05.png)

**Comment by Yuyz0112** [comment]
这 3 部分数据都是在一次 record 里采集的吗？

一次 record 里默认只会产生一次全量快照，后续数据都是增量的。如果你希望某一部分可以独立回放，那需要在开始的时间点上停止上一次 record，重新 record 一次。

**Comment by zhaoxm2016** [comment]
嗯,只是在一次record里采集的。
明白了，感谢。

**Comment by zhaoxm2016** [comment]
@Yuyz0112 确认一下哈，如果三个独立的record采集的数据，可以合并成一个events进行播放吗

**Comment by zhaoxm2016** [comment]
@Yuyz0112 可否看下我的代码帮忙给一些建议呢？可以的话是否可以发下邮箱

**Comment by Yuyz0112** [comment]
> 可以合并成一个events进行播放吗

可以，如果代码遇到问题可以描述一下具体的问题或者最小复现代码

**Comment by zhaoxm2016** [comment]
@Yuyz0112 请教一下，在录制的时候我使用rrweb的pack操作之后，是否可以再使用pako或者其他工具进行一次压缩呢？

**Comment by zhaoxm2016** [comment]
@Yuyz0112 目前在业务系统中采集的数据，感觉还是有点大

**Comment by zhaoxm2016** [comment]
export type recordOptions<T> = {
  emit?: (e: T, isCheckout?: boolean) => void;
  checkoutEveryNth?: number;
  checkoutEveryNms?: number;
  blockClass?: blockClass;
  ignoreClass?: string;
  ****maskAllInputs?: boolean;**
  **maskInputOptions?: MaskInputOptions;****
  inlineStylesheet?: boolean;
  hooks?: hooksParam;
  packFn?: PackFn;
  **sampling?: SamplingStrategy;**
  // departed, please use sampling options
  **mousemoveWait**?: number;
};
您好，能说明一下带*处的设置的含义吗
@Yuyz0112

**Comment by crystalpp** [comment]
由于两个record之间的时间差很大，所以将两个record的数据拼接成一个数组回放时 中间会有很长的时间间隔，想请假下是否有什么比较好的方法可以解决这类问题

**Comment by Yuyz0112** [comment]
@crystalpp 可以参考这个方法 https://github.com/rrweb-io/rrweb/issues/290#issuecomment-687728528

**Comment by Yuyz0112** [comment]
@zhaoxm2016 

maskAllInputs 是指所有输入框的值都记录为星号。maskInputOptions 是对 maskAllInputs 的一个补充，可以详细指定哪些 type 的 input 需要被记录为星号。

sampling 是采样策略，作用如下：
```ts
type SamplingStrategy = Partial<{
  /**
   * false means not to record mouse/touch move events
   * number is the throttle threshold of recording mouse/touch move
   */
  mousemove: boolean | number;
  /**
   * false means not to record mouse interaction events
   * can also specify record some kinds of mouse interactions
   */
  mouseInteraction: boolean | Record<string, boolean | undefined>;
  /**
   * number is the throttle threshold of recording scroll
   */
  scroll: number;
  /**
   * 'all' will record all the input events
   * 'last' will only record the last input value while input a sequence of chars
   */
  input: 'all' | 'last';
}>;
```

mousemoveWait 是废弃的选项，效果和 sampling.mousemove 相同
