### ISSUE TITLE
最新的github代码和npm的版本不同的导致player的问题

### ISSUE THREAD

**Issue by endday** [rrweb-io/rrweb#278]
最新的代码中，events变量被删除了

这次提交还有，后面的版本全部被干掉了
8913bcb9d6bc50850474439b218b85a7e434d6a2

![image](https://user-images.githubusercontent.com/15724410/89153939-7ef5ba80-d598-11ea-9c14-e9836dd1ed6f.png)

在player的controller中生成进度条使用这个events
![image](https://user-images.githubusercontent.com/15724410/89154385-5c17d600-d599-11ea-928e-527c6bc35651.png)

**Comment by Yuyz0112** [comment]
replayer 里应该没有使用过 0.8+ 的 rrweb

**Comment by endday** [comment]
> replayer 里应该没有使用过 0.8+ 的 rrweb

我这边打算做二次开发，所以用了最新rrweb和replayer

**Comment by Yuyz0112** [comment]
@endday 新版做了很多 API 的内部调整，用起来可能会有点别扭，这个 Proposal 里面的内容这周内可能会合入：https://github.com/rrweb-io/rrweb/issues/274 ，提升 API 使用方式。rrweb-player 也会更新到这个版本。
