### ISSUE TITLE
如果页面太长，会卡顿，时间挺长的

### ISSUE THREAD

**Issue by liuxsen** [rrweb-io/rrweb#280]
1. 如果页面dom比较多，会卡顿，导致页面不能够渲染，时间挺长的
2. 项目采用的vue-router，切换页面也会卡顿； 猜测是因为dom变化的数量比较多；

请问这样的我应该怎么处理呢？

**Comment by Yuyz0112** [comment]
是指录制还是回放的时候呢？

**Comment by liuxsen** [comment]
是录制的时候

**Comment by liuxsen** [comment]
能加您微信么，大佬

**Comment by Yuyz0112** [comment]
可以发邮件给我。
