### ISSUE TITLE
导出avi、mp4等格式视频

### ISSUE THREAD

**Issue by myrider** [rrweb-io/rrweb#281]
您好，我想咨询下，我想将录制的生成或导出真实的视频文件，如avi、mp4等格式，我应该如何实现呢？

**Comment by Yuyz0112** [comment]
https://github.com/rrweb-io/rrweb/issues/281

**Comment by pipti** [comment]
我也想问下，是否有后台可以将脚本转换为video

**Comment by Yuyz0112** [comment]
@myrider @pipti 
https://github.com/rrweb-io/rrweb/issues/40
可以参考这里面的讨论
