### ISSUE TITLE
页面跳转回上一个页面，表单的内容读取缓存数据，重新录制，播放的时候表单原样式丢失

### ISSUE THREAD

**Issue by yangmeishux** [rrweb-io/rrweb#283]
初始化 form 表单内容为空，输入之后，页面跳转到下一个页面，然后重新回到上一个页面，页面读取缓存数据并回塞，页面样式也没有问题，录制完成之后。读取录制的数据，发现播放的时候表单的样式丢失了。想知道是啥原因导致的？

**Comment by Yuyz0112** [comment]
可以提供 events 用于 debug 吗？

**Comment by yangmeishux** [comment]
> 可以提供 events 用于 debug 吗？
events的数据:
`
[events.txt](https://github.com/rrweb-io/rrweb/files/5074258/events.txt)
`

**Comment by yangmeishux** [comment]
页面播放页面https ,而录制的页面资源文件http,导致资源加载失败导致渲染问题
