### ISSUE TITLE
seeking forward causing error

### ISSUE THREAD

**Issue by raminious** [rrweb-io/rrweb#285]
Hey, 

I'm getting error when I'm trying to seek forward the progress   

https://github.com/rrweb-io/rrweb/blob/be4cccd6e373c1a6702130a21a1d4557f2944101/src/replay/index.ts#L627

![image](https://user-images.githubusercontent.com/334716/90345608-b0579700-e02a-11ea-9dfd-6471bf8dc64c.png)

steps of reproducing the error:   
https://streamable.com/7df7v7   

rrweb version: 0.9 (latest)

Here is the repository that I'm working on that. https://github.com/raminious/rrweb-player   

`git clone git@github.com:raminious/rrweb-player.git`    
`npm install`   
`npm start`    
open `http://localhost:1234`

you can find the events array in `src/response.js`

**Comment by Juice10** [comment]
I'm having the same issue as @raminious.

## Steps to reproduce
1. Go to https://codepen.io/juice10/pen/LYNRypv
2. Open your browser's console/debugger.
3. Seek anywhere past 30 seconds.
4. Error is triggered in the console. `Cannot read property 'rules' of null`

## Example of offending event:
```json
{"86":{"data":{"id":105,"adds":[{"rule":".css-1qrqtax{height:0.25rem;background-color:#BEE8F2;opacity:0;-webkit-transition:opacity 0.5s;transition:opacity 0.5s;opacity:1;-webkit-transition:opacity 2.5s;transition:opacity 2.5s;-webkit-animation-name:animation-1hmp8dd;animation-name:animation-1hmp8dd;-webkit-animation-duration:2s;animation-duration:2s;-webkit-animation-timing-function:ease-in-out;animation-timing-function:ease-in-out;-webkit-animation-iteration-count:infinite;animation-iteration-count:infinite;}","index":75}],"source":8},"type":3,"timestamp":1597398354895}}
```

## Lines responsible for error
Line where error happens: https://github.com/rrweb-io/rrweb/blob/master/src/replay/index.ts#L627
Line where `styleSheet` is defined: https://github.com/rrweb-io/rrweb/blob/master/src/replay/index.ts#L620

## What I think is happening
From what I could find the problem happens on `IncrementalSource.StyleSheetRule` events where `styleEl.parentNode` is a DocumentFragment (not yet added to the dom). Apparently you can't call `.sheet` on stylesheet elements in a DocumentFragment.

**Comment by Juice10** [comment]
@raminious #293 should fix this, please let me know if that is (or isn't) the case for you. 
Cheers!

**Comment by raminious** [comment]
@Juice10 this is the error that I got when I was trying to test your branch

![image](https://user-images.githubusercontent.com/334716/90985734-7e908400-e586-11ea-9393-80df87507e0a.png)

https://streamable.com/wjnu23

**Comment by Juice10** [comment]
@raminious looks like there are a couple things going on here unfortunately.

I'm going to split these into separate issues so we can create separate fixes for them starting with #306.

**Comment by Juice10** [comment]
> @Juice10 this is the error that I got when I was trying to test your branch
> ... 
> https://streamable.com/wjnu23

@raminious In your video it looks like you are still getting the `Cannot read 'rules' of null` error. However when I try to reproduce it on https://github.com/raminious/rrweb-player with the fix from https://github.com/rrweb-io/rrweb/pull/293 I can't get the error to trigger. Is there any chance you could commit your version that pulls in https://github.com/rrweb-io/rrweb/pull/293 so I can see exactly what is going on?

**Comment by raminious** [comment]
@Juice10 Sorry for the delayed response. here you go buddy
https://github.com/raminious/rrweb-player
