### ISSUE TITLE
多页面应用如何保存在一个record中。

### ISSUE THREAD

**Issue by haoyk** [rrweb-io/rrweb#287]
你好，我是MVC项目多页面应用，一个完整的业务流由多个页面依次跳转完成。请问针对我这种业务场景该如何使用rrweb对这多个页面进行录制呢？还请指教。

**Comment by Yuyz0112** [comment]
@haoyk 每个页面都可以独立录制。对于你的业务场景，如果需要把多次录制关联在一起，可以让跳转时传递一个统一的标识，和录制的数据一起传递给后端，存储时能够识别这些录制的数据属于同一次会话应该就可以了。
