### ISSUE TITLE
replayer.play makes page stop working

### ISSUE THREAD

**Issue by liswift** [rrweb-io/rrweb#29]
![image](https://user-images.githubusercontent.com/13742747/50578520-333bd600-0e76-11e9-899c-c795dbb3dd4d.png)

code like this:
```js
mounted() {
        const self = this;

        this.events = [];
        this.record = rrweb.record({
            emit(event) {
                console.log(1);
                self.events.push(event);
            }
        });
    },
    methods: {
        stopRecord() {
            this.record();
            setTimeout(()=> {
                const replayer = new rrweb.Replayer(this.events);

                replayer.play();
            }, 2000);
        }
    } 
```

I do some actions, then stop recording and use replayer.play. Then the page stops working,as the picture shows. no console errors

**Comment by liswift** [comment]
@Yuyz0112 
Your code doesn't work on my page.
The page stops response. It looks like there's something endless-loop.
![image](https://user-images.githubusercontent.com/13742747/50578912-0b02a600-0e7b-11e9-8fee-8f8005f57806.png)

I debug the code, 'replayer.play' works, but when I step next, this problem occurs.

**Comment by Yuyz0112** [comment]
Sounds weird. It will be appreciated if you can provide your OS info and Chrome version and I will try to reproduce the problem.
And personally, I doubt there is a conflict with some chrome extensions.

**Comment by liswift** [comment]
You are right, I disable all chrome extensions and it works!

**Comment by Yuyz0112** [comment]
@liswift 
Good news! If you are interested in dig into which extension has a conflict, it will be nice to contribute the information to an FAQ doc.

**Comment by liswift** [comment]
@Yuyz0112 AlloyDesigner.

**Comment by dohuyhung** [comment]
@Yuyz0112 I encounter the same issue. When I use my own rrweb extension, I cannot use the rrweb.Replayer package on a VueJS website. The error is : TypeError: Failed to fetch dynamically imported module.
( I dont have this problem with rrweb-player)

If i disable my own rrweb extension, then the website is okay.

@liswift  How you dealt with it ?
