### ISSUE TITLE
多个具有时间差的record如何连续性播放

### ISSUE THREAD

**Issue by crystalpp** [rrweb-io/rrweb#290]
最近使用过程中遇到多个record之间间隔了很长的时间，能否将两个record连续性在一起播放，是否有record播放完成的回调或者其他方式。

**Comment by Yuyz0112** [comment]
可以通过 `replayer.on('finish', () => {})` 的方式监听播放完成。

**Comment by wy6921** [comment]
> 可以通过 `replayer.on('finish', () => {})` 的方式监听播放完成。

@Yuyz0112 老师，您好，我使用的是rrwebReplayer播放，使用addEventListene('finish')的方式监听播放，会导致进度条重新切换，有没有什么方法可以使具有长时间差的record在一个进度条内完成呢？期待您的指导

**Comment by Yuyz0112** [comment]
@wy6921 那可以修改 events 里的时间戳，把它们的时间重新排列为你期望的状态。

比如原来录制的两段时间戳分别是：
```
e1(0) -> e2(100) -> e3(150)
e1'(1000) -> e2'(1050) -> e3'(1100)
```

就可以处理成
```
e1(0) -> e2(100) -> e3(150) -> e1'(150) -> e2'(200) -> e3'(250)
```
