### ISSUE TITLE
一个页面滚动会产生大量录制数据

### ISSUE THREAD

**Issue by huqi1** [rrweb-io/rrweb#291]
在vue项目中接入后一个页面的滚动可能会产生100个event，我在emit中打印console，不论是否有操作，会一直打印，但是很奇怪，并不会一直push数据，请问是否跟我的框架有关
```
rrweb.record({
  emit(event) {
   console.log(1); //页面不动时 console也会一直打印，但不会一直push
  events.push(event);//
  },
});
```

**Comment by Yuyz0112** [comment]
可以发一下采集到的 event，看看是什么内容。比如你的应用里滚动是否触发了动画、修改了 DOM 的属性等

**Comment by Yuyz0112** [comment]
如果有更新可以再 reopen
