### ISSUE TITLE
Does liveMode support building the DOM off of old events?

### ISSUE THREAD

**Issue by mehtamanan** [rrweb-io/rrweb#299]
Is it possible to ingest events that have already happened and then start live mode?

i.e., Let's say I have been recording events for the last 15 minutes and I'm also recording events live. I want the player to ingest everything that happened in the last 15 minutes (so it builds out the DOM from all the mutations) and then immediately join in on the live events and play them in real time?

**Comment by mehtamanan** [comment]
@Yuyz0112 Would appreciate a response for this :)

**Comment by randy-johnson** [comment]
@mehtamanan ,  looks like this PR may be the fix you need.  https://github.com/rrweb-io/rrweb/pull/310

**Comment by mehtamanan** [comment]
@randy-johnson Awesome! Thanks for the update :)
