### ISSUE TITLE
Bookmarklet

### ISSUE THREAD

**Issue by l2aelba** [rrweb-io/rrweb#30]
**Great work so far!** 🍺 

Does it not useful if we could run as [bookmarklet](https://en.wikipedia.org/wiki/Bookmarklet)? For **local recording** ?

```js
javascript:(function(){
  // here
})();
```

_Just an idea 😄_

**Comment by Yuyz0112** [comment]
Not quite familiar with the bookmarklet, but we already have a [REPL tool](https://github.com/rrweb-io/rrweb/blob/master/guide.md#repl-tool) which can record your interactions and generate a static HTML file to display it.
Also, there is a PR #21 trying to improve the REPL tool to generate a more general JS file to replay.

Is this suitable for bookmarklet usage? Would be happy to learn more about that.

**Comment by l2aelba** [comment]
@Yuyz0112 Something like this http://lab.maltewassermann.com/viewport-resizer ?

**Comment by DvdGiessen** [comment]
I've been working on something like this for my [livestreaming branch](https://github.com/DvdGiessen/rrweb/tree/livestream-server). Right now it provides a JS snippet that can be run in the console (or a bookmarklet would work, too) and then allows instant playback on a generated URL.

**Comment by lidong081824** [comment]
I didn't get the pause, the demo on the home page is very general

**Comment by mehtamanan** [comment]
> @DvdGiessen live streaming is cool! I've also written a very simple demo for a live-mode.
> ![peek 2019-01-05 10-27](https://user-images.githubusercontent.com/13651389/50719246-b8bcc180-10d4-11e9-8db6-6ed2a0b3098d.gif)

@Yuyz0112 Where can I find this demo? :) Thanks for the great library and unbelievable support!
