### ISSUE TITLE
in liveMode, when sync with other screen , the scroll position is not synced

### ISSUE THREAD

**Issue by chxuu** [rrweb-io/rrweb#300]
hello

I have two screen, one is teacher, and another is student. when teacher do some thing(includes dropdown scroll), the student refresh page. I will notice teacher, stop current record and start another record. then, the student page content will sync with the teacher besides the scroll position.

Now, face this question, I don't know how to resolve it so that I looking forward to your reply, thank you very much.

**Comment by Yuyz0112** [comment]
@chxuu 

Are you scrolling the whole window or scrolling inside a DOM?

**Comment by chxuu** [comment]
@Yuyz0112 

scrolling inside a DOM

**Comment by Yuyz0112** [comment]
@chxuu https://github.com/rrweb-io/rrweb-snapshot/commit/f7d43f5fee7e064dff44375fae087edb42c3e8ae

Nested scroll will be supported in the coming version 0.9.1
