### ISSUE TITLE
录制回放时页面报错如何跳过错误继续播放

### ISSUE THREAD

**Issue by crystalpp** [rrweb-io/rrweb#301]
在app录制过程中调用了原生方法，回放时到了该部分就报错，是否有相应的方法可以跳过报错继续播放，或者录制时忽略某个方法的调用

**Comment by Yuyz0112** [comment]
错误信息是什么

**Comment by crystalpp** [comment]
报有一个原生方法找不到  getappVerision(android原生方法用来获取app版本的)

**Comment by Yuyz0112** [comment]
重放的时候应该是不会执行任何 JS 代码的，可以看一下对应的 events 或者详细的错误栈吗

**Comment by crystalpp** [comment]
看了下没有报错 我再看看 感谢
