### ISSUE TITLE
不同网络的录制与回放

### ISSUE THREAD

**Issue by Sol0423** [rrweb-io/rrweb#302]
录制时候采用外部网络录制，回放的时候只能采用内网播放，这样会导致有些静态资源图片获取不到。对于这种情况是否有什么好的解决方式，麻烦指导下。谢谢！

**Comment by Yuyz0112** [comment]
期望是能看到图片吗？如果是这样的话，可能需要遍历存储的数据，把所有外部静态资源链接提取出来，用单独的脚本下载到内网后 serve 出来，再把数据中的链接替换为内网链接。
