### ISSUE TITLE
该polyfill对iframe无效

### ISSUE THREAD

**Issue by jokeewu** [rrweb-io/rrweb#303]
https://github.com/rrweb-io/rrweb/blob/772c0e021a3e0fbbc60abee7ff47b0abc9fbd832/src/replay/index.ts#L96
https://github.com/rrweb-io/rrweb/blob/772c0e021a3e0fbbc60abee7ff47b0abc9fbd832/src/replay/index.ts#L97

**Comment by jokeewu** [comment]
> 是指哪部分的 iframe？

https://github.com/rrweb-io/rrweb/blob/772c0e021a3e0fbbc60abee7ff47b0abc9fbd832/src/replay/index.ts#L336
https://github.com/rrweb-io/rrweb/blob/772c0e021a3e0fbbc60abee7ff47b0abc9fbd832/src/replay/index.ts#L890

**Comment by wsq547ak** [comment]
你自己给iframe加一下不就好了

**Comment by Yuyz0112** [comment]
感谢反馈，已修复 @jokeewu
