### ISSUE TITLE
Replay in the page rather than in an iframe ?

### ISSUE THREAD

**Issue by lubenard** [rrweb-io/rrweb#304]
I was wondering if it was possible to replay directly on the webpage body and not in a div created just for the replay ?

**Comment by Yuyz0112** [comment]
We need iframe to provide a safe sandbox: https://github.com/rrweb-io/rrweb/blob/master/docs/sandbox.md

Are you hitting any limitation with the iframe implementation?

**Comment by lubenard** [comment]
Well, i am recording a web session, and need to be able to set a pause, come back in the timeline events (this is where the replayer come in) and modify the webpage as if i was just coming back in time.
I do not know if it is very clear.

**Comment by Yuyz0112** [comment]
Do you need to modify the webpage rebuild by rrweb's replayer? If so, it will not work since it breaks the DOM mapping. You can consider the replay webpage is an immutable view.

**Comment by Yuyz0112** [comment]
Feel free to reopen this issue if there is still any question.
