### ISSUE TITLE
`Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`

### ISSUE THREAD

**Issue by Juice10** [rrweb-io/rrweb#306]
In some cases when `applyMutation` removes a node, the parent of that node is not attached to the document. This triggers the following error `Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`

## Expected behaviour
No error should happen

## To reproduce
1. `git clone git@github.com:juice10/rrweb-player-1.git`
2. `npm install`
3. `npm start`
4. Open [http://localhost:1234](http://localhost:1234)
5. Seek to around the 23 second or 26 second mark and let it play for a couple seconds, error will trigger: <img width="286" alt="image" src="https://user-images.githubusercontent.com/4106/91184454-f24ca100-e6ec-11ea-8bf9-66e469f99c3f.png">

# Additional information

<img width="333" alt="image" src="https://user-images.githubusercontent.com/4106/91185254-de556f00-e6ed-11ea-9a2b-3ac7ca503a78.png">
<img width="1162" alt="image" src="https://user-images.githubusercontent.com/4106/91185362-0513a580-e6ee-11ea-9bf7-39f3e01eb1d4.png">

The error isn't triggered when seeking (`isSync == true`) past the event.
The error also isn't triggered if playing from the very start.

Based off of https://github.com/rrweb-io/rrweb/issues/285#issuecomment-678808349 & https://github.com/rrweb-io/rrweb/issues/285#issue-679841740

## Example event triggering failure
```json
{"source":0,"texts":[{"id":3033,"value":"\n/* sc-component-id: sc-global-2139370859 */\n.intercom-messenger-frame{left:0.5rem !important;bottom:4.25rem !important;}"}],"attributes":[],"removes":[{"parentId":99,"id":2635}],"adds":[{"parentId":99,"nextId":107,"node":{"type":3,"textContent":"\n/* sc-component-id: sc-global-2139370859 */\n.intercom-messenger-frame{left:0.5rem !important;bottom:4.25rem !important;}","isStyle":true,"id":3033}}]}
```

View [all events](https://github.com/Juice10/rrweb-player-1/blob/master/src/response.js).

**Comment by Sol0423** [comment]
请问报Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node 这个错 有什么解决方式吗 浏览了一圈issue 没看到具体的解决方法

**Comment by Juice10** [comment]
> 请问报Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node 这个错 有什么解决方式吗 浏览了一圈issue 没看到具体的解决方法

I don't have a solution for it yet.

I did notice this issue is a duplicate of https://github.com/rrweb-io/rrweb/issues/88

**Comment by Juice10** [comment]
Closing this issue because it is a duplicate of #88
