### ISSUE TITLE
pack和unpack的问题

### ISSUE THREAD

**Issue by cosee128** [rrweb-io/rrweb#308]
pack和unpack在数据存放在localstorage时播放能正常使用；而通过pack压缩后发送到后端，再请求回来就格式不对了，请问下可能是什么原因呢？要如何排查？

**Comment by Yuyz0112** [comment]
格式不对是指遇到什么具体的错误呢？

**Comment by cosee128** [comment]
unpack时报错：unknown data format.

**Comment by Yuyz0112** [comment]
先比较一下前端 unpack 之后数据的长度和后端实际存入的数据的长度？看看是不是尺寸现在

**Comment by cosee128** [comment]
谢谢老师，我对比了一下，每条数据长度都是相同的，但是解析之后，浏览器中打印出来的乱码是不一致的，是否因此播放不成功呢？这种情况下怎么解决呢？

**Comment by Yuyz0112** [comment]
@cosee128 

我不太确定你的后端是什么样的，假如流程是这样的：
```
前端发送(1) -> 后端收到(2) -> 后端存储(3) -> 后端发送(4) -> 前端收到(5)
```

就分别比较一下 1,2,3,4,5，看一下是哪个环节数据发生了变化，再具体看看那个环节里有哪些地方可能修改数据？

**Comment by cosee128** [comment]
非常感谢您的回答，给了我排查思路，我这是因为前后端的encode和decode导致的数据变化，已经解决，十分感谢！
