### ISSUE TITLE
录制数据过大

### ISSUE THREAD

**Issue by Sol0423** [rrweb-io/rrweb#312]
录制时长1分30秒，数据大小达到了4M。是否有什么有效方法可以降低录制数据的大小。已使用pack与pako

**Comment by Yuyz0112** [comment]
数据大小的优化分为两个部分
1. 单次录制的大小。可以通过 sampling、block 不重要但是占用数据多的 DOM、压缩来优化。
2. 总的大小。可以通过提取多次录制间相同的数据块（比如全量快照）来优化。

**Comment by crystalpp** [comment]
如何提取全量快照呢

**Comment by Yuyz0112** [comment]
根据 events 的 type 字段可以判断哪个是全量快照

**Comment by crystalpp** [comment]
那应该如何提取出来呢  我们的events type为 4 2 3 3 3 3 3

**Comment by Yuyz0112** [comment]
提取就是把多个 session 相同的 event 只保存一份。

具体怎么保存、提取的时机和重新组装的时机都是需要自己实现的。

**Comment by zhaoxm2016** [comment]
可否提供一个例子的大体结构哈

**Comment by tangjian1891** [comment]
> 那应该如何提取出来呢 我们的events type为 4 2 3 3 3 3 3

请问有实现如何提取全量快照的方法吗?现在也遇到events总量过大的问题

**Comment by Yuyz0112** [comment]
可以阅读
[深入录制数据](https://github.com/rrweb-io/rrweb/blob/master/docs/recipes/dive-into-event.zh_CN.md)
[优化存储容量](https://github.com/rrweb-io/rrweb/blob/master/docs/recipes/optimize-storage.zh_CN.md)

新的[场景示例](https://github.com/rrweb-io/rrweb/blob/master/docs/recipes/index.zh_CN.md)文档提供了更多信息。

**Comment by websmallrabbit** [comment]
如何去冗， 比如说把样式文件单独抽离出来，events只push 轨迹数据，还原时，再把数据拼接起来/

**Comment by Yuyz0112** [comment]
@websmallrabbit 思路就是文档中描述的，你是指具体实现吗？具体实现是对 events 数据的操作，还需要结合后端、存储的情况进行设计，rrweb 中不会对这部分进行规定。

**Comment by LoooChy** [comment]
文档描述的太笼统了，没有实际例子。对于pack和unpack这个，录制时压缩没有问题，按照文档写的unpackFn: rrweb.unpack，这个地方就是undefined。真的希望完善一下例子，对于刚接触的新人一头雾水。
