### ISSUE TITLE
控制台报错：0: Replayer need at least 2 events.

### ISSUE THREAD

**Issue by superwego** [rrweb-io/rrweb#313]
您好，偶然看到您的项目，觉得很有意思，所以写了个简单的页面试试。录制代码可以正常接收，但是播放却一直实现不了，请您指点。
下面是播放页面的代码：
![replaycode](https://user-images.githubusercontent.com/70262999/91789434-3be34180-ec41-11ea-9848-a8da8ed3702b.png)

下面的文件是events_str的值：
[events_str.txt](https://github.com/rrweb-io/rrweb/files/5153723/events_str.txt)

下面截图是replay页面的效果：
![replay页面效果](https://user-images.githubusercontent.com/70262999/91789184-b495ce00-ec40-11ea-9f46-d368c0134ece.png)
谢谢！

**Comment by Yuyz0112** [comment]
传入的 events 需要是数组类型，不是 string

**Comment by superwego** [comment]
> 传入的 events 需要是数组类型，不是 string

感谢您的回复，昨天上传的文档是我笔误写成了events_str的值，其实应该是jsonObj的值。前台对此对象做了处理再传递给rrwebPlayer的：
1、先把events节点取出来：var eventsObj = jsonObj.events;
2、转成字符串传递给rrwebPlayer对象：var events_str = JSON.stringify(eventsObj);
最终传递给rrwebPlayer对象的值是：
[events_str.txt](https://github.com/rrweb-io/rrweb/files/5159540/events_str.txt)
格式化之后的events_str如下图：
![2222222222](https://user-images.githubusercontent.com/70262999/91921732-c9d13200-ecfe-11ea-9e8e-002f6c9b92d6.png)
传入的是数组格式。
但是chrome浏览器还是报错：
![333333333333](https://user-images.githubusercontent.com/70262999/91921973-5da2fe00-ecff-11ea-8c70-abf3dec632cc.jpg)

**Comment by superwego** [comment]
> 传入的 events 需要是数组类型，不是 string

您好，我按照您的提示把传入播放器的对象改成了数组类型，但是控制台依旧报错。
1、尝试使用rrweb.Replayer(eventsForPlayer)
![20200902-1](https://user-images.githubusercontent.com/70262999/91925508-baa2b200-ed07-11ea-9fa6-f2347e33a90e.jpg)
但是chrome控制台报错：
![20200902-2](https://user-images.githubusercontent.com/70262999/91925524-c5f5dd80-ed07-11ea-8d22-8134dc14e364.jpg)
2、尝试使用rrwebPlayer
![20200902-3](https://user-images.githubusercontent.com/70262999/91925554-d443f980-ed07-11ea-9287-ea8718dcb32d.jpg)
chrome也报错：
![20200902-4](https://user-images.githubusercontent.com/70262999/91925572-dc9c3480-ed07-11ea-95a7-af8995391b86.jpg)
在chrome控制台输出console.info(eventsForPlayer);
当传入数组的是对象时，控制台输出：
![20200902-6](https://user-images.githubusercontent.com/70262999/91925790-592f1300-ed08-11ea-8f22-bd7d7be98e4f.jpg)
当出入数组的是字符串时，控制台输出：
![20200902-5](https://user-images.githubusercontent.com/70262999/91925817-65b36b80-ed08-11ea-92cb-52141b1f04d4.jpg)

**Comment by Yuyz0112** [comment]
按你的写法应该是

```
new rrwebPlayer({
  target: document.body,
  data: {
    events: eventsForPlayer
  }
})
```

**Comment by superwego** [comment]
感谢您的指点！

> 按你的写法应该是
> 
> ```
> new rrwebPlayer({
>   target: document.body,
>   data: {
>     events: eventsForPlayer
>   }
> })
> ```
