### ISSUE TITLE
内容回复有重复的情况

### ISSUE THREAD

**Issue by cgaof** [rrweb-io/rrweb#314]
有些情况下 内容有重复，但并不是必现的

![image](https://user-images.githubusercontent.com/29372321/91923397-d9527a00-ed02-11ea-907b-4d0948052dce.png)
图中  导入编码和是否自动映射 就重复了

**Comment by Yuyz0112** [comment]
可以提供对应的 events debug 吗？

**Comment by cgaof** [comment]
直接comment 数据太大，提交不了。
放到一个工程里面了， https://github.com/cgaof/rrweb-events.git， 里面的json.js 里面

**Comment by Yuyz0112** [comment]
比较奇怪的是在 `1598409897770` 这个时间点采集到了两个内容非常相似的 event。

能否确认一下录制的代码会不会意外触发多次录制？

**Comment by cgaof** [comment]
> 比较奇怪的是在 `1598409897770` 这个时间点采集到了两个内容非常相似的 event。
> 
> 能否确认一下录制的代码会不会意外触发多次录制？
目前没有发现，
如果是多次录制是不是会产生type 等于4的数据？ 这里只有一个type等于4的数据。这边在使用中 测试多次提到有重复的数据。这个是其中一个用例，你那边没有发现过类似的情况吗？

**Comment by Yuyz0112** [comment]
@cgaof 目前没有遇到，可以尝试一下最新 release 的 0.9.1 版本吗？或者有没有可公网访问的例子让我测试一下

**Comment by cgaof** [comment]
> @cgaof 目前没有遇到，可以尝试一下最新 release 的 0.9.1 版本吗？或者有没有可公网访问的例子让我测试一下

好的 我先试一下 0.9.1 的。公网的目前没有 都是公司内网项目。

**Comment by cgaof** [comment]
> > @cgaof 目前没有遇到，可以尝试一下最新 release 的 0.9.1 版本吗？或者有没有可公网访问的例子让我测试一下
> 
> 好的 我先试一下 0.9.1 的。公网的目前没有 都是公司内网项目。

@Yuyz0112  刚刚尝试0.9.1 版本，还是有重复的

**Comment by Yuyz0112** [comment]
在最新版本是否还有这个问题呢？修复了一个相关的代码。

**Comment by liuqin0430** [comment]
你好，使用最新的0.9.4版本，目前发现还是有数据存在重复，多发生在vue 项目中的v-if展示的数据

**Comment by Yuyz0112** [comment]
有可以复现问题的 vue 代码吗

**Comment by Yuyz0112** [comment]
如果有可以复现问题的代码请 reopen 这个 issue。

**Comment by 94zn** [comment]
> 你好，使用最新的0.9.4版本，目前发现还是有数据存在重复，多发生在vue 项目中的v-if展示的数据

解决重复events 的问题了吗？

**Comment by wyysf123** [comment]
重复都是发生在 判断显示隐藏的地方，比如react的三元判断，类似上面说的vue的v-if
