### ISSUE TITLE
图片更新问题

### ISSUE THREAD

**Issue by LyAce** [rrweb-io/rrweb#315]
视频播放时候如果我原网站图片地址发生改变，会导致播放的内容相应的改变，有没有能把图片转成base64的方法进行存储的

**Comment by Yuyz0112** [comment]
如果需要转成 base64 的话可以在 record emit 的回调里判断每次输入的 event，如果是包含了图片 URL 的内容，就把对应 image DOM 转为 base64 字符串保存。

**Comment by LyAce** [comment]
请问下再整体页面存储的时候，如何判断event中包含图片url内容，我看返回的数据里面好像没有比较好的判断依据
