### ISSUE TITLE
图片相关问题

### ISSUE THREAD

**Issue by LyAce** [rrweb-io/rrweb#316]
1.在记录上传问题的操作时，回播的时候图片显示不出来
2.初始化记录页面数据的时候，想要把html 和 css中的图片转换成base64格式，请问emit的回调函数中可以依据什么来判断，目前的需求是想让播放的内容和原网站解除联系

**Comment by Yuyz0112** [comment]
1. 图片显示不了的原因是什么？
2. 可能包含 DOM 节点的 event 包括以下几种

event.type 为 `EventType.FullSnapshot` 的数据，可以使用 `rrweb-snapshot` 提供的 visit function 进行遍历：https://github.com/rrweb-io/rrweb-snapshot/blob/master/src/snapshot.ts#L434

event.type 为 `EventType.IncrementalSnapshot` 且 event.data.source `IncrementalSource.Mutation` 的数据，可以遍历 event.data.adds 这个新增节点的数组进行判断。

**Comment by zhaoxm2016** [comment]
@Yuyz0112 是否支持只让页面中的某张图片Base64呢

**Comment by Yuyz0112** [comment]
@zhaoxm2016 上面的方法有足够的能力判断是否需要把某张图片转化为 base64

**Comment by zhaoxm2016** [comment]
@Yuyz0112 没太理解，inlineStylesheet为false时，现在页面中碰到几张图片url因为有效期的问题，想转换成Base64

**Comment by Yuyz0112** [comment]
@zhaoxm2016 哪部分不理解？

url 信息都是记录在 event 内的

```
event.type 为 EventType.FullSnapshot 的数据，可以使用 rrweb-snapshot 提供的 visit function 进行遍历：https://github.com/rrweb-io/rrweb-snapshot/blob/master/src/snapshot.ts#L434

event.type 为 EventType.IncrementalSnapshot 且 event.data.source IncrementalSource.Mutation 的数据，可以遍历 event.data.adds 这个新增节点的数组进行判断。
```

这个描述是找到包含 url 的 event 的方式。拿到 url 之后就可以用 JS 实现 url 加载图片，再保存为 base64 格式，替换原本的 url

**Comment by zhaoxm2016** [comment]
明白了，谢谢。

**Comment by zhaoxm2016** [comment]
@Yuyz0112 抱歉还没有阅读源码，想问下EventType对应的值在哪个文件中啊

**Comment by Yuyz0112** [comment]
@zhaoxm2016 
https://github.com/rrweb-io/rrweb/blob/master/src/types.ts#L9

**Comment by zhaoxm2016** [comment]
这个文件看到了
![image](https://user-images.githubusercontent.com/51771541/92346578-bd364a80-f0ff-11ea-8b2d-17f741fd44b5.png)
EventType.IncrementalSnapshot这个具体的值是多少呢

**Comment by Yuyz0112** [comment]
我们用的是 TS 的 number enum，所以 enum 对应的实际值就是从上至下 0, 1, 2...

**Comment by zhaoxm2016** [comment]
感谢

**Comment by zhaoxm2016** [comment]
我是用rrweb.record采集的数据，也就是说我只需要在事件类型为EventType.IncrementalSnapshot的事件中，遍历event.data.adds中我需要转换的url做响应Base64处理替换即可。这样理解的对吧？

**Comment by Yuyz0112** [comment]
@zhaoxm2016 

EventType.FullSnapshot 也需要，是包含初始 DOM 信息的全量快照

**Comment by zhaoxm2016** [comment]
这样循环遍历的话性能上估计会存在问题
![image](https://user-images.githubusercontent.com/51771541/92349766-a3016a00-f109-11ea-8c36-659645cff6a1.png)
36是我要转换的数据

**Comment by Yuyz0112** [comment]
这个遍历的开销是不可避免的，就像把当前 DOM 遍历一遍是一样的。

而且这个过程只是 JS 的执行，替换等等都可以是异步按需的。或者可以把整个过程放到后端去进行。

**Comment by zhaoxm2016** [comment]
@Yuyz0112 请教下，rrweb里用的什么方法转换成Base64的呢？

**Comment by zhaoxm2016** [comment]
@Yuyz0112 想看一下这块转换成base64的源码，方便告知一下吗

**Comment by Yuyz0112** [comment]
@zhaoxm2016 rrweb 没有转 base64 的实现。

JS 如何实现可以搜索相应的问题，比如 https://stackoverflow.com/questions/6150289/how-can-i-convert-an-image-into-base64-string-using-javascript

**Comment by cddsgtc** [comment]
@Yuyz0112 base64或者objectUrl形式的图片在录制时会短时间触发3万以上的事件，而且都是回调的，所以会导致页面在录制和播放时非常卡顿，特别是播放时。
我这里的场景是，是吧pdf文件转换成图片然后展示到页面上。
