### ISSUE TITLE
Navigation to a New page in the website

### ISSUE THREAD

**Issue by nikhilrayaprolu** [rrweb-io/rrweb#318]
If my website is not a single page application, what if users navigate to new page in the same webpage on clicking a link - Does the recording still continues?, Especially in the case of live mode?

**Comment by nikhilrayaprolu** [comment]
@Yuyz0112 any suggestion?

**Comment by Yuyz0112** [comment]
The recording will stop because it was hosted on the current page. When you navigate to another page, you'd better start a new record with some identification info so your server will know they are the same session.

**Comment by Yuyz0112** [comment]
Feel free to open this issue if you still have any question:)
