### ISSUE TITLE
DOM结构复杂的页面回放时导致页面直接停止响应

### ISSUE THREAD

**Issue by Rxdey** [rrweb-io/rrweb#319]
使用的最新的`master`版本打包
已发布的`0.9.0`版本也试过
dom结构复杂度比较高的页面回放时会导致页面直接停止响应 
dom结构简单的可以正常播放
看了下似乎是执行到`applyMutation`方法时`appendNode` 会循环到崩溃

**Comment by Yuyz0112** [comment]
可以提供 events 用于 debug 吗？

**Comment by Yuyz0112** [comment]
对于 addedNodeMutation 这个类型，rrweb record 过程返回的应该是 `number | null` 这个类型。从你提供的 events 来看，你在存储 events 的某个序列化过程中应该是自动把值为 null 的 field 给移除了，所以出现了 nextId 为 undefined 的情况（正常应该是 null）

我在新的 patch 里兼容了这种情况，避免了这个问题。不过还是建议检查一下序列化的过程，因为还可能因为这个转化造成其它的问题。
