### ISSUE TITLE
vue 单页面应用 使用router跳转时 只能记录第一个页面

### ISSUE THREAD

**Issue by flameyun** [rrweb-io/rrweb#321]
因为router跳转只修改了url ，所以记录事件不完全 。除非强制刷新每个页面， 请问如何在每次路由跳转的时候能记录完整页面？

**Comment by Yuyz0112** [comment]
可以提供对应的 events 用于 debug 吗？

另外在路由变化的过程中，record function 始终在生效吗？

**Comment by flameyun** [comment]
始终生效，业务需求是将项目以页面做分隔回放

[event.zip](https://github.com/rrweb-io/rrweb/files/5180825/event.zip)

提供的event合并在一起没有问题，单独播放就会缺少元素，请问有什么好的方法解决？

**Comment by flameyun** [comment]
我尝试将record写在了router.afterEach方法里，路由跳转后可以获取完整的页面。但是每个页面都调用一次record，有时会有重复的记录，页面元素会有双份，请问是否有方法能在每次调用之前清掉上一个？

**Comment by Yuyz0112** [comment]
> 提供的event合并在一起没有问题，单独播放就会缺少元素

这个的意思是说从头到尾播放是没有问题的，中间选一段播放才有这个 issue 描述的问题吗？

比如你有编号 1 ~ 100 的 event，播放 20 ~ 30 是不会生效的，因为 event 是以 op-log 的形式增量组织的。

如果需要分段播放，就要把每一段单独录制。record 会返回一个 stop function 用于停止录制，可以在每一段都停止上一段，再开始下一段。

**Comment by flameyun** [comment]
好的，明白。 谢谢您！
