### ISSUE TITLE
录制页面的回放内容和实际应用中的内容有区别

### ISSUE THREAD

**Issue by frcy9** [rrweb-io/rrweb#322]
应用操作中，一个select组件，应用中页面显示数据60。回放录屏内容时候，对应的值却显示的是70。是什么原因导致录屏会和实际内容不一呢？

**Comment by Yuyz0112** [comment]
有对应的 events 可以用于 debug 吗？

**Comment by frcy9** [comment]
> 有对应的 events 可以用于 debug 吗？

开发电脑不便于提供 events ，情况就是前端select值初始是70，后来修改了其他选项值，会联动select的值跟着变动（知乎上写的程序设置型） ，值变成了60，但是后面再后台播放录屏的时候 ，回放一直是70，

**Comment by frcy9** [comment]
> 有对应的 events 可以用于 debug 吗？

复现的events数据和复现的代码已发送aryu0112@gmail.com邮箱。

**Comment by Yuyz0112** [comment]
感谢反馈，已修复
