### ISSUE TITLE
new rrweb.Replayer在root下产生多个replayer-wrapper，能否配置替换而不是新增

### ISSUE THREAD

**Issue by zhaoxm2016** [rrweb-io/rrweb#324]
![image](https://user-images.githubusercontent.com/51771541/92228183-04db8d00-eeda-11ea-9d6f-92942cd0035e.png)

**Comment by Yuyz0112** [comment]
不会有替换的行为，如果需要管理 player 的生命周期可以通过 destroy 销毁

**Comment by zhaoxm2016** [comment]
@Yuyz0112

**Comment by zhaoxm2016** [comment]
好的，谢谢
