### ISSUE TITLE
canvas的drawImage中,toDataURL拿不到数据

### ISSUE THREAD

**Issue by sunzhixun001** [rrweb-io/rrweb#325]
events.data.args = ['data:,', 0, 0, 3617, 758, 0, 0, 1890, 379]...
用canva展示pdf,回放时无法播放

**Comment by Yuyz0112** [comment]
有可以复现的链接用于测试吗？drawImage 时实际的第一个参数对象是什么内容呢？

**Comment by Yuyz0112** [comment]
如果有可以复现的链接或者其它信息，请 reopen 这个 issue。

**Comment by naimao001** [comment]
@Yuyz0112  我也是这个问题 也是canvas展示pdf 出现的  我怎么发events给你  发邮箱吗

**Comment by Juice10** [comment]
@naimao001 you can use gists.GitHub.com to share the events or follow the instructions on rrwebdebug.com.
