### ISSUE TITLE
Test: `captures stylesheet rules` not deterministic

### ISSUE THREAD

**Issue by Juice10** [rrweb-io/rrweb#328]
The `captures stylesheet rules` test fails randomly sometimes without any related code being changed.

Example of the same code running twice and having two different outcomes in Travis CI:
- Build Failed: https://github.com/rrweb-io/rrweb/pull/327/commits/4ab4883764c97db71b3b2f6344dac00aba372013
- Build Passed: https://github.com/rrweb-io/rrweb/pull/327/commits/e72e2014c5355fa52dd27a9d5260069c80fff022

Another example of code being modified that doesn't have to do with this test but the test is randomly failing and passing:
https://github.com/rrweb-io/rrweb/pull/294

**Comment by Yuyz0112** [comment]
Yes, there are some fragile test cases, most of them are causing by the network(like load async stylesheet).

Do not have time to investigate in every case at this moment, but definitely something we can do to improve the dev process.
