### ISSUE TITLE
Please improve the document.

### ISSUE THREAD

**Issue by x-ray-s** [rrweb-io/rrweb#329]
The document is so simple and crude.Some API and method doesn't provide.It confuse me, I want to develop live mode web record, but I don't know how to use some method and what is it meaning.

在阅读文档后，我仍然对一些方法和暴露的 API 感到疑惑，比如我想手动调用初始化，并在后续手动去触发添加事件，并在回放中接收添加的事件，或者给出一个 live mode 的例子。这只是一个困扰我的方面，通过文档，我只能做出一个简单的录制和回放页面，我无法知道内部暴露的方法如何使用，都有哪些提供的功能和方法，以及配置。

现在我只能选择 timeCat，因为他提供更多的文档说明和案例。

**Comment by Yuyz0112** [comment]
@x-ray-s 感谢反馈，[使用指南](https://github.com/rrweb-io/rrweb/blob/master/guide.zh_CN.md)里的内容已经更新了最新的 API 和配置用法。

同时新增了一组[场景示例](https://github.com/rrweb-io/rrweb/blob/master/docs/recipes/index.zh_CN.md)，对应各种常见场景。
