### ISSUE TITLE
最后一秒无法播放

### ISSUE THREAD

**Issue by sunzhixun001** [rrweb-io/rrweb#330]
放到倒数第2秒就finish了, 获取的master最新代码,events暂时无法提供,开发电脑有限制

**Comment by Yuyz0112** [comment]
感谢反馈，已修复

**Comment by frcy9** [comment]
> 感谢反馈，已修复

最新的代码有问题。会导致某个多组件的页面的录屏数据很大，查看的回放的dom结构，生成了多个 “相同” 组件，本来200来KB的大小 ，变成了4M+

**Comment by Yuyz0112** [comment]
@frcy9 可以提供对应的 events 或者录制网站用于 debug 吗？
