### ISSUE TITLE
回放时多了一个和视频同样尺寸的canvas

### ISSUE THREAD

**Issue by sunzhixun001** [rrweb-io/rrweb#332]
这个canvas把iframe挤到了容器外面

**Comment by Yuyz0112** [comment]
@sunzhixun001 

使用的是 rrweb-player 还是 rrweb？

两个包在最新的 release 里应该都有这个样式用来对应 canvas

```
.replayer-mouse-tail {
  position: absolute
}
```

**Comment by sunzhixun001** [comment]
> @sunzhixun001
> 
> 使用的是 rrweb-player 还是 rrweb？
> 
> 两个包在最新的 release 里应该都有这个样式用来对应 canvas
> 
> ```
> .replayer-mouse-tail {
>   position: absolute
> }
> ```

好了,谢谢

**Comment by sunzhixun001** [comment]
ok了

**Comment by xqj123** [comment]
请问怎么解决的
