### ISSUE TITLE
回放过程中的静态资源加载

### ISSUE THREAD

**Issue by crystalpp** [rrweb-io/rrweb#333]
目前我们在回放时某些会遇到页面样式错乱问题，network中显示相应的css文件没有拉取到 。 这种情况是录制时的问题还是回放时的问题呢

**Comment by Yuyz0112** [comment]
没有拉取到是有 CSS 样式表的请求失败了吗？具体失败的原因是什么

**Comment by Yuyz0112** [comment]
如果有进一步的信息可以 reopen 这个 issue。
