### ISSUE TITLE
录制页面有vue的标签:v-if、v-show、select部分显示不正常

### ISSUE THREAD

**Issue by chenkaikevin** [rrweb-io/rrweb#334]
录制页面有vue的标签:v-if、v-show页面错乱，select部分显示文字异常。

**Comment by Yuyz0112** [comment]
可以提供 events 用于 debug 吗？

**Comment by bing086** [comment]
也出现类似的情况  events数据如下
http://47.101.54.2:3001/event.json

**Comment by chenkaikevin** [comment]
@Yuyz0112  就是select下拉数据的，保存后视频数据就会全部展示出来。有什么好的解决办法吗？

**Comment by chenkaikevin** [comment]
@bing086 你那里是什么vue页面吗？用的什么控件出问题？

**Comment by bing086** [comment]
> @bing086 你那里是什么vue页面吗？用的什么控件出问题？

是的用的vant

**Comment by crystalpp** [comment]
请问这个问题有什么比较好的解决方案吗  我也遇到了类似的问题

**Comment by Yuyz0112** [comment]
@bing086 你提供的 events，有问题的地方是哪部分？

@crystalpp 有相关数据和预期行为可以提供吗

**Comment by Yuyz0112** [comment]
如果有可以复现问题的代码，请 reopen 这个 issue
