### ISSUE TITLE
input导致iframe的缩放出现变化

### ISSUE THREAD

**Issue by wy6921** [rrweb-io/rrweb#335]
您好，当我使用h5录制时，因input唤起原生键盘，导致回放的时候页面忽大忽小，还会唤起原生键盘，请问是什么原因？看起来scale是不断变化的，请问我如何避免回放页面忽大忽小呢？

**Comment by Yuyz0112** [comment]
因为键盘谈起会导致 window 尺寸变化，也就触发了 rrweb 回放时候的自动 scale。

自动 scale 的目的是在任意时刻尽可能多的展示内容，如果提供一个配置，可以禁止自动 scale，能够解决你的问题吗？

**Comment by wy6921** [comment]
不知我理解的是禁止自动scale，是否和通过important设置固定scale值的某种程度上的效果是一样。对于我们而言，scale是必须的，想问下有没有设置可以忽视键盘对window尺寸的变化，即完整录下键盘下那一层的内容

**Comment by Yuyz0112** [comment]
不会录制键盘，因为不是 DOM 的一部分。

还有一个方式是把 events 里 resize 的事件全部移除不回放，这样初始化的时候会 scale，后续的 window 变化就不回放不触发 scale 了。

**Comment by wy6921** [comment]
不是很明白您的意思，是在录制的时候还是回放的时候移除呢？是通过什么配置移除的呢？另外，想问下，有设置可以使播放器的高度可以被iframe的高度自动撑开咩？

**Comment by Yuyz0112** [comment]
@wy6921 回放的是会可以移除，根据 event 的 type 和 data.source 可以判断是不是 resize 事件。

播放器的高度被自动撑开可以靠 CSS 实现。

**Comment by wy6921** [comment]
感谢您提供的思路，问题已经解决啦，谢谢~
