### ISSUE TITLE
Interact broken in player with new mouse cursor

### ISSUE THREAD

**Issue by lele0108** [rrweb-io/rrweb#336]
In release 0.92, the new mouse cursor uses a canvas element. This canvas element sits on top of the iframe for replay and prevents me from interacting with any elements in the iframe.

This can be fixed by adding the property "pointer-events: none" to .replayer-mouse-tail.

Compatability: https://caniuse.com/?search=pointer-events

**Comment by Yuyz0112** [comment]
great idea, thanks!

**Comment by Icesofty** [comment]
Unfortunately, 
This doesn't fix the issue for me with the last version of Brave. I simply deleted the canvas on top of the iframe.
