### ISSUE TITLE
Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by iamgaohui** [rrweb-io/rrweb#337]
回放时有机率出现：Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
导致回放卡住不能往下进行
[events.json.zip](https://github.com/rrweb-io/rrweb/files/5198999/events.json.zip)

**Comment by Yuyz0112** [comment]
@iamgaohui 能提供一个最小化的可复现项目用于 debug 吗？

**Comment by Yuyz0112** [comment]
如果有进一步的信息可以 reopen 这个 issue。
