### ISSUE TITLE
回放过程中input获得焦点的时候页面会放大

### ISSUE THREAD

**Issue by hedamao** [rrweb-io/rrweb#339]
我们碰到的问题类似于[#335](https://github.com/rrweb-io/rrweb/issues/335)，不过因为我们的数据量非常大，手动去剔除resize事件可能会比较麻烦，不知道贵团队可否添加一个开发配置来决定页面是否放大缩小呢，十分感谢！

**Comment by Yuyz0112** [comment]
跟数据量应该没什么关系，在最终回放的时候过滤 resize event 就可以

```js
const replayer = new rrweb.Replayer(events.filter(event => {
  return event.type !== EventType.IncrementalSnapshot || event.data.source !== IncrementalSource.ViewportResize
}));
```

**Comment by hedamao** [comment]
EventType，IncrementalSource这两个是从哪里来的啊😂

**Comment by hedamao** [comment]
另外event.type的值是多少的时候表示是resize事件呢
