### ISSUE TITLE
关于视频回放

### ISSUE THREAD

**Issue by wangsitong170301** [rrweb-io/rrweb#340]
您好，我的页面上有iframe，引用录屏后，在回放时不回录制页面的iframe标签里的内容，请问我该如何操作？

**Comment by wangsitong170301** [comment]
举个例子，a.html中使用iframe标签嵌入了b.html，录屏播放回显时a.html标签中的内容是可以看见的，但是b.html标签的内容录屏是并不会回显

**Comment by Yuyz0112** [comment]
社区版目前不支持 iframe

另外你的 iframe 是跨域还是非跨域的呢？

**Comment by wangsitong170301** [comment]
感谢您的解答，我这边iframe是不跨域的 本地a.html访问b.html



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "yz-yu"<notifications@github.com&gt;; 
发送时间: 2020年9月11日(星期五) 下午2:35
收件人: "rrweb-io/rrweb"<rrweb@noreply.github.com&gt;; 
抄送: "桐"<1198410843@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [rrweb-io/rrweb] 关于视频回放 (#340)





 
社区版目前不支持 iframe
 
另外你的 iframe 是跨域还是非跨域的呢？

**Comment by wangsitong170301** [comment]
您好，非跨域的可以解决录制问题吗，需要修改iframe的属性吗?

**Comment by leossw** [comment]
> 您好，非跨域的可以解决录制问题吗，需要修改iframe的属性吗?

我和你场景一样，请问你解决了么，我看nest-record分支可以录制非跨域iframe，但是这个分支落后master一年多了，有些bug而且不能录canvas

**Comment by Yuyz0112** [comment]
同源 iframe 已在 master 分支包含。

**Comment by zh198580** [comment]
您好 请问跨域iframe有解决方案吗
