### ISSUE TITLE
视频回放中途突然暂停

### ISSUE THREAD

**Issue by cosee128** [rrweb-io/rrweb#343]
视频回放突然暂停，报错“allow-script”permission is not set。拖动进度条又能正常播放，请问可能会是什么原因呢？

**Comment by Yuyz0112** [comment]
可以提供对应的 events 用于 debug 吗？

`allow-script` 的报错应该不影响播放，是正常现象。

**Comment by cosee128** [comment]
http://insureapi.zhongmin.cn/rrplayer0911.html?tk=TS1599644170000&pt=-1
打印了events，麻烦您看看是什么原因呢？有时候会突然暂停，有时候又不会

**Comment by Yuyz0112** [comment]
应该是旧版本的 bug，我测试了一下，在最新版本（rrweb 0.9.3, rrweb-player 0.5.6）里已经没有这个问题

**Comment by cosee128** [comment]
您好，升级了版本之后，又有几笔数据中途暂停，有些暂停的没有报错，只是warning：‘request Animation Frame’ handler took 69ms.有些报错uncaught referenceError：i.setAttribute is not a function。我没什么头绪该从何排查呢？

**Comment by Yuyz0112** [comment]
还是麻烦提供 events 我来 debug 一下，谢谢

**Comment by cosee128** [comment]
[jsdata.txt](https://github.com/rrweb-io/rrweb/files/5231461/jsdata.txt)

**Comment by cosee128** [comment]
由于数据过大，只截取了开始到暂停部分的events。6s的时候暂停的，我取到了8s的内容。
