### ISSUE TITLE
Uncaught TypeError: Cannot read property 'value' of null at MutationObserver.processMutations

### ISSUE THREAD

**Issue by yyf365** [rrweb-io/rrweb#344]
你好，我们在使用0.8.2版本时候是没问题的，今天调整到0.9.2和0.9.3版本后报错：

Uncaught TypeError: Cannot read property 'value' of null
    at MutationObserver.processMutations

调试情况如图，node == null

![WechatIMG113](https://user-images.githubusercontent.com/12697067/93078438-103e6d80-f6bd-11ea-95d8-07194770bc6f.jpeg)
![WechatIMG112](https://user-images.githubusercontent.com/12697067/93078440-10d70400-f6bd-11ea-9651-4a277b21f873.jpeg)

麻烦帮助看一下，谢谢

**Comment by Yuyz0112** [comment]
能够提供被录制的页面或者可以复现这个问题的页面用于 debug 吗？

**Comment by yjhnp** [comment]
我也遇到了相同问题。是内网页面所以无法提供复现。

**Comment by yyf365** [comment]
> 能够提供被录制的页面或者可以复现这个问题的页面用于 debug 吗？

确实内网页面拿不出来。  请问是否与0.8.2以后版本不支持我们在js中给dom添加
.rr-block  .rr-ignore类名呢？  我们JS中动态对某些dom添加此类，如图：

![WechatIMG12](https://user-images.githubusercontent.com/12697067/93206924-c4f39000-f78c-11ea-909d-8c17eb57ee21.png)

**Comment by Yuyz0112** [comment]
在 https://github.com/rrweb-io/rrweb/issues/347#issuecomment-693288974 统一处理，可以帮忙测试临时版本是否解决了问题。
