### ISSUE TITLE
新版本的录屏会造成页面卡顿，并且录屏数据大小多达5M+

### ISSUE THREAD

**Issue by frcy9** [rrweb-io/rrweb#347]
新版本的录屏会造成页面卡顿，并且录屏数据大小多达5M+，比原先的录屏数据大很多。查看控制台，是mutation.ts报错了。报错信息截图如下：

![chenyun](https://questionapi.ymhome.vip/storage/2020_09_16/4dc4560f1a89bc3c239225734f8af5bf7939.png)
![chenyun](https://questionapi.ymhome.vip/storage/2020_09_16/22ca82161dea90c59bfc48ba2390316f7249.png)

**Comment by Yuyz0112** [comment]
有没有可以复现的页面用于 debug？

**Comment by frcy9** [comment]
> 有没有可以复现的页面用于 debug？

金融行业，页面数据比较隐私，开发没有权限向外提供。请问能通过最近修改的代码，审查出哪里可能造成bug吗。使用老版本没有这个问题，老版本大概是1个多月前的版本。

**Comment by frcy9** [comment]
> 有没有可以复现的页面用于 debug？

我这边可以配合你测试，然后反馈。

**Comment by Yuyz0112** [comment]
嗯，我做一下 debug 版本

**Comment by Yuyz0112** [comment]
@frcy9 能否帮忙确认一下以下几个版本哪些存在这个问题，哪些不存在？

```
v0.9.1
v.0.9.0
v0.8.5
v0.8.0
v0.7.33
```

**Comment by frcy9** [comment]
> @frcy9 能否帮忙确认一下以下几个版本哪些存在这个问题，哪些不存在？
> 
> ```
> v0.9.1
> v0.9.0
> v0.8.5
> v0.8.0
> v0.7.33
> ```

**Comment by frcy9** [comment]
> @frcy9 能否帮忙确认一下以下几个版本哪些存在这个问题，哪些不存在？
> 
> ```
> v0.9.1
> v0.9.0
> v0.8.5
> v0.8.0
> v0.7.33
> ```

已测试，测试结果如下：

v0.9.1：存在问题
v0.9.0：不存在问题
v0.8.5：不存在问题
v0.8.0：不存在问题
v0.7.33：不存在问题

综上，是 `v0.9.1` 版本修改的代码导致的这个问题，

**Comment by frcy9** [comment]
页面bug复现的video已发送至 `aryu0112@gmail.com` 邮箱。

**Comment by Yuyz0112** [comment]
@frcy9 非常感谢，我尽快处理

**Comment by 18865522675** [comment]
老版本的代码有嘛，新版本确实有很多问题啊

**Comment by frcy9** [comment]
> 老版本的代码有嘛，新版本确实有很多问题啊

`https://cdn.jsdelivr.net/npm/rrweb@0.9.1/dist/rrweb.min.js`
修改版本号即可取对应版本，文档有写。

**Comment by Yuyz0112** [comment]
[rrweb.min.zip](https://github.com/rrweb-io/rrweb/files/5231213/rrweb.min.zip)
@frcy9 能否帮忙测试一下这个临时版本是否修复了问题

**Comment by frcy9** [comment]
可以的，测试完我回复你。 @Yuyz0112

**Comment by frcy9** [comment]
临时版本经测试已经无问题。
但是之前这边提过的select值经程序设置回放无变化的bug依旧存在（前端70经程序设置已经被置为60，但是回放一直保留在70）。

**Comment by Yuyz0112** [comment]
@frcy9 感谢配合。数据量也恢复到正常情况了吗？

vue select 这个我找到了 root cause 做了修复，如果没有修复你的场景我们再尝试复现一下。用你上次邮件发我的 bug.vue 能够复现吗？

**Comment by frcy9** [comment]
嗯嗯，数据量已经恢复到正常情况啦，棒！

我测试了 `真实场景` 和上次邮件发的 `bug.vue`，发现 `bug.vue` 的select值变化已经能够成功回放了。但是真实场景回放还是_没有变化_，我这边在找两者场景的不同之处。 @Yuyz0112

**Comment by sunzhixun001** [comment]
> @frcy9 感谢配合。数据量也恢复到正常情况了吗？
> 
> vue select 这个我找到了 root cause 做了修复，如果没有修复你的场景我们再尝试复现一下。用你上次邮件发我的 bug.vue 能够复现吗？

修复后的代码可以上传一下吗, 我这里也一直在等待这问题解决,非常感谢 @Yuyz0112

**Comment by Yuyz0112** [comment]
@frcy9 可以确认一下两个场景的 Vue 版本分别是什么，root cause 是 Vue 设置 select value 的方式。

**Comment by Yuyz0112** [comment]
@sunzhixun001 0.9.4 版本已包含这个修复
