### ISSUE TITLE
录制过程无限报Uncaught TypeError: Cannot read property 'value' of null at MutationObserver.processMutations

### ISSUE THREAD

**Issue by liuqin0430** [rrweb-io/rrweb#348]
录制过程中无限报这个错误

**Comment by Yuyz0112** [comment]
在 https://github.com/rrweb-io/rrweb/issues/347#issuecomment-693288974 中一起处理，可以帮忙测试一下临时版本是否解决了问题

**Comment by liuqin0430** [comment]
这个问题已经处理了吗？使用0.9.4版本就可以吗？

**Comment by Yuyz0112** [comment]
@liuqin0430 是的，有问题可以再反馈

**Comment by liuqin0430** [comment]
你好，真实项目测试有select的页面，还是会报这个问题
