### ISSUE TITLE
新版canvas回放画图会有很多多余的线

### ISSUE THREAD

**Issue by liuqin0430** [rrweb-io/rrweb#349]
新版canvas回放画图会有很多多余的线，在左上角出现
![image](https://user-images.githubusercontent.com/12492686/93325999-c4213380-f84a-11ea-9e81-8a867cd4d996.png)

**Comment by Yuyz0112** [comment]
之前有使用过哪一个版本是没有这个问题的吗？

**Comment by liuqin0430** [comment]
目前是新版本加了可以录制canvas，之前不支持，是灰色的能看到操作，没有轨迹

**Comment by Yuyz0112** [comment]
有可以复现的 events 吗？

**Comment by liuqin0430** [comment]
你好，附件是events数据，请查收～


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rrweb-io/rrweb"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月17日(星期四) 凌晨2:02
收件人:&nbsp;"rrweb-io/rrweb"<rrweb@noreply.github.com&gt;;
抄送:&nbsp;"奋斗"<475990997@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [rrweb-io/rrweb] 新版canvas回放画图会有很多多余的线 (#349)





 
有可以复现的 events 吗？

**Comment by liuqin0430** [comment]
你好，这个问题有新的进展吗？需要配合测试吗？

**Comment by Yuyz0112** [comment]
@liuqin0430 你是把 events 回复给了 github 的 notification email 了吗？可以通过回复的形式发在 issue 里。

**Comment by zhaoxm2016** [comment]
@liuqin0430 你用的是哪个版本的rrweb呢

**Comment by liuqin0430** [comment]
最新的，0.9.4




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rrweb-io/rrweb"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月21日(星期一) 下午3:51
收件人:&nbsp;"rrweb-io/rrweb"<rrweb@noreply.github.com&gt;;
抄送:&nbsp;"奋斗"<475990997@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [rrweb-io/rrweb] 新版canvas回放画图会有很多多余的线 (#349)





 
@liuqin0430 你用的是哪个版本的rrweb呢

**Comment by zhaoxm2016** [comment]
我的是用react-pdf展示的pdf,但是一直有问题。。

**Comment by Yuyz0112** [comment]
如果有可以复现问题的数据请 reopen 这个 issue。
