### ISSUE TITLE
i.setAttribute is not a function

### ISSUE THREAD

**Issue by cosee128** [rrweb-io/rrweb#350]
视频播着播着暂停，有时候会报错i.setAttribute is not a function。有时候暂停不会报错。events如下。
[jsdata.txt](https://github.com/rrweb-io/rrweb/files/5231835/jsdata.txt)

**Comment by Yuyz0112** [comment]
有使用 checkout 的功能对吧

**Comment by cosee128** [comment]
对，那要怎么解决呢？

**Comment by Yuyz0112** [comment]
最新版本已经处理

**Comment by eoghanmurray** [comment]
Hmmm, the try/catch in  9049f2a is very general, i.e. will catch any errors with attribute setting or removing, and possibly incorrectly report that it's related to 'checkout'.
Was there something more specific about this error case that we can look for?
