### ISSUE TITLE
当dom改变时 Cannot read property 'value' of null     at MutationObserver.K.processMutations

### ISSUE THREAD

**Issue by sunzhengxin92** [rrweb-io/rrweb#352]
table获取后端数据的时候，先为空，后面获取到再渲染到dom上。然后就报错 Cannot read property 'value' of null     at MutationObserver.K.processMutations。

下面是rrweb中引起报错代码部分：
 for (let index = addList.length - 1; index >= 0; index--) {
          const _node = addList.get(index)!;
          const parentId = mirror.getId(
            **(_node.value**.parentNode as Node) as INode,
          );
          const nextId = getNextId(_node.value);
          if (parentId !== -1 && nextId !== -1) {
            node = _node;
            break;
          }
        }

**Comment by Yuyz0112** [comment]
0.9.4 版本应该修复了这个问题

**Comment by liuqin0430** [comment]
个别录制还是会有这个问题，并且报错后页面会回溯重复字段

**Comment by Yuyz0112** [comment]
@liuqin0430 如果在 0.9.7 版本还遇到这个问题，可以提供一个可以复现的页面用于 debug
