### ISSUE TITLE
使用vue-datepicker切换年份时下面的日期显示不出

### ISSUE THREAD

**Issue by gxsnyyx** [rrweb-io/rrweb#353]
![image](https://user-images.githubusercontent.com/37402863/93436433-60a40e00-f8fd-11ea-820e-3a5ff6810492.png)
![image](https://user-images.githubusercontent.com/37402863/93436490-73b6de00-f8fd-11ea-9086-d0f5d0cc1fce.png)
![Uploading image.png…]()
录制过程中控制台有异常，必现的情况，请问是哪里出了问题

**Comment by gxsnyyx** [comment]
![image](https://user-images.githubusercontent.com/37402863/93436610-99dc7e00-f8fd-11ea-99dd-70dc9e8808e3.png)
这里是播放时候的情况，控制台无报错

**Comment by Yuyz0112** [comment]
是这个库吗？ https://github.com/hilongjw/vue-datepicker#readme

我用它提供的 Demo 页面试了一下，没有遇到什么问题

![Peek 2020-09-20 12-56](https://user-images.githubusercontent.com/13651389/93694633-ca602a00-fb40-11ea-8ad4-2b710695e3f1.gif)

**Comment by gxsnyyx** [comment]
是这个库，但是我是在点击年份切换之后出现的上图警告

**Comment by Yuyz0112** [comment]
@gxsnyyx 我也用上面的 Demo 链接测试了一下切换年份，没有遇到问题。可以提供一个能够复现的代码示例或者地址用于测试。

**Comment by gxsnyyx** [comment]
我用新版本录制之后，确实没有再出现此问题了 0.0
