### ISSUE TITLE
播放器存在卡死导致浏览器无响应的情况

### ISSUE THREAD

**Issue by jokeewu** [rrweb-io/rrweb#356]

**Comment by Yuyz0112** [comment]
有可以复现这个问题的 events 可以提供吗？

**Comment by jokeewu** [comment]
> 有可以复现这个问题的 events 可以提供吗？

怎么给到你？邮箱可以吗？

**Comment by Yuyz0112** [comment]
可以的，或者上传到这个 issue

**Comment by jokeewu** [comment]
[events.zip](https://github.com/rrweb-io/rrweb/files/5251210/events.zip)

**Comment by jokeewu** [comment]
> 可以的，或者上传到这个 issue

[events.zip](https://github.com/rrweb-io/rrweb/files/5251215/events.zip)

**Comment by jokeewu** [comment]
https://github.com/rrweb-io/rrweb/blob/65d0d4e54a2c3f1a48fb77a477afea1b72f62e5e/src/replay/index.ts#L870
https://github.com/rrweb-io/rrweb/blob/65d0d4e54a2c3f1a48fb77a477afea1b72f62e5e/src/replay/index.ts#L899
https://github.com/rrweb-io/rrweb/blob/65d0d4e54a2c3f1a48fb77a477afea1b72f62e5e/src/replay/index.ts#L944

push, 回导致while循环不结束

**Comment by Yuyz0112** [comment]
@jokeewu 数据是基于什么版本的 rrweb 录制的？

**Comment by jokeewu** [comment]
> @jokeewu 数据是基于什么版本的 rrweb 录制的？

0.9.0

测试了最新版的还是会卡死

**Comment by Yuyz0112** [comment]
测试了用最新版回放，还是用最新版录制 + 回放？

可以测试一下最新版录制 + 回放，如果也有问题，再提供一下最新版录制的数据或者一个公网可访问、能够复现这个问题的 URL。

**Comment by jokeewu** [comment]
> 测试了用最新版回放，还是用最新版录制 + 回放？
> 
> 可以测试一下最新版录制 + 回放，如果也有问题，再提供一下最新版录制的数据或者一个公网可访问、能够复现这个问题的 URL。

测试的最新版回放

**Comment by Yuyz0112** [comment]
做了一些修复，能够继续播放。不过最好还是帮忙确认一下最新版的录制数据是否有相同的问题。

**Comment by jokeewu** [comment]
> 做了一些修复，能够继续播放。不过最好还是帮忙确认一下最新版的录制数据是否有相同的问题。

好的

**Comment by Sunchunqing** [comment]
请问是什么原因导致的呢？ @Yuyz0112
