### ISSUE TITLE
默认inlineStylesheet为true时，字体图标存在兼容问题

### ISSUE THREAD

**Issue by jokeewu** [rrweb-io/rrweb#359]
测试在电脑chrome下拿到字体图标样式 content: "图标"，在ios下 content: 图标，区别在于图标文字是否被引号("")包裹，未被引号包裹图标无法正常显示。

**Comment by Yuyz0112** [comment]
有可以复现的页面提供一下吗？也欢迎直接 PR。

**Comment by Yuyz0112** [comment]
如果有可以复现的方式请 reopen
