### ISSUE TITLE
canvas打开PDF问题

### ISSUE THREAD

**Issue by zhaoxm2016** [rrweb-io/rrweb#361]
rrweb版本：0.9.5
录制已配置recordCanvas: true,collectFonts: true
PDF打开的是使用react-pdf，
打开之后PDF打开非常慢，且没有事件上送
![image](https://user-images.githubusercontent.com/51771541/93741554-3e70ff80-fc1f-11ea-8b7a-b7753a71b4be.png)
PDF打开之后一直刷上面的内容

**Comment by zhaoxm2016** [comment]
@Yuyz0112

**Comment by zhaoxm2016** [comment]
@Yuyz0112 可否帮忙看下

**Comment by Yuyz0112** [comment]
@zhaoxm2016 提供一下 events 或者可以复现的 URL

**Comment by zhaoxm2016** [comment]
@Yuyz0112 有邮箱吗？我把我的工程简化一下发给你

**Comment by Yuyz0112** [comment]
aryu0112@gmail.com

**Comment by zhaoxm2016** [comment]
暂时先把PDF图片化了

**Comment by Yuyz0112** [comment]
比较推荐 pdf 图片化的思路。因为 canvas 录制 pdfjs 的存储开销相对很大

**Comment by zjsen668** [comment]
@Yuyz0112 我也录制了一个，events发您邮箱了。
