### ISSUE TITLE
是否可以创建一个官方讨论群

### ISSUE THREAD

**Issue by cgaof** [rrweb-io/rrweb#362]
是否可以创建一个官方讨论群，方便大家沟通和解决使用中的问题，大家遇到过的问题，使用rrweb解决了什么问题。产生了什么价值，未来rrweb路线图等等 。

**Comment by frcy9** [comment]
关注

**Comment by Yuyz0112** [comment]
rrweb 社区计划预览版：http://www.myriptide.com/rrweb-community-cn/

**Comment by Yuyz0112** [comment]
目前已经基于上述社区计划展开了一些合作。

后续如果有微信群等媒介会更新在 README 里。
