### ISSUE TITLE
页面中有video 播放进度的改变在回放中无法同步

### ISSUE THREAD

**Issue by WananPr1st** [rrweb-io/rrweb#364]
原始页面上对视频进度条进行拖动，在录制的回放中对应时间点无法同步到相同的观看进度

**Comment by WananPr1st** [comment]
@Yuyz0112

**Comment by weiweiok** [comment]
进度条的变化，已经脱离了 dom 范畴吧

**Comment by Yuyz0112** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/progress_event

也许这个能检测到进度变化

**Comment by WananPr1st** [comment]
> https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/progress_event
> 
> 也许这个能检测到进度变化

对的，需要单独对video addEventListener 监听他的进度变化，rrweb支持发自定义event 来做一些自定义事件的记录么

**Comment by Yuyz0112** [comment]
@WananPr1st 有 addCustomEvent 的方法

https://github.com/rrweb-io/rrweb/blob/master/src/record/index.ts#L313

**Comment by Yuyz0112** [comment]
目前建议通过 custom event 进行实现，未来可能会对 media element 做更好的内置支持
