### ISSUE TITLE
Access to `interactionData` type

### ISSUE THREAD

**Issue by jay-khatri** [rrweb-io/rrweb#366]
I'm using `replayer.on("event-cast", (e: any) => ...)` to subscribe to events from the player, and I'm having some trouble with access to types. 

Right now, I can use `unpack(e)` to get access to the `eventWithTime` type, but how do I access the underlying `interaction` data? For example, this simple prints `object`:

```
        const event = unpack(e);
        console.log(typeof event.data); // The type incrementalData isn't exported :(

```

Maybe this is more of a typescript question, but if not, can these types be exported in the package?

**Comment by jay-khatri** [comment]
@Yuyz0112 I've exported the types that were useful to me here: https://github.com/jay-khatri/rrweb/commit/ebe9f6697688e31fa967ebe153edad3bb7552629

I can open a PR if that's interesting.

**Comment by Yuyz0112** [comment]
I see, we only export Typescript Enums in the `index.ts` file because they existed in runtime. Other Typescript types will be omitted in compile-time, so we do not export them, but I think you can use them like `import { incrementalData } from 'rrweb/typings/types'`

Does this solve your problem?

**Comment by jay-khatri** [comment]
It does! Thanks @Yuyz0112.
