### ISSUE TITLE
Blocked script execution in 错误

### ISSUE THREAD

**Issue by qq540491950** [rrweb-io/rrweb#367]
录制页面的时候有cesium地图,播放的时候没有地图,怎么解决?

**Comment by Yuyz0112** [comment]
地图是基于 iframe 或者 canvas 的实现吗？

iframe 目前还没有完成的方案，canvas 可以参考 https://github.com/rrweb-io/rrweb/blob/master/docs/recipes/canvas.zh_CN.md
