### ISSUE TITLE
页面不刷新情况下，先停止录制后再重新开始录制，滚动条能否记忆

### ISSUE THREAD

**Issue by weiweiok** [rrweb-io/rrweb#368]
您好，我在ie11里使用时，如果页面没有刷新的情况下，先停止一次，再重新开始录制，例如：

//---------------------------------
// 先开始一个录制
rrwebstop = rrweb.record({ …… })
// 此时鼠标操作滚动到页面下方
// 然后停止录制
rrwebstop();
// 然后再重新开始
rrwebstop = rrweb.record({ …… })
// 这个时候，去查看录制的视频，页面滚动条跑到了顶部
//-----------------------------------

我想能不能在 stop 之前，先记下来滚动条位置
等重新 record 产生 event 数据后，把之前的滚动条位置，替换一下 event 数据里的默认位置0
由于 event 产生的结构比较复杂，我不知道应该替换哪里
我尝试找到了一个  { type : 0 , id : 1 } 的节点，然后添加了一个 { type : 0 , id : 1, y : 之前记录的值 } 
但似乎不管用，求指点

**Comment by Yuyz0112** [comment]
新的全量快照应该包含了 offset 信息，可以提供对应的 events 我确认一下

**Comment by Yuyz0112** [comment]
如果还有问题可以 reopen 这个 issue
