### ISSUE TITLE
在Android移动端QQ浏览器上录制页面回放看不到页面动态

### ISSUE THREAD

**Issue by yyf365** [rrweb-io/rrweb#369]
相同录制页面在其他终端（ios任意浏览器、Android chrome、PC浏览器）中录制无问题。

仅在Android QQ浏览器上相同页面录制后回放出现页面卡住不动，仅回放鼠标手势等效果

目前该问题在Android QQ浏览器新老版本中重现率大概在80%以上，烦请帮助，谢谢

**Comment by Yuyz0112** [comment]
可以看一下该浏览器是否支持 MutationObserver 的 API，如果不支持的话就无法使用。

**Comment by zhaoxm2016** [comment]
目前线上跑的情况，确实发现安卓QQ浏览器有采集不到的情况，但是也有成功的（同一台手机），目前分析(难度不小)，另外MutationObserver如何探测是否兼容呢
@Yuyz0112 请教一下
