### ISSUE TITLE
回放时样式丢失

### ISSUE THREAD

**Issue by crystalpp** [rrweb-io/rrweb#370]
采集的文件回放时静态css资源有时候变成link方式去引入了第三方资源有时候样式是直接通过style标签内嵌在项目中的，想请教下出现这样的原因是为啥呢

**Comment by crystalpp** [comment]
录制时的原理是否为请求到了静态资源后就会下载下来存在events中呢 如果第一次请求静态css资源为301 后续请求为200 这种情况是否会将样式存在events中

**Comment by Yuyz0112** [comment]
录制的原理是通过 JS 获取当前页面的样式表，如果是跨域的样式表，就无法 inline

**Comment by crystalpp** [comment]
对于这种情况是否有什么比较好的解决方式呢

**Comment by crystalpp** [comment]
后续是否可以考虑支持这种跨域的情况呢 因为我们很多时候静态资源要走CDN 导致出现了跨域现象

**Comment by Yuyz0112** [comment]
可以在后端遍历收集的 events，把里面的远程 CSS 链接下载，然后保存为一个回放时同源的地址，替换到 events 内
