### ISSUE TITLE
Node can belong to multiple DoubleLinkedLists

### ISSUE THREAD

**Issue by eoghanmurray** [rrweb-io/rrweb#371]
I've found a bug with the new code added in 5d83ee39fd211ec9fc692e4e6ad6ac386da1506f

Basically there are circumstances where a node can already be in a `DoubleLinkedList`, so e.g. in `addNode`, the `if (n.previousSibling && isNodeInLinkedList(n.previousSibling))` clause can resolve as true, even when the current `DoubleLinkedList` is empty ... so effectively when we add the first node, the new linked list gets joined to some previous linked list, and the new node has an incorrect length. 
This may seem innocuous as the head of the new list is correct, but I believe it's the source of further knock on bugs, where another linked list has null entries for `.next` even though the length is reported as being longer.

I believe the problem stems from the usage of the `__ln` property on the DOM node, i.e. it would work fine if the node was only ever added to one linked list.

I started on a fix, but it started to get very complicated so maybe @Yuyz0112 this approach needs to rethought?

**Comment by Yuyz0112** [comment]
I've do some update on this: https://github.com/rrweb-io/rrweb/commit/a68684d881047a6168b47029ca86b37d1712691a

But looks like there are still some bugs?

**Comment by eoghanmurray** [comment]
Ah I don't have this update ... let me check

**Comment by eoghanmurray** [comment]
Update fixed it
