### ISSUE TITLE
回放报错，概率出现, Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by hzlgit** [rrweb-io/rrweb#376]
[events.json](https://hbxh5.haobaoxian.com.cn/events.json)

**Comment by liuqin0430** [comment]
有同样的现象，并且回放会卡住

**Comment by gangli90** [comment]
遇到相似问题，页面假死状态。chrome console日志提示很多条警告信息。
信息内容显示NODE id未找到：“index.js:30 [replayer] Node with id '533' not found in {texts: Array(142), attributes: Array(161), source: 0, removes: Array(0), adds: Array(1453)}”

**Comment by codetaintian** [comment]
@Yuyz0112

**Comment by Yuyz0112** [comment]
@hzlgit 
你的 events 里有 3 段 session 的拼接，报错出现在第 3 段 session。

我按照 meta event 里的信息，在第 3 段 session 对应的 URL 里做对应的操作，收集到的数据没有相应的问题。

你在单页面内做对应的操作能复现这个问题吗？不确定是不是拼接的代码有问题。

**Comment by Yuyz0112** [comment]
@liuqin0430 @codetaintian 相同的报错不一定是相同的原因，请提供 events 用于 debug

**Comment by codetaintian** [comment]
[videoData.json.zip](https://github.com/rrweb-io/rrweb/files/5295782/videoData.json.zip)
@Yuyz0112 这个是当前收集的events，帮忙看看什么原因导致的报错，谢谢了

**Comment by Yuyz0112** [comment]
@codetaintian 

在你的 events 里有多段 session 的拼接，其中出问题的 session 前有多段这个 URL 的 session
```
https://sitgroupgw.e-nci.com/product/productDetail?productId=1bc26bc5b54345a48c7affa34efe8aaf-110000-862100&captchaId=phone-a3d7a458-c42d-4ac6-988e-b00a60ff2df9&captcha=6951
```

可以先确认一下单独对这个页面是否出现问题，是否拼接代码有问题，以及有没有出现一个页面同时有多个录制函数触发的情况。

**Comment by hzlgit** [comment]
@Yuyz0112 单页面的没有问题，就是多个页面合并产生的问题，而且也不是100%出错的。目前要急需解决的是，能不能处理播放的错误，或者怎么捕捉播放异常？

**Comment by Yuyz0112** [comment]
@hzlgit 不应该捕获异常继续播放，因为异常都是不符合预期的的数据，数据本身是 op-log 的链式结构，出现异常继续播放可能引发更多问题。

单个页面没有问题，多个页面合并出现问题，可能是合并的实现有问题。一定要避免有多个页面的数据**穿插**出现。
