### ISSUE TITLE
Uncaught TypeError: Cannot read property 'value' of null     at MutationObserver.J.processMutations

### ISSUE THREAD

**Issue by liuqin0430** [rrweb-io/rrweb#378]
0.9.7版本仍出现该问题，并且导致录制数据重复

**Comment by Yuyz0112** [comment]
是用 0.9.7 录制 + 回放的吗？
如果是的话麻烦提供一个可以复现的应用代码或者公网 URL

**Comment by liuqin0430** [comment]
用 0.9.7 录制 + 0.6.1 rrwebplayer回放




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rrweb-io/rrweb"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月26日(星期六) 中午12:31
收件人:&nbsp;"rrweb-io/rrweb"<rrweb@noreply.github.com&gt;;
抄送:&nbsp;"奋斗"<475990997@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [rrweb-io/rrweb] Uncaught TypeError: Cannot read property 'value' of null     at MutationObserver.J.processMutations (#378)





 
是用 0.9.7 录制 + 回放的吗？
 如果是的话麻烦提供一个可以复现的应用代码或者公网 URL

**Comment by liuqin0430** [comment]
你好，


&nbsp; &nbsp; 用的0.9.7的录制 + 0.6.1的rrwebplayer回放
&nbsp; &nbsp; 录制中用select报这个错误
&nbsp; &nbsp; 附件是events数据
&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rrweb-io/rrweb"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月26日(星期六) 中午12:31
收件人:&nbsp;"rrweb-io/rrweb"<rrweb@noreply.github.com&gt;;
抄送:&nbsp;"奋斗"<475990997@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [rrweb-io/rrweb] Uncaught TypeError: Cannot read property 'value' of null     at MutationObserver.J.processMutations (#378)





 
是用 0.9.7 录制 + 回放的吗？
 如果是的话麻烦提供一个可以复现的应用代码或者公网 URL

**Comment by Yuyz0112** [comment]
@liuqin0430 直接回复 github 的邮件我们是收不到附件的，需要在 issue 里回复

**Comment by liuqin0430** [comment]
好的，辛苦啦～
[events (1).json.zip](https://github.com/rrweb-io/rrweb/files/5287810/events.1.json.zip)

**Comment by Yuyz0112** [comment]
![Peek 2020-09-27 14-54](https://user-images.githubusercontent.com/13651389/94358136-5e963800-00d1-11eb-97db-b45d82cd5ccc.gif)
我用 0.6.1 的 rrweb-player 好像没有遇到

**Comment by liuqin0430** [comment]
好的，视频回放涉及到业务，麻烦数据删除，0.6.1的安装版本删除removeChild更新没有更新到版本中
