### ISSUE TITLE
关于提示sandboxed and the 'allow-scripts' permission is not set

### ISSUE THREAD

**Issue by pipti** [rrweb-io/rrweb#379]
回放时出现下面的错误
![截屏2020-09-27 下午10 57 06](https://user-images.githubusercontent.com/10271122/94368152-58c24600-0115-11eb-8d4d-9cd815327472.png)

我是用本地webstore 启动的服务访问的，不知道是什么原因

**Comment by Yuyz0112** [comment]
sandbox 是保护性的沙盒策略，被触发是正常现象。

有导致回放异常吗？

**Comment by pipti** [comment]
是基于vue 的，鼠标指针无法回放

**Comment by Yuyz0112** [comment]
提供一下 events 看看吧

**Comment by Yuyz0112** [comment]
如果有更相信的信息请 reopen issue。

**Comment by cddsgtc** [comment]
> sandbox 是保护性的沙盒策略，被触发是正常现象。
> 
> 有导致回放异常吗？

有哪里设置设置播放器的iframe的sandbox为`allow-scripts`吗？

**Comment by Mark-Fenng** [comment]
@cddsgtc 在rrweb replayer方法的options中设置UNSAFE_replayCanvas:true， 
需要提醒的是"allow-scripts"之后会使沙盒的保护作用失效，如果发生任何安全性问题后果自负

**Comment by LeeRayno** [comment]
@Yuyz0112 @Mark-Fenng 我现在在 a.baidu.com  嵌入 b.baidu.com 的 iframe. 然后在 c.baidu.com 里面播放。并且设置了UNSAFE_replayCanvas: true, 在播放的时候有 iframe 的页面，但是鼠标指针无法回放，iframe 页面的所有事件都没有，比如鼠标滑动，点击等事件都没有。
然后分别在 a、b、c 三个页面设置 document.domain = 'baidu.com'. 但是在播放的时候还是会报错 Uncaught DOMException: Failed to set the 'domain' property on 'Document': Assignment is forbidden for sandboxed iframes.  并且播放时会把我设置的 document.domain = 'baidu.com'. 改为 <noscript>SCRIPT_PLACEHOLDER</noscript>。请问有什么办法可以解吗？

**Comment by cddsgtc** [comment]
> @cddsgtc 在rrweb replayer方法的options中设置UNSAFE_replayCanvas:true， 需要提醒的是"allow-scripts"之后会使沙盒的保护作用失效，如果发生任何安全性问题后果自负

这个问题已经解决，忘恢复了。
这个问题当时的情景是，录制没有问题，回放时总是报iframe的错。整个话画面也能播放，就是css文件全部废了的样子。
排查了很久，也根据报错去查看设置和源码，一直难以解决。
有次跟同事吃饭聊起此事，然后他稍许愧疚说，内容的是加密的，解密的代码更新了，没有分给到我所在渠道。导致解析的css字符有问题。
更新完解密代码后，一切就ok了。
有需要的朋友，可以参考下。
