### ISSUE TITLE
Does not record shadow-dom/custom-elements

### ISSUE THREAD

**Issue by orenmizr** [rrweb-io/rrweb#38]
scenario: by using repl record a demo page like https://codepen.io/chriscoyier/full/rwvjVN
expected: the page should show the elements
actual: the page shows up empty

**Comment by Yuyz0112** [comment]
Thanks for the report! Will dig into it ASAP.

**Comment by Yuyz0112** [comment]
After taking a look at shadow-dom, it looks like we need to check the `shadowRoot` property when traversing and rebuild shadow dom.

**Comment by Yuyz0112** [comment]
@orenmizr 

After play with shadow dom a little more, I think this is a similar situation with iframe.
Because the mutation observer and event listeners also need to be attached to the shadowRoot, which is a case of `nested recording`.

So this may take more time to discuss whether to implement the feature.
Currently, if you want to track something happened in a shadow-dom/iframe, the best way is to init a recorder inside it.

**Comment by kerbeh** [comment]
@Yuyz0112 

> Currently, if you want to track something happened in a shadow-dom/iframe, the best way is to init a recorder inside it.

Do you have an example of init-ing a recorder inside shadow-dom?

**Comment by TobiaszCudnik** [comment]
[ShadowMutationObserver](https://github.com/medialize/ally.js/blob/b8fd3cdbb9464df08708f11cba35b7481ad846d4/src/observe/shadow-mutations.js#L31) from ally.js may be relevant here.

Im considering taking a dab into this. Would you expect any problems with node IDs in this case? I suppose listeners disposal will have to be added, as handlers won't be delegated any more. Thx.

**Comment by vipulwairagade** [comment]
@TobiaszCudnik Do you have workaround how to record iframe on my webpage ?

**Comment by flowertree** [comment]
我也在期待是否能支持iframe 的录制

**Comment by wupinlang** [comment]
我也在期待是否能支持iframe 的录制

**Comment by TobiaszCudnik** [comment]
> 我也在期待是否能支持iframe 的录制

Is this spanish?

**Comment by wupinlang** [comment]
> > 我也在期待是否能支持iframe 的录制
> 
> Is this spanish?

it is chinese

**Comment by dcaravana** [comment]
> Currently, if you want to track something happened in a shadow-dom/iframe, the best way is to init a recorder inside it.

Yes @Yuyz0112 that's smart, but in my case the problem are page changes that will generate a new recording for each page vs a single recording produced by a recorder instantiated on the page hosting the iframe.

How do you solve the problem of multiple recording? Is there a way to merge them?

**Comment by startupgurukul** [comment]
The issue went towards Iframe, shadow root seems to be easier to handle with @TobiaszCudnik  suggestion from ally.js

**Comment by Yuyz0112** [comment]
shadow DOM recording is GA now.
