### ISSUE TITLE
加上block样式的元素是动态加载的，导致整个页面一直在刷新

### ISSUE THREAD

**Issue by Jupiter-sxc** [rrweb-io/rrweb#380]

**Comment by Yuyz0112** [comment]
是录制还是回放的时候？请提供一下对应的 events 或者可以复现的代码

**Comment by Jupiter-sxc** [comment]
录制的时候，vue项目，加上了之后就打不开页面了，不知道是不是那个类导致了什么循环？整个浏览器都卡住了。不太好复现，需要整个项目启动才能看到，加在类似 <input-occupation :item="item" :dataCol="dataCol" ></input-occupation>这样的组件上

**Comment by Jupiter-sxc** [comment]
<input-occupation :item="item" :dataColumns="dataColumns" ></input-occupation>

**Comment by Yuyz0112** [comment]
@Jupiter-sxc 好像看不到你回复的具体内容

**Comment by Jupiter-sxc** [comment]
for循环 后面请求得到的数据渲染出来的组件加了那个类会卡住页面，但是页面加载完之后才开始录制就不会卡




发自我的iPhone

------------------ 原始邮件 ------------------
发件人: yz-yu <notifications@github.com&gt;
发送时间: 2020年9月28日 17:52
收件人: rrweb-io/rrweb <rrweb@noreply.github.com&gt;
抄送: Jupiter-sxc <1048625354@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[rrweb-io/rrweb] 加上block样式的元素是动态加载的，导致整个页面一直在刷新 (#380)





 
@Jupiter-sxc 好像看不到你回复的具体内容

**Comment by Jupiter-sxc** [comment]
还有个问题想请教一下 vue项目 若页面新增很多元素 就会阻塞界面的更新 页面就很卡 这个有好的办法处理一下嘛？ 可以屏蔽或者怎么样延迟 先让界面更新再去触发收集记录？🤔


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: yz-yu <notifications@github.com&gt;
发送时间: 2020年9月28日 17:52
收件人: rrweb-io/rrweb <rrweb@noreply.github.com&gt;
抄送: Jupiter-sxc <1048625354@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[rrweb-io/rrweb] 加上block样式的元素是动态加载的，导致整个页面一直在刷新 (#380)





 
@Jupiter-sxc 好像看不到你回复的具体内容

**Comment by Jupiter-sxc** [comment]
input-occupation :item="item" :dataColumns="dataColumns" ></input-occupation

**Comment by Yuyz0112** [comment]
@Jupiter-sxc 最好还是提供一个可以复现的 vue 代码来具体看看问题。

另外使用的是最新版本 0.9.7 录制和回放吗？

**Comment by Jupiter-sxc** [comment]
不是最新版本的 我刚看了一下提交内容 有发现对add 的mutation的优化 我先试试用新版本的 谢谢了


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: yz-yu <notifications@github.com&gt;
发送时间: 2020年9月28日 22:32
收件人: rrweb-io/rrweb <rrweb@noreply.github.com&gt;
抄送: Jupiter-sxc <1048625354@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[rrweb-io/rrweb] 加上block样式的元素是动态加载的，导致整个页面一直在刷新 (#380)





 
@Jupiter-sxc 最好还是提供一个可以复现的 vue 代码来具体看看问题。
 
另外使用的是最新版本 0.9.7 录制和回放吗？

**Comment by Jupiter-sxc** [comment]
vue项目出现录制相同元素两次的是不是也要源码复现才能找到原因呢？偶现


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: yz-yu <notifications@github.com&gt;
发送时间: 2020年9月28日 22:32
收件人: rrweb-io/rrweb <rrweb@noreply.github.com&gt;
抄送: Jupiter-sxc <1048625354@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[rrweb-io/rrweb] 加上block样式的元素是动态加载的，导致整个页面一直在刷新 (#380)





 
@Jupiter-sxc 最好还是提供一个可以复现的 vue 代码来具体看看问题。
 
另外使用的是最新版本 0.9.7 录制和回放吗？

**Comment by Yuyz0112** [comment]
@Jupiter-sxc 恩是的，有可以复现的示例比较容易 debug

**Comment by Jupiter-sxc** [comment]
录制的时候控制isblock函数返回的值是true报错了；不知道是不是找不到父级元素，用来控制不录制vconsole的变化。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rrweb-io/rrweb"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月28日(星期一) 上午10:59
收件人:&nbsp;"rrweb-io/rrweb"<rrweb@noreply.github.com&gt;;
抄送:&nbsp;"農"<1048625354@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [rrweb-io/rrweb] 加上block样式的元素是动态加载的，导致整个页面一直在刷新 (#380)





 
是录制还是回放的时候？请提供一下对应的 events 或者可以复现的代码

**Comment by sunlijun** [comment]
你好，我也碰到类似的问题，在vconsole class 增加了rr-block 导致页面卡死，请问现在有解决方法吗

**Comment by Yuyz0112** [comment]
@sunlijun 有可以复现的页面或者示例代码吗？
