### ISSUE TITLE
配置mouseTail:false 播放时依然有红线问题

### ISSUE THREAD

**Issue by LyAce** [rrweb-io/rrweb#382]
配置mouseTail:false 播放时依然有红线问题
![aaa](https://user-images.githubusercontent.com/26018151/94668011-1d588f00-0342-11eb-96c2-6af95ee145bc.png)

**Comment by Yuyz0112** [comment]
应该是
```
new rrwebPlayer({
  target: ...,
  data: {
    ...video_data,
    mouseTail: false
  }
})
```
