### ISSUE TITLE
pdf回放时报错 Failed to execute 'createPattern'

### ISSUE THREAD

**Issue by zjsen668** [rrweb-io/rrweb#383]
回放pdf时，浏览器报错
![image](https://user-images.githubusercontent.com/16451999/94669616-10d53600-0344-11eb-86f2-c0b42d1b637c.png)

看了下录制文件中对应此部分的内容如下：
`{
        "data": {
            "args": [
                {},
                "repeat"
            ],
            "property": "createPattern",
            "source": 9,
            "id": 889
        },
        "type": 3,
        "timestamp": 1601385687723
    },`

看了下回放的代码，感觉执行createPattern时args似乎只取'repeat'才合理

**Comment by Mark-Fenng** [comment]
If you add events or reproducing steps, feel free to reopen this issue.
