### ISSUE TITLE
回放多次卡顿

### ISSUE THREAD

**Issue by wy6921** [rrweb-io/rrweb#388]
作者，您好，回放时卡顿非常严重，发现采用skip inactive时，所有的events跑完了，也监听到了finish，但是进度条仍然没有跑完。不采用skip inactive时，回放是正常的，想问下这是怎么回事呢？因为我们的events多个快照之间的时间间隔非常长，可能有20多小时，有没有可能是跳跃步长太长导致被飞速略过。因为我们的events不方便上传 ，想问下有没有途径解决这个严重卡顿的问题，谢谢！

**Comment by wy6921** [comment]
因为我们的source有很多为0的元素，我尝试将  private isUserInteraction函数部分内容修改为 event.data.source >= IncrementalSource.Mutation ，上述现象就解决了，但是仍然不确定这种修改的影响范围，想问下，这种修改是否可行

**Comment by Yuyz0112** [comment]
skip inactive 的作用是在回放时快进跳过非活跃时间段。
非活跃时间段的判断方式是在一段时间内，没有用户行为事件，例如鼠标移动、鼠标点击、输入等。

造成你所描述问题的原因应该是在很长的一段时间里一致没有用户行为事件，但是对应视图里的 DOM 一直在发生变化，也就录制了很多 source 为 IncrementalSource.Mutation 的事件。
在回放时，因为没有用户行为，所以一段较长的时间配判断为非活跃时间，进行了快进。也就是在短时间内重放大量 DOM 变化，造成卡顿。

修改 `isUserInteraction` 等于是把被动的 DOM 变化也判断为用户行为，这样结果和关闭 skip inactive 没什么区别了。

可以选择：
1. 关闭 skip inactive。
2. 查看这些自动产生的 Mutation event 来源于哪些 DOM，这些 DOM 是否需要被观测（一般是周期性动画之类导致的）。如果不需要，可以给对应 DOM 元素增加 `rr-block` 的类名，忽略其变化。

**Comment by wy6921** [comment]
现在的情况是，对于event.data.source > IncrementalSource.Mutation 的情况也被快速略过了，并且步长并不是每一次都一样，目前不懂这里。此外，对于events的record我们会尽可能的缩减，降低数据量，但对于播放，希望是所有events都展示出来，这个修改刚刚好，因为它可以跳过与下一个快照的大段空白时间的，满足我们的需求。
