### ISSUE TITLE
Possible to confugure whther the rrweb-player loads paused or auto playing

### ISSUE THREAD

**Issue by samjbmason** [rrweb-io/rrweb#39]
Is it possible to allow some kind of configuration with the player to load it as paused. When it currently loads it automatically starts playing

**Comment by Yuyz0112** [comment]
I think you mean `rrweb-player` right? I would like to add a config of autoplay.

**Comment by samjbmason** [comment]
Yeah thats correct

**Comment by samjbmason** [comment]
What also might be useful @Yuyz0112 is if it was possible in the `rrweb-player` to allow scrubbing in the player timeline

**Comment by Yuyz0112** [comment]
@samjbmason Do you mean drag and drop the timeline handler and click to play at any time?
Yeah actually `rrweb-player` already implemented part of that but I temporarily disabled it for performance concern.
It should be available after #6 has been done.

**Comment by Yuyz0112** [comment]
@samjbmason 
The autoplay feature has been implemented in https://github.com/rrweb-io/rrweb-player/commit/f3de70114d80e7cf4cb713a6342a9a087c6d5d3f
