### ISSUE TITLE
current version 0.9.7 doesn't match what's in the doc!!!

### ISSUE THREAD

**Issue by Tonysmark** [rrweb-io/rrweb#390]
I using typescript 4.0.1 and react 16.13.1 
For example this code in the guidance is not usable
```typescript
import rrwebPlayer from 'rrweb'
new rrwebPlayer({
  target: document.body, 
  props: {
    events,
  },
});
```
webpack will got an error because there is not a default export for rrweb module, so I use
```typoescript
import { Replayer } from 'rrweb';
```
but in this case I can't config showController

```typescript
 const replayer = new Replayer(JSON.parse(events), { root, mouseTail: false, showController: true }); // error
```

**Comment by Yuyz0112** [comment]
Where is this code snippet comes from?

```js
import rrwebPlayer from 'rrweb'
new rrwebPlayer({
  target: document.body, 
  props: {
    events,
  },
});
```

Looks like you are using the rrweb-player, so you should do

```diff
- import rrwebPlayer from 'rrweb'
+ import rrwebPlayer from 'rrweb-player'
```

**Comment by Tonysmark** [comment]
> Where is this code snippet comes from?
> 
> ```js
> import rrwebPlayer from 'rrweb'
> new rrwebPlayer({
>   target: document.body, 
>   props: {
>     events,
>   },
> });
> ```
> 
> Looks like you are using the rrweb-player, so you should do
> 
> ```diff
> - import rrwebPlayer from 'rrweb'
> + import rrwebPlayer from 'rrweb-player'
> ```

My fault .... Thanks anyway
