### ISSUE TITLE
JavaScript syntax question

### ISSUE THREAD

**Issue by Immortalin** [rrweb-io/rrweb#391]
![image](https://user-images.githubusercontent.com/7126128/95669752-ec523880-0b51-11eb-8fe6-0e242e633ced.png)

How is the calllback passed to `emit` without parenthesis?

**Comment by Yuyz0112** [comment]
Not quite sure what's the question is, this is the standard ES6 JS syntax.

**Comment by Immortalin** [comment]
I just realized it is a method, not a callback. My bad. 😅
