### ISSUE TITLE
delay为负数，播放卡顿

### ISSUE THREAD

**Issue by cc0217** [rrweb-io/rrweb#393]
作者，您好，
不知道什么原因，我的events的delay存在负数。如果我理解没错的话，delay应该是以第一条的时间戳来计算的，第一条的delay应该为0才对吧，下图为我的events第一条的delay是负数。
![image](https://user-images.githubusercontent.com/72787334/95830158-d919b580-0d69-11eb-9a7e-51793a62d07b.png)

播放卡顿，只能鼠标点击进度条，跳过卡顿的地方。
还可以将进度条往后拉，再往前拉，此时，会出现events正常播放，进度条不动，播放按钮暂停的情况。
我不方便提供events，想请问下，这可能是什么原因，我应该从哪方面改动呢？

**Comment by Yuyz0112** [comment]
可以看一下回放的代码吗？

调用 play 的时候有传入是什么参数吗？

**Comment by cc0217** [comment]
就只有传入了events。代码如下：
new rrwebPlayer({
            target: document.getElementById('player'),
            props: {
                events: result
            }
        });

**Comment by Yuyz0112** [comment]
events 是按 timestamp 顺序排列的吗？

**Comment by cc0217** [comment]
是的

**Comment by Yuyz0112** [comment]
https://github.com/rrweb-io/rrweb/blob/master/docs/recipes/record-and-replay.zh_CN.md

你的 events 如果按照这个最简单的示例代码回放，没有任何额外代码，也会有这个问题吗？如果有的话，可以把所有 events 的 timestamp 提供一下。

**Comment by Yuyz0112** [comment]
如果有更详细的信息请 reopen issue。

**Comment by wy6921** [comment]
@Yuyz0112 作者，您好，我们的events也有很多负数，在使用repl进行测试时，发现createPlayerService中的play()方法多次执行，每次的baseline都不一样，似乎delay为负数跟delay有关，想问下，导致delay为负数的原因是什么呢？
([](![image](https://user-images.githubusercontent.com/33519530/98077674-a5830480-1eab-11eb-87be-afe1375d411b.png)))
[replay_2020_11_04T06_24_30.zip](https://github.com/rrweb-io/rrweb/files/5485862/replay_2020_11_04T06_24_30.zip)

**Comment by wfk007** [comment]
我遇到的 case 是往前 seekTime 比较慢，往后 seekTime 的还行，而且也存在很多为负数的 delay 值
