### ISSUE TITLE
实时回放canvas时出现多余的线

### ISSUE THREAD

**Issue by xiaoBiao** [rrweb-io/rrweb#400]
我将syncit的rrweb版本修改为0.9.7并增加canvas的录制和回放属性，然后在实时回放时会出现多余的线，我尝试去模拟复现一下：
1. 直播时将event全部保存，然后使用livemode通过setTimeout来addEvent来模拟直播回放，正常回放不会出现多余的线
2. 直播时将event全部保存，然后修改syncit的回放代码，在addEvent时直接使用之前保存的event，正常回放不会出现多余的线

后来我猜测可能是和时间有关，然后我修改了回放的代码将
```javascript
replayer.startLive(event.timestamp - buffer.bufferMs);
```
修改为
```javascript
replayer.startLive(event.timestamp + 10000 - buffer.bufferMs);
```
这样回放就正常了，但是过了一会又会出现多余的线
![image](https://user-images.githubusercontent.com/2069368/96433813-df130900-1237-11eb-97b1-a14ef1d61d93.png)

**Comment by Yuyz0112** [comment]
synit 只是 Demo，没有正式的版本，可能存在 bug。

如果基于 rrweb 的 live mode 能够复现问题，可以提供 events 用于 debug。

**Comment by startupgurukul** [comment]
A thought for canvas mutation logic, 
simplest solution would be canvas.captureStream and mediarecorder(but it's not safari friendly)

Another option is, 
capture diff on the prev and current image on the canvas and if image change noticed, getimagedata

if you want to go extra optimal, only save the rect  area of canvas where change is observed (and the corresponding coordinates) 

https://github.com/mapbox/pixelmatch

**Comment by Yuyz0112** [comment]
@startupgurukul rrweb now provides a general solution for canvas, which I think is inefficient and unsafe.

And I think recording media on the client-side is too heavy and not acceptable for rrweb.

What I suggested to do is design an ad-hoc recording with the App's business logic.

**Comment by startupgurukul** [comment]
Although hacky it's pretty smart, what you did for canvas mutation, overriding drawimage function of canvas2dcontext, along with drawimage, may be override the putimagedata function
