### ISSUE TITLE
IE 11浏览器兼容性问题

### ISSUE THREAD

**Issue by TreeLiberty** [rrweb-io/rrweb#401]
rrweb源码中使用了Object.assign这个方法，此方法在IE 11版本中是不支持的，另外rrweb-player中使用了箭头函数，这个在IE 11中也是不支持的，请问有什么好的方法可以兼容IE 11么？

**Comment by Yuyz0112** [comment]
rrweb 和 rrweb-player 的 build 流程中都没有引入 babel。

Object.assign 的问题可能可以通过单独引入 polyfill：https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Polyfill

rrweb-player 可能需要在 rollup 中配置 babel，rrweb-player 使用的 UI 框架 svelte 本身就没有支持 IE11。

**Comment by TreeLiberty** [comment]
@Yuyz0112 非常感谢您的解答。
