### ISSUE TITLE
能否将master代码merge到nest-record分支，以支持非跨域iframe录制

### ISSUE THREAD

**Issue by leossw** [rrweb-io/rrweb#403]
hello，非常高兴能发现这么棒的工具，我需要同时使用canvas和iframe录制功能（同源），能否将master代码同步到nest-record分支，这样可以体验最新功能也能使用iframe，我尝试合并过但是源码了解有限，有些冲突不确定如何处理，感谢～

**Comment by leossw** [comment]
> hello，非常高兴能发现这么棒的工具，我需要同时使用canvas和iframe录制功能（同源），能否将master代码同步到nest-record分支，这样可以体验最新功能也能使用iframe，我尝试合并过但是源码了解有限，有些冲突不确定如何处理，感谢～

**Comment by leossw** [comment]
> hello，非常高兴能发现这么棒的工具，我需要同时使用canvas和iframe录制功能（同源），能否将master代码同步到nest-record分支，这样可以体验最新功能也能使用iframe，我尝试合并过但是源码了解有限，有些冲突不确定如何处理，感谢～

已解决

**Comment by jinlong** [comment]
> > hello，非常高兴能发现这么棒的工具，我需要同时使用canvas和iframe录制功能（同源），能否将master代码同步到nest-record分支，这样可以体验最新功能也能使用iframe，我尝试合并过但是源码了解有限，有些冲突不确定如何处理，感谢～
> 
> 已解决

请问咋解决的？你自己处理冲突了？

**Comment by leossw** [comment]
> > > hello，非常高兴能发现这么棒的工具，我需要同时使用canvas和iframe录制功能（同源），能否将master代码同步到nest-record分支，这样可以体验最新功能也能使用iframe，我尝试合并过但是源码了解有限，有些冲突不确定如何处理，感谢～
> > 
> > 
> > 已解决
> 
> 请问咋解决的？你自己处理冲突了？

是的，自己合并master和nest-record分支，合并后会有冲突和bug需要解决。不过我看作者新建了一个iframe分支，应该是准备支持iframe了吧

**Comment by jinlong** [comment]
> 是的，自己合并master和nest-record分支，合并后会有冲突和bug需要解决。不过我看作者新建了一个iframe分支，应该是准备支持iframe了吧

我也看到有个iframe分支，我周末测试这个分支好像没跑起来，我再看看吧...

你自己合并完的代码可以录制同源 iframe 是吧？我们也需要这个功能

**Comment by leossw** [comment]
> 我也看到有个iframe分支，我周末测试这个分支好像没跑起来，我再看看吧...
> 
> 你自己合并完的代码可以录制同源 iframe 是吧？我们也需要这个功能
是的，可以录制同源iframe，就是要花时间熟悉代码处理冲突，有问题可以互相交流
