### ISSUE TITLE
回放相关问题

### ISSUE THREAD

**Issue by mrxiongmao** [rrweb-io/rrweb#404]
1.录制过程中产生截图文件，后端以base64编码返回图片文件，回放无法播放图片，
   问：录制的产生的截图有没有办法可以播放
2.如果没法播放截图
   问：在回放视频播放途中，我能拿到每个event的时间戳和截图的时间戳，有没有办法能根据时间戳停止播放视频

**Comment by Yuyz0112** [comment]
1. 可以提供 events 用于 debug 吗？
2. `replayer.pause()` 可以停止回放，`replayer.on('event-cast', (event) => console.log('current event', event))` 可以监听当前播放到的事件

**Comment by Yuyz0112** [comment]
1. 可以提供 events 用于 debug 吗？
2. `replayer.pause()` 可以停止回放，`replayer.on('event-cast', (event) => console.log('current event', event))` 可以监听当前播放到的事件

**Comment by mrxiongmao** [comment]
正常录制数据的截图的数据 后端是以2种不同的形式返回，截图并不是events，只是一段base64
我注意到有这个配置参数 UNSAFE_replayCanvas  可以播放canvas，那有没有办法在录制的时候可以把截图处理成canvas

**Comment by mrxiongmao** [comment]
@Yuyz0112  抱歉，你说的replayer.on('event-cast', (event) => console.log('current event', event)) 这个方法我用了，控制台没有任何输出。
我是这样使用，rrwebPlayer不能这么用吗？
const replayer = new rrwebPlayer({
  target: ...
  data:{..}
})
replayer.on('event-cast', (event) => console.log('current event', event))

**Comment by Yuyz0112** [comment]
rrwebPlayer 的话是用 `rrwebPlayer.addEventListener` 的 API

可以看看 [指南](https://github.com/rrweb-io/rrweb/blob/master/guide.zh_CN.md) 和 [场景示例](https://github.com/rrweb-io/rrweb/blob/master/docs/recipes/index.zh_CN.md) 里的内容是否解决你的问题

**Comment by mrxiongmao** [comment]
@Yuyz0112   我用了rrwebPlayer的ui-update-current-time 事件，然而控制台没任何输出
跟rrwebPlayer的版本有关系吗？ 我的是0.4.6
replayer.addEventListener('ui-update-current-time', (event) => {
  console.log(event.detail.payload, 'current-time');
});

**Comment by mrxiongmao** [comment]
@Yuyz0112 , 打扰，换了一种思路
场景：有3个回放源，我想在第一个回放完之后播放第二个，请问播放完成之后能拿到相应的事件或者标识吗
我试过 ui-update-player-state 没有任何输出

**Comment by Yuyz0112** [comment]
> @Yuyz0112 我用了rrwebPlayer的ui-update-current-time 事件，然而控制台没任何输出
> 跟rrwebPlayer的版本有关系吗？ 我的是0.4.6
> replayer.addEventListener('ui-update-current-time', (event) => {
> console.log(event.detail.payload, 'current-time');
> });

最新版本的 rrweb-player 应该才有这个事件

**Comment by Yuyz0112** [comment]
> @Yuyz0112 , 打扰，换了一种思路
> 场景：有3个回放源，我想在第一个回放完之后播放第二个，请问播放完成之后能拿到相应的事件或者标识吗
> 我试过 ui-update-player-state 没有任何输出

@mrxiongmao 可以监听 finish 事件
