### ISSUE TITLE
请问如何将会放到的数据转成视频

### ISSUE THREAD

**Issue by yukunan** [rrweb-io/rrweb#406]

**Comment by startupgurukul** [comment]
pls try these 

https://github.com/niklasvh/html2canvas
https://github.com/bubkoo/html-to-image

**Comment by Yuyz0112** [comment]
I've built [rrvideo](https://github.com/rrweb-io/rrvideo) for this.

**Comment by startupgurukul** [comment]
Thank you for sharing rrvideo, the rtcrecord can help build something within browser without needing to get to cli

**Comment by TrustA906** [comment]
@Yuyz0112 大佬你好，有详细点的例子吗？采集的数据有压缩处理，是将采集的event拼成一个大的数组写到文件当中吗
