### ISSUE TITLE
mouse Tail

### ISSUE THREAD

**Issue by vfasoulas** [rrweb-io/rrweb#408]
I Can'nt disable mouse tail.

**Comment by Yuyz0112** [comment]
@vfasoulas Please try this

```js
new Replayer(events, {
  mouseTail: false
})
```

**Comment by vfasoulas** [comment]
thanks

Στις Κυρ, 1 Νοε 2020 στις 3:37 μ.μ., ο/η yz-yu <notifications@github.com>
έγραψε:
