### ISSUE TITLE
livemode无法关闭？

### ISSUE THREAD

**Issue by sunzhixun001** [rrweb-io/rrweb#412]
浏览器tab标签上始终在转，没有发送任何请求，network里有个livereload一直是pending
`new replayer(events, {
     liveMode: false //这里写不写都一样效果
})`
rrweb版本是0.9.9

**Comment by Yuyz0112** [comment]
livereload 应该和 rrweb 无关。

livemode 也和这个没有关系，是用来配置是否开启直播模式的 flag。

tab 的 loading 不确定具体原因，可以自行 debug 一下，rrweb 没有预期去优化这个部分。
