### ISSUE TITLE
页面里面录制成功后，当前页面重新录制是空白页面。

### ISSUE THREAD

**Issue by adking1** [rrweb-io/rrweb#413]
当录制当前页面的表单提交后，我会调用rrwebMin.record 返回的stop停止录制，然后清空当前表单后， 重新调用record录制，但是第二次录制后出来的页面是空白的。怎么解决呢？

**Comment by Yuyz0112** [comment]
可以提供录制的数据和回放的示例代码用于 debug 吗

**Comment by Yuyz0112** [comment]
有进一步信息时可以 re-open issue.
