### ISSUE TITLE
Is there way to filter events?

### ISSUE THREAD

**Issue by isallavat** [rrweb-io/rrweb#414]
For example I don't need mousemove events.

**Comment by Mark-Fenng** [comment]
I think you might be able to hide mouse movement when replaying the record.

**Comment by isallavat** [comment]
No. I don't need to store this events. Because they take up a lot of space in DB

**Comment by Mark-Fenng** [comment]
For now, there's not a setting to do this.
But I have another idea that might help with you.
```
rrweb.record({
  emit(event) {
    // push event into the events array
    events.push(event);
  },
});
```
You can filter the mousemove events in emit function to skip some unimportant events.

**Comment by isallavat** [comment]
Ok. But how to detect mousemove events in event object?

**Comment by Mark-Fenng** [comment]
This is the data structure for event:
```json
{
    type: number,
    data: {
        source: number
    }
}
```
type tells the event type and source tells the specific event type e.g. mousemove

**Comment by isallavat** [comment]
Ok. And where is list of types and sources?

**Comment by Mark-Fenng** [comment]
They are defined in src/types.ts.
EventType is the "type" property and IncrementalSource is the "source" property.

**Comment by isallavat** [comment]
Can you write here full list of event types/source numbers like this?
MouseMove = 1
Click = 2
Somthing else = 3
...

**Comment by Mark-Fenng** [comment]
Their numbers are in order start from 0.
type: range from 0 to 5.
![image](https://user-images.githubusercontent.com/27533910/98658536-221b5480-237e-11eb-81e0-9f80f56c5d6b.png)
source: range from 0 to 11.
![image](https://user-images.githubusercontent.com/27533910/98658488-10d24800-237e-11eb-8b02-830d31083f22.png)

**Comment by isallavat** [comment]
Tnx

**Comment by VikramTiwari** [comment]
Hey @YunFeng0817 Could this be made optional? 

I am thinking of it as a setting for events that you don't want to record at all. Or maybe a few pre-defined modes (skip-mouse-events, skip-keyboard-events).

**Comment by YunFeng0817** [comment]
Yes, in the future we may add related options. But it is not in a high priority so it may take a long time. Right now, it's easier to filter events in the `emit` callback function.
