### ISSUE TITLE
有木有添加全量快照的api呢？就像addCustomEvent那样的

### ISSUE THREAD

**Issue by wahh33** [rrweb-io/rrweb#415]
如题

**Comment by Mark-Fenng** [comment]
添加全量快照是什么意思呢 抱歉我没有看明白

**Comment by wahh33** [comment]
> 添加全量快照是什么意思呢 抱歉我没有看明白

类似rrweb.record.addFullSnapshotEvent()这样的？好像重新调rrweb.record()也可以制作全量快照，就是想通过addCustomEvent给eventList打个标志来分段存储，来区分操作的场景，然后查找哪个会话的哪个操作场景来播放，据我理解用来播放的数据好像是要从全量快照开始的？

**Comment by Mark-Fenng** [comment]
重新调用record是一种方式，是否也可以通过记录场景的开始时间来区分呢，在播放时可以从指定的位置开始播放

**Comment by joket1999** [comment]
我也有这个需求，在录制过程中某些情况下需要手动执行全量快照
