### ISSUE TITLE
distinguish user actions from background events

### ISSUE THREAD

**Issue by eoghanmurray** [rrweb-io/rrweb#418]
I've got a use-case where I'd like to be able to end a recording if nothing has happened for a certain time.  Just looking at the event stream does not work however, as there can be ongoing background mutations etc. or media plays that are triggered periodically.  This is somewhat related to #224 which was merged in #385 

Both user actions and background events are generally categorized under `IncrementalSnapshot`.
I wonder is there a way of flagging the difference between a mutation and a 'real' user action such as a click, scroll, or text entry.

(might also need to distinguish between e.g. real and programmatic clicks; 
https://stackoverflow.com/questions/6674669/in-jquery-how-can-i-tell-between-a-programmatic-and-user-click )

I'm wondering if this is a good addition?  
Another use-case would be in constructing a more meaningful timeline for playback.

**Comment by Yuyz0112** [comment]
I also find some situations I need to distinguish between programmatic focus and a user focus. But the way to do it looks very tricky and dangerous as a general tracking lib.

Is it possible to do some heuristic check like
1. Interactions when the page is not visible can be considered as non-user.
2. Focus/Blur without keyboard/mouse interactions can be considered as non-user.

Anyway, do not have too many thoughts on this yet.

**Comment by startupgurukul** [comment]
Can istrusted help
https://developer.mozilla.org/en-US/docs/Web/API/Event/isTrusted

The isTrusted read-only property of the Event interface is a Boolean that is true when the event was generated by a user action, and false when the event was created or modified by a script or dispatched via EventTarget.dispatchEvent().

**Comment by Yuyz0112** [comment]
@startupgurukul Thanks! This looks really interesting and related.

**Comment by Mark-Fenng** [comment]
This is implemented in https://github.com/rrweb-io/rrweb/pull/495
