### ISSUE TITLE
Replay of various sites doesn't work

### ISSUE THREAD

**Issue by mariusrak** [rrweb-io/rrweb#42]
Hi, using tampermonkey I inserted recording code to all websites visited by me through my browser. The recording code sends event JSONs to a server which stores them in a file. Each event in a single row. I have 294 events recorded. I want to further replay the record but it doesn't work. The player is there and the duration of the record is 21:59 so it seems that it resolves the data, however the cursor doesn't move and the player screen is blank. When I removed first events from the file until the events of type 4 and then 2, leaving 199, the duration is only 2:11, cursors moves first half of second and then stops, screen is also blank.
I get an error `TypeError: n is null` at ` e.previousId && (o = E.getNode(e.previousId)), e.nextId && (s = E.getNode(e.nextId)), -1 !== e.previousId && -1 !== e.nextId ? (o && o.nextSibling && o.nextSibling.parentNode ? n.insertBefore(t, o.nextSibling) : s && s.parentNode ? n.insertBefore(t, s) : n.appendChild(t), (e.previousId || e.nextId) && i.resolveMissingNode(r, n, t, e)) : r[e.node.id] = {`

How can I make this work or where can be a problem? I'm attaching replay code.

``` html
<!DOCTYPE html>
<html>
        <head>
                <meta charset="UTF-8">
                <title>Player</title>
                <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/rrweb-player@latest/dist/style.css">
                <script src="https://cdn.jsdelivr.net/npm/rrweb-player@latest/dist/index.js"></script>
                
                <script>
                        'use strict';
                        var FR = new FileReader();
                        var textToArr = res => res.split(/\n/).reduce((arr, row) => {
                                try {
                                        var e = JSON.parse(row);
                                        return [...arr, e];
                                } catch(e){
                                        return arr;
                                }
                        }, []);
                        FR.onload = function(e) {
                                var events = textToArr(e.target.result)
                                new rrwebPlayer({
                                        target: document.body,
                                        data: { events },
                                });
                        };

                        fetch('./output')
                                .then(res => res.blob())
                                .then(res => FR.readAsText(res));
                </script>
        </head>
        <body>
                
        </body>
</html> 
```

**Comment by mariusrak** [comment]
Further news:
I've tried a pretty simple page and everything worked correctly, once I've recorded some js-heavy page, record failed with the errors. It seems like a problem with recording all the mutations on page. Commercial solutions are able to record even the js-heavy sites, so it's possible to do it.

**Comment by Yuyz0112** [comment]
@mariusrak thanks for the reporting! Could you provide the js-heavy website you have tried to record or the events you already recorded to me? Then I can debug what’s the corner case rrweb does not handle.

**Comment by mariusrak** [comment]
So I've injected `https://cdn.jsdelivr.net/npm/rrweb@latest/dist/record/rrweb-record.min.js` to alza.sk and got out this: https://mariusrak.sk/rec which doesn't work.

**Comment by Yuyz0112** [comment]
@mariusrak I've downloaded your records and found it looks like missing some events. Could you provide your inject and collect code so I can see why this happen.

**Comment by Yuyz0112** [comment]
@mariusrak Where do you inject the client side code? In the header or at the end of body.

**Comment by mariusrak** [comment]
I'm using tampermonkey - https://tampermonkey.net/ I'm not sure where it is puttting the script.

**Comment by Yuyz0112** [comment]
Please have a try with the latest release, and feel free to reopen the issue if it still exists.
