### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by kooler** [rrweb-io/rrweb#421]
Hi guys,

I was wondering, is there a place to see browser support? To know what are the minimal versions of browsers that can run rrweb.

Thanks!

**Comment by Yuyz0112** [comment]
On the record side, you can check the compatibility of mutation observer: https://caniuse.com/?search=mutation%20observer

On the replay side, if you are using `rrweb-player` as the UI, it does not support IE 11 because it's using svelte as the UI framework.
