### ISSUE TITLE
请问，可以录制正在进行视频通话中的视频吗？如果可以话，可以将声音录制进去吗？

### ISSUE THREAD

**Issue by LearnForfuture2019** [rrweb-io/rrweb#425]

**Comment by Mark-Fenng** [comment]
可以录制你对视频的操作，视频本身只会保存视频链接，不会下载资源

**Comment by Yuyz0112** [comment]
基于 custom event 可能可以实现更好的效果

**Comment by LearnForfuture2019** [comment]
就是想录制类似微信视频通话的这样一个功能，之后可以再次播放@Yuyz0112 @Mark-Fenng

**Comment by Yuyz0112** [comment]
@LearnForfuture2019 可以参考文档理解一下原理，音视频流不是 DOM 录制的一部分。可以考虑通过 custom event 之类的方式令音视频在回放时被加载，但总之都是上层业务要实现的业务逻辑。
