### ISSUE TITLE
多个replayer实例下回放会错乱

### ISSUE THREAD

**Issue by Kefeng2017** [rrweb-io/rrweb#429]
例如，我页面上有两个replayer， replayerA和replayerB，对应recorderA和recorderB，此时recorderA产生的recordA，调用replayerA.addEvent(recordA)时，recordA会被add到replayerB实例上，即recorderA产生的变化会体现在replayerB中。导致错乱。几乎必现，产生的record几乎总是会被添加到页面上最后生成的replayer上。

**Comment by Kefeng2017** [comment]
看了下源码，好像与mirror机制有关

**Comment by Mark-Fenng** [comment]
是的，所有的replayer共享一个mirror

**Comment by Kefeng2017** [comment]
嗯，我修改了一下源码，实例化了一下mirror，可以满足需求了
