### ISSUE TITLE
svg标签的元素录制出来一片空白

### ISSUE THREAD

**Issue by wangkai0717** [rrweb-io/rrweb#430]
用pdfjs对pdf做了在线解析，采用的是svg模式，渲染出来的标签都是svg标签，但是录出来是空白的，请问是不支持还是需要做什么配置？

**Comment by Yuyz0112** [comment]
不太确定具体的原因，目前已知对 pdfjs 可行的方案

1. 使用 canvas 渲染，并打开 rrweb 的 canvas 录制和回放配置（会采集大量数据）
2. 使用 img 渲染
3. 使用自定义事件传递 pdf 的打开事件，在回放时自行实现再次打开

**Comment by leossw** [comment]
> 不太确定具体的原因，目前已知对 pdfjs 可行的方案
> 
> 1. 使用 canvas 渲染，并打开 rrweb 的 canvas 录制和回放配置（会采集大量数据）
> 2. 使用 img 渲染
> 3. 使用自定义事件传递 pdf 的打开事件，在回放时自行实现再次打开

我也遇到过，不知道是不是同一个问题

![image](https://user-images.githubusercontent.com/17774199/104700060-92fc3580-574e-11eb-94c7-84cf8cdbea08.png)

这种情况会被当成相对路径，转换成绝对路径，其实对应的是id

rrweb-snapshot snapshot.ts文件

我的做法：
const RELATIVE_PATH = /^(?!www\.|(?:http|ftp)s?:\/\/|[A-Za-z]:\\|\/\/).*/;
改成
const RELATIVE_PATH = /^(?!www\.|(?:http|ftp)s?:\/\/|[A-Za-z]:\\|\/\/|#).*/;

**Comment by Yuyz0112** [comment]
@leossw 可以给 rrweb-snapshot 提一个 PR 吗？

**Comment by leossw** [comment]
> @leossw 可以给 rrweb-snapshot 提一个 PR 吗？

@Yuyz0112  PR：https://github.com/rrweb-io/rrweb-snapshot/pull/59

**Comment by huqi1** [comment]
> 用pdfjs对pdf做了在线解析，采用的是svg模式，渲染出来的标签都是svg标签，但是录出来是空白的，请问是不支持还是需要做什么配置？

请问你们解决了吗
