### ISSUE TITLE
vue项目打包后同样是独立的css样式文件，为什么有部分样式打包进了json文件？

### ISSUE THREAD

**Issue by ListerZhang** [rrweb-io/rrweb#431]
如图，vue项目打包后同样是独立的css样式文件，为什么有部分样式打包进了json文件？绿色箭头的样式文件是不会被采集进去，红色箭头部分就会被打包到json中，导致json文件特别大 @Yuyz0112 
![截图](https://user-images.githubusercontent.com/71001710/100848402-03f7ce80-34bc-11eb-81ae-41830e9ab5fa.png)

**Comment by Yuyz0112** [comment]
默认会尽可能的把样式表内联，以保证回放的稳定性和质量。

不需要这部分的话可以在录制配置里让 `inlineStylesheet` 为 false

**Comment by ListerZhang** [comment]
收到，非常感谢




张乐

发件人： yz-yu
发送时间： 2020-12-02 17:15
收件人： rrweb-io/rrweb
抄送： ListerZhang; Author
主题： Re: [rrweb-io/rrweb] vue项目打包后同样是独立的css样式文件，为什么有部分样式打包进了json文件？ (#431)
默认会尽可能的把样式表内联，以保证回放的稳定性和质量。
不需要这部分的话可以在录制配置里让 inlineStylesheet 为 false

**Comment by ListerZhang** [comment]
> 默认会尽可能的把样式表内联，以保证回放的稳定性和质量。
> 
> 不需要这部分的话可以在录制配置里让 `inlineStylesheet` 为 false

收到，非常感谢，我们试试看

**Comment by ListerZhang** [comment]
![image](https://user-images.githubusercontent.com/71001710/101302725-5c8de980-3877-11eb-88c9-c4fdeb854dac.png)
按照您提供的方法试了一下发现还是会内联进来大量的独立css文件的样式

**Comment by ListerZhang** [comment]
@Yuyz0112

**Comment by ListerZhang** [comment]
https://ecuat.tk.cn/tkproperty/prd/S20180209/?verify=N 这是我们的测试产品链接，我们将采集的数据放到了localstorage缓存中，可以看看

**Comment by ListerZhang** [comment]
@Yuyz0112

**Comment by Yuyz0112** [comment]
@ListerZhang 

我在最新的 0.9.11 版本上对这个链接测试，传入 option

```js
record({
  emit() {},
  inlineStylesheet: false
})
```

没有再录制内联的 CSS
