### ISSUE TITLE
Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.

### ISSUE THREAD

**Issue by JayeshGridScape** [rrweb-io/rrweb#436]
When I use  recordCanvas: true its breaks recording with the error "Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported."  
can you please help with this issue.
thanks

**Comment by startupgurukul** [comment]
It seems like  CORS issue
https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image

img.crossOrigin = "Anonymous";
This only works if the remote server sets the following header appropriately:

Access-Control-Allow-Origin "*" 

we have no control on what server returns Access-Control-Allow-Origin and it may not work sometimes, 

A work around that would be using browser extension web request api where we can edit http headers on the fly and set to what ever we want...
https://developers.chrome.com/docs/extensions/reference/webRequest/

**Comment by Yuyz0112** [comment]
I think https://github.com/rrweb-io/rrweb/pull/536 remove the usage of `toDataURL`.
