### ISSUE TITLE
ie11浏览器不能正常播放

### ISSUE THREAD

**Issue by daerduotu** [rrweb-io/rrweb#439]
录制的视频其他播放器可以播放,但是ie11不行

**Comment by Yuyz0112** [comment]
有具体的错误信息吗？也欢迎直接 PR 修复。

**Comment by daerduotu** [comment]
没有报错,iframe中播放器内容无法显示

**Comment by Yuyz0112** [comment]
如果使用的是 rrweb-player，兼容性和 svelte 相同，不会支持 IE11。

如果使用的是 rrweb 内置的 Replayer，我们近期包含了一些 IE11 修复，但后续不保证持续兼容 https://github.com/rrweb-io/rrweb/commit/b83123a23c2fe5d08ebeff6a74f839bc8efcb865
