### ISSUE TITLE
Printscreen or Screen Recording

### ISSUE THREAD

**Issue by douglas-88** [rrweb-io/rrweb#442]
Good night,

I would very much like to take screenshots of the user's screen, or if possible record it and be able to store this image or video, but I am unable to implement this by consulting only the documentation, I do not understand.
Note: My backend is in PHP, I would like to send the created file via ajax and store these files for later consultations.

Can someone help me, please?
Much obliged.

**Comment by Mark-Fenng** [comment]
If you just need screenshots rather than records like video, I think [rrweb-snapshot](https://github.com/rrweb-io/rrweb-snapshot) is enough.

**Comment by douglas-88** [comment]
But how does that work?
I made the git clone to try to run an example, but found nothing.

The ideal would be the video, but if you can save a screen print, it would be fine.

**Comment by Mark-Fenng** [comment]
This project doesn't record web as video directly. What you need is to record web as video format?
Maybe [this project](https://github.com/rrweb-io/rrvideo) could help you.

**Comment by douglas-88** [comment]
> This project doesn't record web as video directly. What you need is to record web as video format?
> Maybe [this project](https://github.com/rrweb-io/rrvideo) could help you.

It would be too bureaucratic for my project to install ffmpeg ...
Can I, with just that .json file of events, play a video with these user interactions in the future?

**Comment by Mark-Fenng** [comment]
Of course, here's a [demo](https://www.rrweb.io/)

**Comment by startupgurukul** [comment]
Give this a try 
https://github.com/rrweb-io/rrvideo/issues/2

**Comment by Yuyz0112** [comment]
Feel free to re-open if there is further information.
