### ISSUE TITLE
Playing from specified time not working in rrwebPlayer

### ISSUE THREAD

**Issue by slicvic** [rrweb-io/rrweb#444]
Hi,

Started using rrweb recently and my hat goes off to you guys.

Truly amazing work. Keep it up!

My issue is I can't seem to play from a specified time as your guide suggests.

For example, this won't play from 4th second:

`const player = new rrwebPlayer({...}); player.play(4000)`

Thanks so much,
V

**Comment by Mark-Fenng** [comment]
Is there any message in console like error or this
![image](https://user-images.githubusercontent.com/27533910/102296397-35769c80-3f88-11eb-8689-6ec32f9a1cbf.png)

**Comment by slicvic** [comment]
Hi, thanks for quick reply.

No errors whatsoever.

I'm also loading from CDN.

https://cdn.jsdelivr.net/npm/rrweb-player@latest/dist/index.js

**Comment by slicvic** [comment]
> Is there any message in console like error or this
> ![image](https://user-images.githubusercontent.com/27533910/102296397-35769c80-3f88-11eb-8689-6ec32f9a1cbf.png)

**Comment by Mark-Fenng** [comment]
It will be very helpful to upload a reproducible code through codepen or a repo

**Comment by slicvic** [comment]
Hi, 

After some [debugging](https://imgur.com/GLORl3j) I noticed you expose a `getReplayer` method and the following worked:

`player.getReplayer().play(9000)`

Cheers and keep up the fantastic work!
V

**Comment by Mark-Fenng** [comment]
Oh, I know your problem. You are using rrweb-player and its api is a little different from rrweb.
In rrweb-replayer, you have to call player.goto(4000).

**Comment by slicvic** [comment]
Sweet!

That works too!

Thanks dude!
