### ISSUE TITLE
如何修改播放器的宽高?播放器容器大小变了,怎么修改播放器宽高?

### ISSUE THREAD

**Issue by kangling098** [rrweb-io/rrweb#446]
如何修改播放器的宽高?播放器容器大小变了,怎么修改播放器宽高?

**Comment by kangling098** [comment]
找到了api     
this.rrwebPlayerInstance.$set({
          width: replayWidth,
          height: replayHeight - 80,
        })

**Comment by Yuyz0112** [comment]
参考这个文档： https://github.com/rrweb-io/rrweb/blob/6c4f10e4e7/docs/recipes/customize-replayer.zh_CN.md

```ts
rrwebPlayer.$set({
  width: NEW_WIDTH,
  height: NEW_HEIGHT,
});
rrwebPlayer.triggerResize();
```

**Comment by hanfengcan** [comment]
> 参考这个文档： https://github.com/rrweb-io/rrweb/blob/6c4f10e4e7/docs/recipes/customize-replayer.zh_CN.md
> 
> ```ts
> rrwebPlayer.$set({
>   width: NEW_WIDTH,
>   height: NEW_HEIGHT,
> });
> rrwebPlayer.triggerResize();
> ```

为什么我使用 $set的时候, 提示undefined呢?

```
rrplayer = new Replayer(e, { ...opts, showController: false });
rrplayer.$set()
```

**Comment by Mark-Fenng** [comment]
@hanfengcan $set方法是[rrweb-player](https://github.com/rrweb-io/rrweb-player)库的方法，你创建的replayer是rrweb的player

**Comment by kangling098** [comment]
rrweb-player 的文档更新一下吧,$set方法没有写出来,然后 开始播放方法,是play,文档上写的start

**Comment by Yuyz0112** [comment]
@kangling098 哪个文档提到的 `start` 方法？

**Comment by kangling098** [comment]
![image](https://user-images.githubusercontent.com/20222196/103326812-03d3fa00-4a8d-11eb-8fe5-e899482e3591.png)
@Yuyz0112

**Comment by Yuyz0112** [comment]
@kangling098 

![image](https://user-images.githubusercontent.com/13651389/103326940-86f55000-4a8d-11eb-91e1-ec0f0883bcd1.png)

start 是事件，不是方法
