### ISSUE TITLE
回放时css样式未生效

### ISSUE THREAD

**Issue by silenwym** [rrweb-io/rrweb#447]
录制成功后，在回放时css样式未生效，这个可能是什么问题导致的呢？附件是录制的json
[1606792435060.json.zip](https://github.com/rrweb-io/rrweb/files/5722951/1606792435060.json.zip)

回放时控制台有这个错误：because the document's frame is sandboxed and the 'allow-scripts' permission is not set

**Comment by Mark-Fenng** [comment]
The issue is not reproducible. More information is needed for debugging.
这个问题没有办法重现, 需要更多信息来debug问题.
