### ISSUE TITLE
[QUESTION] Best way to play live recording

### ISSUE THREAD

**Issue by L3o-pold** [rrweb-io/rrweb#45]
I'd like to play in real time the record. Is that something possible?

I actually record a web page and send events to a backend that's broadcasting events with websocket.

What's the best way to add new fetched events to current replay?

I tried something like this:

```javascript
mixed.on('progress.update', function (data) {
    if (data.events && data.events.length) {
          if (!player) {
            player = new rrwebPlayer({
              target: document.getElementById('player'),
              data: data,
            });
          } else {
            for (var i = 0; i < data.events.length; i++) {
              player.options.data.events.push(data.events[i]);
            }
         }
    }
});
```

If that's not possible is it a planned feature? I'd like to make a live debugging feature for our customer, something similar to [www.fullstory.com](https://www.fullstory.com/).

**Comment by Yuyz0112** [comment]
@L3o-pold Actually I have tried live-mode in a local branch, here is a preview: https://github.com/rrweb-io/rrweb/issues/30#issuecomment-451620595
I think it is definitely possible, an `addEvents` method is needed. Also, need to handle cases like network latency.

So this is in the future plan, and any discussion or contribution will be great to accelerate the progress.

**Comment by mattc0llier** [comment]
First off - amazing work! thank you for sharing, this came just at the right time.

Just so you have some example use cases for live events... I am looking to stream live events to a player with a similar set up to youtube live. 

<img width="758" alt="Screen Shot 2019-03-20 at 17 44 26" src="https://user-images.githubusercontent.com/2234289/54706966-06739280-4b38-11e9-9539-bc6d7f0b0717.png">

I am sending live events to a backend and then broadcasting events using WebSockets for a live view with live pause, instant 30-second replay and then full replay via drag and drop scroll bar.

**Comment by marcospassos** [comment]
This is one of the most wanted features for us.

@Yuyz0112 you demo looks promising! Any plans to make it public?

**Comment by JagdishThavasi** [comment]
> I'd like to play in real time the record. Is that something possible?
> 
> I actually record a web page and send events to a backend that's broadcasting events with websocket.
> 
> What's the best way to add new fetched events to current replay?
> 
> I tried something like this:
> 
> ```js
> mixed.on('progress.update', function (data) {
>     if (data.events && data.events.length) {
>           if (!player) {
>             player = new rrwebPlayer({
>               target: document.getElementById('player'),
>               data: data,
>             });
>           } else {
>             for (var i = 0; i < data.events.length; i++) {
>               player.options.data.events.push(data.events[i]);
>             }
>          }
>     }
> });
> ```
> 
> If that's not possible is it a planned feature? I'd like to make a live debugging feature for our customer, something similar to [www.fullstory.com](https://www.fullstory.com/).

Did you find any solution to implement this ?

**Comment by Yuyz0112** [comment]
https://github.com/rrweb-io/rrweb/blob/master/docs/recipes/live-mode.md
