### ISSUE TITLE
Recording <video> stream

### ISSUE THREAD

**Issue by vincenzocasu** [rrweb-io/rrweb#450]
Hi, is there a way to record a webcam stream injected into video srcObject?
At moment the record show a video container only not initialized... but the video stream was not recorded...

**Comment by startupgurukul** [comment]
Pls try mediarecorder it takes the stream as param 

https://developer.mozilla.org/en-US/docs/Web/API/MediaStream_Recording_API/Recording_a_media_element

**Comment by Yuyz0112** [comment]
Binary assets will be recorded as src URLs. Capture the video stream will not be part of rrweb's function, and I think users can implement this by creating a custom plugin.

**Comment by Juice10** [comment]
@vincenzocasu rrweb now has a webrtc plugin that can easily be modified to stream video files as well as canvas via webrtc https://github.com/rrweb-io/rrweb/tree/master/packages/rrweb/src/plugins/canvas-webrtc
