### ISSUE TITLE
最新版本rrweb在使用屏蔽组件功能屏蔽vconsole时内部函数报错

### ISSUE THREAD

**Issue by ListerZhang** [rrweb-io/rrweb#452]
如题，报错后导致死循环，页面卡死
![微信图片_20201225093907](https://user-images.githubusercontent.com/71001710/103113300-19b07c00-4695-11eb-8bab-6d2a0bc9b9b7.jpg)

**Comment by ListerZhang** [comment]
@Yuyz0112 您好，这个问题帮忙看看是否是最新版本在屏蔽部分无需采集的节点那块有什么特殊写法？

**Comment by ListerZhang** [comment]
[testInsertIframe.txt](https://github.com/rrweb-io/rrweb/files/5746141/testInsertIframe.txt)

**Comment by 94zn** [comment]
我也遇到 vconsole中录制时 卡死现象 只能把vconsole关掉才可以。。如果不关掉 还有其他办法吗？？

**Comment by Yuyz0112** [comment]
@ListerZhang 我用这个 demo 页面没有遇到问题，需要做什么操作吗？

**Comment by ListerZhang** [comment]
> @ListerZhang 我用这个 demo 页面没有遇到问题，需要做什么操作吗？

@Yuyz0112 抱歉，忘了加场景说明了，是必须在苹果系统下，使用webkit的浏览器才会复现，比如safari

**Comment by ListerZhang** [comment]
> 我也遇到 vconsole中录制时 卡死现象 只能把vconsole关掉才可以。。如果不关掉 还有其他办法吗？？

我们也暂时还没有找到解决方案，除了注释掉vconsole

**Comment by Mark-Fenng** [comment]
@ListerZhang 是否可以更新一下demo页面，我在macos 的safari上也没有遇到问题

**Comment by z408550513** [comment]
[testInsertIframe.txt](https://github.com/rrweb-io/rrweb/files/5767937/testInsertIframe.txt)
demo页面已更新. 0.8.5版本没有问题. 0.9.x版本发现会出现问题

**Comment by Mark-Fenng** [comment]
@z408550513 这次在safari上复现了

**Comment by Mark-Fenng** [comment]
@z408550513 屏蔽部分无需采集的节点 现在的写法是什么

**Comment by z408550513** [comment]
@Mark-Fenng 
doms.forEach((id) => {
      const dom = document.getElementById(id);
      if (dom) {
        dom.classList.add('rr-block');
        dom.classList.add('rr-ignore');
      }
    });
根据节点id动态赋值class

**Comment by bobjiang1988** [comment]
vue项目引入vconsole, 修改代码热部署后同样出现这个问题

**Comment by 94zn** [comment]
> vue项目引入vconsole, 修改代码热部署后同样出现这个问题

目前只能关掉vconsole了。

**Comment by Yuyz0112** [comment]
@bobjiang1988 @94zn 都是在 webkit(safari)浏览器上遇到的吗？我的 MacBook 正在路上。。

**Comment by Mark-Fenng** [comment]
@Yuyz0112 只有safari上出现这个问题，chrome上是正常的

**Comment by bobjiang1988** [comment]
我的不是Mac OS
我的`navigator.appVersion`值为
`5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36`

**Comment by Mark-Fenng** [comment]
> @Mark-Fenng
> doms.forEach((id) => {
> const dom = document.getElementById(id);
> if (dom) {
> dom.classList.add('rr-block');
> dom.classList.add('rr-ignore');
> }
> });
> 根据节点id动态赋值class

可以提供一下更完整的使用代码吗，从混淆的代码里看不出来你是怎么使用rrweb的

**Comment by z408550513** [comment]
> > @Mark-Fenng
> > doms.forEach((id) => {
> > const dom = document.getElementById(id);
> > if (dom) {
> > dom.classList.add('rr-block');
> > dom.classList.add('rr-ignore');
> > }
> > });
> > 根据节点id动态赋值class
> 
> 可以提供一下更完整的使用代码吗，从混淆的代码里看不出来你是怎么使用rrweb的

方便提供一下微信或者邮箱么?

**Comment by Mark-Fenng** [comment]
> > > @Mark-Fenng
> > > doms.forEach((id) => {
> > > const dom = document.getElementById(id);
> > > if (dom) {
> > > dom.classList.add('rr-block');
> > > dom.classList.add('rr-ignore');
> > > }
> > > });
> > > 根据节点id动态赋值class
> > 
> > 
> > 可以提供一下更完整的使用代码吗，从混淆的代码里看不出来你是怎么使用rrweb的
> 
> 方便提供一下微信或者邮箱么?

我github主页上就有邮箱

**Comment by bobjiang1988** [comment]
@Mark-Fenng @Yuyz0112 
这个Demo可以复现
https://github.com/bobjiang1988/rrweb-vconsole

**Comment by bobjiang1988** [comment]
Hi, all. 请教下, 有没有什么进展呢?

**Comment by Yuyz0112** [comment]
已经定位到问题，正在测试修复的方案

**Comment by Yuyz0112** [comment]
可以试一下 0.9.13，包含了这个修复

**Comment by z408550513** [comment]
@Yuyz0112 多谢. 测试过了好使
