### ISSUE TITLE
Programatically retrieve current url 

### ISSUE THREAD

**Issue by mariendev** [rrweb-io/rrweb#458]
The current URL is emitted with the MetaEvent in combination with the current dimensions. What I see in the code is that the dimensions are translated to resize events. But nothing is done with the URL. Is it possible to also retrieve this from the replayer?

**Comment by Mark-Fenng** [comment]
It's not supported yet and I'm not sure what we can do with the URL.  Maybe you can retrieve it from MetaEvent directly.

**Comment by mariendev** [comment]
I have figured it out. I use it to display current url of the user above the recording.

`replayer.on('event-cast', e => {
                if (e.type === 4) { //meta
                    setPlayerUrl(e.data.href);
                }
            });`
