### ISSUE TITLE
Call additional functions after playback ends [rrweb-player]

### ISSUE THREAD

**Issue by warely** [rrweb-io/rrweb#46]
When defining the configuration for the playback player rrwebPlayer, is there a way to trigger a function after playback ends?

For example, a function on finish, on pause, on start?

**Comment by Yuyz0112** [comment]
@warely Yes, the `rrweb.Replayer` has a public method `on`, which emit events.
https://github.com/rrweb-io/rrweb/blob/master/src/replay/index.ts#L79

The rrweb-player relies on it too. Is this what you are looking for? We can add this to document and re-export it in the `rrweb-replayer`.

**Comment by warely** [comment]
Yes, that would be great.  Being able to trigger additional events or listen to events of the playback.

**Comment by Yuyz0112** [comment]
added documents in https://github.com/rrweb-io/rrweb/commit/6abf4fd4a0d6c2dd052112e55f2a21156a16c84c
also exposed in rrweb-player via the `component.addEventListener` API

**Comment by Yuyz0112** [comment]
@warely use addEventListener like this:

```js
const component = new rrwebPlayer({
  target: document.body,
  data: {
    events,
  },
});
component.addEventListener('finish', () => console.log('finish'));
```
