### ISSUE TITLE
Uncaught TypeError: Cannot read property 'value' of null

### ISSUE THREAD

**Issue by macobo** [rrweb-io/rrweb#460]
Ran into an interesting case with the latest rrweb:

```
Uncaught TypeError: Cannot read property 'value' of null
    at MutationBuffer.emit (rrweb.js:1932)
    at MutationBuffer.processMutations (rrweb.js:1826)
    at MutationObserver.nrWrapper (design-projects:26)
```

How to reproduce:
1. Go to https://www.betabrand.com/design-projects, open chrome console
2. Paste into console" `var script = document.createElement('script'); script.type = 'text/javascript'; script.src = 'https://cdn.jsdelivr.net/npm/rrweb@latest/dist/rrweb.js'; document.head.appendChild(script); `
3. Paste into console: `rrweb.record({ emit: () => {} })`
4. Open navigation, go to Yoga Denim.
5. See uncaught errors in console

The site is using angular-js under the hood. 

I added some debugging code to the library, and I _think_ the suspicious element (that is later being read as null) is shown in the screenshot (1224), it matches with the index of addList element being null.

![2021-01-12_10-23](https://user-images.githubusercontent.com/148820/104288815-fc671480-54c0-11eb-9617-9b26a112c511.png)

**Comment by Yuyz0112** [comment]
I'll check this tonight.

**Comment by Yuyz0112** [comment]
@macobo I can reproduce this code with 0.9.12, and 0.9.13 looks have fixed this issue.

**Comment by macobo** [comment]
Thanks for taking a look. Took a couple of attempts, but could still reproduce with the same steps, though it took 2 tries navigating on-and-off the named page.

**Comment by Yuyz0112** [comment]
@macobo yes you are right, two tries reproduce it. Investigating again.

**Comment by Yuyz0112** [comment]
@macobo I think I've found the root cause. You can have a try on v0.9.14.
