### ISSUE TITLE
录制时，只产生events 一条数据，求解

### ISSUE THREAD

**Issue by sunlijun** [rrweb-io/rrweb#461]
开启录制后目前通过日志返回，0.6%的概率会只录制一条event 
{"type":4, "data": {"href":"https:xxxx"}}
目前尝试了好几种测试方式，还没有测试复现，其他开发者如有遇到，可以共同探讨下，多谢大家！~

**Comment by Yuyz0112** [comment]
可以检查一下是不是后端或者通信的问题，比如 nginx body size 限制了之类的
