### ISSUE TITLE
rrwebplayer  time

### ISSUE THREAD

**Issue by kuanghongliang** [rrweb-io/rrweb#462]
请问下有没有其他回调方法能拿到当前回放的时间？
看了文档，ui-update-current-time 方法在当前的版本中好像是不起作用的。
我的版本是  rrweb 0.7.33   rrweb-player 0.4.6
npm install也拉不到最新版

**Comment by Yuyz0112** [comment]
rrweb-player 最新的版本是 0.7.0， rrweb 最新版本是 0.9.14

有 lock file 的话 npm i 不会自动更新 major version，可以试试 `npm i rrweb rrweb-player`
