### ISSUE TITLE
node is null

### ISSUE THREAD

**Issue by lukesmurray** [rrweb-io/rrweb#463]
for some reason the node here is occasionally null, which triggers an error cannot read property 'value' of null. Is that expected? If so could it be handled so it doesn't cause an error?

https://github.com/rrweb-io/rrweb/blob/c712fc77a6fd6dfa25364beb4de795a8c391c924/src/record/mutation.ts#L282-L285

**Comment by Yuyz0112** [comment]
are you using rr-block to block some element？
and are you using the latest 0.9.13 version？

**Comment by lukesmurray** [comment]
I'm on the latest version and not using rrblock.

**Comment by Yuyz0112** [comment]
is there an URL to reproduce this？

**Comment by lukesmurray** [comment]
Unfortunately it is on a private project and the project is fairly large. I was able to determine that it is a [styled-component](https://styled-components.com/) which is causing the issue. I can close this issue since I don't have a straight forward way to give you a reproducible case.
