### ISSUE TITLE
rrweb.record Error

### ISSUE THREAD

**Issue by neckish** [rrweb-io/rrweb#47]
Hello.I'm getting this error in the console.
======================================
TypeError: Cannot read property '0' of undefined
    at rrweb-snapshot.js:55
    at String.replace (<anonymous>)
    at s (rrweb-snapshot.js:47)
    at u (rrweb-snapshot.js:163)
    at d (rrweb-snapshot.js:189)
    at d (rrweb-snapshot.js:209)
    at d (rrweb-snapshot.js:209)
    at d (rrweb-snapshot.js:209)
    at d (rrweb-snapshot.js:209)
    at f (rrweb-snapshot.js:220)
======================================
I use this code:
////=====CODE
var events = [];
rrweb.record({
  emit(event) {
    events.push(event);
  },
});    
////=====CODE

**Comment by Yuyz0112** [comment]
@neckish thanks for the reporting. Could you tell me which URL are you trying to record when facing this error?

**Comment by neckish** [comment]
> @neckish thanks for the reporting. Could you tell me which URL are you trying to record when facing this error?

Hi. I try to record https://www.kyp.mx/learning

**Comment by Yuyz0112** [comment]
@neckish I've recorded the login interactions and it looks ok, you can extract this HTML file in your browser to see it.
[replay_2019_01_23T04_25_40.zip](https://github.com/rrweb-io/rrweb/files/2785666/replay_2019_01_23T04_25_40.zip)

Could you provide more details about how did you meet the error?

**Comment by neckish** [comment]
> @neckish I've recorded the login interactions and it looks ok, you can extract this HTML file in your browser to see it.
> [replay_2019_01_23T04_25_40.zip](https://github.com/rrweb-io/rrweb/files/2785666/replay_2019_01_23T04_25_40.zip)
> 
> Could you provide more details about how did you meet the error?
Hi @Yuyz0112, i just add this code to my page: 

<script>
let events = [];

rrweb.record({
  emit(event) {
    // push event into the events array
    events.push(event);
  },
});

// this function will send events to the backend and reset the events array
function save() {
  const body = JSON.stringify({ events });
  events = [];
  fetch('https://YOUR_BACKEND_API', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body,
  });
}

// save events every 10 seconds
setInterval(save, 10 * 1000);
    
</script>
=========== And now im getting this:
<img width="996" alt="captura de pantalla 2019-01-23 a la s 10 27 17" src="https://user-images.githubusercontent.com/12134502/51621154-8646fd00-1ef9-11e9-9422-70f0760612ef.png">
<img width="518" alt="captura de pantalla 2019-01-23 a la s 10 27 34" src="https://user-images.githubusercontent.com/12134502/51621158-8810c080-1ef9-11e9-8e1c-78efbe724602.png">

**Comment by Yuyz0112** [comment]
fixed in https://github.com/rrweb-io/rrweb-snapshot/commit/c4c147649c2c6442497b8c0c127bccdd7f60f09e
@neckish you can have a try with latest `rrweb`.
