### ISSUE TITLE
Allowed memory size of ****** bytes exhausted

### ISSUE THREAD

**Issue by vincenzocasu** [rrweb-io/rrweb#472]
Hi everyone, I have json files as large as 300mb and over. When I try to open the file via the player, the server fails because it doesn't have enough memory.

Allowed memory size of 536870912 bytes exhausted (tried to allocate 269086928 bytes)

Is there a quick way to fix this?

**Comment by vincenzocasu** [comment]
maybe there is a way to optimize json file asynchronous loading ... right now I use this code:

```
<?php
$json = file_get_contents($file_name, false, stream_context_create($arrContextOptions));
?>

const data = [{ events: <?php echo $json; ?> }];

function player(data){
const events = data.reduce((prev, cur) => prev.concat(cur.events), []);

new rrwebPlayer({
target: document.body, // customizable root element
props: {
events
},
});
}

player(data);
```

can someone suggest me an alternative way to upload the json?

**Comment by Yuyz0112** [comment]
is this a PHP issue?

Does the events pagination recipe help? https://github.com/rrweb-io/rrweb/blob/master/docs/recipes/pagination.md

**Comment by vincenzocasu** [comment]
Yes, it is a PHP issue... I'm increasing memory limit, but the performances on loading alla events in one shot are very bad in case of largest JSON file...

I don't understand how load event by Ajax request... I have one JSON file... How I can use this recipe https://github.com/rrweb-io/rrweb/blob/master/docs/recipes/pagination.md in my contest?

Can you give me an example code?

**Comment by vincenzocasu** [comment]
what is the best way to record events and replay them, considering i use ajax and php?

I currently send an ajax request during registration to php, which appends the contents of the events of the last 10 seconds to the json file. During registration the page is ok, and there are no particular anomalies.
The json at the end of the session is about 200 / 300MB, but today it also reached 700MB ...

In the replay phase, I don't know how to read the events a little at a time and load the next ones dynamically without having to load all the internal JSON when loading the page.

**Comment by vincenzocasu** [comment]
@Yuyz0112 can you help me by sharing some examples code to use PHP as backend and Ajax request to load big json rrweb data file?

**Comment by Yuyz0112** [comment]
Sorry for the late, but the community currently does not have the capability to help debug backend issues that are not related to rrweb's core function.
