### ISSUE TITLE
When record method is called several times

### ISSUE THREAD

**Issue by MutelyMilo** [rrweb-io/rrweb#473]
In this case, multiple events are registered

exam：

`record({
            emit(event) {
                if (bool) return;
                console.log(event);
                _this.setState(() => ({
                    events: [..._this.state.events, event]
                }))
            }
        });`

**Comment by johnanthonyeletto** [comment]
@MutelyMilo Did you figure out what’s going on here? I think I’m running into something similar.

**Comment by Mark-Fenng** [comment]
> @MutelyMilo Did you figure out what’s going on here? I think I’m running into something similar. 

Have you turned on the switch for recording logs？
Cause in this case, console.log shouldn't be used in the emit function.
