### ISSUE TITLE
直播时鼠标停止，为避免计时器停止，如何延长finish事件监听时间

### ISSUE THREAD

**Issue by zhu956645239** [rrweb-io/rrweb#475]
![image](https://user-images.githubusercontent.com/38211259/106373740-8f57e800-63b7-11eb-8358-9c1a9eccfa9e.png)

**Comment by 18613109040** [comment]
你找到解决的方法了吗？

**Comment by Yuyz0112** [comment]
如果是 live mode 的场景，可以考虑定时发送 custom event，保持 replayer 活跃
