### ISSUE TITLE
The page refresh problem of live broadcast terminal during live broadcast

### ISSUE THREAD

**Issue by zhu956645239** [rrweb-io/rrweb#478]
Hello, great creator, now I have a problem, if during the live broadcast, the live broadcast side page refresh, all the elements of the page will be lost, because the Addevent is incremental, is there any way to solve this problem?

**Comment by Yuyz0112** [comment]
You can implement a re-connect like this
1. send a `START` signal from the 'guest' to the 'host' when the 'guest' loaded.
2. stop the current record and restart a new one when receiving the `START` signal on the 'host' page.

**Comment by zhu956645239** [comment]
Wow, that's great, but how do you restart a recorded event? Can you give me a hint, is there an API that I can call directly?

**Comment by Yuyz0112** [comment]
https://github.com/rrweb-io/rrweb/blob/master/docs/recipes/record-and-replay.md

The record function return a stop function handler, so you can stop the current record and start a new one.
