### ISSUE TITLE
[Firefox] Uncaught TypeError: s.blur is not a function

### ISSUE THREAD

**Issue by Sh1d0w** [rrweb-io/rrweb#48]
When playing replays recorded from Firefox I get the error in the title.

It is reproducible every time with the following steps:

1. Open a page and start recording
2. Loose the focus of the page for several seconds, e.g. switch the browser window with another application window, e.g. Mail, Sublime etc.
3. Regain the browser window focus and continue to interact with the page

After that when you replay the saved events, it will show the correct session length, however when the player reaches the place where the browser window looses the focus it will throw this error in the console and will stop to play.

Here are all json events recorded and used in the replay. The error occurs on 16th second.

https://pastebin.com/k6PGhPng

More info:

It happens only when the recording is done in Firefox. The same page recorded in other browsers does not break the player.

Firefox 64.0.2 on macOS 
Related issues: https://github.com/rrweb-io/rrweb/issues/13

**Comment by Yuyz0112** [comment]
@Sh1d0w Thanks for the events file and reproducible steps, I've found the root cause.
In the Firefox, switch to another tab or application will trigger a blur event which has an event target as HTMLDocument.
When trying to replay the interactions, rrweb will call `blur` on the target, but HTMLDocument does not have this method.

**Comment by Yuyz0112** [comment]
@Sh1d0w After the fix I can replay the whole session provided by you. Not gonna to release a new version ASAP, but you can bundle with the latest master branch get the fix.

**Comment by Sh1d0w** [comment]
@Yuyz0112 Wow that was very quick, thanks! Cheers
