### ISSUE TITLE
[feat.][Extensions] Not find related docs for recording request and response

### ISSUE THREAD

**Issue by GGAGloria** [rrweb-io/rrweb#480]
Hi, I found there is one part in readme mentioning that the recording of request and response is supported by extensions. But I did not find related documents or codes. Is this function still supported?

**Comment by Yuyz0112** [comment]
yep, the request recording is a WIP feature

**Comment by Yuyz0112** [comment]
We can use https://github.com/rrweb-io/rrweb/issues/552 to track this.
