### ISSUE TITLE
Is it possible to achieve bi-directional event synchronization in real-time live mode？

### ISSUE THREAD

**Issue by zhu956645239** [rrweb-io/rrweb#482]
Hello, excellent developer, may I ask you a question. In real-time live mode, the player is turned on replayer.enableInteract (); is bidirectional synchronization possible? In other words, the recording end can also be used as the playback end? 
Thank you very much！！

**Comment by Yuyz0112** [comment]
Is this the thing you are looking for? https://github.com/Yuyz0112/syncit

**Comment by zhu956645239** [comment]
Oh, thank you very much. Are Syncit and RRWeb compatible ？？

**Comment by Yuyz0112** [comment]
syncit is using rrweb under the hood

**Comment by zhu956645239** [comment]
Hello, I use the excellent API later found an error, https://github.com/Yuyz0112/syncit/blob/master/guide.md
 `
[Vue warn]: Error in v-on handler: "TypeError: Cannot read property 'Embed' of undefined"

found in

---> <Audience> at src/views/Audience.vue
       <App> at src/App.vue
         <Root>
warn @ vue.runtime.esm.js?2b0e:619
logError @ vue.runtime.esm.js?2b0e:1884
globalHandleError @ vue.runtime.esm.js?2b0e:1879
handleError @ vue.runtime.esm.js?2b0e:1839
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1862
invoker @ vue.runtime.esm.js?2b0e:2179
original._wrapper @ vue.runtime.esm.js?2b0e:6917
vue.runtime.esm.js?2b0e:1888 TypeError: Cannot read property 'Embed' of undefined
    at VueComponent.openAssist (Audience.vue?d8ff:154)
    at invokeWithErrorHandling (vue.runtime.esm.js?2b0e:1854)
    at HTMLButtonElement.invoker (vue.runtime.esm.js?2b0e:2179)
    at HTMLButtonElement.original._wrapper (vue.runtime.esm.js?2b0e:6917)`

**Comment by Yuyz0112** [comment]
syncit issue can go to its own repo.
