### ISSUE TITLE
the Syncit API can be unstable

### ISSUE THREAD

**Issue by zhu956645239** [rrweb-io/rrweb#484]
Hello, the Syncit API can be unstable, as Readme.md said
Currently, Syncit is at an early development stage. During this stage, API could be changed frequently.
but I wondered if TogetherJS could be used in conjunction with RRWeb ?

**Comment by startupgurukul** [comment]
Why togetherjs. Is it for audio ? 

you can use webrtc for that, 
here is a lib that simplifies using webrtc https://github.com/feross/simple-peer

**Comment by Yuyz0112** [comment]
syncit is just an experimental project to show the concept of live mode in rrweb.

I believe TogetherJS has a fundamentally different design than syncit.

There are no master-slave roles in TogetherJS, all the users visit **real** websites and only send interaction events to others.
And for syncit, there is only one master role in visiting the real website, others are just viewing a mirror of the website which is static.
