### ISSUE TITLE
Uncaught TypeError: Cannot read property 'value' of null

### ISSUE THREAD

**Issue by gertqin** [rrweb-io/rrweb#491]
This seems to be the same as #460 but we still experience the error in 0.9.14.
![Screenshot 2021-02-16 201543](https://user-images.githubusercontent.com/17803278/108112943-1c2cc200-7097-11eb-866e-f62da1a0740f.png)

I've tried to reproduce the error in a small example app, but unfortunately I couldn't :( (and I cannot share our real app). Then I tried to debug what caused the problem, and so far I've discovered that before the error occurs, a node is added to the DoubleLinkedList which has a sibling with the ```__ln``` property, but the linked list is empty (i.e. head is null).

![Screenshot 2021-02-16 203726](https://user-images.githubusercontent.com/17803278/108113243-90fffc00-7097-11eb-89ae-20e949109ef3.png)

I don't know how that can happen - my only guess is that somehow the DOM reuses a node added in an earlier processMutation cycle. Can you guess what is happening from these screenshots? Or can you tell me what else you would like me to debug, in order to find the cause of the problem?

**Comment by guillaume-ro-fr** [comment]
I have the same problem with Angular and ng-select when the selector was empty and a selection is made.

**Comment by Yuyz0112** [comment]
@guillaume-ro-fr Do you have any reproducible code or URL?

**Comment by jeffxenog** [comment]
当遇到想要在头部前插入一个节点的时候，下面的代码会造成head指针不正确，current是null
https://github.com/rrweb-io/rrweb/blob/e5587435a0900661ea240ac0fc66d8d4e88ed638/src/record/mutation.ts#L65
https://github.com/rrweb-io/rrweb/blob/e5587435a0900661ea240ac0fc66d8d4e88ed638/src/record/mutation.ts#L66


是否应该要增加判断`n.nextSibling.__ln.previous`存在
```
else if (n.nextSibling && isNodeInLinkedList(n.nextSibling) && n.nextSibling.__ln.previous ) {
```

**Comment by Yuyz0112** [comment]
@jeffxenog 是的，这里看起来是有问题的，感谢！

**Comment by PeterChen1997** [comment]
@Yuyz0112 hi大佬，想请问下可以发个 release 吗
