### ISSUE TITLE
How does RRWeb achieve two-way live streaming？

### ISSUE THREAD

**Issue by zhu956645239** [rrweb-io/rrweb#498]
Can I just use RRWeb for bidirectional control without Syncit

**Comment by zhu956645239** [comment]
Or is there such a tool in the industry that can realize live broadcast and live broadcast？

**Comment by zhu956645239** [comment]
In other words, after the content of the live broadcast player is modified, can it be returned to the recording side?

**Comment by provinceinnovation** [comment]
Yes, this is possible using rrweb. Take a look at https://github.com/Yuyz0112/syncit for a good starting point.
