### ISSUE TITLE
use rr-block classname but still record event

### ISSUE THREAD

**Issue by FeSeason** [rrweb-io/rrweb#499]
![image](https://user-images.githubusercontent.com/12840843/108584473-c436d980-737c-11eb-806d-c561b1fab229.png)

### Case

For the image as a case，

### Package Version
`https://cdn.jsdelivr.net/npm/rrweb@latest/dist/rrweb.js`

### Question & Reappearance

1、use default className  rr-block want to prevent record event for the img element，but it exist in record event

2、in replay page, don`t want show the img elemeng, buit it is appear in the iframe widthout image src

### Summary

blockClass not working properly！

**Comment by Tang-jianchao** [comment]
this question is ressovled?
