### ISSUE TITLE
Deciphering Event Types

### ISSUE THREAD

**Issue by warely** [rrweb-io/rrweb#50]
So I'm wondering if there is documentation breaking down the types of events logged in by the recorder.  For example - some cool features of fullstory that would be good to have include some variables that could be determined by the event history:

- User active time
- User inactive time
- Session length
- Number of clicks and where (heatmaps & rage clicks)
- Portion of the page viewed (total page height minus scrolled area)

I see a few types of events (type 2, 3, 4, etc) but it's hard to understand which events are which, and how to extract information like that from the recorded events.

Any ideas?

**Comment by Yuyz0112** [comment]
Good question! And I would like to answer it in two aspects.

First are some of the features you have mentioned may rely on backend analysis implementations for better performance, but it also could be done in pure client side. Anyway, these implementations will not happen in rrweb's repo very soon, but if someone is interesting to give a try I will be happy to help.

And the main question is what's the meaning of currently collected data, especially the `type` and `source` fields?
Actually, we are using typescript's enum feature to keep the collected data small but also be semantic in the code. For example, the `type` field is representing by the following enum:
```ts
enum EventType {
  DomContentLoaded,
  Load,
  FullSnapshot,
  IncrementalSnapshot,
  Meta,
}
```
So `type: 0` means DomContentLoaded, `type: 4` means Meta, etc. Definitely, we need a way or a tool to transform the collected data to a more readable way without referring to the enums manually. I think an online parsing tool is suitable for this.
I will start to do this later next week, you can also use the following snippets for a quick workaround.
```ts
import { EventType, eventWithTime, IncrementalSource } from '../src/types';

function format(event: eventWithTime) {
  const f: any = { ...event };
  f.type = EventType[f.type];
  if (event.type === EventType.IncrementalSnapshot) {
    f.data.source = IncrementalSource[event.data.source];
  }
  return f;
}
```

**Comment by warely** [comment]
I see!  I was planning on doing the data processing on the backend so it minimizes resources used by client side JavaScript.

For example, right now the recorder emits the event types and incrementally sends the events array back to my backend server, where a PHP file receives it and stores it.  Likely, I was thinking about parsing it via PHP and building an understandable event log.

Basically, if I understood or could find a glossary to match event types and their data to a more meaningful index, developers could then use the data received to calculate these.

**Comment by Yuyz0112** [comment]
Yeah, I’m not sure if there is a typescript parser in php, but since the enum is really simple and seldom been updated, maybe you can just maintain the mapping manually.
