### ISSUE TITLE
Masking all text

### ISSUE THREAD

**Issue by shadow1349** [rrweb-io/rrweb#502]
I have been searching around for a while and I haven't found anything about this. Is there a way to mask all text on the screen? For example, if we are accidentally displaying a user's PII as an H1 instead of in a field it will still show up. Is there any way to configure it to just mask all text?

**Comment by Yuyz0112** [comment]
Hi @shadow1349 

Currently, there is no such feature built-in. But I really like the idea of providing a "privacy by default" option.

**Comment by JohnPhamous** [comment]
@Yuyz0112 I am interested in building this. Do you have any thoughts on the implementation?

**Comment by Yuyz0112** [comment]
Thanks for the contribution from @re-fort!
