### ISSUE TITLE
Is there an emit event triggered in replay UI interaction?

### ISSUE THREAD

**Issue by FeSeason** [rrweb-io/rrweb#506]
Trying to build co-browsing feature

In real-time replay, 

want to deliver events to the initiator, is there any corresponding event monitoring available?

**Comment by Yuyz0112** [comment]
are these events work for your scenario?
https://github.com/rrweb-io/rrweb/blob/master/guide.md#events

**Comment by Yuyz0112** [comment]
Please feel free to re-open if there are still some problems with the current API.
