### ISSUE TITLE
Make recorder.takeFullSnapshot() public

### ISSUE THREAD

**Issue by dmakeev** [rrweb-io/rrweb#507]
Hello!

I need to force the recorder to make a full snapshot. The easiest way, as I see, is to make recorder's method takeFullSnapshot() public. Is it possible?

Thank you!

**Comment by tur-ing** [comment]
Could you do that @Yuyz0112? Would be very helpful

**Comment by Yuyz0112** [comment]
Thanks @dmakeev 

I've implemented this and looking for your feedback before shipping v1.0

**Comment by dmakeev** [comment]
@Yuyz0112 Great, thank you!

Could you push it to npm, please?
