### ISSUE TITLE
update the dimension of rrweb-replayer not exist 

### ISSUE THREAD

**Issue by joaqra** [rrweb-io/rrweb#512]
Can't find the $set API anymore in the latest version of rrweb-replayer
```
rrwebPlayer.$set({
  width: NEW_WIDTH,
  height: NEW_HEIGHT,
});
rrwebPlayer.triggerResize();
```

**Comment by Yuyz0112** [comment]
Hi @joaqra 

Is the API calls failed or it has no effect? I've tested the API in v0.7.0 and v0.7.1 and both APIs works. In v0.7.0 there is a CSS bug so the dimension may look strange, and it has been fixed in v0.7.1.
