### ISSUE TITLE
On blocked components, send the blocked class selector name through

### ISSUE THREAD

**Issue by brunoluiz** [rrweb-io/rrweb#513]
As a developer, I want to block a component using a class (eg: `.rr-block`) and then customise its place holder on the player. But, currently, while the recorder emits the component itself (empty, as it is blocked), it goes without the blocked selector attached to `class` (it contain all the other original classes though).

If rrweb emitted the blocked class as well, developers would be able to use `injectStyleRules` to customise the appearance of it.

**Comment by Yuyz0112** [comment]
Hi @brunoluiz 

Could you provide a Demo or URL that can reproduce this issue? From the integration tests, I think block class has been emitted the same as other class names: https://github.com/rrweb-io/rrweb/blob/master/test/__snapshots__/integration.test.ts.snap#L287

**Comment by Yuyz0112** [comment]
Please feel free to re-open if there are still some problems with the current API.
