### ISSUE TITLE
Blocked script execution

### ISSUE THREAD

**Issue by FeSeason** [rrweb-io/rrweb#514]
`
Blocked script execution in [URL] because the document's frame is sandboxed and the 'allow-scripts' permission is not set.
`

In replay mode

Chrome: 89.0.4389.82（正式版本） (x86_64)

Safari: 13.1.3

Chrome and Safari  all  have this problem in dev console.

**Comment by Yuyz0112** [comment]
This is an expected error since we are using the sandbox. Do you meet some problems during replay besides these error messages?

**Comment by FeSeason** [comment]
In replay mode using the sandbox and enableInteract;
,can not trigger some event (input, blur, change ... ) in listening iframe.

Only happen in replay client browers is safari (Safari: 13.1.3)， chrome is ok.

**Comment by Yuyz0112** [comment]
I think this is a WebKit bug: https://bugs.webkit.org/show_bug.cgi?id=218086

**Comment by joket1999** [comment]
The same error in Chrome(version 99.0.4844.51)
