### ISSUE TITLE
Whether rrweb can record WebGL content in canvas or not

### ISSUE THREAD

**Issue by Meowu** [rrweb-io/rrweb#521]
I have browsed some of the code, and only found the CanvasRenderingContext2D observer.

**Comment by Yuyz0112** [comment]
WebGL is not supported yet.

**Comment by ezewu** [comment]
我也测试了下，webgl贴图丢失，是否可以，只录制用户的操作，如滑动，点击来代替埋点统计,回放时不用iframe 真接在原url上面 进行操作回放
