### ISSUE TITLE
可以发一个 release 吗

### ISSUE THREAD

**Issue by PeterChen1997** [rrweb-io/rrweb#526]
https://github.com/rrweb-io/rrweb/issues/491

这个 issues 目前会让 ng 项目报错，从而暂停录制，不知可否发个新的 version 呢 @Yuyz0112

**Comment by Yuyz0112** [comment]
@PeterChen1997 现在在准备 1.0 版本，还需要比较多测试工作。需要的话可以 `npm i https://github.com/rrweb-io/rrweb.git` 的方式安装 master branch

**Comment by PeterChen1997** [comment]
好的，感谢
