### ISSUE TITLE
Regarding drag and drop events

### ISSUE THREAD

**Issue by iAmShakil** [rrweb-io/rrweb#530]
The `mousemove` event does not fire while the mouse is on drag mode. As a result, mouse positions during that time are not recorded. It can be listened to using a `dragover` event handler during that time.

Recording and playing drag and drop events will also be necessary in many cases. Any plan to implement them in the future?

**Comment by iAmShakil** [comment]
@Yuyz0112 your thoughts on this?

**Comment by Yuyz0112** [comment]
@iAmShakil 

I've done a simple test on drag and drop, and looks like it's emitting mouse move event. Could you provide a simple example for me to debug?

![image](https://user-images.githubusercontent.com/13651389/114158860-c1596d80-9957-11eb-8af6-16360950f382.png)

**Comment by Mark-Fenng** [comment]
@Yuyz0112 I think iAmShakil is saying that although mouse events can be recorded, rrweb still can't play drag over effects.
Here is my test case:
#### actual behaviour:

https://user-images.githubusercontent.com/27533910/114171742-4dbf5c80-9967-11eb-99aa-fe23f72d0604.mp4

#### replaying behaviour:

https://user-images.githubusercontent.com/27533910/114171836-692a6780-9967-11eb-9432-b681e6c572e7.mp4

**Comment by Yuyz0112** [comment]
@Mark-Fenng I'm not sure we can record the process of dragging since there is no DOM attribute changes during the process.

**Comment by iAmShakil** [comment]
@Yuyz0112 recording the mouse movement while dragging would be better than a static pointer IMO.
[Demo with the mouse positions not being recorded while dragging](https://cdpn.io/shakil_ahmed/debug/gOgowdo/PNrvYXxxgJZM)

[Demo with the mouse positions being recorded using the dragover handler](https://cdpn.io/shakil_ahmed/debug/xxgpEBV/mWAoNzZZBpBr)

**Comment by Yuyz0112** [comment]
@iAmShakil Thanks for the report, mouse event is not fired when an element has the native `draggable` attribute. I think using the `drag` event will help this.
