### ISSUE TITLE
n.getRootNode is not a function

### ISSUE THREAD

**Issue by PeterChen1997** [rrweb-io/rrweb#531]
![image](https://user-images.githubusercontent.com/21072589/113808479-abea1500-9798-11eb-960f-41c8eddec50e.png)

While in windows8 system, use wechat core broswer will occur this problem, please have a look~

**Comment by Yuyz0112** [comment]
Thanks for the report!

**Comment by PeterChen1997** [comment]
> Thanks for the report!

@Yuyz0112 想问问大佬，这个报错会导致回放不可用对吧，我这里先判断 UA 进行下初始化的过滤行不？

**Comment by Yuyz0112** [comment]
@PeterChen1997 你可以判断当前 runtime 是否有 getRootNode 这个放啊
