### ISSUE TITLE
关于页面iframe录制和pdf录制问题的疑问

### ISSUE THREAD

**Issue by xingtangren** [rrweb-io/rrweb#533]
您好，我在使用rrweb录制过程中遇到以下几个问题：
1、iframe里的内容录制不上，请问如何解决？需要加什么特殊配置吗？没找相关例子，我使用的版本是0.9.14。
2、pdf录制出来的events特别大，回放时会卡死，请问如何优化才能减小events的大小
3、部分页面录制会出现dom节点重复录制的问题，比如表单项有两个输入项，回访时变成了4个，查看保存的json里面的dom重复存储了。
以上三个问题比较棘手，无从下手，请教大神该如何解决？非常感谢！

**Comment by Yuyz0112** [comment]
1. master branch 有同源 iframe 的支持，可以安装 master branch 进行测试
2. 使用的是 pdfjs 的话，可以考虑转成图片。或者咨询 rrweb-pro http://www.myriptide.com/rrweb-community/
3. 可以提供 events 用于 debug？

**Comment by woshidahuaidan** [comment]
@xwLyc 您好，我也遇到了和您一样的问题，有同源和非同源的，我是把非同源的通过配置改为同源地址，也是录制不上，请问您有解决吗？期待您的回复

**Comment by LeeRayno** [comment]
iframe 同样的问题，可以播放时可以看到 iframe 的页面，但是 在iframe页面的操作录制不上
我是 a.baidu.com  嵌套 的 iframe 的域名是 b.baidu.com ，然后在c.baidu.com 上面播放
