### ISSUE TITLE
Separate FullSnapshot to smaller chunks

### ISSUE THREAD

**Issue by phuong** [rrweb-io/rrweb#534]
Thank you for make rrweb better day by day.

Based on the [document](https://github.com/rrweb-io/rrweb/blob/master/docs/serialization.md#uniquely-identifies), `FullSnapshot` record will be increase the size bigger and bigger. 

@Yuyz0112 @here is there any way to separate `FullSnapshot` into small chunks?

**Comment by ucjonathan** [comment]
Have you considered using the recipe to compress the events generated on the client side?

**Comment by phuong** [comment]
> Have you considered using the recipe to compress the events generated on the client side?

@ucjonathan I did tried with `compress-json`, but the size is still large

**Comment by Yuyz0112** [comment]
@phuong 

You can stringify the full snapshot `JSON.stringify(snapshot)` and split the string into multiple chunks

```js
function chunkSubstr(str, size) {
  const numChunks = Math.ceil(str.length / size)
  const chunks = new Array(numChunks)

  for (let i = 0, o = 0; i < numChunks; ++i, o += size) {
    chunks[i] = str.substr(o, size)
  }

  return chunks
}
```

**Comment by ucjonathan** [comment]
Have you looked at the packFn support in this recipe?

https://github.com/rrweb-io/rrweb/blob/master/docs/recipes/optimize-storage.md

**Comment by startupgurukul** [comment]
Can this help https://github.com/saltyrtc/chunked-dc-js
