### ISSUE TITLE
Seeking forward is causing error

### ISSUE THREAD

**Issue by goldy-13** [rrweb-io/rrweb#537]
Problem is in replayer.pause(number) function

DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
    at appendNode (http://localhost:3000/static/js/0.chunk.js:150185:16)
    at http://localhost:3000/static/js/0.chunk.js:150194:7
    at Array.forEach (<anonymous>)
    at Replayer.applyMutation (http://localhost:3000/static/js/0.chunk.js:150193:12)
    at Replayer.applyIncremental (http://localhost:3000/static/js/0.chunk.js:149790:16)
    at castFn (http://localhost:3000/static/js/0.chunk.js:149494:17)
    at wrappedCastFn (http://localhost:3000/static/js/0.chunk.js:149556:9)

**Comment by Yuyz0112** [comment]
@goldy-13 Could you provide the events for debugging?

**Comment by goldy-13** [comment]
> @goldy-13 Could you provide the events for debugging?

sure

**Comment by goldy-13** [comment]
@Yuyz0112 here is my events:

**Comment by Mark-Fenng** [comment]
@goldy-13 After debug, I find that there are some problems with your event data.
Normally, one node ID should map to a unique element but I find several nodes with the id 629. I suppose you have made some changes to the original event data.

**Comment by Yuyz0112** [comment]
> @goldy-13 After debug, I find that there are some problems with your event data.
> Normally, one node ID should map to a unique element but I find several nodes with the id 629. I suppose you have made some changes to the original event data.

maybe there is more than one record instance?

**Comment by Mark-Fenng** [comment]
I think so because I can find several different meta data events.
