### ISSUE TITLE
liveMode, In local dev mode，replay delay.

### ISSUE THREAD

**Issue by FeSeason** [rrweb-io/rrweb#538]
### Device

Record Client: Mobile (IOS / Android)

Replay Client: PC device

### Case Problem & Expect

Using the simplest local page development, there is a relatively large delay in liveMode, about 1-3 seconds, which is more obvious on Android devices and slightly better on iPhone.

The recording end has done data compression and other operations. Is there any other optimization method?

### Transport 

`websocket`

### Record & Replay Code

```js
# record

this.events = []

record({
  // sampling: {
  //   scroll: 300, // 每 150ms 最多触发一次
  // },
  emit(event: any) {
    this.filterEvent(event);
  },
  blockClass: BLOCK_CLASS,
  ignoreClass: IGNORE_CLASS,
  packFn: pack,
  // packFn: this.isDebug ? undefined : pack,
});



# replayer

if (!this.player) {
  this.player = new Replayer(events, {
    unpackFn: unpack,
    liveMode: true,
    root: this.replayContainerEle,
    pauseAnimation: false,
    UNSAFE_replayCanvas: true,
    // loadTimeout: 100,
    // showWarning: true,
    // showDebug: true,
    mouseTail: false,
  });
  this.player.startLive(events[0].timestamp - 0);
}

events.map((event: any) => this.player.addEvent(event));

```

**Comment by Yuyz0112** [comment]
Could you describe the amount of delay you are experiencing? 

For example, the time range between send and receive on each websock client.
