### ISSUE TITLE
stacks切割方式直接使用‘at’字符串会误切一些字符串

### ISSUE THREAD

**Issue by theFrontCalf** [rrweb-io/rrweb#542]
function parseStack(
    stack: string | undefined,
    omitDepth: number = 1,
  ): string[] {
    let stacks: string[] = [];
    if (stack) {
      stacks = stack
        .split('at')
        .splice(1 + omitDepth)
        .map((s) => s.trim());
    }
    return stacks;
  }
  如：'aa/operation/page/index.js' 会被切割成两个路径
是不是应该使用...split('at ')... 后面多加个空格来解决？

**Comment by Yuyz0112** [comment]
@Mark-Fenng logger parser 可能还需要更多测试？

**Comment by Mark-Fenng** [comment]
好的，我会增加更多单元测试
