### ISSUE TITLE
录制canvas后，回放卡顿

### ISSUE THREAD

**Issue by SGAMERyu** [rrweb-io/rrweb#543]
1. 录制19秒钟，等到的events数组长度为26万个左右
2. 当全量使用events，会导致addActions 报出RangeError，应该是传递events数量太大，导致apply参数超出
3. 当只截取10w条数据时能进行播放，但是播放会有卡顿，并且无法完全播放完全，4秒钟的时间，只播放了2秒钟

**Comment by RobertM574** [comment]
有同样的问题~求解

**Comment by Yuyz0112** [comment]
canvas 的内容大概是什么呢？

**Comment by SGAMERyu** [comment]
> canvas的内容大概是什么呢？

主要是这类折线图的类似数据，具体内容因为是内部项目，不太容易能放出来
![image](https://user-images.githubusercontent.com/17926105/115339424-59b4e500-a1d7-11eb-9d28-005a49a9a33d.png)

**Comment by SGAMERyu** [comment]
> canvas 的内容大概是什么呢？

使用最新的master分支，参数溢出的错误解决了，但是回放19秒的数据还是会卡顿，是否是录制那块也需要使用最新master的代码，录制方面是有针对canvas有进行特殊的优化吗？

**Comment by RobertM574** [comment]
> canvas 的内容大概是什么呢？
有1.0的changelog可以看么？我发现用master分支打包后有一定的优化 1.0在canvas这里做了什么优化吗

**Comment by Yuyz0112** [comment]
参数溢出的问题在最新的 master 上由解决。

目前录制 canvas 的方式是劫持了 canvas context 的所有 API，这个方式在很多场景下效率不高。如果对录制 canvas 有强需求，可以考虑使用 custom events 实现自定义的逻辑回放。

例如 canvas 在被录制侧的业务含义是`绘制图像 A`，这个操作对应 1000 个 canvas context 调用，那么可以不录制 canvas，而是在`绘制图像 A`时调用 custom event，记录下这次绘制事件。

再在回放时监听 custom event，遇到对应的事件就调用同样的 canvas 逻辑，执行 `绘制图像 A`。

总的来说需要一定的二次开发。

**Comment by SGAMERyu** [comment]
> 参数溢出的问题在最新的 master 上由解决。
> 
> 目前录制 canvas 的方式是劫持了 canvas context 的所有 API，这个方式在很多场景下效率不高。如果对录制 canvas 有强需求，可以考虑使用 custom events 实现自定义的逻辑回放。
> 
> 例如 canvas 在被录制侧的业务含义是`绘制图像 A`，这个操作对应 1000 个 canvas context 调用，那么可以不录制 canvas，而是在`绘制图像 A`时调用 custom event，记录下这次绘制事件。
> 
> 再在回放时监听 custom event，遇到对应的事件就调用同样的 canvas 逻辑，执行 `绘制图像 A`。
> 
> 总的来说需要一定的二次开发。

感谢您的回复，我还有一些疑问，例如在回放时监听custom event这个事件，来执行canvas的操作，是指对回放中的iframe里面的canvas进行操作吗？还是说在回放界面中的把呈现canvas的元素换成图像
