### ISSUE TITLE
支持多个快照文件合并为一个回放视图吗

### ISSUE THREAD

**Issue by Wilson-hu** [rrweb-io/rrweb#544]
我这边通过录制页面所有的iframe，然后想要把这些数据组装成一个完整的页面

相当于正常访问，是页面+页面上不同源的iframe，
录制的，把页面和iframe都单独录制下来，有各自的events，
我想把这两个events结合起来，回放的时候和正常访问是一样的，能实现吗

**Comment by Yuyz0112** [comment]
是 cross-origin iframe 场景计划提供的功能，目前还没有方案，自己实现可能会比较复杂。

**Comment by Wilson-hu** [comment]
@Yuyz0112 cross-origin iframe 这一块目前遇到的难点是什么呢？

**Comment by Mark-Fenng** [comment]
@Wilson-hu 不同的events结合起来难度主要在于两个events的node id会发生冲突，导致很多的错误发生

**Comment by Juice10** [comment]
Check out this PR for cross origin iframe support: https://github.com/rrweb-io/rrweb/pull/1035
