### ISSUE TITLE
Pause Any Media Playing after the recorded session finished

### ISSUE THREAD

**Issue by rifaideen** [rrweb-io/rrweb#545]
It would be great if the re-player stops any media playbacks after the recorded session finished its replay.

Right now, the video is continuously playing even after the player finished it's playback.

@Yuyz0112 Please check and let me know if this already implemented in the latest releases.

**Comment by Yuyz0112** [comment]
This has not been implemented.

And I believe the replay should try its best to reproduce the session. If one recording a session where he plays media at 00:05 and ends the session at 00:10 without pause, maybe we'd best do not pause the media either.

**Comment by lazyvab** [comment]
@Yuyz0112 @Juice10 Any solution or workaround for this yet?
