### ISSUE TITLE
iframe引用pdfjs文件的路径，播放报错

### ISSUE THREAD

**Issue by mikeyreilin** [rrweb-io/rrweb#546]
页面中有iframe，iframe的url为pdfjs的viewer.html 页面，播放时会报错   Failed to execute 'appendChild' on 'Node': Can't insert a doctype before the root element. 还会出现pdf空白的情况。单纯录制iframe或者pdfjs都没问题，两个一结合就不行

![image](https://user-images.githubusercontent.com/26787043/115829540-b1568900-a441-11eb-8889-382f38e73819.png)

**Comment by Yuyz0112** [comment]
使用的是最新的 master 分支版本吗？

**Comment by mikeyreilin** [comment]
> 使用的是最新的 master 分支版本吗？

是的

**Comment by Mark-Fenng** [comment]
If there are any reproducible events to provide, feel free to reopen this issue anytime.
