### ISSUE TITLE
H5 page side scroll bar causes page to be compressed and style is misaligned

### ISSUE THREAD

**Issue by yuanyiying123** [rrweb-io/rrweb#554]
HTML 5页面滚动条样式用的是浏览器的滚动条的样式，导致页面大小被压缩，页面内容错位。

HTML 5 page scroll bar style is the browser's scroll bar style, resulting in page size is compressed, page content dislocation.

**Comment by Yuyz0112** [comment]
可以提供 events 用于 debug 吗？

**Comment by yuanyiying123** [comment]
http://oss-test.lysy90.com/myfiles/recordFile/2021/20210506/2021-05-06_10.15.02-670516-caadda43e559db64bbe87826554c931c.txt    
这个地址应该能访问到

**Comment by yuanyiying123** [comment]
网络不太好，回复的有点慢，请勿介意

**Comment by Yuyz0112** [comment]
@yuanyiying123 可能因为我是 mac 的电脑默认滚动条也是不占空间的，所以复现不出来这个问题。

能否帮忙：

1. 截图看一下错位的现象，是否是滚动条占据了一定的宽度。
2. 页面本身在移动端的时候是否有通过 CSS 定制滚动条样式？

**Comment by Yuyz0112** [comment]
![image](https://user-images.githubusercontent.com/13651389/117566326-a90c7800-b0e8-11eb-82a1-2121776777db.png)

我通过定制 scrollbar CSS 可以复现这个问题。

如果不是出现移动端定制了 CSS 样式，但是在回放端查看时没有的问题，那现象应该是符合预期的。

如果希望在回放端模拟没有滚动条不占位的样式，可以通过 `insertStyleRules` 的配置向回放内部注入 CSS，例如：

```js
var player = new rrweb.Replayer(events, {
      insertStyleRules: [
        `
        *::-webkit-scrollbar {
          width: 0;
        }
        `,
      ],
    });
```

**Comment by yuanyiying123** [comment]
大佬辛苦了，没带电脑 我明天去公司看看能否解决。感谢



---Original---
From: ***@***.***&gt;
Date: Sun, May 9, 2021 16:59 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [rrweb-io/rrweb] H5 page side scroll bar causes page to be compressed and style is misaligned (#554)




 
@yuanyiying123 可能因为我是 mac 的电脑默认滚动条也是不占空间的，所以复现不出来这个问题。
 
能否帮忙：
  
截图看一下错位的现象，是否是滚动条占据了一定的宽度。 

页面本身在移动端的时候是否有通过 CSS 定制滚动条样式？
