### ISSUE TITLE
为什么要做错误、日志、网络请求劫持？？？

### ISSUE THREAD

**Issue by RobertM574** [rrweb-io/rrweb#557]
本身rrweb是一个很好的录屏软件，但是加上错误、日志、网络请求劫持让我觉得他的功能变得越来越臃肿且不可控，关于劫持这块，要考虑的东西太多（重复错误过滤，上报时机控制，自定义错误配置等等），我们在对页面监控的时候可以用sentry或自研的错误监控工具，rrweb做的事情变得使录屏这件事不再专一了，这让人很失望，希望慎重考虑这个功能，不要让sdk变得越来越杂乱

**Comment by Yuyz0112** [comment]
感谢反馈。

rrweb 会按照 core runtime 和 plugin runtime 来划分运行时代码的内容，依据是
1. core runtime 只包含会对 `视图` 产生影响的录制和回放
2. plugin runtime 可以按需录制回放 web 中发生的其它事件

所以错误、日志、网络请求这些常见需求，以及用户行为聚合、PDF 场景等特殊需求都会以 plugin runtime 的形式提供，在代码上和 core runtime 相互独立。

plugin runtime 的需求来源于社区以及构建在 rrweb 之上的很多商业化产品。

这也是为什么对于异常、网络请求的录制的需求已经提出一年以上，但是还没有实现的原因。

目前唯一在 core runtime 里的 plugin 代码是日志的录制，这部分因为 plugin 框架的设计还没有稳定，所以当时实现在了 core runtime 里，但是默认也是关闭的。

plugin 框架的设计、实现，以及日志的录制从 core runtime 移至 plugin runtime 都会是接下来要发布的 1.0 必备 patch。

**Comment by RobertM574** [comment]
> 感谢反馈。
> 
> rrweb 会按照 core runtime 和 plugin runtime 来划分运行时代码的内容，依据是
> 
> 1. core runtime 只包含会对 `视图` 产生影响的录制和回放
> 2. plugin runtime 可以按需录制回放 web 中发生的其它事件
> 
> 所以错误、日志、网络请求这些常见需求，以及用户行为聚合、PDF 场景等特殊需求都会以 plugin runtime 的形式提供，在代码上和 core runtime 相互独立。
> 
> plugin runtime 的需求来源于社区以及构建在 rrweb 之上的很多商业化产品。
> 
> 这也是为什么对于异常、网络请求的录制的需求已经提出一年以上，但是还没有实现的原因。
> 
> 目前唯一在 core runtime 里的 plugin 代码是日志的录制，这部分因为 plugin 框架的设计还没有稳定，所以当时实现在了 core runtime 里，但是默认也是关闭的。
> 
> plugin 框架的设计、实现，以及日志的录制从 core runtime 移至 plugin runtime 都会是接下来要发布的 1.0 必备 patch。



> 感谢反馈。
> 
> rrweb 会按照 core runtime 和 plugin runtime 来划分运行时代码的内容，依据是
> 
> 1. core runtime 只包含会对 `视图` 产生影响的录制和回放
> 2. plugin runtime 可以按需录制回放 web 中发生的其它事件
> 
> 所以错误、日志、网络请求这些常见需求，以及用户行为聚合、PDF 场景等特殊需求都会以 plugin runtime 的形式提供，在代码上和 core runtime 相互独立。
> 
> plugin runtime 的需求来源于社区以及构建在 rrweb 之上的很多商业化产品。
> 
> 这也是为什么对于异常、网络请求的录制的需求已经提出一年以上，但是还没有实现的原因。
> 
> 目前唯一在 core runtime 里的 plugin 代码是日志的录制，这部分因为 plugin 框架的设计还没有稳定，所以当时实现在了 core runtime 里，但是默认也是关闭的。
> 
> plugin 框架的设计、实现，以及日志的录制从 core runtime 移至 plugin runtime 都会是接下来要发布的 1.0 必备 patch。

感谢回复。
作为一个开源项目，商业化产品是有必要的。希望越做越好，尽快发布1.0。
