### ISSUE TITLE
Sentry integration is not working. No Replay section on sentry dashboard

### ISSUE THREAD

**Issue by andrei10k** [rrweb-io/rrweb#559]
repost from here: https://github.com/getsentry/sentry-rrweb/issues/36

// package.json
"@sentry/browser": "^6.3.4",
"@sentry/rrweb": "^0.3.1",
"rrweb": "^0.9.14"

// index.js
import { SENTRY_CONFIG } from './config'
import * as Sentry from '@sentry/browser'

if (process.env.NODE_ENV === 'production') {
Sentry.init(SENTRY_CONFIG)
}

// config.js
import SentryRRWeb from '@sentry/rrweb'

export const SENTRY_CONFIG = {
dsn: '********',
integrations: [new SentryRRWeb()]
}

I'm using react and webpack 5. Doesn't appear to do anything. There is no Replay section on sentry dashboard. Am I doing something wrong?

In sentry i see this issue: 

![](https://user-images.githubusercontent.com/14038494/118523789-29188a80-b746-11eb-817d-437a82eda46b.png)

**Comment by Yuyz0112** [comment]
I think we have the [fix](https://github.com/rrweb-io/rrweb/issues/528) in the master branch. Going to release v1.0 ASAP.

**Comment by andrei10k** [comment]
When will v1 be releases?

**Comment by Yana5417** [comment]
How is it going? Has it been published?
