### ISSUE TITLE
rrwebplayer如何放慢播放

### ISSUE THREAD

**Issue by zhaoxm2016** [rrweb-io/rrweb#561]
在生产环境上采集到的数据时间戳好像有问题，导致播放时快放，现在想通过speed控制慢放，但是好像不起作用，请教一下。
@Yuyz0112

**Comment by Mark-Fenng** [comment]
@zhaoxm2016 使用rrweb-player的话，可以参考[文档](https://github.com/rrweb-io/rrweb/blob/master/guide.zh_CN.md)
![image](https://user-images.githubusercontent.com/27533910/118909460-9fd7a280-b955-11eb-983e-e7e3b74bed25.png)

**Comment by zhaoxm2016** [comment]
![F1F82B6F-0F3B-4DB0-9F4B-2AFE85D5155E](https://user-images.githubusercontent.com/51771541/118911040-15447280-b958-11eb-80a2-e4a7d0ac23c9.png)
通过这里的speed控制不起作用，想慢放

**Comment by zhaoxm2016** [comment]
@Mark-Fenng

**Comment by zhaoxm2016** [comment]
或者说这个speed取值范围

**Comment by Mark-Fenng** [comment]
@zhaoxm2016  也可以试试player.setSpeed()方法，取值范围应该是(0, infinity)

**Comment by Yuyz0112** [comment]
@zhaoxm2016 可以看一下你的代码示例吗？

https://github.com/rrweb-io/rrweb/blob/master/docs/recipes/customize-replayer.zh_CN.md
这里有 setSpeed 的示例

**Comment by zhaoxm2016** [comment]
const replayer = new rrweb.Replayer(events,{root:rrwebRef.current,unpackFn: unpack,skipInactive:true,mouseTail:false,UNSAFE_replayCanvas: true,speed:0.5});
			replayer.play();

**Comment by Yuyz0112** [comment]
@zhaoxm2016 对应的配置我在本地看起来是生效的。你观察不起作用的方式是什么？

**Comment by Yuyz0112** [comment]
如果有更多信息可以 reopen

**Comment by zhaoxm2016** [comment]
@Mark-Fenng @Yuyz0112 生产环境录制的数据一部分数据录制的回放是快放状态，一部分是正常的，可能是由于业务逻辑导致的，现在是想对快放的数据希望能够进行慢放
我现在使用的回放是const replayer = new rrweb.Replayer（）创建的，通过options传入speed:0.1感觉没起到作用，看看大佬们有什么方法先帮忙把这个问题临时解决一下
