### ISSUE TITLE
can not record canvas(无法录制canvas)

### ISSUE THREAD

**Issue by raintygao** [rrweb-io/rrweb#562]
Hello, since i run "yarn repl" and input url:https://sf-tk-sg.ibytedtos.com/obj/union-fe-sg/playable/799c1aa20f9103b39126ac4b3bb1a266/index.html. When i stop and replay, i can"t see the canvas content.
Please have a look.thanks🙏

**Comment by raintygao** [comment]
@Mark-Fenng 又看了下文档 应该是支持录制和回放canvas内容的 不知道这是不是个问题😂

**Comment by Yuyz0112** [comment]
不太确定 cocos 是怎么使用 canvas 的，但是看起来没有被 rrweb 劫持。像图像很多的 canvas 场景不建议用 rrweb 录制，rrweb 的 canvas 也是实验性功能，无法保证安全性和正确性。
