### ISSUE TITLE
Stream replay

### ISSUE THREAD

**Issue by jetdream** [rrweb-io/rrweb#564]
Is there a way to play events from real time stream coming from a recorder?
Currently I have to pass an array of events to the player.

This is useful case for support service to see what user is doing in real time and record for training purposes.

**Comment by Juice10** [comment]
@jetdream you can also add the events by calling `replayer.addEvent(event)`
You have to set the player in streaming mode to be able to do that though. Here is some more documentation on the subject: https://github.com/rrweb-io/rrweb/blob/df455c483a294addedd1e325e5e2c534bf0e6013/docs/recipes/live-mode.md

**Comment by Yuyz0112** [comment]
Yes, @Juice10 already helps point to the right recipe.
