### ISSUE TITLE
Expose mirror 

### ISSUE THREAD

**Issue by Juice10** [rrweb-io/rrweb#565]
PR #407 changes the way accessing the mirror works. Using `import { mirror } from 'rrweb'` to access the mirror doesn't work anymore. This breaks [getMirror() on the rrweb player](https://github.com/rrweb-io/rrweb-player/blob/34588c451b12493d8167aa3d726292b748c55743/src/Player.svelte#L3-L25).

### Proposed solution A:
Maybe we can expose the mirror by also adding a `getMirror()` method on the rrweb replayer to re-enable this behaviour.

### Proposed solution B:
Alternatively we can make the mirror attribute `public` on the replayer instead of `private`:
https://github.com/rrweb-io/rrweb/blob/0f86a72705b998a9abf5b4aae5b01a4f3b679954/src/replay/index.ts#L124

**Comment by Yuyz0112** [comment]
@Juice10 Thanks for the report.

I merge this PR because it's a breaking change and will be released in v1.0.

For general usage, I think solution B is good enough. And I'm also thinking about adding some warning if someone is using `import { mirror } from 'rrweb'`, do you have any ideas about this?

**Comment by Juice10** [comment]
@Yuyz0112 thats a great idea! I'm not sure if you are planning any pre-1.0 releases at the moment but if you are, we could maybe add a deprecation message to the "old" way of including `mirror` to help people migrate over. And otherwise just adding in an error message that points people to this issue (or something else that explains how to solve their problem) should work too.

**Comment by Yuyz0112** [comment]
@Juice10 Please let me know whether the latest commit works.

**Comment by Juice10** [comment]
@Yuyz0112 commit looks great! Let me verify this works with production code, I'll update here. In the meantime I added an issue to rrweb-player so we don't forget: https://github.com/rrweb-io/rrweb-player/issues/69
