### ISSUE TITLE
Make player responsive

### ISSUE THREAD

**Issue by warely** [rrweb-io/rrweb#57]
Is there a way to make the replayer module responsive?  Right now, it expands to a set size no matter what the size of the parent container.

**Comment by Yuyz0112** [comment]
Maybe get parent container's dimension and set to the replayer is the easiest way to do that now.

**Comment by remisharrock** [comment]
I have used the css scale to "shrink" the target div player (just modify the ratio), like this:
```
.shrink{
    --ratio: 0.7;
    -webkit-transform:scale(var(--ratio));
    -moz-transform:scale(var(--ratio));
    -ms-transform:scale(var(--ratio));
    transform:scale(var(--ratio));
   }
```
But for sure there might be better solutions

**Comment by Yuyz0112** [comment]
Looks like the scale solution works.

**Comment by johannbuscail** [comment]
Any update on this ?

**Comment by Rice-Tech** [comment]
I replaced the annoying fixed pixel dimensions within a React useEffect hook with the viewport width as the dependency in and was able to get it to resize according to viewport width nicely.
``` 
useEffect(() => {
    document
      .querySelector(".rr-player")
      ?.setAttribute("style", "width:75vw; height:45vw;");
    document
      .querySelector(".rr-player__frame")
      ?.setAttribute("style", "width:75vw;height:45vw;");
    document
      .querySelector(".replayer-wrapper")
      ?.setAttribute(
        "style",
        `transform: scale(${(width * 0.75) / 1920}) translate(-50%,-50%);`
      );
  }, [width]);
```
