### ISSUE TITLE
REPL does not with with sites that open a new tab

### ISSUE THREAD

**Issue by sushil-relicx** [rrweb-io/rrweb#571]
Try recording the flow starting with https://onedrive.live..com. This redirects browser to https://www.microsoft.com/en-us/microsoft-365/onedrive/online-cloud-storage. 

Click on the sign in button which open a new tab. Any interaction on the new tab is not captured by REPL

**Comment by Mark-Fenng** [comment]
No plan to implement this case. This work can be done in https://github.com/rrweb-io/rrweb-chrome-extension/pull/2
