### ISSUE TITLE
Replayed nodes don't inherit event listeners from original nodes. 

### ISSUE THREAD

**Issue by bachmanity1** [rrweb-io/rrweb#576]
I noticed that nodes generated during the replay don't have event listeners of original nodes. So for example if the original node had some behavior(like sound) associated with `click` event, this behavior is not replicated in the replayed node when `click` event is triggered. Is it possible to solve this problem?

**Comment by bachmanity1** [comment]
After digging into the code I think that this issue may be related to the fact that  `rrweb` blocks scripts in the replayed page. Maybe you could add an option to manually enable scripts? Because disabling scripts leads to inconsistent replay of pages containing interactive content such as [H5P iframes](https://h5p.org/).

**Comment by Yuyz0112** [comment]
H5P iframes looks like a very interesting thing and rrweb may have the chance to support recording it without executing JS. I think this is an issue related to our media events recording.

I'll do some tests with https://h5p.org/interactive-video
