### ISSUE TITLE
Using rrweb on sites with/behind authentication

### ISSUE THREAD

**Issue by bernhardh** [rrweb-io/rrweb#577]
Is it possible to use rrrweb with sites with authentication? I am trying to track a user process including registration to my page. But of course the replay doesn't work as expected. Is there a way to record this?

**Comment by Yuyz0112** [comment]
rrweb should not be restricted by any business logic because it simply records DOM mutations. Could you share the events for debugging?

**Comment by bernhardh** [comment]
Hmm. Maybe there is another problem, which hasn't to do with authentication. I see a lot of "null" on recorded events on a testpage.

Please find attached the events json.

[test.zip](https://github.com/rrweb-io/rrweb/files/6623170/test.zip)

This was recorded on a test page http://test.bmdev.at/rr-recorder/example.html (which stores the visit into my database. The relevant code for recording is at the bottom of the sourcecode:

```
<script src="https://cdn.jsdelivr.net/npm/rrweb@latest/dist/record/rrweb-record.min.js"></script>
<script src="https://webrecorder.bmdev.at/js/webrecorder/webrecorder-recorder.js"></script>
<script>
    WebRecorder.init('https://webrecorder.bmdev.at')
</script>
```

**Comment by bernhardh** [comment]
@Yuyz0112 Did you have a chance to have a look at the problem?

**Comment by Mark-Fenng** [comment]
@bernhardh I don't know how this phenomenon happens, but you can just replace all null in your events with blank string `""`.

**Comment by Yuyz0112** [comment]
@bernhardh 
I think the issue may happen when there is serialization progress in your backend that turns undefined to null in JSON.

**Comment by bernhardh** [comment]
Maybe. I am using the build in `json_encode` method in php. As you suggested, I am now removing the nulls with `""`
