### ISSUE TITLE
在回放时，会出现重复渲染相同DOM的情况。

### ISSUE THREAD

**Issue by Huhui-coder** [rrweb-io/rrweb#579]
重复渲染的DOM为 在dom 渲染模式下的 xterm，并不是必现的，但是出现的概率有点高，十次能有八次。
请问如何该处理，

异常情况下为这种,
![image](https://user-images.githubusercontent.com/37322200/121313031-93cd7800-c938-11eb-86c1-c0a0d8a83a85.png)

正常情况下，是这种。
![image](https://user-images.githubusercontent.com/37322200/121313160-b2cc0a00-c938-11eb-9da4-4a2ea7bcc8bc.png)

**Comment by Yuyz0112** [comment]
是同一组 events，渲染的结果不同吗？还是不同的 events？

**Comment by Huhui-coder** [comment]
> 是同一组 events，渲染的结果不同吗？还是不同的 events？

是录制的时候，界面上是没有 重复的DOM 的， 但是 回放的时候，偶尔会出现 重复DOM 的情况。上面两个截图 是不同的 events , 应该是 录制的时候 ，上传的 events 是有问题的，导致回放的时候，出现了重复渲染的问题。我想请问下，有什么机制可以避免出现这种情况吗？ 我尝试给 包裹的 div 加过 id 属性， 但是 并没有生效。

**Comment by Yuyz0112** [comment]
需要 events 具体 debug

**Comment by Huhui-coder** [comment]
> 需要 events 具体 debug

好的，我提供给你。
http://q4k.cn/YRS6/JP


可以通过此链接进行下载。感谢。

**Comment by Yuyz0112** [comment]
@Huhui-coder 这个链接 not found

**Comment by Huhui-coder** [comment]
> @Huhui-coder 这个链接 not found

我直接发送到你的邮箱吧，请记得查收咯。文件名是 重复DOM渲染events.

**Comment by Huhui-coder** [comment]
> > @Huhui-coder 这个链接 not found
> 
> 我直接发送到你的邮箱吧，请记得查收咯。文件名是 重复DOM渲染events.

你好，还有在继续关注吗？ @Yuyz0112

**Comment by jb145161** [comment]
我也出现了相同的问题，作者给回复了吗

**Comment by Mark-Fenng** [comment]
This problem is happening case by case. If you are still facing the problem, please open a new issue with reproducible steps or events for debugging.
