### ISSUE TITLE
Missing styles in recording

### ISSUE THREAD

**Issue by Richard87** [rrweb-io/rrweb#58]
Hi!

First I want to say that this project is amazing to use, simple and fast to implement! :)

I have 2 react SPA, one is relativley straight forward, while the other is much more complex. The simple site works perfectly! :) 

But the slightly more complex site looks like this:
![image](https://user-images.githubusercontent.com/5749715/54261922-430a2180-456d-11e9-9a2d-8dab4acba439.png)

But in the records it looks like this instead:
![image](https://user-images.githubusercontent.com/5749715/54261952-53220100-456d-11e9-9b20-0ba8df7ba76d.png)

This site uses styled-components heavily, and the grey color comes from the default index.scss.

My code looks like this:
```js
const useRRWeb = () => {
    const [allow, setAllow] = useState(false)
    const eventsRef = useRef([])

    const allowRecording = () => setAllow(true)
    const getRandom = () => Math.random().toString(36).substring(7);
    import("rrweb").then(({record}) => {
        record({
            emit: (event) => {
                eventsRef.current.push(event)
            }
        })
    })
    useEffect(() => {
        if (!allow)
            return;

        const sessionId = getRandom() + getRandom() + getRandom();
        const save = () => {
            const events = eventsRef.current
            const body = JSON.stringify({events});
            eventsRef.current = [];

            fetch(getUrl(sessionId), {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body,
            }).catch(() => {
                eventsRef.current.unshift(events)
            });
        }
        const saveInterval = setInterval(save, 10 * 1000);

        record({
            emit: (event) => {
                eventsRef.current.push(event)
            }
        })

        return () => {
            clearInterval(saveInterval)
            save()
        }
    }, [allow])

    return [allow, allowRecording]
}
export default useRRWeb
```

Any ideas about where I should start to look?

**Comment by Yuyz0112** [comment]
@Richard87 This may be related to a known issue, are you using some CSS in JS library in that project?

**Comment by Richard87** [comment]
Hi! Yes, "styled-components" is a CSS-in-JS project, and is used heavily troughout...

**Comment by arliber** [comment]
Hi, having the same issue - have you been able to find a solution?

**Comment by r6047736** [comment]
I am facing the same issue on an Angular project. 
The first page didn't save the customized SCSS style: It saves the external CSS (in my case, I use Ant design for Angular), But I write my own SCSS style in the .scss file and it doesn't record the customized style. The problem only happened on the first page.
Does anyone have a clue that what causes the issue?

**Comment by jasan-s** [comment]
any solution yet?

**Comment by dacort** [comment]
I think #124 is a temporary workaround, but [discussion on that PR](https://github.com/rrweb-io/rrweb/pull/124#issuecomment-524686990) indicates there's more work to do.

**Comment by alexcroox** [comment]
Does anyone know the current status of this? The PR seemed to be progressing in that other repo but looked to be abandoned late December (changed from "in progress" to "ideas").

**Comment by alexcroox** [comment]
I've not had much luck in getting different results using Vue and:

"rrweb": "^0.7.29",
"rrweb-player": "^0.4.3"

Is anyone else seeing styles in their playback now?

**Comment by Yuyz0112** [comment]
@alexcroox Could you provide your events log or a sample project for debugging?

**Comment by slimlime** [comment]
Adding another checkpoint here

Missing styles for months in Angular / Ionic PWA apps

Checked today cloning rrweb master and running repl

**Comment by Yuyz0112** [comment]
@slimlime Is there any public website as an example that I can do a test?

**Comment by havard024** [comment]
@Yuyz0112 I'm also experiencing styling issues, using ionic with angular with a rrweb sentry integratioon, I have a public web page you can look at. You can't really navigate much, but you can trigger an exception which will trigger the call to sentry with the rrweb events.

The button to trigger the exception is on the bottom of the left menu.

<img width="737" alt="Screen Shot 2020-10-13 at 10 22 50 PM" src="https://user-images.githubusercontent.com/2212037/95912202-cc658380-0da2-11eb-8486-369ef03bb767.png">


Here's the url to the public webpage: https://vehicle-registry-staging.nor1.se/
