### ISSUE TITLE
How do I extract all of them into one file?

### ISSUE THREAD

**Issue by woshidahuaidan** [rrweb-io/rrweb#580]
Now I hope to be able to put such as recording, playback and so on in a JS file, how should I operate, thank you for your answer

**Comment by Yuyz0112** [comment]
All the events are JSON, so you can dump all the events into a JSON string and embed into a JS file?

**Comment by woshidahuaidan** [comment]
> 所有的事件都是JSON，所以你可以把所有的事件转储成一个JSON字符串并嵌入到一个JS文件中？

Now all the files provided are in TS format, I have converted to JS format, there are some such as :exports. IFrameManager = void 0;
So what about this one, thank you

**Comment by Yuyz0112** [comment]
Maybe you can take a look at how the REPL tool generate a single HTML file with events embed: https://github.com/rrweb-io/rrweb/blob/master/scripts/repl.ts#L161-L186
