### ISSUE TITLE
Merge rrweb-snapshot into rrweb

### ISSUE THREAD

**Issue by eoghanmurray** [rrweb-io/rrweb#582]
The two projects are very closely coupled.  I have a custom setup where I have site specific commits living on top of both rrweb and rrweb-snapshot.  As such I don't use the regular NPM inclusion of rrweb-snapshot.

 - new functionality in the form of pull requests often needs to be added to both projects at once, which renders the new functionality hard to discuss and see all at once
 - testing in rrweb is dependent on the rrweb-snapshot pull request being accepted and published to NPM
 - it's very hard to do a bisect over both projects when you are unsure where a breaking change was introduced.  You have to account for API changes in function signatures e.g. in `snapshot` `serializeNodeWithId` etc. (this is particularly hard when you are not pulling rrweb-snapshot from NPM but are compiling a local version of rrweb-snapshot)
 - both projects need to duplicate config options like blockClass / maskInputOptions etc.

I imagine rrweb-snapshot was originally a separate project with the idea that it could be used in other projects.  Would preserving the separate rrweb-snapshot NPM library still maintain this goal?  I.e. if the rrweb-snapshot NPM library could be an export target for a new combined repository?

**Comment by Yuyz0112** [comment]
yes, monorepo is a good idea.

**Comment by Juice10** [comment]
Oh man, Yes please!

**Comment by Juice10** [comment]
In this topic, the rrweb-player suffers from the same issue. Maybe it would be a good idea to also merge that into the same repo?

**Comment by ucjonathan** [comment]
I believe the decision to merge should be done before a 1.0 release.

**Comment by Yuyz0112** [comment]
@ucjonathan I think we can keep the compatibility of public APIs. So maybe it's not a blocker of 1.0?
