### ISSUE TITLE
回放时报错

### ISSUE THREAD

**Issue by mlinda** [rrweb-io/rrweb#589]
回放时报错  Uncaught Error:Replayer need at least 2 events.请求的数据是有events的。最开始回放是正常的，后边突然报错

**Comment by JohnPhamous** [comment]
@mlinda Can you share how you're loading the events?

**Comment by mlinda** [comment]
通过script引入
let replayer = null
const gotoReplay = () => {
        let url = 'events url';
        fetch(url).then(function(data){
          return data.text()
        }).then(function(ert){
          const resData = JSON.parse(ert)
          if(resData.code === 0) {
            let playEvents = resData.data
            if(playEvents.length === 0) {
              return
            }
            replayer = new window.rrwebPlayer({
                target: document.getElementById('palyer'),
                data: {
                    playEvents,
                },
                UNSAFE_replayCanvas: true
            });
            replayer.play()
          }
        })
      }

**Comment by mlinda** [comment]
传参有问题，已经处理了，打扰了
