### ISSUE TITLE
replay inspect 无法直接定位到 dom

### ISSUE THREAD

**Issue by PeterChen1997** [rrweb-io/rrweb#590]
![image](https://user-images.githubusercontent.com/21072589/122858425-d5085380-d34c-11eb-8e7b-c5d9ed773e84.png)
 由于 canvas 覆盖在 iframe 上，无法直接 inspect iframe，查看了下 chrome 好像也无法直接查看 iframe 内的元素，如果想定位回放中的内部元素，有什么比较好的方法吗

**Comment by Mark-Fenng** [comment]
把iframe的pointer-events:none这个style去掉，就可以正常inspect了

**Comment by PeterChen1997** [comment]
> 把iframe的pointer-events:none这个style去掉，就可以正常inspect了

666 可以啦，感谢
