### ISSUE TITLE
DragEvent is not supported on all Safari Browsers

### ISSUE THREAD

**Issue by IMFIL** [rrweb-io/rrweb#591]
Hey @Yuyz0112 

tag 1.0.0-beta.0 (https://github.com/rrweb-io/rrweb/releases/tag/1.0.0-beta.0) Introduced a pretty bad bug where the browser tries to access the DragEvent window attribute but that attribute does not exist on Safari browsers. 

(https://stackoverflow.com/questions/56137343/angular-not-working-on-safari-browser-but-working-well-on-other-browsers).

**Comment by Mark-Fenng** [comment]
Looks like safari already has the full support of DragEvent since v3.1.
![image](https://user-images.githubusercontent.com/27533910/123049397-16266380-d432-11eb-9147-0d2893ab0174.png)

**Comment by IMFIL** [comment]
Yeah, I am seeing that as well. I am getting errors on mobile Iphones running ios 13.5 and Safari 13.1. The error message is: Cannot find variable DragEvent.

**Comment by Yuyz0112** [comment]
merged https://github.com/rrweb-io/rrweb/pull/630 to fix this
