### ISSUE TITLE
Replay is trying to load javascript files for the recorded site

### ISSUE THREAD

**Issue by brec-c** [rrweb-io/rrweb#597]
This is really bad. Hopefully this is a bug or at least configurable and I can find a way to turn it off. Otherwise, i'll try to disable it locally.

**Comment by brec-c** [comment]
Seems like I reported this in the wrong repo? Looks like it should be in the snapshot repo.

**Comment by Mark-Fenng** [comment]
Could you please provide your events for us to debug the issue?

**Comment by brec-c** [comment]
I cannot, sorry. I tracked it down to the rrweb-snapshot repo, in the rebuild.ts `buildNodeWithSN` method. (https://github.com/rrweb-io/rrweb-snapshot/blob/master/src/rebuild.ts#L257).

It seems the node being rebuilt was the `HTML`  node and the script tags with the no longer available resources were part of the `innerText` I believe of that one node. (the only errors in the console when we were trying to view the replay were `ERR_ABORTED 404` for the `GET` to those old JS resources)

I'm not sure if this description helps at all. Sorry I can't help more but need to move on to other evaluations.

**Comment by jeffRTC** [comment]
We pretty much face the same kind of issue. In our case, we see scripts with _rel="prefetch"_ are fetched. Prefetch ones should be omitted. 

@Mark-Fenng Could you omit these type ones?

`<link rel="prefetch" href="https://example/path/to/script.js">`

@Mark-Fenng  It also better to remove or malform the src part of every script as @brec-c  suggested

**Comment by Yuyz0112** [comment]
@jeffRTC I'm going to fix the prefetch JS issue.
