### ISSUE TITLE
DOM Recording Replaying with styling Inconsistencies

### ISSUE THREAD

**Issue by omairnabiel** [rrweb-io/rrweb#600]
rrweb is built very nicely , very easy to integrate and was up and running within couple of minutes. So thank you for that. I've tried a few DOM Recording tools and almost all of them come with some inconsistencies. I also tried Time
cats chrome extension and the results were almost the same but with some fewer inconsistencies. Here are the screenshots of few styling inconsistencies. Wondering if it's got to do with DOMContentLoaded

<img width="1439" alt="Screenshot 2021-06-28 at 2 09 36 PM" src="https://user-images.githubusercontent.com/13148988/123650088-b40b9b00-d843-11eb-80fc-7bd8ea15e33f.png">

<img width="1434" alt="Screenshot 2021-06-28 at 2 10 14 PM" src="https://user-images.githubusercontent.com/13148988/123650258-d6051d80-d843-11eb-8dc9-ff8e17cd5ea8.png">

<img width="692" alt="Screenshot 2021-06-28 at 2 14 25 PM" src="https://user-images.githubusercontent.com/13148988/123650299-e3220c80-d843-11eb-90ef-b46b01a26f33.png">

**Comment by Mark-Fenng** [comment]
What's the chrome extension you are using?

**Comment by omairnabiel** [comment]
Not using any chrome extension, I used TimeCat chrome extension which is also a DOM Recording Tool through chrome extension. I've tried integrating rrweb with my own chrome extension and results were the same as the images I've attached. It mostly happens because of Navigation I suppose, because any recording with no navigation works fine

**Comment by Juice10** [comment]
Any chance you are getting CORS errors when replaying the recording?

**Comment by omairnabiel** [comment]
These are the errors in dev console

<img width="1437" alt="Screenshot 2021-06-29 at 11 55 52 AM" src="https://user-images.githubusercontent.com/13148988/123751957-bf0d0c80-d8d1-11eb-9754-14144286221d.png">

**Comment by Mark-Fenng** [comment]
I believe that these CORS errors have been fixed by this [PR](https://github.com/rrweb-io/rrweb-snapshot/pull/79) but this fix isn't updated by rrweb-player-vue.

**Comment by omairnabiel** [comment]
This library uses the latest rrweb package version `0.9.14`. It constructs it's own player using rrweb. This is basically the Vue version of the Svelete app (exactly the same)

**Comment by omairnabiel** [comment]
I tried the `rrweb-player` directly and the results are the same. Does it have to do anything with navigation? Because it only happens when I navigate to some other page on the website (some other on which the recording was started). Also using TimeCat I saw the recording pauses when the navigation starts until it's completed and it replays fine even with navigations

**Comment by omairnabiel** [comment]
I think I've solved the issue. The issue was that on navigation the chrome's API re-runs the `content_scripts`, which made the `rrweb.record` function to be run again and again on every page refresh. Simply adding a `boolean` to run it only once seems to the solve the issue of Styling and also these warnings. cheers
