### ISSUE TITLE
Image srcset attribute is not handling correctly relative URLs

### ISSUE THREAD

**Issue by xavier-heysch** [rrweb-io/rrweb#61]
Hi everyone !
I have started to use rrweb on a website and it's awesome !

I just have a small problem with the record. Some images are not correctly displayed in the replay, when they use the "srcset" attribute with relative URLs.

As you can see in the image below, in the HTML page, relative URLs are used for the images.

<img width="1237" alt="screen_1" src="https://user-images.githubusercontent.com/7370867/55159439-4e5e6f00-5161-11e9-898b-cddf0fe67c82.png">

In the screenshot below, it's a part of the event formatted by rrweb. As you can see, the "src" attribute is now absolute URL and it's good ! But the "srcset" attribute remains relative and it's causing trouble in the replay.

<img width="1434" alt="screen_2" src="https://user-images.githubusercontent.com/7370867/55159440-4ef70580-5161-11e9-8277-ce71652f90ea.png">

Is there a way to fix that ?

Thanks for the help ! :)

**Comment by Yuyz0112** [comment]
Sure, the relative to absolute transform was done in the full snapshot phase, which belongs to the rrweb-snapshot repo.

Looks like we can handle the srcset attribute with some parae and transform work either.

**Comment by xavier-heysch** [comment]
> Sure, the relative to absolute transform was done in the full snapshot phase, which belongs to the rrweb-snapshot repo.
> 
> Looks like we can handle the srcset attribute with some parae and transform work either.

Ok perfect ! I need to post the issue on the good repo then?

**Comment by xavier-heysch** [comment]
In the same way, I have discovered another problem with relative URL on images.

<img width="1068" alt="Screen Shot 2019-04-05 at 16 51 39" src="https://user-images.githubusercontent.com/7370867/55636680-aaf60580-57c3-11e9-85fd-ba6f782a1b0c.png">

As you can see, images in inline style are not converted into absolute path. Then in the replay, the image is not visible.

Maybe I need to post this on snapshot git repo ?

**Comment by IMFIL** [comment]
Any news on this ?

**Comment by xavier-heysch** [comment]
@IMFIL It's not a clean way at all, but here you can find my "temporary" fix for that.

[srcset_fix.txt](https://github.com/rrweb-io/rrweb/files/3646175/srcset_fix.txt)

PS: It seems that there is a limitation to the length of text that can be put in code part. So you will find the code in attachement

**Comment by IMFIL** [comment]
```
// Start the record
var options = {
    maskAllInputs: true,
    emit: function (event) {
        var json_event = JSON.stringify(event);
        try {
            // Fixing srcset issue with relative URLs
            // Browse all occurences of srcset starting with relative URLs
            while (json_event.indexOf('"srcset":"/') !== -1) {
                var srcset_index = json_event.indexOf('"srcset":"/');

                var srcset = json_event.substring(srcset_index + 10, json_event.indexOf('"', srcset_index + 10));

                var srcset_splitted = srcset.split(',');
                var srcset_splitted_fixed = [];
                for (var i = 0; i < srcset_splitted.length; i++) {
                    var srcset_item = srcset_splitted[i].replace(/(\\n)/g, ' ').trim();
                    if (srcset_item.indexOf("/") == 0) {
                        srcset_item = location.protocol + '//' + location.host + srcset_item;
                    }
                    srcset_splitted_fixed.push(srcset_item);
                }
                var srcset_fixed = srcset_splitted_fixed.join(', ');

                // Clean previous srcset and replace it with the fixed one
                json_event = json_event.substring(0, srcset_index + 10) + srcset_fixed + json_event.substring(json_event.indexOf('"', srcset_index + 10));
            }
        }
        catch (exc) {
            // Reset json event 
            json_event = JSON.stringify(event);
        }

        events_list.push(JSON.parse(json_event));
    }
};
```

**Comment by Yuyz0112** [comment]
I think @IMFIL 's patch already impl this.
