### ISSUE TITLE
How do I save the initialized data structure

### ISSUE THREAD

**Issue by dengshicheng1996** [rrweb-io/rrweb#615]
I need to save the data that was loaded long ago when I initialized it, because I might need to change the HTML structure in a later production iteration, resulting in inconsistent UI operations. Whether the current method to control

![image](https://user-images.githubusercontent.com/41374066/124536764-26373d80-de4b-11eb-9646-5da88898cc0e.png)

**Comment by Juice10** [comment]
Could you give us a bit more background on what you are trying to accomplish and what you need?

**Comment by dengshicheng1996** [comment]
> Could you give us a bit more background on what you are trying to accomplish and what you need?

Us this is a fast iterative project, during the process of users to use in our application we need to record user operation, eventually operate emersion, but may be in the process of iteration, we ran a new demand to modify some of the current code, so if there was no way to reconstruct the part of records before?

So I think if record the initialized data stream, each record will have its own initialized state, so will the previous operation record be maintained?

**Comment by Yuyz0112** [comment]
I do not understand your issue very well.

Bu rrweb records a website by serializing all the DOM things, so your live site iteration may not affect your recorded sessions.
