### ISSUE TITLE
Keep only last 200-400 events

### ISSUE THREAD

**Issue by omairnabiel** [rrweb-io/rrweb#616]
I'm trying to keep only last 200-400 events but I can't use the checkout feature as I'm using rrweb inside of an extension. The problem with extension is that DOM related events are to be run in the `content_scripts` context, which re-runs after every page refresh or navigation. This. causes the new `record()` to be called and run again causing the checkout to also reset. I'm maintaining the count outside of `content_scripts` where data can persist. What I do is hacky, I create my own snapshot event and attach it to each event passed to the DB layer and check if the count is 100 I insert a snapshot event before it. At times this works without any problems but breaks with a blank screen always sometime later or with certain websites. Do I also need something other than my snapshot event or is there any better way to keep only last 200-400 events and not break the replayer. Here's my snapshot logic

<img width="719" alt="Screenshot 2021-07-06 at 11 07 06 AM" src="https://user-images.githubusercontent.com/13148988/124550584-4f0b0300-de4a-11eb-8753-50a9881bc664.png">

**Comment by omairnabiel** [comment]
This is the error I get 

<img width="784" alt="Screenshot 2021-07-06 at 1 18 19 PM" src="https://user-images.githubusercontent.com/13148988/124566602-a4501000-de5c-11eb-8916-82abdd1a4c5b.png">

**Comment by Juice10** [comment]
You can think of full snapshot `type: EventType.FullSnapshot` or `type: 2` events as keyframes in video files. When choosing what events to purge it is safe to do so _before_ a full snapshot event. Just make sure you keep the full snapshot event. Mutation events (type: 3) are going to use that full snapshot as their base.

You might have to add on a meta event before that to include the page width/height but you can create those after the fact as well.

Some comments on your example code:
Between the `setTimeout` and the `document.dispatchEvent` I'm afraid your events might get saved in the wrong order. It might help to push everything to an array and create a worker function that manipulates and sends the events via `document.dispatchEvent`. That way you can guarantee the events get sent in order.
Personally I also wouldn't change the timestamp if I where you. I'm afraid it can mess things up in the replay.

**Comment by omairnabiel** [comment]
Yea lesson learnt. I eventually had to remove all this hacky code, knowing it's too volatile and un-natural. It was indeed messing things up. I've now taken a different approach, where I'm deleting events between the `Meta` events (first Meta inclusive). Things are working as expected now.

Your comment has helped to understand things in more depth and made things clear as to why my old way was not gonna work. Thanks alot 😊

**Comment by Juice10** [comment]
@omairnabiel happy I could help!

**Comment by omairnabiel** [comment]
@Juice10 Is there a way to take a FullSnapshot on demand or I'll have to create one using the `rrweb-snapshot`, just like in [here](https://github.com/rrweb-io/rrweb/blob/c658ee9e01a936daa6986774b7a2d4a2543737ba/src/record/index.ts#L220) ?

**Comment by Juice10** [comment]
You can use `record.takeFullSnapshot()` to do that.

**Comment by omairnabiel** [comment]
It was throwing error, then I realized I'm on the wrong version. Bumped it and it's working like charm. I guess that's all I need. I'll be closing this issue. Thanks a bunch ❤️
