### ISSUE TITLE
Failed to execute 'appendChild' on 'Node': This node type does not support this method

### ISSUE THREAD

**Issue by omairnabiel** [rrweb-io/rrweb#617]
I'm not using checkout feature, but manually triggering the checkout. I want to keep only last 200-400 events. This works when I delete previous events and create a new snapshot event before adding new ones, but sometimes it fails with this error

<img width="1157" alt="Screenshot 2021-07-06 at 1 19 08 PM" src="https://user-images.githubusercontent.com/13148988/124566967-f5f89a80-de5c-11eb-8064-95883cd220c8.png">

<img width="773" alt="Screenshot 2021-07-06 at 1 22 43 PM" src="https://user-images.githubusercontent.com/13148988/124567250-42dc7100-de5d-11eb-958f-5583e9e75bd8.png">

**Comment by Yuyz0112** [comment]
@omairnabiel Sorry for the late. Is their some events for debugging?

**Comment by endypark** [comment]
how to fix this issue (failed to execute 'appendChild' on 'Node': This node type does not support his method.

function replaycontentShow(){
		new rrwebPlayer({
			target: document.getElementById("replaycontent"), // 可以自定义 DOM 元素
			data: {
				events:userBehaviorVideoWholeData,
			},
		});
		$("#videoPlayBtn").hide();
		$("#replaycontent").show();
	}

the video stops at 30s.


![30s-stop-running-issue](https://user-images.githubusercontent.com/5320122/177042221-cc6f83ae-eff3-4afa-baa1-a59dc4837f75.png)

**Comment by Juice10** [comment]
@endypark can you share your events? Otherwise it won't be possible for us to debug I'm afraid

**Comment by endypark** [comment]
the data is sensitive, so I cannot make it publicly.
could you tell me your email address ( send email to endypark@126.com) , then I could send the events:json to your email, thanks.

Issue: 
The video stops at 0:30, and the console-of-the-browser print [ Failed to execute 'appendChild' on 'Node': This node type does not support this method ]

Reason:
I guess the {“data”: xxxx} from line-6564 to line-9006 has some errors, so the JavaScript runtime of the browser could not rebuild the view, then the video replay failed.

My expectation:
If the json-data has some errors, the rrweb-player could skip this section and running the video continuously. (currently the rrweb-player will stop the world)

**Comment by endypark** [comment]
> @endypark can you share your events? Otherwise it won't be possible for us to debug I'm afraid

I Had remove the sensitive words, please help to debug, thanks.

[trace-video-data.txt](https://github.com/rrweb-io/rrweb/files/9052662/trace-video-data.txt)

**Comment by endypark** [comment]
@Juice10 , how about the debug progress ? could you find the error-data-statement ?

**Comment by endypark** [comment]
@Yuyz0112 , could you help to debug the events json ?

**Comment by endypark** [comment]
I knew that issue-271, there are about 10 issues about this kind of issue, but no one provide the solution. what shall I do ?
