### ISSUE TITLE
Hovers, tooltips, modals, loaders etc. , not working properly during session replay

### ISSUE THREAD

**Issue by Gili-Sinai** [rrweb-io/rrweb#619]
Hi, 

Im trying to record sessions on a react based app , but when i see the replay , components with tooltips or hover statements stays on the screen and not changing back to its normal state

what i should see :
![image](https://user-images.githubusercontent.com/82466001/124713940-d7041200-df09-11eb-8690-59383f8aea11.png)

what i really see:
![image](https://user-images.githubusercontent.com/82466001/124713803-a91ecd80-df09-11eb-94c9-2bc97e777a2e.png)

did it happend to someone who used react? 

thats the function invoking the record and putting all the events inside the array:
const recordDom = () => {
        
        record({
            emit(event) {
                if (isRecording) {
                    setEvents(events => [...events, event])      
                }
            },
            maskAllInputs: true,
        })
    }

or maybe someone did a better implementation for it in react apps?

**Comment by omairnabiel** [comment]
Probably related to this [Pull Request](https://github.com/rrweb-io/rrweb/pull/618)

**Comment by Yuyz0112** [comment]
Hi @Gili-Sinai, could you try the latest v1.0.2 version?

**Comment by Yuyz0112** [comment]
Feel free to reopen this issue if it still exists in the latest version.
