### ISSUE TITLE
Feature request: Inactive activity indicator on progressbar

### ISSUE THREAD

**Issue by omairnabiel** [rrweb-io/rrweb#621]
The `rrweb-player` shows an indicator for snapshot events but it would also be nice, to have some sort of indication of the inactive portion of the recording during playback. Recorded events can span to several minutes and it might be useful to know before hand where the inactive part is so it can be skipped `manually` as-well

**Comment by Juice10** [comment]
Thanks for the suggestion! Could you create an issue in the rrweb-player repo for this?

**Comment by omairnabiel** [comment]
Sure

**Comment by userback** [comment]
+1
