### ISSUE TITLE
录屏回放出现重复dom

### ISSUE THREAD

**Issue by angle0585** [rrweb-io/rrweb#624]
如果是点击链接进入初始页面录屏不会出现dom重复的情况，但是如果是在上一个vue页面跳转到录屏页面会出现dom重复显示 的问题，且发现只有在生命周期里面调用录屏方法会导致重复，点击事件调用录屏不会

**Comment by angle0585** [comment]
this.$nextTick(()=>{
        this.crateWeb();
      })
在生命周期使用这个可以解决，唉

**Comment by Yuyz0112** [comment]
可以提供 events 用于 debug 吗？

另外同一页面只应该调用一次 record 方法，这个在代码中是否得到保证？

**Comment by angle0585** [comment]
可以确保同一个页面只调用一次，可以播放只是会在回放的里面多一个一样的静态dom内容

**Comment by angle0585** [comment]
events 已经用pako的压缩过，要怎么发，发哪里

**Comment by Yuyz0112** [comment]
@angle0585 可以压缩为 zip 后上传在这里

**Comment by angle0585** [comment]
events数据，未压缩的


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rrweb-io/rrweb"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月12日(星期一) 下午3:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [rrweb-io/rrweb] 录屏回放出现重复dom (#624)





 
@angle0585 可以压缩为 zip 后上传在这里

**Comment by angle0585** [comment]
已发

**Comment by Yuyz0112** [comment]
@angle0585 好像没有在 issue 内看到

**Comment by Yuyz0112** [comment]
Please re-open the issue if there is any further information.

**Comment by a11266897** [comment]
每次重新录制之前stop一下。你发现不管你是单页还是多页。这个问题都解决了。因为我碰到了同样得问题。。。
