### ISSUE TITLE
回放時 Uncaught TypeError: Cannot add property delay, object is not extensible

### ISSUE THREAD

**Issue by gogojimmy** [rrweb-io/rrweb#625]
我的調用方式
<img width="371" alt="CleanShot 2021-07-13 at 03 34 45@2x" src="https://user-images.githubusercontent.com/726221/125345573-4b680680-e38b-11eb-97da-b89d88005afa.png">

但在 chrome console 總是會出現錯誤
timer.js:105 Uncaught TypeError: Cannot add property delay, object is not extensible

<img width="984" alt="CleanShot 2021-07-13 at 03 35 23@2x" src="https://user-images.githubusercontent.com/726221/125345701-70f51000-e38b-11eb-9c21-6152121ca95b.png">

我是在 React 環境下使用的，找了很久找不到相關問題，請求協助🙏

**Comment by Yuyz0112** [comment]
是不是使用了 apollo client 之类的库获取 events 数据？看起来 events 被 Object.freeze 处理过。

rrweb 回放的时候会在 event 上增加属性，freeze 会导致增加属性失败。可以试试传入 replayer 之前做一次深拷贝移除 freeze 的效果。

**Comment by gogojimmy** [comment]
真的是這個問題，感謝！！
