### ISSUE TITLE
录制与回放console失败

### ISSUE THREAD

**Issue by Soxiaoxin** [rrweb-io/rrweb#631]
按照[#623](https://github.com/rrweb-io/rrweb/issues/623)的方式添加了console的plugin，但是报了一下错误，也没有成功回放console信息

![image](https://user-images.githubusercontent.com/52018542/125582479-00ef187b-54fc-40dc-9d95-1f6a677269e0.png)

**Comment by Mark-Fenng** [comment]
看起来是error log的解析出错了，能否提供一下出错误events来帮助我们debug

**Comment by Soxiaoxin** [comment]
@Mark-Fenng 
这个是录制时的event
![image](https://user-images.githubusercontent.com/52018542/125585472-c0dc2517-c32a-4c0d-bb62-4d37703dff0e.png)
回放时：
![image](https://user-images.githubusercontent.com/52018542/125585811-ffc1484f-d25c-4f76-9bb6-440801b3a998.png)
顺便请问一下成功的回放效果是怎样的呢

**Comment by Mark-Fenng** [comment]
截图中"this is an error"的输出就是预期的回放效果
