### ISSUE TITLE
开发者你们好，如果不使用CDN，哪里有这些文件？是我直接用工具下载吗？

### ISSUE THREAD

**Issue by hulang** [rrweb-io/rrweb#637]
https://github.com/rrweb-io/rrweb/blob/0f86a72705b998a9abf5b4aae5b01a4f3b679954/guide.zh_CN.md
这个页面中的

```shell
# 包含录制、回放、压缩数据、解压缩数据
rrweb-all.js
rrweb-all.min.js
# 包含录制、回放
rrweb.js
rrweb.min.js
# 回放所需的样式文件
rrweb.min.css
# 录制
record/rrweb-record.js
record/rrweb-record.min.js
# 压缩数据
record/rrweb-record-pack.js
record/rrweb-record-pack.min.js
# 回放
replay/rrweb-replay.js
replay/rrweb-replay.min.js
# 解压缩数据
replay/rrweb-replay-unpack.js
replay/rrweb-replay-unpack.min.js
```

**Comment by Yuyz0112** [comment]
通过 npm 安装的 rrweb 里 dist 文件夹会包含这些文件。如果你在使用 webpack/rollup 之类的 bundler，它们也会自动从 rrweb 的 es module bundle 中引入文件并进行 tree-shaking。

**Comment by hulang** [comment]
@Yuyz0112 我的页面是纯html那种，不是vue等等之类的。。也不会用npm。。。
作者你们能编译到dist文件夹中吗？一劳永逸。。。

**Comment by Yuyz0112** [comment]
可以 git clone，然后本地编译。也可以从 cdn 下载。
