### ISSUE TITLE
Feature Required !! how to copy Text fields from the replay

### ISSUE THREAD

**Issue by codesiddhant** [rrweb-io/rrweb#639]
I wonder to know that how one can copy any of the text fields from the running replay to another
Html div on the same html page.

For example. If I record the screencast of online code editor and later it is possible to auto copy to these code to another div on the same page.
Using rrpalyer.

Please someone help me in this.

**Comment by Mark-Fenng** [comment]
I assume you have to modify the recorded events data by adding a event like this:
```
{
    "type": 3,
    "data": {
      "source": 0,
      "texts": [
           {
                "id":  id of the target div,
                "value": "text you want to copy",
           }
      ],
      "attributes": [],
      "removes": [],
    }
}
```
