### ISSUE TITLE
回放错误

### ISSUE THREAD

**Issue by hulang** [rrweb-io/rrweb#641]
保存到数据库中的代码，使用了：JSON.stringify({ events });
```js
var events = []
rrweb.record({
    emit(event) {
        events.push(event);
    },
    inlineStylesheet: false
});
function ajaxSuccessFun() {
    var d = JSON.stringify({ events });
    var j = $('#hulangfy_rrweb');
    $.ajax({
        type: 'POST',
        url: '/manage/rrweb/save',
        data: {
            url: j.data('url'),
            modules: j.data('modules'),
            ids: j.data('id'),
            info: d
        },
        dataType: 'json',
        success: function (data) {
            console.log(data)
        }
    });
}
```

回放代码：
```js
var d = {"events":[这里面是代码]};
var events = d.events;
new rrwebPlayer({
    target: document.getElementById('play_box'),
    // 配置项
    props: {
        events
    }
});
```

有的回放正常，代码多了的就错误了。。直接显示了代码
![q1](https://user-images.githubusercontent.com/4961831/126273892-d31386d2-f79a-4a8e-b53b-17130bb4e041.png)

查看源码，发现events中应该有注释代码，直接把下面的也就是上面的回放代码也给注释了。
![q2](https://user-images.githubusercontent.com/4961831/126273928-5258e5ec-563a-4b59-bab4-a5589b384b4a.png)

回放的代码，麻烦作者帮忙查看下，给个解决方案
[events.zip](https://github.com/rrweb-io/rrweb/files/6846032/events.zip)

**Comment by Yuyz0112** [comment]
数据本身是正常的，看起来是将 events 直接输出为字符串拼接在 HTML 中？这样的话需要对输出的字符串进行转义。

可以参考 https://github.com/rrweb-io/rrweb/blob/master/packages/rrweb/scripts/repl.ts#L175

**Comment by hulang** [comment]
@Yuyz0112 作者老大，我已经说了，有的可以正常播放，少量的不行。如你发的链接，我加上后，全部不能播放了。

**Comment by Yuyz0112** [comment]
@hulang 

![image](https://user-images.githubusercontent.com/13651389/127772831-8b60a8c9-7bf2-4567-8163-9953120bb822.png)

查看你拼接的 HTML，应该也很容易看出是因为数据中有 `</script>` 导致了这个问题，少量不行是因为只有少量包含这个数据。

这个问题最简的复现代码是这样

![image](https://user-images.githubusercontent.com/13651389/127772890-d2bfbbd7-2453-4dc1-a99f-2a3f0a85d517.png)

上面发的链接就是解决这个问题的，并且包含了两种解决方式
1. 对 `</script>` 做正则替换转义。
2. 在数据上下方通过 HTML 注释。

[641.html.zip](https://github.com/rrweb-io/rrweb/files/6912759/641.html.zip)

我用方式二就没有错误了。

基础 JS/HTML 问题可以先查 stackoverflow https://stackoverflow.com/questions/28643272/how-to-include-an-escapedscript-script-tag-in-a-javascript-variable/28643409

**Comment by hulang** [comment]
可以了。。。谢谢了。
`/**/`
