### ISSUE TITLE
Record iframe websites with different domain names

### ISSUE THREAD

**Issue by HackerBoy856** [rrweb-io/rrweb#642]
Put the address of someone else’s website in the iframe. Can this be recorded? I understand that the same-origin iframe is not cross-domain, but the iframe I want to record is from another website. Can you help me?

**Comment by Juice10** [comment]
This is unfortunately not possible without changing your browser's security settings:
<img width="947" alt="image" src="https://user-images.githubusercontent.com/4106/126812743-1882af3f-993f-424f-b3b5-dd91d400d852.png">

**Comment by Yuyz0112** [comment]
Cross-origin iframe has more limitations and is not supported by rrweb yet.

You can join the slack channel to get information when we implemented that.

**Comment by Buwaggish** [comment]
Has rrweb supported cross-origin iframe by now ?

**Comment by Juice10** [comment]
@Buwaggish It hasn't

**Comment by Juice10** [comment]
@Buwaggish @HackerBoy856 Check out this PR for cross origin iframe support: https://github.com/rrweb-io/rrweb/pull/1035
