### ISSUE TITLE
录制的数据中没有全量快照

### ISSUE THREAD

**Issue by RobertM574** [rrweb-io/rrweb#644]
目前采集到的数据有一些没有全量快照信息，只有类型为3的上报数据，不知道是被特定的浏览器屏蔽了还是什么原因，麻烦帮忙定位下

**Comment by RobertM574** [comment]
回放时候的控制台信息
![image](https://user-images.githubusercontent.com/19481711/127296955-907c0b1f-dbc1-4662-b825-acf6d1abcb90.png)

**Comment by Yuyz0112** [comment]
和回放没有关系，可以在录制的 emit 回调里看一下是否正确输出了 event，如果 emit 正确的话大概率是网络传输和存储过程中丢失了。

**Comment by RobertM574** [comment]
相同的用户，有的有全量快照，有的没有，而且就是type 4 和 2 的没有，其他的都有，这个应该不是网络传输或存储问题，不太好定位到，我看了源码，如果拿不到node的话好像会不做全量快照

**Comment by Yuyz0112** [comment]
type 4 是 meta event，是一定会创建的 event。

full snapshot 体积较大，如果同一个用户访问不同的页面，有的 full snapshot 超过了你系统某个环节的体积限制也是可能错误的。

**Comment by Yuyz0112** [comment]
Feel free to reopen if there is any further information.
