### ISSUE TITLE
Set current time in player

### ISSUE THREAD

**Issue by milancakic89** [rrweb-io/rrweb#648]
### There should be an option to set current time on replayer object similar to html video element.<br/>
replayer.currentTime = x;<br/><br/>

I have and app inside angular, my recording are replaying just fine, but i haven't installed svelte and i am not planing to.<br/>
This lead to recordings without controls (seek, pause, play etc)... Since there is an option to get startTime, endTime, and total of recording, its not hard to make simple range input with some calculation and make my own seek control. But after the calculation i need a way to set that time on currently playing record...

**Comment by JohnPhamous** [comment]
The player API doesn't expose this explicitly but you can set the player's time with `Replayer.play(time: number)` and `Replayer.pause(time: number)`.

**Comment by Yuyz0112** [comment]
Agree with @JohnPhamous
