### ISSUE TITLE
Obtaining the node ID from the node instance and vice-versa

### ISSUE THREAD

**Issue by marcospassos** [rrweb-io/rrweb#65]
First of all, thank you very much for the excellent job you did!

We realised that the tooling provided by RRWeb is not only useful for recording sessions, but also for analysing user behaviour. However, there are some events that we are interested in that are not captured, such as form submissions. To capture these events, we are registering listeners that share the same array of events as the recorder's callback to maintain the order in which the events occurred. It works fine, but we have two use cases that we do not manage to solve: 1) enrich the events supported by RRWeb with extra information, such as the element ID and 2) include the node ID into our custom events. To do so, we need to retrieve the node ID from a DOM Node, as well as retrieve the DOM Node from a node ID.

Could you give us some guidance if it is possible and how to expose such features?

**Comment by Yuyz0112** [comment]
A custom event hook is something seems will help, but I do not have too much idea about it at this moment.

More feedback will be nice to build a better API for this feature!

**Comment by marcospassos** [comment]
Is there any way to expose the the feature needed to obtain the node ID
from a DOM node and the DOM node from the node ID? I’m considering for now
to fork the repository and expose it to gather insight on how to improve
the API to better accommodate those cases.

**Comment by Yuyz0112** [comment]
Yes, the node id is in `node.__sn.id`, and there is an `id -> node` mirror map.

**Comment by marcospassos** [comment]
Thank for the tip, @Yuyz0112! It does the job!
