### ISSUE TITLE
rrweb not capturing styling changes coming from material-ui

### ISSUE THREAD

**Issue by Equlnox** [rrweb-io/rrweb#650]
Code sandbox link - https://codesandbox.io/s/competent-cdn-ckn2h?file=/src/App.tsx:360-366

If you visit https://ckn2h.csb.app/#, the button click updates the color of box from red to blue.
Sessions recorded through rrweb don't have the color changing.

Here is a loom recording showing that the color doesn't change in rrweb replay - 
https://www.loom.com/share/62b6685ea5bd49c2a1895571572c6ed6

**Comment by Yuyz0112** [comment]
The reason is we do not observe `CSSStyleDeclaration.setProperty` and `CSSStyleDeclaration.removeProperty`.

Going to send a PR for fix.

**Comment by Equlnox** [comment]
Hey @Yuyz0112 .. any chance you were able to work on this?

**Comment by Yuyz0112** [comment]
@Equlnox You can check https://github.com/rrweb-io/rrweb/pull/671 for the status.
