### ISSUE TITLE
console output large object cause OOM problem

### ISSUE THREAD

**Issue by PeterChen1997** [rrweb-io/rrweb#653]
We use angular in app and console a big obj to reproduce  this problem

first i get this error 
![image](https://user-images.githubusercontent.com/21072589/128113065-143c7259-79fa-4248-b70b-3c415917d260.png)

the mango.esm.js is the lib we seal rrweb in

i check the call stack, found the toString problem

stack 1
![image](https://user-images.githubusercontent.com/21072589/128113236-bc29b996-e272-432f-b63f-5f876c932f06.png)
stack 2
![image](https://user-images.githubusercontent.com/21072589/128113313-85fd0e16-52be-4b9d-a5bc-2e99cd903801.png)

i think the problem is to stringify a big obj that cause OOM. Is there any good ideas to fix this, thx

**Comment by PeterChen1997** [comment]
i think maybe we can judge the object's depth before we call toString?

**Comment by PeterChen1997** [comment]
I fix this problem by doing this

```js
export function stringify(obj: any, stringifyOptions?: StringifyOptions): string {
    const options: StringifyOptions = {
        numOfKeysLimit: 50,
        objectKeysDeep: 4
    };
    Object.assign(options, stringifyOptions);
    const stack: any[] = [];
    const keys: any[] = [];

    if (typeof obj === 'object' && isObjTooDeep(obj, options.objectKeysDeep)) {
        return `(${Object.keys(obj).length} items...) 由于对象嵌套过深，内容被丢弃`;
    }

    return JSON.stringify(obj, function (key, value) {
```

**Comment by Yuyz0112** [comment]
@PeterChen1997 Thanks! Would you love to send a PR?

**Comment by PeterChen1997** [comment]
> @PeterChen1997 Thanks! Would you love to send a PR?

@Yuyz0112 Here is my suggestion, maybe has some problem
 https://github.com/rrweb-io/rrweb/pull/656
