### ISSUE TITLE
Run repl error

### ISSUE THREAD

**Issue by wqcstrong** [rrweb-io/rrweb#655]
Following is the error info:

```zsh
created dist/plugins/console-record.min.js in 620ms
? Enter the url you want to record, e.g https://react-redux.realworld.io:  https://react-redux.realworld.
io
Going to open https://react-redux.realworld.io...
Error: Evaluation failed: ReferenceError: rrwebSnapshot is not defined
    at __puppeteer_evaluation_script__:29:34684
    at ExecutionContext._evaluateInternal (/Users/blucas/Project/test/rrweb/packages/rrweb/node_modules/puppeteer/src/common/ExecutionContext.ts:221:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at ExecutionContext.evaluate (/Users/blucas/Project/test/rrweb/packages/rrweb/node_modules/puppeteer/src/common/ExecutionContext.ts:140:12)
^C
```

Any help ?

**Comment by wqcstrong** [comment]
@Yuyz0112 Give some advice , Thx!

**Comment by wqcstrong** [comment]
And there is some trouble when I use rrweb in React.

The detail case is rrweb don't emit event when I call `rrweb.record` in one `onClick` callback which triiger setState.

Here is the [sandbox demo](https://codesandbox.io/s/ji-ben-yong-fa-antd-4-16-10-forked-0swh8?file=/index.js)

**Comment by Yuyz0112** [comment]
@wqcstrong the REPL tool need some fix.

And for the React usage, I think `setRecordDone(done)` cause the issue.

`done` is the stop handler return from `rrweb.record`, but in React, when you pass a function to the setState, it thinks you are using a call back to update the state like this `setState((prevState => newState))`. So it calls the `done` function and stops the recording.

**Comment by wqcstrong** [comment]
> @wqcstrong the REPL tool need some fix.
> 
> And for the React usage, I think `setRecordDone(done)` cause the issue.
> 
> `done` is the stop handler return from `rrweb.record`, but in React, when you pass a function to the setState, it thinks you are using a call back to update the state like this `setState((prevState => newState))`. So it calls the `done` function and stops the recording.

Thank you very much~
