### ISSUE TITLE
How do i do with this error?

### ISSUE THREAD

**Issue by babyWatchmen** [rrweb-io/rrweb#66]
![image](https://user-images.githubusercontent.com/24561833/56644646-adef6200-66ae-11e9-92d9-f42a6ef85e99.png)
![image](https://user-images.githubusercontent.com/24561833/56644666-b778ca00-66ae-11e9-9dfe-2037a82bf734.png)

**Comment by Yuyz0112** [comment]
Looks like a typing bug since [this file](https://github.com/rrweb-io/rrweb/blob/master/index.d.ts) is not included in the typings list. Will be fixed in next release
