### ISSUE TITLE
import rrweb from 'rrweb' underfined

### ISSUE THREAD

**Issue by callmesoul** [rrweb-io/rrweb#67]
```
import rrweb from 'rrweb' 

console.log(rrweb )
```
//underfined

**Comment by Yuyz0112** [comment]
rrweb has no default export, use:
```
import { record, Replayer } from 'rrweb'

console.log(record, Replayer)
```

**Comment by aiduck** [comment]
为什么我们播放的时候会出现index.mjs?c1c8:1 Uncaught Error: undefined:15:6: property missing ':'这个报错

**Comment by Yuyz0112** [comment]
@aiduck 好像和 #121 是同一个问题？可以在那个 issue 里提供一下录制的 events 用于 debug 吗？
