### ISSUE TITLE
chrome 86 css position

### ISSUE THREAD

**Issue by sershine** [rrweb-io/rrweb#672]
when i use chrome 86+ to record,then i use chrome 86 to replay . I find css prop "position: absolute;left:0;right:0;top:0;bottom:0;" become to "position: absolute;inset :0px;" . Oh, chrome 86 is nonsupport "inset"

**Comment by sershine** [comment]
Oh, I use rrweb@1.0.1

**Comment by sershine** [comment]
when i use chrome 86 to record.It works normal

**Comment by Yuyz0112** [comment]
Some UI lib use `inset: 0px` and fallback to `left:0;right:0;top:0;bottom:0;` when `inset` property is not supported. So you may record styles with inset from newer browser, and it failed to replay in the old browser.

You can try this to polyfill the CSS:

```
new rrweb.Replayer(events, {
  insertStyleRules: [`[style*="inset: 0px"] { left: 0; top: 0; right: 0; bottom: 0 }`]
})
```
