### ISSUE TITLE
Replayer not functioning as expected

### ISSUE THREAD

**Issue by LiamMacmillan** [rrweb-io/rrweb#674]
When trying to play the replayer, I'm getting errors such as: 

> Node with id '290' not found

Here are my code, alongside the JSON events:

```
const events = [
  {
    type: 3,
    data: {
      source: 0,
      texts: [

      ],
      attributes: [
        {
          id: 290,
          attributes: {
            style: {
              width: '78%',
            },
            'aria-valuenow': '78',
          },
        },
      ],
      removes: [

      ],
      adds: [

      ],
    },
    timestamp: 1629462720020,
  },
  {
    type: 3,
    data: {
      source: 1,
      positions: [
        {
          x: 398,
          y: 407,
          id: 23500,
          timeOffset: -305,
        },
        {
          x: 509,
          y: 329,
          id: 1807,
          timeOffset: -251,
        },
        {
          x: 892,
          y: 165,
          id: 36809,
          timeOffset: -192,
        },
        {
          x: 1028,
          y: 127,
          id: 36941,
          timeOffset: -139,
        },
        {
          x: 1056,
          y: 120,
          id: 280,
          timeOffset: -81,
        },
        {
          x: 1058,
          y: 120,
          id: 280,
          timeOffset: -1,
        },
      ],
    },
    timestamp: 1629462720064,
  },
  {
    type: 3,
    data: {
      source: 6,
      positions: [
        {
          x: 126,
          y: 5,
          id: 37321,
          timeOffset: 0,
        },
      ],
    },
    timestamp: 1629462720173,
  },
  {
    type: 3,
    data: {
      source: 1,
      positions: [
        {
          x: 1052,
          y: 118,
          id: 280,
          timeOffset: -455,
        },
        {
          x: 550,
          y: 483,
          id: 23928,
          timeOffset: -371,
        },
      ],
    },
    timestamp: 1629462720569,
  },
  {
    type: 3,
    data: {
      source: 0,
      texts: [

      ],
      attributes: [
        {
          id: 290,
          attributes: {
            style: {
              width: '77%',
            },
            'aria-valuenow': '77',
          },
        },
      ],
      removes: [

      ],
      adds: [

      ],
    },
    timestamp: 1629462720624,
  },
  {
    type: 3,
    data: {
      source: 0,
      texts: [

      ],
      attributes: [
        {
          id: 290,
          attributes: {
            style: {
              width: '76%',
            },
            'aria-valuenow': '76',
          },
        },
      ],
      removes: [

      ],
      adds: [

      ],
    },
    timestamp: 1629462721227,
  },
  {
    type: 3,
    data: {
      source: 0,
      texts: [

      ],
      attributes: [
        {
          id: 290,
          attributes: {
            style: {
              width: '75%',
            },
            'aria-valuenow': '75',
          },
        },
      ],
      removes: [

      ],
      adds: [

      ],
    },
    timestamp: 1629462721830,
  },
];

const replayer = new window.rrweb.Replayer(events);
replayer.play();
```

**Comment by Yuyz0112** [comment]
@LiamMacmillan Looks like you are missing some events. Basically, there should be an event with type 2, which is the full snapshot.

Maybe your backend is dropping some events.

**Comment by Yuyz0112** [comment]
Feel free to reopen if there is any further information.

**Comment by JulienPlanchetCoineo** [comment]
Hello, same problem here.
I don't have any type: 2, only type:3 in events array.
Even when I lookup on front-end, so it's not backend limitation related.

Here is the frontcode : 
`<script type="text/javascript">
    $(document).ready(function () {

      let events = [];

      rrweb.record({
        emit(event) {
          // push event into the events array
          events.push(event);
        },
      });

      // this function will send events to the backend and reset the events array
      function save() {
        const body = JSON.stringify({
          events
        });
        events = [];
        fetch('/record', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body,
        });
      }

      // save events every 10 seconds
      setInterval(save, 10 * 1000);
    });
  </script>`
Impossible to read back, I have a lot of "Node with id 'xxx' not found, and of course, a blank and empty video.

Do you have an idea ?

Thanks

**Comment by JulienPlanchetCoineo** [comment]
> Hello, same problem here. I don't have any type: 2, only type:3 in events array. Even when I lookup on front-end, so it's not backend limitation related.
> 
> Here is the frontcode : `<script type="text/javascript"> $(document).ready(function () {
> 
> ```
>   let events = [];
> 
>   rrweb.record({
>     emit(event) {
>       // push event into the events array
>       events.push(event);
>     },
>   });
> 
>   // this function will send events to the backend and reset the events array
>   function save() {
>     const body = JSON.stringify({
>       events
>     });
>     events = [];
>     fetch('/record', {
>       method: 'POST',
>       headers: {
>         'Content-Type': 'application/json',
>       },
>       body,
>     });
>   }
> 
>   // save events every 10 seconds
>   setInterval(save, 10 * 1000);
> });
> ```
> 
> </script>` Impossible to read back, I have a lot of "Node with id 'xxx' not found, and of course, a blank and empty video.
> 
> Do you have an idea ?
> 
> Thanks

Found the solution.
I'm using expressJS, I needed to set bodyParser.json({limit:'50mb'}) for example
It couldn't send the first snapshot to the back.. My bad, hope it helps someone else :)
