### ISSUE TITLE
rrweb-plyer 回放时，style显示的为[Object Object]

### ISSUE THREAD

**Issue by WhyAlive** [rrweb-io/rrweb#676]
events:[
    {
        "type": 4,
        "data": {
            "href": "http://127.0.0.1:5500/index.html",
            "width": 834,
            "height": 852
        },
        "timestamp": 1629862511199,
        "delay": 0
    },
    {
        "type": 2,
        "data": {
            "node": {
                "type": 0,
                "childNodes": [
                    {
                        "type": 1,
                        "name": "html",
                        "publicId": "",
                        "systemId": "",
                        "id": 2
                    },
                    {
                        "type": 2,
                        "tagName": "html",
                        "attributes": {
                            "lang": "en"
                        },
                        "childNodes": [
                            {
                                "type": 2,
                                "tagName": "head",
                                "attributes": {},
                                "childNodes": [
                                    {
                                        "type": 3,
                                        "textContent": "\n  ",
                                        "id": 5
                                    },
                                    {
                                        "type": 2,
                                        "tagName": "meta",
                                        "attributes": {
                                            "charset": "UTF-8"
                                        },
                                        "childNodes": [],
                                        "id": 6
                                    },
                                    {
                                        "type": 3,
                                        "textContent": "\n  ",
                                        "id": 7
                                    },
                                    {
                                        "type": 2,
                                        "tagName": "meta",
                                        "attributes": {
                                            "name": "viewport",
                                            "content": "width=device-width, initial-scale=1.0"
                                        },
                                        "childNodes": [],
                                        "id": 8
                                    },
                                    {
                                        "type": 3,
                                        "textContent": "\n  ",
                                        "id": 9
                                    },
                                    {
                                        "type": 2,
                                        "tagName": "title",
                                        "attributes": {},
                                        "childNodes": [
                                            {
                                                "type": 3,
                                                "textContent": "Document",
                                                "id": 11
                                            }
                                        ],
                                        "id": 10
                                    },
                                    {
                                        "type": 3,
                                        "textContent": "\n  ",
                                        "id": 12
                                    },
                                    {
                                        "type": 5,
                                        "textContent": " 引入录屏所需文件 ",
                                        "id": 13
                                    },
                                    {
                                        "type": 3,
                                        "textContent": "\n  ",
                                        "id": 14
                                    },
                                    {
                                        "type": 2,
                                        "tagName": "link",
                                        "attributes": {
                                            "_cssText": ".replayer-wrapper { position: relative; }.replayer-mouse { position: absolute; width: 20px; height: 20px; transition: all 0.05s linear 0s; background-size: contain; background-position: 50% center; background-repeat: no-repeat; background-image: url(\"data:image/svg+xml;base64,PHN2ZyBoZWlnaHQ9IjMwMCIgd2lkdGg9IjMwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiBkYXRhLW5hbWU9IkxheWVyIDEiIHZpZXdCb3g9IjAgMCA1MCA1MCI+PHBhdGggZD0iTTQ4LjcxIDQyLjkxTDM0LjA4IDI4LjI5IDQ0LjMzIDE4YTEgMSAwIDAwLS4zMy0xLjYxTDIuMzUgMS4wNmExIDEgMCAwMC0xLjI5IDEuMjlMMTYuMzkgNDRhMSAxIDAgMDAxLjY1LjM2bDEwLjI1LTEwLjI4IDE0LjYyIDE0LjYzYTEgMSAwIDAwMS40MSAwbDQuMzgtNC4zOGExIDEgMCAwMC4wMS0xLjQyem0tNS4wOSAzLjY3TDI5IDMyYTEgMSAwIDAwLTEuNDEgMGwtOS44NSA5Ljg1TDMuNjkgMy42OWwzOC4xMiAxNEwzMiAyNy41OEExIDEgMCAwMDMyIDI5bDE0LjU5IDE0LjYyeiIvPjwvc3ZnPg==\"); }.replayer-mouse::after { content: \"\"; display: inline-block; width: 20px; height: 20px; border-radius: 10px; background: rgb(73, 80, 246); transform: translate(-10px, -10px); opacity: 0.3; }.replayer-mouse.active::after { animation: 0.2s ease-in-out 0s 1 normal none running click; }.replayer-mouse-tail { position: absolute; pointer-events: none; }@keyframes click { \n  0% { opacity: 0.3; width: 20px; height: 20px; border-radius: 10px; transform: translate(-10px, -10px); }\n  50% { opacity: 0.5; width: 10px; height: 10px; border-radius: 5px; transform: translate(-5px, -5px); }\n}"
                                        },
                                        "childNodes": [],
                                        "id": 15
                                    },
                                    {
                                        "type": 3,
                                        "textContent": "\n  ",
                                        "id": 16
                                    },
                                    {
                                        "type": 2,
                                        "tagName": "script",
                                        "attributes": {
                                            "src": "https://cdn.jsdelivr.net/npm/rrweb@latest/dist/rrweb.min.js"
                                        },
                                        "childNodes": [],
                                        "id": 17
                                    },
                                    {
                                        "type": 3,
                                        "textContent": "\n  ",
                                        "id": 18
                                    },
                                    {
                                        "type": 5,
                                        "textContent": " rrweb播放器 ",
                                        "id": 19
                                    },
                                    {
                                        "type": 3,
                                        "textContent": "\n  ",
                                        "id": 20
                                    },
                                    {
                                        "type": 2,
                                        "tagName": "link",
                                        "attributes": {
                                            "_cssText": ".replayer-wrapper { position: relative; }.replayer-mouse { position: absolute; width: 20px; height: 20px; transition: all 0.05s linear 0s; background-size: contain; background-position: 50% center; background-repeat: no-repeat; background-image: url(\"data:image/svg+xml;base64,PHN2ZyBoZWlnaHQ9IjMwMCIgd2lkdGg9IjMwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiBkYXRhLW5hbWU9IkxheWVyIDEiIHZpZXdCb3g9IjAgMCA1MCA1MCI+PHBhdGggZD0iTTQ4LjcxIDQyLjkxTDM0LjA4IDI4LjI5IDQ0LjMzIDE4YTEgMSAwIDAwLS4zMy0xLjYxTDIuMzUgMS4wNmExIDEgMCAwMC0xLjI5IDEuMjlMMTYuMzkgNDRhMSAxIDAgMDAxLjY1LjM2bDEwLjI1LTEwLjI4IDE0LjYyIDE0LjYzYTEgMSAwIDAwMS40MSAwbDQuMzgtNC4zOGExIDEgMCAwMC4wMS0xLjQyem0tNS4wOSAzLjY3TDI5IDMyYTEgMSAwIDAwLTEuNDEgMGwtOS44NSA5Ljg1TDMuNjkgMy42OWwzOC4xMiAxNEwzMiAyNy41OEExIDEgMCAwMDMyIDI5bDE0LjU5IDE0LjYyeiIvPjwvc3ZnPg==\"); }.replayer-mouse::after { content: \"\"; display: inline-block; width: 20px; height: 20px; border-radius: 10px; background: rgb(73, 80, 246); transform: translate(-10px, -10px); opacity: 0.3; }.replayer-mouse.active::after { animation: 0.2s ease-in-out 0s 1 normal none running click; }.replayer-mouse-tail { position: absolute; pointer-events: none; }@keyframes click { \n  0% { opacity: 0.3; width: 20px; height: 20px; border-radius: 10px; transform: translate(-10px, -10px); }\n  50% { opacity: 0.5; width: 10px; height: 10px; border-radius: 5px; transform: translate(-5px, -5px); }\n}.rr-player { position: relative; background: white; float: left; border-radius: 5px; box-shadow: rgba(17, 16, 62, 0.12) 0px 24px 48px; }.rr-player__frame { overflow: hidden; }.replayer-wrapper { float: left; clear: both; transform-origin: left top; left: 50%; top: 50%; }.replayer-wrapper > iframe { border: none; }.rr-controller.svelte-19ke1iv.svelte-19ke1iv { width: 100%; height: 80px; background: rgb(255, 255, 255); display: flex; flex-direction: column; justify-content: space-around; align-items: center; border-radius: 0px 0px 5px 5px; }.rr-timeline.svelte-19ke1iv.svelte-19ke1iv { width: 80%; display: flex; align-items: center; }.rr-timeline__time.svelte-19ke1iv.svelte-19ke1iv { display: inline-block; width: 100px; text-align: center; color: rgb(17, 16, 62); }.rr-progress.svelte-19ke1iv.svelte-19ke1iv { flex: 1 1 0%; height: 12px; background: rgb(238, 238, 238); position: relative; border-radius: 3px; cursor: pointer; box-sizing: border-box; border-top: 4px solid rgb(255, 255, 255); border-bottom: 4px solid rgb(255, 255, 255); }.rr-progress.disabled.svelte-19ke1iv.svelte-19ke1iv { cursor: not-allowed; }.rr-progress__step.svelte-19ke1iv.svelte-19ke1iv { height: 100%; position: absolute; left: 0px; top: 0px; background: rgb(224, 225, 254); }.rr-progress__handler.svelte-19ke1iv.svelte-19ke1iv { width: 20px; height: 20px; border-radius: 10px; position: absolute; top: 2px; transform: translate(-50%, -50%); background: rgb(73, 80, 246); }.rr-controller__btns.svelte-19ke1iv.svelte-19ke1iv { display: flex; align-items: center; justify-content: center; font-size: 13px; }.rr-controller__btns.svelte-19ke1iv button.svelte-19ke1iv { width: 32px; height: 32px; display: flex; padding: 0px; align-items: center; justify-content: center; background: none; border: none; border-radius: 50%; cursor: pointer; }.rr-controller__btns.svelte-19ke1iv button.svelte-19ke1iv:active { background: rgb(224, 225, 254); }.rr-controller__btns.svelte-19ke1iv button.active.svelte-19ke1iv { color: rgb(255, 255, 255); background: rgb(73, 80, 246); }.rr-controller__btns.svelte-19ke1iv button.svelte-19ke1iv:disabled { cursor: not-allowed; }.switch.svelte-9brlez.svelte-9brlez { height: 1em; display: flex; align-items: center; }.switch.disabled.svelte-9brlez.svelte-9brlez { opacity: 0.5; }.label.svelte-9brlez.svelte-9brlez { margin: 0px 8px; }.switch.svelte-9brlez input[type=\"checkbox\"].svelte-9brlez { position: absolute; opacity: 0; }.switch.svelte-9brlez label.svelte-9brlez { width: 2em; height: 1em; position: relative; cursor: pointer; display: block; }.switch.disabled.svelte-9brlez label.svelte-9brlez { cursor: not-allowed; }.switch.svelte-9brlez label.svelte-9brlez::before { content: \"\"; position: absolute; width: 2em; height: 1em; left: 0.1em; transition: background 0.1s ease 0s; background: rgba(73, 80, 246, 0.5); border-radius: 50px; }.switch.svelte-9brlez label.svelte-9brlez::after { content: \"\"; position: absolute; width: 1em; height: 1em; border-radius: 50px; left: 0px; transition: all 0.2s ease 0s; box-shadow: rgba(0, 0, 0, 0.3) 0px 2px 5px 0px; background: rgb(252, 255, 244); animation: 0.2s ease-out 0s 1 normal none running switch-off; z-index: 2; }.switch input[type=\"checkbox\"]:checked + label.svelte-9brlez.svelte-9brlez::before { background: rgb(73, 80, 246); }.switch input[type=\"checkbox\"]:checked + label.svelte-9brlez.svelte-9brlez::after { animation: 0.2s ease-out 0s 1 normal none running switch-on; left: 1.1em; }"
                                        },
                                        "childNodes": [],
                                        "id": 21
                                    },
                                    {
                                        "type": 3,
                                        "textContent": "\n  ",
                                        "id": 22
                                    },
                                    {
                                        "type": 2,
                                        "tagName": "script",
                                        "attributes": {
                                            "src": "https://cdn.jsdelivr.net/npm/rrweb-player@latest/dist/index.js"
                                        },
                                        "childNodes": [],
                                        "id": 23
                                    },
                                    {
                                        "type": 3,
                                        "textContent": "\n  ",
                                        "id": 24
                                    },
                                    {
                                        "type": 2,
                                        "tagName": "link",
                                        "attributes": {
                                            "_cssText": "* { margin: 0px; padding: 0px; }iframe { border: none; }.rrweb-container { text-align: center; }.rrweb-container .rrweb-content { display: flex; width: 100%; height: 100px; }.rrweb-container .rrweb-content .red { flex: 1 1 0%; background-color: red; }.rrweb-container .rrweb-content .green { flex: 1 1 0%; background-color: green; }.rrweb-container .rrweb-content .blue { flex: 1 1 0%; background-color: blue; }.rrweb-container .rrweb-button { margin-top: 10px; }.rrweb-container .rrweb-button button { width: 100px; height: 40px; }.rrweb-container .rrweb-alert { width: 100%; height: 300px; line-height: 300px; margin-top: 10px; color: rgb(255, 255, 255); background-color: rgb(0, 0, 0); display: none; }"
                                        },
                                        "childNodes": [],
                                        "id": 25
                                    },
                                    {
                                        "type": 3,
                                        "textContent": "\n",
                                        "id": 26
                                    }
                                ],
                                "id": 4
                            },
                            {
                                "type": 3,
                                "textContent": "\n\n",
                                "id": 27
                            },
                            {
                                "type": 2,
                                "tagName": "body",
                                "attributes": {},
                                "childNodes": [
                                    {
                                        "type": 3,
                                        "textContent": "\n  ",
                                        "id": 29
                                    },
                                    {
                                        "type": 2,
                                        "tagName": "div",
                                        "attributes": {
                                            "class": "rrweb-container"
                                        },
                                        "childNodes": [
                                            {
                                                "type": 3,
                                                "textContent": "\n    ",
                                                "id": 31
                                            },
                                            {
                                                "type": 2,
                                                "tagName": "h1",
                                                "attributes": {},
                                                "childNodes": [
                                                    {
                                                        "type": 3,
                                                        "textContent": "录屏",
                                                        "id": 33
                                                    }
                                                ],
                                                "id": 32
                                            },
                                            {
                                                "type": 3,
                                                "textContent": "\n    ",
                                                "id": 34
                                            },
                                            {
                                                "type": 2,
                                                "tagName": "div",
                                                "attributes": {
                                                    "class": "rrweb-content"
                                                },
                                                "childNodes": [
                                                    {
                                                        "type": 3,
                                                        "textContent": "\n      ",
                                                        "id": 36
                                                    },
                                                    {
                                                        "type": 2,
                                                        "tagName": "div",
                                                        "attributes": {
                                                            "class": "red",
                                                            "data-content": "red"
                                                        },
                                                        "childNodes": [],
                                                        "id": 37
                                                    },
                                                    {
                                                        "type": 3,
                                                        "textContent": "\n      ",
                                                        "id": 38
                                                    },
                                                    {
                                                        "type": 2,
                                                        "tagName": "div",
                                                        "attributes": {
                                                            "class": "green",
                                                            "data-content": "green"
                                                        },
                                                        "childNodes": [],
                                                        "id": 39
                                                    },
                                                    {
                                                        "type": 3,
                                                        "textContent": "\n      ",
                                                        "id": 40
                                                    },
                                                    {
                                                        "type": 2,
                                                        "tagName": "div",
                                                        "attributes": {
                                                            "class": "blue",
                                                            "data-content": "blue"
                                                        },
                                                        "childNodes": [],
                                                        "id": 41
                                                    },
                                                    {
                                                        "type": 3,
                                                        "textContent": "\n    ",
                                                        "id": 42
                                                    }
                                                ],
                                                "id": 35
                                            },
                                            {
                                                "type": 3,
                                                "textContent": "\n    ",
                                                "id": 43
                                            },
                                            {
                                                "type": 2,
                                                "tagName": "div",
                                                "attributes": {
                                                    "class": "rrweb-button"
                                                },
                                                "childNodes": [
                                                    {
                                                        "type": 3,
                                                        "textContent": "\n      ",
                                                        "id": 45
                                                    },
                                                    {
                                                        "type": 2,
                                                        "tagName": "button",
                                                        "attributes": {},
                                                        "childNodes": [
                                                            {
                                                                "type": 3,
                                                                "textContent": "录制",
                                                                "id": 47
                                                            }
                                                        ],
                                                        "id": 46
                                                    },
                                                    {
                                                        "type": 3,
                                                        "textContent": "\n      ",
                                                        "id": 48
                                                    },
                                                    {
                                                        "type": 2,
                                                        "tagName": "button",
                                                        "attributes": {},
                                                        "childNodes": [
                                                            {
                                                                "type": 3,
                                                                "textContent": "停止",
                                                                "id": 50
                                                            }
                                                        ],
                                                        "id": 49
                                                    },
                                                    {
                                                        "type": 3,
                                                        "textContent": "\n      ",
                                                        "id": 51
                                                    },
                                                    {
                                                        "type": 2,
                                                        "tagName": "button",
                                                        "attributes": {},
                                                        "childNodes": [
                                                            {
                                                                "type": 3,
                                                                "textContent": "播放",
                                                                "id": 53
                                                            }
                                                        ],
                                                        "id": 52
                                                    },
                                                    {
                                                        "type": 3,
                                                        "textContent": "\n      ",
                                                        "id": 54
                                                    },
                                                    {
                                                        "type": 2,
                                                        "tagName": "button",
                                                        "attributes": {},
                                                        "childNodes": [
                                                            {
                                                                "type": 3,
                                                                "textContent": "绘制canvas",
                                                                "id": 56
                                                            }
                                                        ],
                                                        "id": 55
                                                    },
                                                    {
                                                        "type": 3,
                                                        "textContent": "\n    ",
                                                        "id": 57
                                                    }
                                                ],
                                                "id": 44
                                            },
                                            {
                                                "type": 3,
                                                "textContent": "\n    ",
                                                "id": 58
                                            },
                                            {
                                                "type": 2,
                                                "tagName": "div",
                                                "attributes": {
                                                    "class": "rrweb-alert"
                                                },
                                                "childNodes": [],
                                                "id": 59
                                            },
                                            {
                                                "type": 3,
                                                "textContent": "\n    ",
                                                "id": 60
                                            },
                                            {
                                                "type": 2,
                                                "tagName": "canvas",
                                                "attributes": {
                                                    "id": "myCanvas",
                                                    "width": "200",
                                                    "height": "100",
                                                    "style": "border: 1px solid #000000;margin-top: 10px;",
                                                    "rr_dataURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMgAAABkCAYAAADDhn8LAAACnklEQVR4Xu3VsRHAMAzEsHj/pTOBXbB9pFchyLycz0eAwFXgsCFA4C4gEK+DwENAIJ4HAYF4AwSagD9IczM1IiCQkUNbswkIpLmZGhEQyMihrdkEBNLcTI0ICGTk0NZsAgJpbqZGBAQycmhrNgGBNDdTIwICGTm0NZuAQJqbqREBgYwc2ppNQCDNzdSIgEBGDm3NJiCQ5mZqREAgI4e2ZhMQSHMzNSIgkJFDW7MJCKS5mRoREMjIoa3ZBATS3EyNCAhk5NDWbAICaW6mRgQEMnJoazYBgTQ3UyMCAhk5tDWbgECam6kRAYGMHNqaTUAgzc3UiIBARg5tzSYgkOZmakRAICOHtmYTEEhzMzUiIJCRQ1uzCQikuZkaERDIyKGt2QQE0txMjQgIZOTQ1mwCAmlupkYEBDJyaGs2AYE0N1MjAgIZObQ1m4BAmpupEQGBjBzamk1AIM3N1IiAQEYObc0mIJDmZmpEQCAjh7ZmExBIczM1IiCQkUNbswkIpLmZGhEQyMihrdkEBNLcTI0ICGTk0NZsAgJpbqZGBAQycmhrNgGBNDdTIwICGTm0NZuAQJqbqREBgYwc2ppNQCDNzdSIgEBGDm3NJiCQ5mZqREAgI4e2ZhMQSHMzNSIgkJFDW7MJCKS5mRoREMjIoa3ZBATS3EyNCAhk5NDWbAICaW6mRgQEMnJoazYBgTQ3UyMCAhk5tDWbgECam6kRAYGMHNqaTUAgzc3UiIBARg5tzSYgkOZmakRAICOHtmYTEEhzMzUiIJCRQ1uzCQikuZkaERDIyKGt2QQE0txMjQgIZOTQ1mwCAmlupkYEBDJyaGs2AYE0N1MjAgIZObQ1m4BAmpupEQGBjBzamk1AIM3N1IiAQEYObc0mIJDmZmpE4Af1gABlH0hlGgAAAABJRU5ErkJggg=="
                                                },
                                                "childNodes": [],
                                                "id": 61
                                            },
                                            {
                                                "type": 3,
                                                "textContent": "\n  ",
                                                "id": 62
                                            }
                                        ],
                                        "id": 30
                                    },
                                    {
                                        "type": 3,
                                        "textContent": "\n\n",
                                        "id": 63
                                    },
                                    {
                                        "type": 5,
                                        "textContent": " Code injected by live-server ",
                                        "id": 64
                                    },
                                    {
                                        "type": 3,
                                        "textContent": "\n",
                                        "id": 65
                                    },
                                    {
                                        "type": 2,
                                        "tagName": "script",
                                        "attributes": {
                                            "type": "text/javascript"
                                        },
                                        "childNodes": [
                                            {
                                                "type": 3,
                                                "textContent": "SCRIPT_PLACEHOLDER",
                                                "id": 67
                                            }
                                        ],
                                        "id": 66
                                    },
                                    {
                                        "type": 3,
                                        "textContent": "\n",
                                        "id": 68
                                    },
                                    {
                                        "type": 2,
                                        "tagName": "script",
                                        "attributes": {},
                                        "childNodes": [
                                            {
                                                "type": 3,
                                                "textContent": "SCRIPT_PLACEHOLDER",
                                                "id": 70
                                            }
                                        ],
                                        "id": 69
                                    },
                                    {
                                        "type": 2,
                                        "tagName": "script",
                                        "attributes": {
                                            "src": "http://127.0.0.1:5500/index.js?v=0.14918186012471057"
                                        },
                                        "childNodes": [],
                                        "id": 71
                                    },
                                    {
                                        "type": 3,
                                        "textContent": "\n",
                                        "id": 72
                                    },
                                    {
                                        "type": 5,
                                        "textContent": " <script src=\"./index.js\"></script> ",
                                        "id": 73
                                    },
                                    {
                                        "type": 3,
                                        "textContent": "\n",
                                        "id": 74
                                    },
                                    {
                                        "type": 5,
                                        "textContent": " <script src=\" ./canvas.js\"></script> ",
                                        "id": 75
                                    },
                                    {
                                        "type": 3,
                                        "textContent": "\n\n",
                                        "id": 76
                                    },
                                    {
                                        "type": 2,
                                        "tagName": "script",
                                        "attributes": {
                                            "src": "http://127.0.0.1:5500/canvas.js?v=0.3713288516156219"
                                        },
                                        "childNodes": [],
                                        "id": 77
                                    },
                                    {
                                        "type": 2,
                                        "tagName": "iframe",
                                        "attributes": {
                                            "style": "overflow: hidden; position: fixed; height: 155px; width: 400px; bottom: 20px; right: 20px; background: none; border: none; z-index: 2147483646; visibility: hidden; user-select: none;"
                                        },
                                        "childNodes": [],
                                        "id": 78
                                    }
                                ],
                                "id": 28
                            }
                        ],
                        "id": 3
                    }
                ],
                "id": 1
            },
            "initialOffset": {
                "left": 0,
                "top": 0
            }
        },
        "timestamp": 1629862511206,
        "delay": 7
    },
    {
        "type": 3,
        "data": {
            "source": 1,
            "positions": [
                {
                    "x": 248,
                    "y": 175,
                    "id": 46,
                    "timeOffset": 0
                }
            ]
        },
        "timestamp": 1629862511293,
        "delay": 94
    },
    {
        "type": 3,
        "data": {
            "source": 2,
            "type": 1,
            "id": 37,
            "x": 185,
            "y": 101
        },
        "timestamp": 1629862511542,
        "delay": 343
    },
    {
        "type": 3,
        "data": {
            "source": 2,
            "type": 6,
            "id": 46
        },
        "timestamp": 1629862511542,
        "delay": 343
    },
    {
        "type": 3,
        "data": {
            "source": 2,
            "type": 0,
            "id": 37,
            "x": 185,
            "y": 101
        },
        "timestamp": 1629862511604,
        "delay": 405
    },
    {
        "type": 3,
        "data": {
            "source": 2,
            "type": 2,
            "id": 37,
            "x": 185,
            "y": 101
        },
        "timestamp": 1629862511604,
        "delay": 405
    },
    {
        "type": 3,
        "data": {
            "source": 0,
            "texts": [],
            "attributes": [
                {
                    "id": 59,
                    "attributes": {
                        "style": {
                            "background-color": "red",
                            "display": "block"
                        }
                    }
                }
            ],
            "removes": [],
            "adds": [
                {
                    "parentId": 59,
                    "nextId": null,
                    "node": {
                        "type": 3,
                        "textContent": "这是红色盒子的点击事件触发的",
                        "id": 79
                    }
                }
            ]
        },
        "timestamp": 1629862511607,
        "delay": 408
    },
    {
        "type": 3,
        "data": {
            "source": 1,
            "positions": [
                {
                    "x": 220,
                    "y": 151,
                    "id": 46,
                    "timeOffset": -456
                },
                {
                    "x": 211,
                    "y": 140,
                    "id": 37,
                    "timeOffset": -405
                },
                {
                    "x": 195,
                    "y": 117,
                    "id": 37,
                    "timeOffset": -352
                },
                {
                    "x": 186,
                    "y": 102,
                    "id": 37,
                    "timeOffset": -295
                },
                {
                    "x": 188,
                    "y": 100,
                    "id": 37,
                    "timeOffset": -144
                },
                {
                    "x": 259,
                    "y": 97,
                    "id": 37,
                    "timeOffset": -88
                },
                {
                    "x": 333,
                    "y": 94,
                    "id": 39,
                    "timeOffset": -32
                }
            ]
        },
        "timestamp": 1629862511804,
        "delay": 149
    },
    {
        "type": 3,
        "data": {
            "source": 2,
            "type": 1,
            "id": 39,
            "x": 351,
            "y": 91
        },
        "timestamp": 1629862511905,
        "delay": 706
    },
    {
        "type": 3,
        "data": {
            "source": 2,
            "type": 0,
            "id": 39,
            "x": 351,
            "y": 91
        },
        "timestamp": 1629862511966,
        "delay": 767
    },
    {
        "type": 3,
        "data": {
            "source": 2,
            "type": 2,
            "id": 39,
            "x": 351,
            "y": 91
        },
        "timestamp": 1629862511967,
        "delay": 768
    },
    {
        "type": 3,
        "data": {
            "source": 0,
            "texts": [],
            "attributes": [
                {
                    "id": 59,
                    "attributes": {
                        "style": {
                            "background-color": "green"
                        }
                    }
                }
            ],
            "removes": [
                {
                    "parentId": 59,
                    "id": 79
                }
            ],
            "adds": [
                {
                    "parentId": 59,
                    "nextId": null,
                    "node": {
                        "type": 3,
                        "textContent": "这是绿色盒子的点击事件触发的",
                        "id": 80
                    }
                }
            ]
        },
        "timestamp": 1629862511968,
        "delay": 769
    },
    {
        "type": 3,
        "data": {
            "source": 1,
            "positions": [
                {
                    "x": 351,
                    "y": 91,
                    "id": 39,
                    "timeOffset": -464
                },
                {
                    "x": 354,
                    "y": 91,
                    "id": 39,
                    "timeOffset": -311
                },
                {
                    "x": 437,
                    "y": 92,
                    "id": 39,
                    "timeOffset": -256
                },
                {
                    "x": 532,
                    "y": 95,
                    "id": 39,
                    "timeOffset": -192
                },
                {
                    "x": 560,
                    "y": 95,
                    "id": 41,
                    "timeOffset": -136
                },
                {
                    "x": 626,
                    "y": 95,
                    "id": 41,
                    "timeOffset": -79
                },
                {
                    "x": 653,
                    "y": 95,
                    "id": 41,
                    "timeOffset": -24
                }
            ]
        },
        "timestamp": 1629862512308,
        "delay": 645
    },
    {
        "type": 3,
        "data": {
            "source": 2,
            "type": 1,
            "id": 41,
            "x": 694,
            "y": 95
        },
        "timestamp": 1629862512341,
        "delay": 1142
    },
    {
        "type": 3,
        "data": {
            "source": 2,
            "type": 0,
            "id": 41,
            "x": 694,
            "y": 95
        },
        "timestamp": 1629862512421,
        "delay": 1222
    },
    {
        "type": 3,
        "data": {
            "source": 2,
            "type": 2,
            "id": 41,
            "x": 694,
            "y": 95
        },
        "timestamp": 1629862512421,
        "delay": 1222
    },
    {
        "type": 3,
        "data": {
            "source": 0,
            "texts": [],
            "attributes": [
                {
                    "id": 59,
                    "attributes": {
                        "style": {
                            "background-color": "blue"
                        }
                    }
                }
            ],
            "removes": [
                {
                    "parentId": 59,
                    "id": 80
                }
            ],
            "adds": [
                {
                    "parentId": 59,
                    "nextId": null,
                    "node": {
                        "type": 3,
                        "textContent": "这是蓝色盒子的点击事件触发的",
                        "id": 81
                    }
                }
            ]
        },
        "timestamp": 1629862512422,
        "delay": 1223
    },
    {
        "type": 3,
        "data": {
            "source": 1,
            "positions": [
                {
                    "x": 694,
                    "y": 95,
                    "id": 41,
                    "timeOffset": -470
                },
                {
                    "x": 695,
                    "y": 95,
                    "id": 41,
                    "timeOffset": -351
                },
                {
                    "x": 660,
                    "y": 135,
                    "id": 41,
                    "timeOffset": -287
                },
                {
                    "x": 569,
                    "y": 228,
                    "id": 59,
                    "timeOffset": -231
                },
                {
                    "x": 505,
                    "y": 285,
                    "id": 59,
                    "timeOffset": -175
                },
                {
                    "x": 485,
                    "y": 300,
                    "id": 59,
                    "timeOffset": -111
                },
                {
                    "x": 478,
                    "y": 304,
                    "id": 59,
                    "timeOffset": -46
                }
            ]
        },
        "timestamp": 1629862512811,
        "delay": 1142
    },
    {
        "type": 3,
        "data": {
            "source": 2,
            "type": 1,
            "id": 59,
            "x": 478,
            "y": 304
        },
        "timestamp": 1629862512907,
        "delay": 1708
    },
    {
        "type": 3,
        "data": {
            "source": 2,
            "type": 0,
            "id": 59,
            "x": 478,
            "y": 304
        },
        "timestamp": 1629862512964,
        "delay": 1765
    },
    {
        "type": 3,
        "data": {
            "source": 2,
            "type": 2,
            "id": 59,
            "x": 478,
            "y": 304
        },
        "timestamp": 1629862512965,
        "delay": 1766
    },
    {
        "type": 3,
        "data": {
            "source": 0,
            "texts": [],
            "attributes": [
                {
                    "id": 59,
                    "attributes": {
                        "style": {
                            "display": "none"
                        }
                    }
                }
            ],
            "removes": [],
            "adds": []
        },
        "timestamp": 1629862512965,
        "delay": 1766
    },
    {
        "type": 3,
        "data": {
            "source": 1,
            "positions": [
                {
                    "x": 478,
                    "y": 301,
                    "id": 61,
                    "timeOffset": -309
                },
                {
                    "x": 440,
                    "y": 229,
                    "id": 61,
                    "timeOffset": -257
                },
                {
                    "x": 408,
                    "y": 203,
                    "id": 61,
                    "timeOffset": -207
                },
                {
                    "x": 406,
                    "y": 200,
                    "id": 30,
                    "timeOffset": -156
                },
                {
                    "x": 397,
                    "y": 195,
                    "id": 30,
                    "timeOffset": -104
                },
                {
                    "x": 391,
                    "y": 193,
                    "id": 30,
                    "timeOffset": -48
                }
            ]
        },
        "timestamp": 1629862513316,
        "delay": 1808
    },
    {
        "type": 3,
        "data": {
            "source": 2,
            "type": 1,
            "id": 49,
            "x": 385,
            "y": 185
        },
        "timestamp": 1629862513422,
        "delay": 2223
    },
    {
        "type": 3,
        "data": {
            "source": 2,
            "type": 5,
            "id": 49
        },
        "timestamp": 1629862513422,
        "delay": 2223
    },
    {
        "type": 3,
        "data": {
            "source": 2,
            "type": 0,
            "id": 49,
            "x": 385,
            "y": 185
        },
        "timestamp": 1629862513476,
        "delay": 2277
    },
    {
        "type": 3,
        "data": {
            "source": 2,
            "type": 2,
            "id": 49,
            "x": 385,
            "y": 185
        },
        "timestamp": 1629862513476,
        "delay": 2277
    },
    {
        "type": 3,
        "data": {
            "source": 1,
            "positions": [
                {
                    "x": 387,
                    "y": 189,
                    "id": 49,
                    "timeOffset": -497
                },
                {
                    "x": 385,
                    "y": 185,
                    "id": 49,
                    "timeOffset": -408
                }
            ]
        },
        "timestamp": 1629862513821,
        "delay": 2125
    }
]

**Comment by MengHao233** [comment]
遇到了同样的问题，回放时 style 显示的为 [Object Object]

**Comment by woshidahuaidan** [comment]
有找到方法解决这个问题吗？我也遇到了

**Comment by Yuyz0112** [comment]
@WhyAlive @MengHao233 @woshidahuaidan 

使用的版本是？我在最新的 master 上用 issue 里的 events 好像没有遇到问题

![Kapture 2021-09-13 at 20 08 59](https://user-images.githubusercontent.com/13651389/133080979-29145cfa-5fba-45cb-987d-48914499d78b.gif)

**Comment by woshidahuaidan** [comment]
使用的是0.9.12版本的------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年9月13日(星期一) 晚上8:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [rrweb-io/rrweb] rrweb-plyer 回放时，style显示的为[Object Object] (#676)

**Comment by Yuyz0112** [comment]
最新版本如果还有该问题请 reopen

**Comment by liurongliurong** [comment]
您好，请问解决了吗？我也遇到这样的问题
