### ISSUE TITLE
录制出现空白不显示问题

### ISSUE THREAD

**Issue by liurongliurong** [rrweb-io/rrweb#677]
<van-form  v-show="lsresPai" ref="formxx" :scroll-to-error="true"></van-form>

代码如上。

vant表单组件上面使用v-show，会导致其他兄弟元素以及这一块表单所有的元素都录制不上，录制的时候这一块显示空白。

**Comment by yanglilong127** [comment]
我也是啊   我用的v-if有时候也会有这样的问题   在ie11浏览器上面

**Comment by PeterChen1997** [comment]
+1 https://github.com/rrweb-io/rrweb/issues/700

**Comment by PeterChen1997** [comment]
尝试升级下 player 版本看看呢，我升级后修复了
