### ISSUE TITLE
Getting a rrweb player error when try to load it via your cdn

### ISSUE THREAD

**Issue by upifyio** [rrweb-io/rrweb#681]
Hey there,
I'm getting this error:
Could not load content for https://cdn.jsdelivr.net/npm/rrweb-player@latest/src/main.ts (HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE)

**Comment by Yuyz0112** [comment]
going to publish a hotfix

**Comment by upifyio** [comment]
@Yuyz0112 
When will it be available? :)

**Comment by Yuyz0112** [comment]
you can use 0.7.4 at this moment

**Comment by upifyio** [comment]
Just load like this right:
https://cdn.jsdelivr.net/npm/rrweb-player@0.7.4/dist/index.js

**Comment by Yuyz0112** [comment]
@upifyio Has published the hot fix version and purge CDN files.
