### ISSUE TITLE
this.config.root is null

### ISSUE THREAD

**Issue by o-kamalGit** [rrweb-io/rrweb#683]
Hi,
I'm facing this issue this.config.root is null and when I checked in the GitHub repository I found that it was closed so why I'm facing it.
I followed your documentation and used your CDN files and it is not working.
Here is what I did following the doc.

```
<html>
    <head>
        <title>Player</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
       <link
            rel="stylesheet"
            href="https://cdn.jsdelivr.net/npm/rrweb@latest/dist/rrweb.min.css"
    />
    <script src="https://cdn.jsdelivr.net/npm/rrweb@latest/dist/rrweb.min.js"></script>
        <script>
            var events = {"events":[{"type":3,"data":{"source":1,"positions":[{"x":733,"y":336,"id":4,"timeOffset":0}]},"timestamp":1630323239708},{"type":3,"data":{"source":1,"positions":[{"x":676,"y":203,"id":4,"timeOffset":-447},{"x":665,"y":138,"id":4,"timeOffset":-397},{"x":653,"y":51,"id":26,"timeOffset":-346}]},"timestamp":1630323240209}]};
                console.log(events);
                let player = new rrweb.Replayer({
                root: document.body, // customizable root element
                data: {
                  events
                }
              });
                player.play(events);
        </script>
    </head>
    <body>
        <div id='player'></div>
    </body>
</html> 
```
I was able to follow your documentation to do the record but it is not working for reading a recording so I'm sure your documentation is confusion or something is missing.

Thanks.

**Comment by o-kamalGit** [comment]
OK, I followed you suggestions and surrounding the events I have with [] made it an array and that this.config.root is no longer showing, instead I'm seeing "" as you motioned and this is wired because to save the screen I also followed your tutorial and the code is below:

```
<html>
    <head>
        <title>Recorder</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="css/rrweb.min.css"/>
        <script src="js/rrweb-record.js"></script>
        <script>
            var events = [];
            rrwebRecord({
              emit(event) {
                // push event into the events array
                events.push(event);
              }
            });

            // this function will send events to the backend and reset the events array
            function save() {
                if(events.length > 0){
                    var body = JSON.stringify({ events });
                    events = [];
                    fetch('recorder.php', {
                      mode: 'no-cors',
                      method: 'POST',
                      headers: {
                        'Content-Type': 'application/json'
                      },
                      body: body
                    });
                }
            }
            // save events every 5 seconds
            setInterval(save, 5 * 1000);
        </script>
    </head>
    <body>
        <div>
            <form action="/action_page.php">
                <label for="fname">First name:</label><br>
                <input type="text" id="fname" name="fname" value="John"><br>
                <label for="lname">Last name:</label><br>
                <input type="text" id="lname" name="lname" value="Doe"><br><br>
                <input type="submit" value="Submit">
            </form> 
        </div>
    </body>
</html>
```
As you can see in the capture below, the fetch is sending data to my back-end every 5 seconds and from the console log I can see that one of the data sent looks like: 
`{"events":[{"type":3,"data":{"source":2,"type":6,"id":39},"timestamp":1630336065224},{"type":3,"data":{"source":2,"type":6,"id":1},"timestamp":1630336065224}]} `

So there is nothing missing from it, it does simply not have an event with type 2.

Is there something wrong with the way I'm collecting the events?

I have attached an image of my console: [console log](https://ibb.co/NFmgXTy)

Thanks.

**Comment by Yuyz0112** [comment]
@o-kamalGit 

Please add this console.log in the record side and check the events emitted.

```
            rrwebRecord({
              emit(event) {
                console.log(event) <- check this
                // push event into the events array
                events.push(event);
              }
            });
```

**Comment by o-kamalGit** [comment]
When I load the page it shows 5 objects with types 0, 1, 2, 3, 4 then after that only type 3 is shown see [here](https://ibb.co/kX6CFjH)

**Comment by Yuyz0112** [comment]
@o-kamalGit 

That's the right behavior. Then you should have an array of events [0, 1, 4, 2, 3, 3, 3, 3, ..., 3]

**Comment by o-kamalGit** [comment]
Oh I suspected that though but if it is the case, when do you consider that a session recording has ended? I mean you cannot show all recordings continuously for a user [0, 1, 4, 2, 3, 3, 3, 3, ..........] ?

**Comment by Yuyz0112** [comment]
A session is end when the record side does not save send any new events, usually is the user left the page.

**Comment by o-kamalGit** [comment]
OK I see, it is actually when the event is empty because it keeps sending events even if you stay on the page whitout touching the mouse, I tired it. Anyway, thanks for your answers :)
