### ISSUE TITLE
回放参数UNSAFE_replayCanvas:true时， 调用preloadAllImages方法进行后使用Canvas画图播放暂停

### ISSUE THREAD

**Issue by lwadsy** [rrweb-io/rrweb#688]
回放参数UNSAFE_replayCanvas:true时， 调用preloadAllImages方法进行后使用Canvas画图，为什么需要暂停播放？
<img width="579" alt="截屏2021-09-02 下午3 49 29" src="https://user-images.githubusercontent.com/17978301/131804426-1d75e1a4-4370-480c-91e7-5a0fc8d22629.png">

**Comment by Yuyz0112** [comment]
Thanks for the report!
