### ISSUE TITLE
Can checkout be triggered manually now?

### ISSUE THREAD

**Issue by shmilyoo** [rrweb-io/rrweb#689]
Previously, this was achieved by stopping the record and restarting it, which was not very elegant

**Comment by Yuyz0112** [comment]
`rrwebRecord.takeFullSnapshot(isCheckout: boolean)` can be used.

https://github.com/rrweb-io/rrweb/blob/master/packages/rrweb/src/record/index.ts#L481

**Comment by shmilyoo** [comment]
@Yuyz0112 👍🏻
