### ISSUE TITLE
Bug in recording events

### ISSUE THREAD

**Issue by hayait599** [rrweb-io/rrweb#69]
I am using rrweb.record from this CDN

`  <script src="https://cdn.jsdelivr.net/npm/rrweb@latest/dist/rrweb.min.js"></script>`

This is how I record my events 
```
let events = [];
  rrweb.record({
     emit(event) {
        events.push(event);
     }
});
```
I call this function every 10 sec 

```
    function save() {
        console.log(events)
        events = [];
    }
    setInterval(save, 10 * 1000);
```
The first record is recorded correctly and displays the dom elements 
other wise all the other events are corrupted  
and data is like this  data: {source: 2, type: 0, id: 40, x: 286, y: 126} 
when I try to play it, it only displays a courser position 

this is the whole code page
```

<html>
<head>
    <!-- <script src="https://cdn.jsdelivr.net/npm/rrweb@latest/dist/record/rrweb-record.min.js"></script> -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/rrweb@latest/dist/rrweb.min.css" />
    <script src="https://cdn.jsdelivr.net/npm/rrweb@latest/dist/rrweb.min.js"></script>
    <!-- <script src="https://cdn.jsdelivr.net/npm/rrweb-player@latest/dist/index.js"></script> -->
    <!-- 
    <script src="https://cdn.jsdelivr.net/npm/rrweb@latest/dist/record/rrweb-record.min.js"></script> -->

</head>
<script>
    let eventsArray = [];
    let events = [];
    rrweb.record({
        emit(event) {
            events.push(event);
        },
    });

    function save() {
        eventsArray.push(events)
        if (eventsArray.length == 1) {
            //  const replayer = new rrweb.Replayer(events);
            // replayer.play();
        }
        console.log(events)
        events = [];
    }
 
    setInterval(save, 10 * 1000);
</script>

<body>
    <ul>
        <li>Coffee</li>
        <li>Tea</li>
        <li>Milk</li>
    </ul>
</body>
</html>
```

**Comment by Yuyz0112** [comment]
So you are recording and replaying in the same page?

**Comment by hayait599** [comment]
this file is for testing, I don't plan to
but event when I do, the first event is played other than it, white screen 
....
in the previews code I console.log ( not replaying the events) the events, the data object content is the cursor position 
...
when I try to replaying those events in different page I have a white screen

**Comment by hayait599** [comment]
I send a file sample ( for the events ) on the community channel before, would you like me to resend it ?
I did not know what was causing the issue back then.
After debugging every recorded event except the first event is like that file :(  ...

**Comment by Yuyz0112** [comment]
@hayait599 yeah, please upload the events file to this issue, it will be helpful.

**Comment by hayait599** [comment]
[Mon-Mar-18-2019-08_04_03-GMT_0000-_Coordinated-Universal-Time_ (1).txt](https://github.com/rrweb-io/rrweb/files/3126730/Mon-Mar-18-2019-08_04_03-GMT_0000-_Coordinated-Universal-Time_.1.txt)

**Comment by Yuyz0112** [comment]
I've checked the events file and looks like it only stores little events and missing the full snapshot.
Where did you store the events? e.g DB or file or something else?

**Comment by hayait599** [comment]
![Capture777](https://user-images.githubusercontent.com/29176402/56893119-4fe5c480-6a8a-11e9-96e1-68b8dfd3a897.PNG)
this is how they are recordedd !! :(

**Comment by Yuyz0112** [comment]
could you check the first 5 event?

**Comment by hayait599** [comment]
![Capture9999](https://user-images.githubusercontent.com/29176402/56945284-5bd79200-6b2f-11e9-9411-fdc6efa452a9.PNG)
![Captureeeeeeeeee](https://user-images.githubusercontent.com/29176402/56945287-5d08bf00-6b2f-11e9-9a03-07cc445d7418.PNG)

**Comment by Yuyz0112** [comment]
@hayait599 Okay, I think I catch your point.

It looks like you are trying to do the following things?
1. store emitted event in an array
2. save the array every 10 seconds and then empty the array
3. try tp replay every 10 seconds events **separately**

The third step will not work because rrweb store event as full snapshot and incremental events, it works like a chain. So you need to concat all the events into one array before replay.

BTW, if you are wishing to have some feature like only keep the last 10 seconds events, you can try this [config](https://github.com/rrweb-io/rrweb/blob/master/guide.md#checkout).

**Comment by hayait599** [comment]
Thank you soo much for the tip :) 
I edited my code like this ( I think you should update the document in case anyone wanted to send the events separately every 10 sec )

```
            let eventsMatrix = [[]];

            rrweb.record({
                emit(event, isCheckout) {
                    if (isCheckout) {
                        eventsMatrix.push([]);
                    }
                    const lastEvents = eventsMatrix[eventsMatrix.length - 1];
                    lastEvents.push(event);

                },
                checkoutEveryNms: 5 * 1000, // checkout every 5 minutes
            });
            function save() { 
                let merged = [].concat.apply([], eventsMatrix);
                if (merged.length == 0) {
                    return
                }
                let body = {
                   record: merged, 
                }
                body = JSON.stringify(body)
                fetch('backend url', { 
                    method: 'POST',
                    mode: 'no-cors',
                    headers: {
                        'Content-Type': 'application/json'
                    },
                    body: body
                }).then(res => console.log(res));
                 eventsMatrix = [[]];
            }
            setInterval(save, 5 * 1000);

```

**Comment by mukeshsalaria01** [comment]
@hayait599 @Yuyz0112  Do you have an end to end working example of this? 

I need the table structure you are using?
I also need how you are merging different events to play a big video. 

I want to merge every 10-second event and play up to 5 minutes of video. Is it possible? 
Also, do you how we will differentiate if it's a new session or old while merging the events?

**Comment by Dhaval-ACE** [comment]
@Yuyz0112  Can I request the whole HTML event during incremental change?

**Comment by pratikshaganage** [comment]
Hey @mukeshsalaria01 Did you get the end to end working example. I am also storing events in an array and wants to send it to backend every 10 seconds and play the video. Can you help?
