### ISSUE TITLE
CSSGroupingRule not supported on Safari

### ISSUE THREAD

**Issue by JohnPhamous** [rrweb-io/rrweb#690]
Safari on desktop and mobile [doesn't support CSSGroupingRule](https://caniuse.com/?search=CSSGroupingRule). This is causing errors when recording on Safari.

```
ReferenceError: Can't find variable: CSSGroupingRule
```

The error is happening [on this line](https://github.com/rrweb-io/rrweb/blob/5dcbfa530f3a1c6d7cadaba076be25e4b263de39/packages/rrweb/src/record/observer.ts#L524).

Not sure what the pattern for handling browser API support. The obvious fix is to check if `CSSGroupingRule` is defined before monkey patching the methods. This would silence the error but would cause the recording to be inaccurate.

Any suggestions @Yuyz0112 and @Juice10 ?

**Comment by Juice10** [comment]
Good catch John, it looks like we have to monkey patch everything that inherits from CCSGroupingRule individually: CSSMediaRule, CSSSupportsRule & CSSConditionRule.

**Comment by Yuyz0112** [comment]
@JohnPhamous Would you love to send a fixed patch in the meantime to avoid the runtime error?

**Comment by Monchi** [comment]
PR submitted: https://github.com/rrweb-io/rrweb/pull/693
