### ISSUE TITLE
是否支持动态添加屏蔽元素

### ISSUE THREAD

**Issue by SGAMERyu** [rrweb-io/rrweb#692]
场景如下: 
初始快照，并没有要屏蔽的元素，需要用户出现一定的行为，才会出现屏蔽元素，此时rrweb会将该元素也录制进去

**Comment by champkeh** [comment]
你可以在需要的时候手动触发一次全量快照，这样就可以基于最新的dom录制后续数据了

**Comment by Yuyz0112** [comment]
@SGAMERyu 屏蔽目前是基于选择器的，后期动态出现的元素，只要在屏蔽范围内（比如 `.rr-block`），应该也会被屏蔽？

**Comment by 961998264** [comment]
请问如何主动（手动）触发rrweb重新来一次全量快照的录制

**Comment by Mark-Fenng** [comment]
@961998264 rrweb.record.takeFullSnapshot(true);
