### ISSUE TITLE
iframe滑动和翻页录制不上

### ISSUE THREAD

**Issue by woshidahuaidan** [rrweb-io/rrweb#698]
在页面引入最新版rrwbe，录制到iframe页面的时候，iframe里面进行滑动和拖拽录制不上，iframe里面进行翻页也录制不上，请问是需要进行什么配置吗？

**Comment by xwLyc** [comment]
> 在页面引入最新版rrwbe，录制到iframe页面的时候，iframe里面进行滑动和拖拽录制不上，iframe里面进行翻页也录制不上，请问是需要进行什么配置吗？

iframe静态的你能录制上？目前我看录制 含有iframe元素的时候都是空白的呀

**Comment by Yuyz0112** [comment]
@woshidahuaidan 拖拽和翻页有具体的例子吗？
