### ISSUE TITLE
Support in Micro-frontend framework

### ISSUE THREAD

**Issue by PeterChen1997** [rrweb-io/rrweb#699]
Hi, we are now add rrweb into qiankun micro-frontend framework's subApp and meet some problem...

The console plugin cannot unmount while we run the stop function, i think maybe we need a unmount lifecycle in plugin?

**Comment by Yuyz0112** [comment]
Hi @PeterChen1997 

After checking the code, I think currently it will unmount plugin observer when calling the `stop` function.

1. The plugin will return a `stop` function in their observer: https://github.com/rrweb-io/rrweb/blob/master/packages/rrweb/src/plugins/console/record/index.ts#L156
2. The `stop` functions returned by plugins have been collected: https://github.com/rrweb-io/rrweb/blob/master/packages/rrweb/src/record/observer.ts#L1017
3. All the `stop` functions will be called when stopping: https://github.com/rrweb-io/rrweb/blob/master/packages/rrweb/src/record/observer.ts#L1033

So could you provide a sample code to reproduce this issue? I think it may be related to the way we patch the global console object.
