### ISSUE TITLE
rrvideo安装完成之后 执行报错

### ISSUE THREAD

**Issue by liubianjiaoshou** [rrweb-io/rrweb#712]
![微信图片_20210926111925](https://user-images.githubusercontent.com/20527468/134792186-eb84b250-1ecf-43d7-8211-f8dc3de96c0d.png)
请问这个怎么解决？

**Comment by Yuyz0112** [comment]
看起来是 puppeteer 安装失败。请参考报错信息里 puppeteer 的 troubleshooting 链接。
