### ISSUE TITLE
[rrweb-player]: can't reply and show NaN:NaN

### ISSUE THREAD

**Issue by zhoushoujian** [rrweb-io/rrweb#714]
It seems play data are correct, but it can't reply success.
reply data: http://charm123.oss-cn-beijing.aliyuncs.com/OSS/monitor/e18d814e-d784-4003-8c2d-a4259ddaca37/7b3e768a-2189-4054-8a96-cef0bdb498e2.json
![image](https://user-images.githubusercontent.com/36908047/135046436-bbdcdf77-2195-403b-afc7-bacde6c77e2a.png)

**Comment by zhoushoujian** [comment]
Can someone explain for this issue? or is it dirty data?

**Comment by Yuyz0112** [comment]
@zhoushoujian 

There are some nested arrays in your data, which is not a valid rrweb events format.

```js
events.reduce((prev, cur) => prev.concat(cur), [])
```

**Comment by Yuyz0112** [comment]
you should check your code, since rrweb just emit events and the storage process was done by you.
