### ISSUE TITLE
No way to gracefully stop or destroy Replayer when removing or unmounting DOM

### ISSUE THREAD

**Issue by wbobeirne** [rrweb-io/rrweb#715]
I'm using `rrweb` with React, and I want to be able to gracefully handle unmounting a component that has a `Replayer` in it. If  I unmount now, I get a flood of `Looks like your replayer has been destroyed` and `Unable to access iframe.contentDocument` warnings, which says to me that the replayer is still doing a bunch of work, processing events etc.

I saw #119 while searching around for this, but I do not see any `destroy` method in the implementation anywhere. Ideally `Replayer` would have some kind of `stop` or `destroy` methods that would stop the replayer and stop it from trying to access the DOM anymore.

**Comment by omairnabiel** [comment]
Can't you use `player.pause()` in the unmount lifecycle?

**Comment by wbobeirne** [comment]
It does appear that this behaves without issue, my mistake.
