### ISSUE TITLE
同一页面多次调用record方法，录制出来的数据在回放时出现重复。

### ISSUE THREAD

**Issue by Nice-Ming** [rrweb-io/rrweb#728]
我们的项目接入了Sentry，且集成了SentryRRWeb插件。此时在Sentry初始化会调用一次record，如今我们想自己记录一份rrweb的录制数据，作为日志存储下来，再一次手动调用了record，后来发现，我们手动record的记录的events在回放时会出现元素重复。想问一下这种情况，该如何处理？

**Comment by Yuyz0112** [comment]
因为录制会在 DOM 元素上记录一些数据，所以导致多个 rrweb 录制冲突。
看起来我们使用一个内存对象保存这些数据会更好。

**Comment by Yuyz0112** [comment]
在 https://github.com/rrweb-io/rrweb/pull/868 之后，rrweb 不再通过 DOM 记录数据，这个问题也就被解决了。
