### ISSUE TITLE
Snapshot images as base64

### ISSUE THREAD

**Issue by croqaz** [rrweb-io/rrweb#737]
Hi!

First of all awesome project, thanks for making it public!

I have a question regarding saving images offline as base64, but also keeping the original URL link.
Right now an image is stored something like:

```js
{'type': 2,
 'tagName': 'img',
 'attributes': {'id': 'mainImage', 'src': 'https://whatever.com/something.gif'},
 'childNodes': [],
 'id': 29},
```

Ideally the image content would be stored somewhere in there like: `src="data:image/gif;base64,deadbeef ...`

There's an option to save the canvas like that.

Is it possible for the images as well?

**Comment by champkeh** [comment]
This could be cause result storage very big. 
My current method is to store images separately in Minio based on their content hash at project build time, then in the playback phase, dynamically proxy the address of the image to Minio's url.

**Comment by croqaz** [comment]
Thanks for your response!

I think storage is not such a big issue if you really want a complete, portable and self-container snapshot with everything.
Saving the image is not that complicated, the problem is I don't know any way of doing it in a sync mode. So this means all the functions will have to be converted to async.
Eg: https://stackoverflow.com/a/42508185

After saving the base64 in the `rr_dataURL'`, you only need to update the rebuild.ts here:

```js
// from
if (tagName === 'canvas' && name === 'rr_dataURL') {
// to
if ((tagName === 'canvas' || tagName === 'img') && name === 'rr_dataURL') {
```

**Comment by champkeh** [comment]
Oh, I see what you mean，you can create a global canvas element as a render service, then in `serializeNode` function add follow code:

```js
const canvasService: HTMLCanvasElement = document.createElement('canvas');
const canvasCtx: CanvasRenderingContext2D | null = canvasService.getContext('2d');

function serializeNode(n, options) {

  // ...

  // convert image to base64
  if (tagName === 'img' && canvasCtx) {
    canvasService.width = (n as HTMLImageElement).naturalWidth;
    canvasService.height = (n as HTMLImageElement).naturalHeight;
    canvasCtx.drawImage((n as HTMLImageElement), 0, 0);
    attributes.rr_dataURL = canvasProvider.toDataURL();
  }

  // ...
}
```

and i test that in local environment, result is follow, it seems feasible:

![image](https://user-images.githubusercontent.com/7316006/142144273-27143099-f10b-4a9b-b5d7-62a09390448d.png)

**Comment by croqaz** [comment]
Your solution is really cool and it should work! Thanks for sharing!!

**Comment by Yuyz0112** [comment]
@croqaz has sent a PR to make this solution integrated into rrweb's code, thanks, everyone!
