### ISSUE TITLE
Expose event typings

### ISSUE THREAD

**Issue by marcospassos** [rrweb-io/rrweb#74]
Currently, the event typings are not exported from the `index.d.ts`, making it inaccessible for external libraries.

Could you consider exposing it? :) Accessing the event-related types would be very helpful.

**Comment by Yuyz0112** [comment]
@marcospassos 

I think now we can get all the typings in a way like `import { ... } from 'rrweb/typings/types'`.
(Maybe other paths, just example of using other typing files instead of index.d.ts)

Since rrweb was written in typescript, the compiler can automatically generate typings but will not merge them together. So I'm not sure import and re-export typings from the root file is needed or not:)

**Comment by marcospassos** [comment]
I see, but unfortunately some tools, such as Rollup, cannot recognise
definitions outside the `index.d.ts` (it treats the file as external
dependencies). To be honest, I’m not sure what is the proper solution
either :)

**Comment by Yuyz0112** [comment]
Ok, could you provide some sample code for me to have a try?

Because I've tried using rollup to bundle some graphQL related TS projects which use types like this:
```
import {
  IFieldResolver,
  MergeInfo,
} from '@smartx/graphql-tools/dist/Interfaces'
```

And it works with `rollup-plugin-typescript2`.

**Comment by marcospassos** [comment]
@Yuyz0112 I realized the problem is related to enum, since enum declarations generate no runtime code. See https://stackoverflow.com/questions/36803967/declare-an-enum-in-a-typescript-definition-file and https://github.com/Microsoft/TypeScript/issues/432#issuecomment-51855590.

**Comment by Yuyz0112** [comment]
@marcospassos so `export { EventType } from './types';` will help?

**Comment by marcospassos** [comment]
In fact, all enums :)

```javascript
import record from './record';
import { Replayer } from './replay';
import { mirror } from './utils';

export { EventType,  IncrementalSource, MouseInteractions, ReplayerEvents } from './types'
export { record, Replayer, mirror };
```

**Comment by Yuyz0112** [comment]
Sure, I will have time to do this in the weekend. So feel free to make a PR if you need it in a hurry:)

**Comment by marcospassos** [comment]
Done in #77, thank you very much! :)
