### ISSUE TITLE
Textarea shows default value twice in replay

### ISSUE THREAD

**Issue by userback** [rrweb-io/rrweb#745]
When there a a textarea with some default value say "123" like `<textarea>123</textarea>`, in the replay, you will see 123123 in the textarea instead of just 123. 

I can replicate the bug on the demo page on rrweb website. The bug is recorded here: https://app.userback.io/viewer/1/8/1358718w25i6iM2/

**Comment by userback** [comment]
Hi, any idea why this was closed?

**Comment by omairnabiel** [comment]
@userback the fix was commited here -> https://github.com/rrweb-io/rrweb/commit/3d5b43890e28ea9b137d32dc7a454a698db1c695

**Comment by userback** [comment]
Oh, sorry, I didn't see the fix.

**Comment by YanJie-001** [comment]
This problem still exists, you can use rrweb-player, remember not to use the default version, use 2.0.0-alpha.11.

**Comment by YanJie-001** [comment]
This problem still exists. You can use rrweb-player and remember not to use the default version.To use 2.0.0-alpha.11.

**Comment by eoghanmurray** [comment]
@YanJie-001 This fix was for the same problem but in the mutations; your problem was happening in the fullSnapshot and should be fixed by #1351
