### ISSUE TITLE
Playback Full Screen Doesn't Work on IOS

### ISSUE THREAD

**Issue by Sanan4li** [rrweb-io/rrweb#747]
I am working on a project and using this library. Everything works fine except the full screen functionality on IOS. You can see the example below. I have checked the demo on the official website and that's not working either. 

Demo [Link](https://www.rrweb.io/demo/checkout-form) 

Short GIF Example of my issue 

![ezgif-6-9d397f3c6491](https://user-images.githubusercontent.com/45590156/140039222-95c8178b-0f5a-4aa5-b179-9915b10dd528.gif)

**Comment by Juice10** [comment]
Unfortunately iOS on iPhone does not support `requestFullscreen` which is needed to go fullscreen. Please see item number 4 on this page for more info: https://caniuse.com/mdn-api_element_requestfullscreen
