### ISSUE TITLE
请问下，如何在react项目中播放

### ISSUE THREAD

**Issue by stoneyallen** [rrweb-io/rrweb#75]
1.从db中取出数据后，放到前端展示
2.前端是使用react的单应用，在取到数据之后
`
    new rrwebPlayer({
      target: document.body.querySelector('#container'), 
      data: {
        events,
        autoPlay: true,
      },
    });
`
页面出现大面积报错

**Comment by Yuyz0112** [comment]
Could you provide the events as a JSON file for debugging?

**Comment by Yuyz0112** [comment]
Feel free to reopen this issue if you confirmed it was a rrweb's bug.
