### ISSUE TITLE
Console log plugin: weird escaping on \"

### ISSUE THREAD

**Issue by userback** [rrweb-io/rrweb#751]
When I log a message using ```console.log('abc\"def')```, what gets recorded in the json event is

```
"payload":["\"abc\\\\\\\"def\""]
```

Why 7 slashes between abc and def?

**Comment by Mark-Fenng** [comment]
Because slashes have special meaning in strings.
If you want to print out abc\"def, the real string content is abc\\\"def.
To generate the record, I stringify the content and so that more slashes are added.
In playback, the record will be parsed and these additional slashes will be removed.

**Comment by userback** [comment]
I understand that slash have a special meaning. The bug here is when the content is stringified, there should NOT be 7 slashes in the stringified content. In the playback, you will actually more than one slash in the parsed result.

**Comment by Mark-Fenng** [comment]
Did you parse the result before printing the content?
![image](https://user-images.githubusercontent.com/27533910/140664111-5e3e928f-c616-44e2-a3ea-9ff1ff51472a.png)

**Comment by userback** [comment]
Ahh, I didn't realize that after the whole json file is fetched and decoded, each individual event payload needs to be parsed again. Thanks for your help.

**Comment by Mark-Fenng** [comment]
That's ok, I parsed them here: https://github.com/rrweb-io/rrweb/blob/master/packages/rrweb/src/plugins/console/replay/index.ts#L73
