### ISSUE TITLE
Shadowroot support not working properly

### ISSUE THREAD

**Issue by maximilianMairinger** [rrweb-io/rrweb#754]
A recent [project of mine](https://github.com/maximilianMairinger/xcenic/tree/record) heavily utilizes nested custom elements with shadowroots. I tried implementing rrweb but failed. Here is a running example (implementing the [getting started guide](https://github.com/rrweb-io/rrweb/blob/master/guide.md#getting-started); view source [recording start](https://github.com/maximilianMairinger/xcenic/blob/record/app/record.ts) and [recording play](https://github.com/maximilianMairinger/xcenic/blob/record/app/_component/_themeAble/_frame/_page/adminPage/adminPage.ts)): http://035401c.xcenic.maximilian.mairinger.com/admin/. After clicking "Stop recording" view the recording object in the console. Everything outside the first shadowroot is properly recorded, but nothing inside (very similar to a lot of other solutions out there).

I noticed however your effort to support shadow roots and tried setting a decently low checkoutEveryNms time. Which **worked**, although at the cost of absurdly high cpu utilization (not surprising), proving that the pure serialization process works.

**Comment by Yuyz0112** [comment]
looks like the new PR from @Mark-Fenng fixed this.
