### ISSUE TITLE
是否支持将录制的数据转为视频呢？

### ISSUE THREAD

**Issue by likaia** [rrweb-io/rrweb#755]
作者，你好，我在寻找一个获取用户当前网站的所有内容，并将其转换为图片的方法，无意间看到你这个库，刚才写了个demo试了下，发现他回放的东西在浏览器里是个iframe，我想把录制的东西的某一帧转换为图片。

我有一个web端截屏插件，现在获取网站内容，采用了两种方案：html2canvas、webrtc，这两种方案都不太理想，所以想看看能不能用上你这个插件。

我的插件地址：https://github.com/likaia/js-screen-shot

**Comment by lgh06** [comment]
https://github.com/rrweb-io/rrweb/blob/master/docs/recipes/index.md#convert-to-video

**Comment by likaia** [comment]
好，谢啦

**Comment by TrustA906** [comment]
@lgh06 文件的格式有参考示例吗

**Comment by lgh06** [comment]
@TrustA906 我不是这个项目的贡献者， 具体看这个 https://github.com/rrweb-io/rrvideo  
本质上是puppeteer (headless chrome) + ffmpeg 录屏 实现的……
好像已经很久没人维护了 得更新更新依赖的版本号
