### ISSUE TITLE
Modal was closed but was still visible in replayer recording

### ISSUE THREAD

**Issue by omairnabiel** [rrweb-io/rrweb#757]
At around `00:21` the close icon was clicked which closed the overlay modal while recording. But when replayed the recording the modal stays there and doesn't close.

https://rrwebdebug.com/play/index.html?url=https%3A%2F%2Fgist.githubusercontent.com%2Fomairnabiel%2F62eb3f37087f8ffe2f4a08220b6be2fc%2Fraw%2F0fbbc79184d6f8fe573c45355128bf07a527b1d4%2Fcostco-dom-events.json&version=0.7.8

**Comment by rcmarron** [comment]
Hey @omairnabiel, I was hitting something similar the other day, and it ended up being that I had two instances of the recorder running, so I had duplicate events (with slightly different timestamps). Looking through the events in the sample you shared, you might be hitting the same thing.

**Comment by a11266897** [comment]
I have the same problem with  modal and loading

**Comment by Mark-Fenng** [comment]
On the latest version 2.0.0-alpha.3, the problem is not reproducible. Feel free to reopen this issue if you want to provide more information for debugging.
