### ISSUE TITLE
Feature request: Turn on/off mouse tail without having to reload the player.

### ISSUE THREAD

**Issue by userback** [rrweb-io/rrweb#759]
At the moment, the mouse tail can be turned on or off using the `mouseTail` config when setting up the replayer. It will be great to have the ability to turn the mouse tail on or off using a method such as `rrwebPlayer.setMouseTail(false);` when the replay has already started. 

The current workaround is to find and hide the `<canvas class="replayer-mouse-tail">` element.But that is not the best practice because it relies on a class name in the DOM.

**Comment by JohnPhamous** [comment]
There's already `rrwebPlayer.setConfig({ mouseTail: false });` which can called at any point in the player's lifetime. The full config is here: https://github.com/rrweb-io/rrweb/blob/53492c1ee4bfac647ac15aaa0c4c563235ea978b/packages/rrweb/src/types.ts#L532

**Comment by userback** [comment]
Ummm, the `setConfig` is **undefined** for me. I tried it on your debug site too. See the attached screenshot
<img width="1378" alt="Screen Shot 2021-11-18 at 08 24 58" src="https://user-images.githubusercontent.com/33855493/142292289-7d649c55-741d-4cfd-9638-1c4aca741540.png">

**Comment by JohnPhamous** [comment]
OH got it. I didn't realize you were talking about `rrweb-player`. `setConfig` is on the `Replayer`.  Not sure how the Svelte code works so not sure if we can access `replayer` directly.

https://github.com/rrweb-io/rrweb/blob/e9405c560a96985fc6db8bcc4d5993125a001a6e/packages/rrweb-player/src/Controller.svelte#L20

We could probably add a new method to the `rrweb-player` for `setConfig` that forwards the argument to `Replayer`'s `setConfig`.

**Comment by userback** [comment]
No worries. I will just stick to my current hack of setting the `display` property of the mouse tail canvas to `none`.
