### ISSUE TITLE
rrWebplayer.addEvent(event)异步加载数据后，回放播放进度条的总时长如何更新

### ISSUE THREAD

**Issue by LucuicuiJohn** [rrweb-io/rrweb#773]
![avatar](http://edu-image.nosdn.127.net/ec010aa2d21641598ac96cbcb4b42093.png?imageView&quality=100)
![avatar](http://edu-image.nosdn.127.net/0c6a39e0ac1944f79bcec686a9c7cd1e.png?imageView&quality=100)

**Comment by pjxxcc** [comment]
同样遇到楼主的问题，用的是`rrwebPlayer`，按理说应该会在`addEvent`的时候自动更新总时长的，看了下代码也有类似的逻辑，如图：  
![image](https://user-images.githubusercontent.com/18558054/164683525-3132fde8-9ef0-4eae-a119-4dc8644d038a.png)

然而实际并没有更新播放控制器的时长，通过查看源码以及打印`replayer.getMetaData()`也确实看到`totalTime`其实是更新了的。  
最终发现问题存在于vue版的控制器代码中，仅在`mounted`钩子中获取了一次播放器的meta。所以解决问题的办法就是在调用`addEvent`之后再让控制器去获取一次=播放器的meta即可。
