### ISSUE TITLE
你好。我想问一下添加压缩函数后，如何拿到开始录制时间和结束录制时间呢，因为此时record已经被编码了

### ISSUE THREAD

**Issue by LiuJing1014** [rrweb-io/rrweb#777]

**Comment by champkeh** [comment]
你需要先解码，然后拿里面的时间戳

**Comment by Yuyz0112** [comment]
如果是通过 events 获取，可以先解压再计算。

如果从 replayer 内获取，可以通过 `getMetaData` 获取：https://github.com/rrweb-io/rrweb/blob/master/packages/rrweb/src/replay/index.ts#L318

**Comment by LiuJing1014** [comment]
好的，谢谢解答
