### ISSUE TITLE
record生成的结果，将整个html文件都储存了起来，生成的dom tree也太庞大了吧

### ISSUE THREAD

**Issue by HowCanLove** [rrweb-io/rrweb#778]
是 rrweb.record 还有什么参数少填了么。
另外如果获取的record没有dom tree的话， Replayer 的时候，要如何把dom tree丢进去。

**Comment by champkeh** [comment]
有一个pack选项，用来压缩数据用的。不过全量快照是对整个文档进行序列化，结果肯定跟文档的大小有关系。另外如非必需，不要使用checkoutEveryNms/checkoutEveryNth选项，这两个选项会持续进行全量快照。

**Comment by Yuyz0112** [comment]
@champkeh 已经解释的很清楚了 👍 

保存 DOM 是回放的基础：https://github.com/rrweb-io/rrweb/blob/master/docs/serialization.zh_CN.md
存储优化可以参考：https://github.com/rrweb-io/rrweb/blob/master/docs/recipes/optimize-storage.zh_CN.md
