### ISSUE TITLE
添加自定义事件

### ISSUE THREAD

**Issue by LiuJing1014** [rrweb-io/rrweb#779]
你好，在录屏过程中添加自定义事件时，比如我要在用户结账的时候添加自定义事件，那么我怎么判断当前的这个时间点就是结账时间点呢

**Comment by champkeh** [comment]
你可以在点击支付按钮的时候记录一个开始支付时间，然后完成支付的时候再记录一个完成支付时间。我目前是这样做的，至于具体支付时间，只能查数据库订单

**Comment by Yuyz0112** [comment]
> 那么我怎么判断当前的这个时间点就是结账时间点呢

没有太理解这个问题

**Comment by Yuyz0112** [comment]
如果有更多信息可以 reopen
