### ISSUE TITLE
请问能否提供一个压缩数据的库

### ISSUE THREAD

**Issue by stoneyallen** [rrweb-io/rrweb#78]
您好，最近用了你们开源的rrweb库，配合上mongodb，使用起来非常方便。
不过我现在发现当dom节点陡增时，event采集的数据也会大量增加，请问能否提供一个压缩和解压数据的库，让使用者能够享受到性能方面的生态工具链。

**Comment by jo0ger** [comment]
试下[lz-string](https://github.com/pieroxy/lz-string)

**Comment by jo0ger** [comment]
还有种方法，使用TypedArray进行压缩，一般用的是原生的Uint8Array

**Comment by a597873885** [comment]
@jo0ger  使用lz-string压缩之后的字符串无法使用JSON方式解析， 因为里边可能包含 : , ", {, } 等字符，请问，有此类问题的解决方法吗？

**Comment by jo0ger** [comment]
@a597873885 lz-string 没有提供 deccompress 这个解压方法吗？

**Comment by a597873885** [comment]
@jo0ger

**Comment by a597873885** [comment]
@jo0ger 提供了deccompress解压方法，但是传入后台解析的时候，长度小的可以解析，长度大的经常解析不出来。  转而使用compressToBase64, 但是这个压缩效果不是很好。还是想使用compress这种压缩方式

**Comment by jo0ger** [comment]
@a597873885 那试一下这个呢？[lzma](https://github.com/LZMA-JS/LZMA-JS)

**Comment by Yuyz0112** [comment]
Further discussion and action can be found in this issue:
https://github.com/rrweb-io/rrweb/issues/151
