### ISSUE TITLE
rrweb.Replayer 是否支持重复加载 events？

### ISSUE THREAD

**Issue by cheungseol** [rrweb-io/rrweb#780]
在初始化通过 new 实例构造 rrweb.Replayer ， 传入 events 之后，后续是否支持复用同一个 Replayer 实例，传入不同的 events ？
还有就是单页面应用路由跳转的时候，直接卡死了？

**Comment by Yuyz0112** [comment]
> 后续是否支持复用同一个 Replayer 实例，传入不同的 events ？

暂时没有 destroy 的 API

> 还有就是单页面应用路由跳转的时候，直接卡死了？

使用的版本是？可以提供 events 用于 debug

**Comment by cheungseol** [comment]
> > 后续是否支持复用同一个 Replayer 实例，传入不同的 events ？
> 
> 暂时没有 destroy 的 API
> 
> > 还有就是单页面应用路由跳转的时候，直接卡死了？
> 
> 使用的版本是？可以提供 events 用于 debug

切换路由 crash 的问题解决了，原因是录制过程中将生成的 events 重复 setState 了，导致页面一直重复渲染

**Comment by cheungseol** [comment]
但是在 echarts svg render 的时候，还是会卡死
