### ISSUE TITLE
goto函数

### ISSUE THREAD

**Issue by LiuJing1014** [rrweb-io/rrweb#781]
你好，使用this.player.go(3000,true)时，报错 Error in v-on handler: "TypeError: Cannot read properties of undefined (reading 'source')"，为什么啊

**Comment by LiuJing1014** [comment]
在播放的过程，用户点击进度条，也会报这个错误，这是为什么呢？保存数据时用了压缩函数，这个有影响吗

**Comment by Yuyz0112** [comment]
回放的示例代码是什么？v-on 看起来是 vue 指令，rrweb 没有使用 vue

**Comment by LiuJing1014** [comment]
问题解决了，是因为录屏数据中存在重复的数据段，就导致了这个错误
