### ISSUE TITLE
rrweb not capturing html form validation tooltip

### ISSUE THREAD

**Issue by Equlnox** [rrweb-io/rrweb#787]
If you visit https://www.w3schools.com/js/tryit.asp?filename=tryjs_validation_html
On clicking "Submit", you would see this tooltip from html form validation.
![image](https://user-images.githubusercontent.com/11289825/147264476-ea2c7379-515a-4daf-8765-c9ad484269f9.png)

It doesn't show up in a rrweb replay
https://www.loom.com/share/50748bcdb891455e8bb143eec7f8ee2d

**Comment by JohnPhamous** [comment]
rrweb only records things on the DOM. That native tooltip doesn't get rendered onto the DOM so rrweb right now can't capture it.
