### ISSUE TITLE
存在阻塞主线程情况

### ISSUE THREAD

**Issue by William-Cai** [rrweb-io/rrweb#789]
你好，我在使用的过程中发现个_问题_，处理的过程会存在**阻塞**主线程并使得界面会卡住。

发现在
![耗时过长](https://user-images.githubusercontent.com/17944714/147634172-494e75bc-fd8b-4f74-ba2e-2f203039164b.png)

测试使用```console.time``` & `console.timeEnd`针对上图的效果进行检测，会发现处理了很长，有时候会几秒，甚至可能是**20s+**。

Chrome Performance
![d9c7c842-4420-4bfe-817a-919c1307c9e9](https://user-images.githubusercontent.com/17944714/147635207-d3994393-a320-4a1c-a247-e6fd6c208bff.jpg)

并影响了接口，使得接口一直处于**pending**状态

**Comment by William-Cai** [comment]
问题已沉

**Comment by wuhanjun** [comment]
请问这个问题解决了吗？

**Comment by wuhanjun** [comment]
请问这个问题解决了吗？

**Comment by cuijiudai** [comment]
页面有大量dom 更新就会有问题，我这里是有个大表格
