### ISSUE TITLE
如何让数据分片

### ISSUE THREAD

**Issue by stoneyallen** [rrweb-io/rrweb#79]
您好，最近使用了rrweb库的录屏与重放功能，发现如果数据是从中间开始选择，则会出现页面空白。

情景重放：
1.使用rrweb记录数据并保存至mongodb中
2.选取某天的全量数据进行播放，发现数据量巨大，播放时间过长，使用者无法高效率播放某个片段内容
3.对（2）进行改进，不再选取一天的数据，而是根据用户选择的任意时间范围，从数据库中捞取数据
4.由于rrweb的后面数据总是基于前面数据，当任意选择时间点时，在没有前面基础数据的前提下，导致播放未正常进行，页面大量空白

需求：
能否让后面数据中存入一个标识，即使我的时间范围选在了某个点上，也能根据该点上的标识再次将时间起点调整到正确的数据点上，或者说将数据纳入到一个时间片范围内，用户选择时间段时，只能选择某段的时间片数据

**Comment by stoneyallen** [comment]
最近阅读你们的源码，发现了checkoutEveryNms、checkoutEveryNth这两个属性，可以触发takeFullSnapshot事件，此时触发的emit第二个参数checkout为true，再将数据添加uuid作为分片的标识，通过上述方式可以达到分片的要求。

不过发现takeFullSnapshot之后的数据，还是要基于前面的dom数据，能否提供一个属性，当takeFullSnapshot发生时，会重新取完整的dom节点数据

**Comment by Yuyz0112** [comment]
fullsnapshot 对应的 data 应该就是完整的 Dom，`还是要基于前面的dom数据` 是指什么？

**Comment by stoneyallen** [comment]
哦，如果是这样的话，那可能是我的代码问题，多谢回答，我再实验下

**Comment by zxysofia** [comment]
> fullsnapshot 对应的 data 应该就是完整的 Dom，`还是要基于前面的dom数据` 是指什么？

fullsnapshot 上传的时候可以分片么？阿里云日志只支持get 而且数据不能超过16KB

**Comment by stoneyallen** [comment]
> > fullsnapshot 对应的 data 应该就是完整的 Dom，`还是要基于前面的dom数据` 是指什么？
> 
> fullsnapshot 上传的时候可以分片么？阿里云日志只支持get 而且数据不能超过16KB

fullsnapshot里的数据确实比较大，这个数据只能你自己拆分了吧，最好用一个压缩体积的库，你的数据放日志里面有问题吧，我这边用了mongo到后面都出现了性能问题，最后采用的是分表原则（根据日期和系统），性能问题已经得到了解决。如果你的系统uv比较大，rrweb采集到的数据量会大的惊人，我在一天半内就收到了3000万行的数据，估计你用日志扛不住。

**Comment by zxysofia** [comment]
> > > fullsnapshot 对应的 data 应该就是完整的 Dom，`还是要基于前面的dom数据` 是指什么？
> > 
> > 
> > fullsnapshot 上传的时候可以分片么？阿里云日志只支持get 而且数据不能超过16KB
> 
> fullsnapshot里的数据确实比较大，这个数据只能你自己拆分了吧，最好用一个压缩体积的库，你的数据放日志里面有问题吧，我这边用了mongo到后面都出现了性能问题，最后采用的是分表原则（根据日期和系统），性能问题已经得到了解决。如果你的系统uv比较大，rrweb采集到的数据量会大的惊人，我在一天半内就收到了3000万行的数据，估计你用日志扛不住。

谢谢，我看看能不能通过其它方式解决。

**Comment by hughfenghen** [comment]
@zxysofia 我在做一个页面类似直播的demo，恰好web rtc单次发送的数据存在上限（各浏览器限制不同，小于16kb最安全），所以必须要做拆包。

这是核心代码（channel是web rtc中的概念），希望对你有帮助：
```js
// ============= 拆包 ============= 
channel.onmessage = ({ data }) => {
  console.log('===== Received Message: ', channel, data);
  if (data === 'action play') {
    // rtc发送的数据有上限，安全起见单次最大发送16k数据，超过则分包发送
    const maxLen = 16 * 1024 - 1;
    stopRecord = rrweb.record({
      emit(event) {
        let ab = new TextEncoder().encode(JSON.stringify(event));
        console.log('=======ab.length', ab.length, channel.readyState);
        while (ab.length !== 0) {
          const sendContent = ab.slice(0, maxLen);
          ab = ab.slice(maxLen);
          channel.send(concatArrayBuffer(new Uint8Array([ab.length === 0 ? 1 : 0]), sendContent));
        }
      },
    });
  }
};

// ============= 组装 ============= 
let buffer = new Uint8Array();
sendChannel.onmessage = evt => {
  const msg = new Uint8Array(evt.data);
  // 如果数据包太大，超过单次上限，需要组装数据包
  const isComplete = !!msg[0];
  const content = msg.slice(1);
  buffer = concatArrayBuffer(buffer, content);
  console.log('---- chan msg', buffer);
  try {
    if (isComplete) {
      const str = new TextDecoder().decode(buffer);
      buffer = new Uint8Array();
      addEvent(JSON.parse(str));
    }
  } catch (err) {
    console.error(err);
  }
};
```

**Comment by moweng** [comment]
你好~请问最终那个分片问题你这边是怎么解决的呢？

**Comment by stoneyallen** [comment]
> @zxysofia 我在做一个页面类似直播的demo，恰好web rtc单次发送的数据存在上限（各浏览器限制不同，小于16kb最安全），所以必须要做拆包。
> 
> 这是核心代码（channel是web rtc中的概念），希望对你有帮助：
> 
> ```js
> // ============= 拆包 ============= 
> channel.onmessage = ({ data }) => {
>   console.log('===== Received Message: ', channel, data);
>   if (data === 'action play') {
>     // rtc发送的数据有上限，安全起见单次最大发送16k数据，超过则分包发送
>     const maxLen = 16 * 1024 - 1;
>     stopRecord = rrweb.record({
>       emit(event) {
>         let ab = new TextEncoder().encode(JSON.stringify(event));
>         console.log('=======ab.length', ab.length, channel.readyState);
>         while (ab.length !== 0) {
>           const sendContent = ab.slice(0, maxLen);
>           ab = ab.slice(maxLen);
>           channel.send(concatArrayBuffer(new Uint8Array([ab.length === 0 ? 1 : 0]), sendContent));
>         }
>       },
>     });
>   }
> };
> 
> // ============= 组装 ============= 
> let buffer = new Uint8Array();
> sendChannel.onmessage = evt => {
>   const msg = new Uint8Array(evt.data);
>   // 如果数据包太大，超过单次上限，需要组装数据包
>   const isComplete = !!msg[0];
>   const content = msg.slice(1);
>   buffer = concatArrayBuffer(buffer, content);
>   console.log('---- chan msg', buffer);
>   try {
>     if (isComplete) {
>       const str = new TextDecoder().decode(buffer);
>       buffer = new Uint8Array();
>       addEvent(JSON.parse(str));
>     }
>   } catch (err) {
>     console.error(err);
>   }
> };
> ```



> @zxysofia 我在做一个页面类似直播的demo，恰好web rtc单次发送的数据存在上限（各浏览器限制不同，小于16kb最安全），所以必须要做拆包。
> 
> 这是核心代码（channel是web rtc中的概念），希望对你有帮助：
> 
> ```js
> // ============= 拆包 ============= 
> channel.onmessage = ({ data }) => {
>   console.log('===== Received Message: ', channel, data);
>   if (data === 'action play') {
>     // rtc发送的数据有上限，安全起见单次最大发送16k数据，超过则分包发送
>     const maxLen = 16 * 1024 - 1;
>     stopRecord = rrweb.record({
>       emit(event) {
>         let ab = new TextEncoder().encode(JSON.stringify(event));
>         console.log('=======ab.length', ab.length, channel.readyState);
>         while (ab.length !== 0) {
>           const sendContent = ab.slice(0, maxLen);
>           ab = ab.slice(maxLen);
>           channel.send(concatArrayBuffer(new Uint8Array([ab.length === 0 ? 1 : 0]), sendContent));
>         }
>       },
>     });
>   }
> };
> 
> // ============= 组装 ============= 
> let buffer = new Uint8Array();
> sendChannel.onmessage = evt => {
>   const msg = new Uint8Array(evt.data);
>   // 如果数据包太大，超过单次上限，需要组装数据包
>   const isComplete = !!msg[0];
>   const content = msg.slice(1);
>   buffer = concatArrayBuffer(buffer, content);
>   console.log('---- chan msg', buffer);
>   try {
>     if (isComplete) {
>       const str = new TextDecoder().decode(buffer);
>       buffer = new Uint8Array();
>       addEvent(JSON.parse(str));
>     }
>   } catch (err) {
>     console.error(err);
>   }
> };
> ```

你这种拆分方式在连续发送录屏数据时，是否会产生混乱，例如前后两次分片数据在后端组装时，发生混淆

**Comment by moweng** [comment]
分片上传数据之后，在服务器端是整合数据？那在重放的时候呢？需要怎么处理数据

**Comment by stoneyallen** [comment]
> 分片上传数据之后，在服务器端是整合数据？那在重放的时候呢？需要怎么处理数据

我的分片方式不是单个数据的分片，是如何把一天的数据或者是连续不刷新页面的数据进行分片，在rrweb里叫snapshot。
我是每隔10分钟或者数据超过一定大小之后，进行一次数据分片。这样在播放的时候，可以获取某一段的数据，不用播放一整天的。

**Comment by moweng** [comment]
@stoneyallen 单次的数据量比较大，这个怎么解决传输问题，还有数据的存储方案~方便加个微信或者QQ，向你请教下吗？QQ: 1308490015  微信：jnfamcxd

**Comment by Yuyz0112** [comment]
如果大家有需要的话可以建一个中文用户的微信群：）gitter 可能不太方便国内用户

**Comment by stoneyallen** [comment]
> @stoneyallen 单次的数据量比较大，这个怎么解决传输问题，还有数据的存储方案~方便加个微信或者QQ，向你请教下吗？QQ: 1308490015 微信：jnfamcxd

个人的总结文档，感兴趣的可以看一看
https://segmentfault.com/a/1190000019806254?_ea=15195553

**Comment by Yuyz0112** [comment]
We already support the checkout feature to break the op-log chain into multiple smaller chains.

Further discussion and action about the size of events can be found in this issue:
https://github.com/rrweb-io/rrweb/issues/151
