### ISSUE TITLE
Duplicate style node added hundreds of times

### ISSUE THREAD

**Issue by rcmarron** [rrweb-io/rrweb#790]
Hey everyone,

We've been having an issue lately where style nodes get added hundreds of times to a recording, and it causes the recording to become massive.

I haven't figured out how to reliably reproduce the issue, but it happens occasionally on our web app (app.posthog.com) and on several of our customer's web apps. I can't share the entire recording because it's massive and includes PII, but here is a gist with a subset of the snapshots: https://gist.github.com/rcmarron/d473fc0e5aeae281fffd978d6cc121a6

A couple of notes/thoughts:
* I've only seen it happen when really large nodes are added, but that's not to say it never happens with smaller nodes.
* I'm wondering if adding nodes [to the `addedSet`](https://github.com/rrweb-io/rrweb/blob/master/packages/rrweb/src/record/mutation.ts#L161) is slow/async when the node is large, so when the `MutationObserver` sends duplicates, they aren't properly de-duped?

Let me know if I can share any more details

Thanks!

**Comment by Yuyz0112** [comment]
Thanks, for the report, going to debug this.

**Comment by rcmarron** [comment]
@Yuyz0112 I think I have a consistent repro for this issue.

If I use this Chrome Extension: https://help.getguru.com/en/articles/4680811-chrome-guru-browser-extension and open almost any website and run rr-web on it, it happens.

If you look at the full snapshots that are produced, you should see lots of duplicated large style nodes that start with the class name `.SigninBlurb`.

Thanks, and let me know if I can provide any more details or help at all.

**Comment by rcmarron** [comment]
Looks like this commit fixed this: https://github.com/rrweb-io/rrweb/pull/866 🎉

Closing this issue
