### ISSUE TITLE
Is there any way to pause recording and then resume recording?

### ISSUE THREAD

**Issue by cheungseol** [rrweb-io/rrweb#792]

**Comment by champkeh** [comment]
At present, there seems to be no `pause` and `resume` function, but there has `record` and `stop` function(`record` function's return value is `stop` function). If you want to resume after stop, you have to re-invoke `record` function with same options.

**Comment by cheungseol** [comment]
> At present, there seems to be no `pause` and `resume` function, but there has `record` and `stop` function(`record` function's return value is `stop` function). If you want to resume after stop, you have to re-invoke `record` function with same options.

yeah, currently i have tried to `stop` and then `restart` recording to hacking `pause`, but it seems make the final events json large, cause every time it restart recording, it will emit a total full-snapshot event.

**Comment by Yuyz0112** [comment]
rrweb data is an incremental op-log, so when you do pause at timing 1 and resume at timing 2, what do you expect the events during this period to be handled? If the events are not emitted or dropped, we can not replay to timing 2.

If you do a full snapshot at timing 2 to start a new op-log session, it will work. And this is what the stop + re-record do.
