### ISSUE TITLE
关于canvas录制触发大量的快照录制问题

### ISSUE THREAD

**Issue by 961998264** [rrweb-io/rrweb#794]
问题描述：我有一个页面有一些echart图，底层是canvas。我想要录制该canvas，在使用了  recordCanvas: true参数之后，引发了大量的快照录制，10s之内大概一千个快照以上。在鼠标滑过canvas之后，同样产生了大量快照。
请问：是什么原因导致的，有什么办法能解决该问题吗。

-[这是我的页面](https://fs.sylapp.cn/upload/20220112/20220112095734462226bd8123caa27ca25b2f3676a9a1c146.png)

**Comment by 961998264** [comment]
我看到了有类似的问题，不知道作者，或者其他使用者有解决方案吗

**Comment by Yuyz0112** [comment]
可以看一下 events 吗？

canvas 的录制原理是劫持了所有 canvas API，所以如果应用在调用大量 canvas API，就会产生很多事件。这类场景不太适合进行 canvas 录制。

**Comment by 961998264** [comment]
@Yuyz0112 感觉回复。是的，所以我屏蔽了echart的录制。
