### ISSUE TITLE
Include `volume` and `muted` in media elements serialization

### ISSUE THREAD

**Issue by wbobeirne** [rrweb-io/rrweb#796]
In the same way that `currentTime` and `paused` are carried over, it'd be great if `volume` and `muted` were too. Muted is especially important due to React not including it in the DOM even when the `muted` prop is set: https://github.com/facebook/react/issues/10389

**Comment by Yuyz0112** [comment]
Thanks for the feature request, implemented in the latest patch.

**Comment by wbobeirne** [comment]
Amazing, thank you!
