### ISSUE TITLE
rrwebPlayer不支持事件回放插件

### ISSUE THREAD

**Issue by pjxxcc** [rrweb-io/rrweb#797]
这几天项目接入rrweb，不得不说这个录制思路很有意思，而且维护得很好。  
接入过程中发现文档有的地方没更新，比如 [这里](https://github.com/rrweb-io/rrweb/blob/master/guide.zh_CN.md#%E9%85%8D%E7%BD%AE%E5%8F%82%E6%95%B0)的配置说明还有`recordLog`属性，然而这个属性在[半年前](https://github.com/rrweb-io/rrweb/pull/598)就已经废弃了，取而代之的是插件功能。

下面才是主要想问的问题，  
精简版的回放器`rrweb.Replayer`中可以通过`plugins`属性成功使用`rrweb.getReplayConsolePlugin`来回放日志，然而在完整版的回放器`rrwebPlayer`中反而无法使用插件回放日志，在其中加入`rrweb.getReplayConsolePlugin`没有任何作用。

**Comment by Yuyz0112** [comment]
感谢反馈，文档已更新。

rrwebPlayer 的使用方式是这样：

```diff
new rrwebPlayer({
  target: document.body,
  props: {
    events,
+   plugins: [rrweb.getReplayConsolePlugin()],
  },
});

props 内的参数除了 events，都会透传给 `rrweb.Replayer` 的 options。
```

**Comment by wensiyuanseven** [comment]
还是不行
