### ISSUE TITLE
inlineImages 功能不能正常转 base64

### ISSUE THREAD

**Issue by liuwanj** [rrweb-io/rrweb#799]
转换后的数据如下图
![image](https://user-images.githubusercontent.com/19161565/150060721-5221f81f-a5fd-44bd-9d2e-10207c1b8ceb.png)

**Comment by Yuyz0112** [comment]
图片是同源的吗？

**Comment by liuwanj** [comment]
是同源地址。

**Comment by liuwanj** [comment]
这里是别的原因没有转成功。
不同源的图片我测试过了，也是正常可以转成 base64，源码里面处理过跨域 `image.crossOrigin = 'anonymous';`
