### ISSUE TITLE
Question - Record only certain part of the DOM?

### ISSUE THREAD

**Issue by amitpareek49** [rrweb-io/rrweb#800]
Is it possible to record selected part of the screen? For eg. Only record the dialog box that appear as popup on the screen.

**Comment by amitpareek49** [comment]
@Yuyz0112 - Is this something that has been tried already?

**Comment by Yuyz0112** [comment]
@amitpareek49 You can check the previous discussion here: https://github.com/rrweb-io/rrweb/issues/111

Going to close this issue and we can keep the discussion in #111
