### ISSUE TITLE
回放时需要执行页面脚本如何配置

### ISSUE THREAD

**Issue by andyzys** [rrweb-io/rrweb#802]
录制页面的操作，在回放需要开启脚本能力，执行页面的一些js逻辑，请问如何配置，设置了UNSAFE_replayCanvas为true没用，页面脚本还是会被替换成noscript和SCRIPT_PLACEHOLDER

**Comment by Yuyz0112** [comment]
需要执行 JS 逻辑的场景是什么？

rrweb 的录制时通过序列化转为静态数据实现的
https://github.com/rrweb-io/rrweb/blob/master/docs/serialization.zh_CN.md
https://github.com/rrweb-io/rrweb/blob/master/docs/sandbox.zh_CN.md
