### ISSUE TITLE
Replay sometimes does not work on scrolling and writing input fields

### ISSUE THREAD

**Issue by jackiehamchen** [rrweb-io/rrweb#804]
I have recorded updating input form but sometimes the replay does not replay the scrolling and updating input fields in the form part.

In the sample events attached, i have recorded "Writing input field" in an input field as you can see this event in the event file also but that part is not replayed.

Could you please check the events attached?
[problematic_events.json.zip](https://github.com/rrweb-io/rrweb/files/7909570/problematic_events.json.zip)

**Comment by Mark-Fenng** [comment]
I find that your events data has multiple meta events and full snapshots so have you ever edited your events by yourself?

**Comment by jackiehamchen** [comment]
Hello @Mark-Fenng 
No, I have only manually replaced some text with another text e.g. to "Sample" text and removed some events, but I haven't added any events or anything else.

Could you please suggest what would cause the issue? I have tried to remove some button wrapper events manually and the replayer tried to scroll and wrote input fields but it didn't replay perfectly.

I have attached the rrweb record code
[rrweb_record.js.zip](https://github.com/rrweb-io/rrweb/files/7919873/rrweb_record.js.zip)

**Comment by Mark-Fenng** [comment]
Your record code may have some issues.
If the "record" component is rendered more than once, your component would get several record instances and the save function would upload all these events to your backend. The would cause serious event chaos which I saw in your uploaded sample event data.

**Comment by jackiehamchen** [comment]
@Mark-Fenng  thank you so much for the suggestion. 

I have just tried to run the "record" component only once in my index file that has conditional rendering e.g. if users log-in, I render the "record" component once.

However, when I go to the next component (after logging-in), there is no event emitted from the record component.

Could you please suggest what would be the practice to render the rrweb "record" component in a React SPA application?

**Comment by Mark-Fenng** [comment]
I would suggest the 'record' component be at the top level and set the record condition a state. The stored events and stopFn function could be reference data rather than local variables. Every time the condition changed, the side effect could be stopping the existed record and creating a new record instance if needed.

**Comment by jackiehamchen** [comment]
@Mark-Fenng  thank you again for the suggestion.. let me confirm my understanding..
(1) I will need to set a record state when the 'record' component is rendered for each page to ensure that the 'record' component won't be called twice for each page

(2) when another component is loaded, e.g. clicking a new menu for another form, the side effect (useEffect) will call the stopFn of the previous 'record' instance and create a new record for the new page

could you please confirm if the above understanding is correct?

With my problematic events previously attached, I tried to print console log to check if the 'record' component is rendered twice and it seems to be called twice on the first page load and click the menu (useEffect is called), but the 'record' component is not called again while filling the form.

> The stored events and stopFn function could be reference data rather than local variables.
I'm not sure regarding this as i understand the local variable record's events are reset when they are sent to backend and a props could be passed to the 'record' component to call stopFn, do you have a pseudo code or a reference to a sample code?

**Comment by Mark-Fenng** [comment]
@jackiehamchen 
_2. when another component is loaded, e.g. clicking a new menu for another form, the side effect (useEffect) will call the stopFn of the previous 'record' instance and create a new record for the new page_

rrweb always records the whole page rather than components so I think loading new component won't affect the recording process. You only need to recreate a record instance when you want to pause the recording for a while.
