### ISSUE TITLE
Test cloning website to see examples

### ISSUE THREAD

**Issue by frankcom** [rrweb-io/rrweb#818]
Hello,
I tried "cloning" the website from https://github.com/rrweb-io/web for test purposes, but I am noticing many path problems, also there are some issues - maybe of rewriting? E.g. Import of the Navigation -> xxx/web-master/src/components/Nav.html

Do you see any chance posting some example code for integration on website?

I want to "Autostart" recording event when a user is visiting website and I am also looking for Website (I can password to watch the recordings).

Kind regards, great work!

**Comment by Yuyz0112** [comment]
The web repo is our official website repo, which is not a minimal use case of rrweb.

You can start from the [guide](https://github.com/rrweb-io/rrweb/blob/master/guide.md) or the [recipes](https://github.com/rrweb-io/rrweb/blob/master/docs/recipes/index.md).

**Comment by frankcom** [comment]
Hi I have seen the guide and recipes, but unfortunately I have not found a "direct" example in form of a ready built webpage. Also NPM showed error for me in installing. Thanks.

**Comment by Yuyz0112** [comment]
@frankcom rrweb is a JS library which means you can integrate it into any ready-built web page to record.
What kind of error are you facing during using NPM?
