### ISSUE TITLE
Add option to pass custom logger to rrweb record

### ISSUE THREAD

**Issue by wbobeirne** [rrweb-io/rrweb#831]
I use a custom logger in my frontend to send logs server side for analysis. Unfortunately I'm unable to record any rrweb debug logging since it uses a `console.log` with no way to override it: https://github.com/rrweb-io/rrweb/blob/f75679015d839daa23bbd7852a61cf4e459c3de1/packages/rrweb/src/replay/index.ts#L1892-L1899

It'd be nice if there was an option for passing a custom function that would be called instead. Ideally the call happens before the `showDebug` check so that we can implement custom logic for `showDebug` instead of having to call `setConfig` to update it.

**Comment by Yuyz0112** [comment]
cc @Mark-Fenng

**Comment by Mark-Fenng** [comment]
Maybe I can expand the `showDebug` option to receive a custom logger just like what we did in the [console plugin](https://github.com/rrweb-io/rrweb/blob/master/docs/recipes/console.md). But I have one thing not sure about. Do I have to replace the warn log like this:  https://github.com/rrweb-io/rrweb/blob/master/packages/rrweb/src/replay/index.ts#L1962-L1967 with the custom logger?

**Comment by wbobeirne** [comment]
> Do I have to replace the warn log... with the custom logger?

For my use case, that would be ideal. I'm trying to send rrweb logs to my server so that we can debug issues in production, so I'd like any and all logs to be accessible.
