### ISSUE TITLE
SVG in iframe can be recorded but cannot be displayed during playback

### ISSUE THREAD

**Issue by Jiacheng787** [rrweb-io/rrweb#841]
录制一个同源 iframe 中的页面，发现 svg 渲染的图表已被录制下来，但无法展示，另外还有 svg 的图标也被录制，但同样无法展示

![image](https://user-images.githubusercontent.com/43509711/155269078-afb18a21-dd48-4ced-8d1b-9f43afa982a1.png)

**Comment by Mark-Fenng** [comment]
could you provide the code of that SVG icon?

**Comment by Jiacheng787** [comment]
Actually, any svg code is reproducible, but just make sure to include it in a iframe page.

```html
<svg width="42" height="24" fill="none" xmlns="http://www.w3.org/2000/svg" class="dash-debug-menu__icon dash-debug-menu__icon--debug"><path d="M14.85 21.197 5.616 12l9.225-9.197L12.028 0 0 12l12.037 12 2.813-2.803Zm12.3 0L36.375 12 27.15 2.803 29.963 0 42 12 29.962 24l-2.812-2.803Z" fill="#fff"></path></svg>
```

**Comment by Mark-Fenng** [comment]
Thanks for the report!  I'll look into it.

**Comment by Jiacheng787** [comment]
Ok, please let me know if there is any progress. Waiting for your fix method.
