### ISSUE TITLE
display 控制显隐的元素以及设置了 animation 的元素回放异常

### ISSUE THREAD

**Issue by smileCris** [rrweb-io/rrweb#842]
<ol>
<li> hover 时 display: none 控制显示隐藏的元素回放会出现多个，例如 element ui input 框的 clear 图标；</li>
<li>样式设置了 animation 的元素，会在停止回放时动画仍然生效。</li>
</ol>

**Comment by Mark-Fenng** [comment]
> hover 时 display: none 控制显示隐藏的元素回放会出现多个，例如 element ui input 框的 clear 图标；

Could you provide events data to reproduce the problem?

> 样式设置了 animation 的元素，会在停止回放时动画仍然生效。

You can add the option `pauseAnimation: true` to the replayer to solve the problem.
