### ISSUE TITLE
页面关闭后会重新开启record

### ISSUE THREAD

**Issue by Buwaggish** [rrweb-io/rrweb#845]
onClick = (e) =>{
    someThing();
    stopFn = rrweb.record(emit(event){
        debugger;
    })
}
stopFn();

onClick()通过addEventlistener绑定在控件上，调用stopFn()时会停止emit，用户关闭页面又回触发record的emit，并且重新进入页面，即使没有onclick启动record，也会一直在emit，像是关闭页面又把这个record打开了，请问是什么原因呢

**Comment by Buwaggish** [comment]
页面关闭时触发了一次onceIframeLoaded(n, function(){})函数，走到了serializeNodeWithId(iframe,{})， 然后把event那个打开了，请问可能的原因是啥。。

**Comment by eoghanmurray** [comment]
@Buwaggish did you just want to take a single 'screenshot' of your page?  If so https://github.com/rrweb-io/rrweb/tree/master/packages/rrweb-snapshot is intended for this use case.

**Comment by Buwaggish** [comment]
> @Buwaggish did you just want to take a single 'screenshot' of your page? If so https://github.com/rrweb-io/rrweb/tree/master/packages/rrweb-snapshot is intended for this use case.

It seems that the return value of function snapshot() cannot be stringified as json format; 
Is there any way  I can store the result of that function?

**Comment by Buwaggish** [comment]
> @Buwaggish did you just want to take a single 'screenshot' of your page? If so https://github.com/rrweb-io/rrweb/tree/master/packages/rrweb-snapshot is intended for this use case.

Is there any demo of snapshot and rebuild ?
