### ISSUE TITLE
Does inlineImages option work with rrweb.record function?

### ISSUE THREAD

**Issue by mchusovlianov** [rrweb-io/rrweb#847]
I use as simple code as this but I don't see any base64 encoded images after I enabled inlineImages.
` rrweb.record({
      inlineImages: true,
      emit(event) {
        console.log(event);
      }
  });`

**Comment by Yuyz0112** [comment]
What version are you using?

**Comment by mchusovlianov** [comment]
1.1.2

**Comment by mchusovlianov** [comment]
That was my bad. It works.
