### ISSUE TITLE
bundle:browser not being run when publish on NPM

### ISSUE THREAD

**Issue by timgl** [rrweb-io/rrweb#848]
I'm trying to use `rrweb-record.min.js` and `console-record.min.js` together from the NPM package, but `console-record.min.js` isn't included in the NPM module. Would it be possible to run `bundle:browser` and pushing the result of that to NPM?

**Comment by Yuyz0112** [comment]
I think it's already in the package
https://www.jsdelivr.com/package/npm/rrweb?path=dist%2Fplugins

**Comment by timgl** [comment]
Sorry about that! I was still on 1.0.6 hence the issue :)
