### ISSUE TITLE
Only the first frame of SVG chart inside iframe can be recorded

### ISSUE THREAD

**Issue by Jiacheng787** [rrweb-io/rrweb#854]
In a scenario, the front end needs to display a web page inside the iframe, and a SVG chart needs to be displayed inside this page, and can be dynamically switch the content.

After testing, it is found that the SVG inside iframe can be recorded, but only the content rendered in the first frame. When switching SVG charts later, the recording still shows the content of the first frame, and the changed content cannot be displayed.

![image](https://user-images.githubusercontent.com/43509711/156959855-04eebd35-ae8e-46b3-851f-74e1ffeaa682.png)

**Comment by Mark-Fenng** [comment]
could you please provide a small demo to reproduce this problem?

**Comment by Mark-Fenng** [comment]
Feel free to reopen this issue if a reproducible demo is provided.
