### ISSUE TITLE
childNodes array includes null in the facebook capture

### ISSUE THREAD

**Issue by mchusovlianov** [rrweb-io/rrweb#858]
There is an issue with the facebook capture which leads to error when replay
<img width="272" alt="image" src="https://user-images.githubusercontent.com/196578/157718184-adfd3ab1-500e-4a93-9f81-7512633d9ee3.png">
<img width="269" alt="image" src="https://user-images.githubusercontent.com/196578/157718965-c5fbcc70-d227-477a-979b-1544c3405a38.png">

**Comment by mchusovlianov** [comment]
There was an issue with JSON.stringify

**Comment by ming535** [comment]
@mchusovlianov Hi, may I ask why is this issue closed? How do you deal with this issue?
