### ISSUE TITLE
[Question] Using for analytics use-case

### ISSUE THREAD

**Issue by boazpeer1** [rrweb-io/rrweb#86]
Is it possible to use rrweb for analytics rather than replay?
I would only need the recorder and comprehensive documentation of the events so I can extract the required data which is needed for the analytics.

Is such documentation available?

**Comment by marcospassos** [comment]
@boazpeer1 it's entirely possible, and in fact, it's the use case of some users.  Currently, most of the documentation covers specification details only, but the data structure is available at the [`types.ts`](https://github.com/rrweb-io/rrweb/blob/master/src/types.ts) file.

Notice that some of the information included in the events depends on post-processing on the replay part, so they cannot be consumed without tweaks yet. However, there are some ongoing efforts to fix it, see #82 and #82.
