### ISSUE TITLE
有上百小时甚至更多，回放怎么分段播放？

### ISSUE THREAD

**Issue by joket1999** [rrweb-io/rrweb#861]
目前只能通过addEvent来添加新数据。但是如果需要更新（替换）当前播放器的数据，请问有什么方法实现？

**Comment by Yuyz0112** [comment]
可以 destroy 之后重建

**Comment by joket1999** [comment]
> 

貌似没有相应的方法销毁。
意思是手动销毁之前的实例和页面的html，重新实例化吗？
