### ISSUE TITLE
[bug]regexp maskTextClass dont work

### ISSUE THREAD

**Issue by caotsinghua** [rrweb-io/rrweb#864]
`needMaskingText `will never return true if `maskTextClass`  is regexp

because use reurn in forEach. 

![image](https://user-images.githubusercontent.com/15075816/159888580-10cd86ca-6f38-4403-8977-dffa2177b46f.png)

**Comment by Yuyz0112** [comment]
Thanks for the report.

**Comment by caotsinghua** [comment]
@Yuyz0112  hello , when can we get a new release ?
