### ISSUE TITLE
input左侧的标签是label，label里面的文字不能回放，如果label标签改成div是可以回放的。

### ISSUE THREAD

**Issue by xuna987** [rrweb-io/rrweb#869]
页面的dom结构：
![image](https://user-images.githubusercontent.com/16288212/161924123-5c411d05-dc6f-4244-82f9-e403094812b3.png)
rrweb中回放的页面
![image](https://user-images.githubusercontent.com/16288212/161924258-b8350e17-6295-46af-aa5b-2211a2438d65.png)

期望回放：
![image](https://user-images.githubusercontent.com/16288212/161925028-bd90112e-e102-4283-8ed6-4045d195dfda.png)

代码
`<taro-view-core class="custom-input__container hydrated"><taro-view-core class="at-input completeInfo-insurance__input hydrated" style=""><taro-view-core class="at-input__container hydrated"><taro-view-core class="at-input__overlay at-input__overlay--hidden hydrated"></taro-view-core><taro-label-core class="at-input__title false hydrated" for="xingming"><!----><label for="xingming">车主姓名</label></taro-label-core><taro-input-core class="at-input__input hydrated" id="xingming" name="xingming" type="text" placeholderstyle="" placeholderclass="placeholder" placeholder="请输入车主姓名" cursorspacing="50" maxlength="140" value="许*" confirmtype="done" cursor="0" selectionstart="-1" selectionend="-1" adjustposition="true"><input class="weui-input" type="text" placeholder="请输入车主姓名" maxlength="140" name="xingming"></taro-input-core><taro-view-core class="at-input__children hydrated"></taro-view-core></taro-view-core></taro-view-core></taro-view-core>`

**Comment by Yuyz0112** [comment]
不太熟悉 taro，这个是一个 web 页面？

**Comment by xuna987** [comment]
对，这是web页面，您看需要我提供什么材料呢

**Comment by Yuyz0112** [comment]
如果有可以最小化的 Demo 可以提供一下代码，或者一个可访问的 URL

**Comment by xuna987** [comment]
怎么发您资料呢

**Comment by Mark-Fenng** [comment]
@xuna987 是否使用的是这个库https://tard-ui.selling.cn/comps/form，在这个页面上没有复现你描述的问题
如果有最小化的 Demo 或者可访问的URL, 可以随时reopen issue
