### ISSUE TITLE
rrweb-snapshot cannot record iframe contents

### ISSUE THREAD

**Issue by Buwaggish** [rrweb-io/rrweb#870]
All Iframes in the page are set to the same origin by setting document.domain or nginx cors config
use snapshot() in rrweb-snapshot,the iframe result of which is rebuilt to an empty iframe div, while the other elements of the snapshots are quite normal

**Comment by Yuyz0112** [comment]
@Buwaggish Have you tried rrweb instead of rrweb-snapshot? The snapshot may not contain iframe contents since it was loaded async(where we can improve of course).

**Comment by Buwaggish** [comment]
Cause we only need one snapshot rather than a whole period of video, even if we use rrweb, we have to record more events to ensure iframe content has completely loaded? Are there any plans to finish this improvement?

**Comment by Buwaggish** [comment]
I tried rrweb  version 1.1.1, the iframe still cannot be displayed, and I have checked the events  ,where no the dom elements inside iframe could be found

**Comment by Buwaggish** [comment]
https://github.com/rrweb-io/rrweb/pull/481 
Did you mean that we have to use rrweb inside iframe ,not the other way around?

**Comment by Yuyz0112** [comment]
is it an same origin iframe?

**Comment by Buwaggish** [comment]
Yes, same origin,

**Comment by Buwaggish** [comment]
> is it an same origin iframe?

Is there any other options or config I need to put in the recordOptions to make it work? Inside iframe also seemed to be not working

**Comment by Buwaggish** [comment]
According to #481 
I found that OnIframeLoad was never triggered , what if record() was called after all the iframes had alreadey loaded, would events still held the iframe dom?

**Comment by Buwaggish** [comment]
It turned out to be cross origin problem

**Comment by Juice10** [comment]
Check out this PR for cross origin iframe support: https://github.com/rrweb-io/rrweb/pull/1035
