### ISSUE TITLE
数据暴增问题

### ISSUE THREAD

**Issue by a11266897** [rrweb-io/rrweb#872]
业务场景：每次提交表单的时候会去请求后台接口。后端接口会去校验表单数据。返回相应的错误信息

实际操作：每次校验失败，stop当前录屏，提交一次record数据，清除缓存的events，清理mirror.map 。

遇见问题：数据递增，且window与mac os 表现不一致，
                   mac为200  - 400 - 600 - 800 递增
                   window为200 - 800 - 3000 - 40000递增。

版本： 0.9.0以及最新版

**Comment by Yuyz0112** [comment]
这个数量是 events 的数量？有观察过 events 中是否有重复的吗？

**Comment by a11266897** [comment]
找到问题了，由于开启了vconsole的问题。
