### ISSUE TITLE
In the console recording plugin, console.log(undefined) isn't handled as expected

### ISSUE THREAD

**Issue by rcmarron** [rrweb-io/rrweb#877]
If you have the console recording plugin setup, and you do `console.log(undefined)`, the emitted event has a payload with the value `undefined` instead of the string `'undefined'`.

It seems like this is the only case where the payload isn't a string. For example, `console.log(null)` emits an event with the payload `'null'`.

**Comment by Juice10** [comment]
Hi @rcmarron, good catch, I think we can pull your fix into the main repo. Could you make a pull request for it?

**Comment by Yuyz0112** [comment]
Looks like this is the same behavior as JSON.stringify.

```js
JSON.stringify(undefined)
// undefined
JSON.stringify(null)
// 'null'
```

The problem is we are declaring the types like

```ts
type LogData = {
  level: LogLevel;
  trace: string[];
  payload: string[]; // <- not always string
};
```

Shall we stringify `undefined` to string `'undefined'` or change the type declaration and keep the current behavior? Maybe @Mark-Fenng has some suggestions?

**Comment by Mark-Fenng** [comment]
Thanks for the mention. This could be a difficult dicision to make. I'd love to try both ways and compare them.
