### ISSUE TITLE
Error: Replayer need at least 2 events.

### ISSUE THREAD

**Issue by zhangqingrui-creater** [rrweb-io/rrweb#880]
Error: Replayer need at least 2 events.从数据库取数据回放失败

**Comment by Yuyz0112** [comment]
可以检查一下你传入 replayer 的 events 是否为数组

**Comment by zhangqingrui-creater** [comment]
谢谢回复，刚刚已经解决了，确实是这么回事。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月22日(星期五) 晚上10:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [rrweb-io/rrweb] Error: Replayer need at least 2 events. (Issue #880)





 
可以检查一下你传入 replayer 的 events 是否为数组
