### ISSUE TITLE
new rrweb.Replayer 销毁

### ISSUE THREAD

**Issue by cheungseol** [rrweb-io/rrweb#883]
请问通过 `new rrweb.Replayer` 创建的回放，有办法销毁吗？
页面上可能先后重复创建多个 `new rrweb.Replayer` ，担心会有内存或者重复创建的事件等问题。
目前只是手动清空了 replayer-wrapper DOM 节点。

**Comment by Juice10** [comment]
Hi @cheungseol,

This be fixed by a new method: `replayer.destroy()` which then removes all of the rrweb elements from the page and cleans up some internal memory?

**Comment by cheungseol** [comment]
> Hi @cheungseol,
> 
> This be fixed by a new method: `replayer.destroy()` which then removes all of the rrweb elements from the page and cleans up some internal memory?

thanks . but currently i could not found the `destroy` method in [replay/index.ts](https://github.com/rrweb-io/rrweb/blob/master/packages/rrweb/src/replay/index.ts).

Will this destroy method be available in future version ?

**Comment by Juice10** [comment]
> > Hi @cheungseol,
> > This be fixed by a new method: `replayer.destroy()` which then removes all of the rrweb elements from the page and cleans up some internal memory?
> 
> thanks . but currently i could not found the `destroy` method in [replay/index.ts](https://github.com/rrweb-io/rrweb/blob/master/packages/rrweb/src/replay/index.ts).
> 
> Will this destroy method be available in future version ?

Hi @cheungseol, apologies for my confusing message!

You are right, a `destroy` method doesn't exist yet.
I was wondering if it would fix your problem if a destroy did method exist.

And just so I understand your use case, what would you need that destroy method to do?

**Comment by alexcroox** [comment]
This method didn't make it into rrwebPlayer, only rrweb.Replayer. 

What's the recommended way of destroying rrwebPlayer so a new playback can be loaded in it's place?
