### ISSUE TITLE
通过canvas实时展现摄像头里的内容可以录屏吗

### ISSUE THREAD

**Issue by sunxu0429** [rrweb-io/rrweb#889]

**Comment by sunxu0429** [comment]
canvas 录屏dom快照数据量太大，导致浏览器卡死

**Comment by sunxu0429** [comment]
https://github.com/rrweb-io/rrweb/blob/master/docs/recipes/canvas.zh_CN.md

**Comment by Juice10** [comment]
If the default canvas recording doesn't work you could try the second example in the canvas docs:

```js
rrweb.record({
  emit(event) {},
  recordCanvas: true,
  sampling: {
    canvas: 15,
  },
});
```

Just an FYI, this is on master but hasn't been an official release for it yet. That'll happen soon enough.

**Comment by Juice10** [comment]
You could turn the sampling speed down (`canvas: 1`) which will give you less frames per second and less data. Or you can make sure you empty your events array periodically by sending the events to a server and saving them.

**Comment by sunxu0429** [comment]
I have set sampling speed to (`canvas:1`),but after several seconds the browser still crash. Well, maybe for the use of canvas to display the video in device camera in real time, recording screen cannot be performed through rrweb.

**Comment by sunxu0429** [comment]
It should be that dom snapshots increase sharply over time, resulting in memory overflow.

**Comment by sunxu0429** [comment]
After 10 seconds recoring, the events data is 232MB.That is too large for application.
![image](https://user-images.githubusercontent.com/34266586/167233714-9a81b16a-355a-48e7-a413-901f2224ebb4.png)

**Comment by Juice10** [comment]
Are you using master or rrweb 1.1.3?
1.1.3 doesn't take sampling in to account yet, and depending on your app the events might grow very heavily

**Comment by sunxu0429** [comment]
Aaha, i use  `npm install`  and it should be 1.1.3 which i used.
When will the new version be released?

**Comment by Juice10** [comment]
Earliest next week, but could be later
