### ISSUE TITLE
Page is crashing during recording due to processing elements that are missed in current document

### ISSUE THREAD

**Issue by dkozlovskyi** [rrweb-io/rrweb#890]
**Steps to reproduce:**
1. Start the rrweb recording process
2. In your main tab navigate to https://edition.cnn.com/travel/article/qantas-project-sunrise-worlds-longest-flights-intl-hnk/index.html
3. Open the page in the new tab by clicking on the link [was still a priority for Qantas](https://www.cnn.com/travel/article/qantas-world-longest-flight-suspended-coronavirus/index.html). Do not switch to newly opened tab.
4. Open the page in the new tab by clicking on the link [connecting Melbourne and Dallas](https://www.cnn.com/travel/article/qantas-dallas-melbourne-ultra-long-haul-flight/index.html). Do not switch to the newly opened tab.
5. In your main tab observe development console errors and page performance.

**Actual result:** The page hangs, and within a few navigations, it crashes. rrweb exceptions are an observer in dev. console. Error happening due to processing element that doesn't exist in the document.
**Expected result:** The performance should not be impacted. Logic should better detect cases where an element doesn't exist in the document.

**Comment by Mark-Fenng** [comment]
Thank you very much for the report. Your solution is correct. I didn't expect `rootShadowHost` to be `undefined`, because of the TS‘s type inference. Would you like to PR with a comment referenced to this Issue?

**Comment by dkozlovskyi** [comment]
Thanks for the quick reply. 
Sure, [here you go](https://github.com/rrweb-io/rrweb/pull/891)

**Comment by pavlogavryliuk** [comment]
@Mark-Fenng is it expected that rootShadowHost to be a string?

![image](https://user-images.githubusercontent.com/46223649/179203927-e43df4ca-9f46-419d-8f75-ce2cb20b29c6.png)

**Comment by Mark-Fenng** [comment]
@pavlogavryliuk No, it should be an element or null.

**Comment by pavlogavryliuk** [comment]
@Mark-Fenng hmm, i caught an issue, when rootShadowHost is string

![image](https://user-images.githubusercontent.com/46223649/179225688-ac9ab74c-a380-40ba-9bb5-c9ae8b30d6bc.png)

**Comment by Mark-Fenng** [comment]
That's ok, would you like to open a new issue and describe how to reproduce the bug?
