### ISSUE TITLE
移动端h5项目由于input输入内容时输入发弹起，导致回放是窗体总是改变大小，能控制么？

### ISSUE THREAD

**Issue by coder1379** [rrweb-io/rrweb#899]
当录制移动端项目时，用户点击输入框，弹起输入法，可以正常录制。
但是在回放时，用户在输入那部分窗体只能看见一般，由于弹起输入法改变了容器大小。
那么有办法在录制的时候不记录这种输入法相关的容器改变吗？
或者回放时是否有办法屏蔽或处理？

**Comment by Yuyz0112** [comment]
区分不了是否为输入法导致。可以把 resize 事件排除

**Comment by coder1379** [comment]
已解决，通过类型在回放前先移除resize相关内容就行。
例如：
events.filter(event => {
  return event.type !== 3 || event.data.source !== 4
});

**Comment by ywhniubi** [comment]
可以解决了我的问题
