### ISSUE TITLE
Please add a LICENSE

### ISSUE THREAD

**Issue by malucky** [rrweb-io/rrweb#9]
This is very cool! Please add a LICENSE

**Comment by Yuyz0112** [comment]
Sure, I selected MIT as the license when I init the `package.json`. Not sure what I need to do to finish the license related stuff, such as copy an MIT license file and add to the repo?

Any help is welcomed.

**Comment by snowkrebs** [comment]
Here are some guidelines from github:
https://help.github.com/articles/licensing-a-repository/#determining-the-location-of-your-license
