### ISSUE TITLE
[Proposal] Add a new option "sensitiveInputFields" that will make all inputs anonymized 

### ISSUE THREAD

**Issue by xavier-heysch** [rrweb-io/rrweb#90]
Hi ! 

Currently, we can only hide inputs content with the addition of a specific class (like specified in https://github.com/rrweb-io/rrweb/blob/master/guide.md#privacy).

My idea is to add a boolean option named "sensitiveInputFields" in the recorder, that will permits to hide the content of all inputs at once.

Moreover, we can add a class "rr-allow" to specify inputs that should be recorded even if sensitiveInputFields is set to true.

What do you think about this @Yuyz0112 ?

**Comment by Yuyz0112** [comment]
I think we already have this feature:
https://github.com/rrweb-io/rrweb/blob/master/src/record/index.ts#L28

Do not have time to update the guide these days.

**Comment by xavier-heysch** [comment]
Wow seriously? 
We just have to pass the "maskAllInputs" option in the recorder and we are good? 

Glad to know that we can customize the ignore class too !

**Comment by Yuyz0112** [comment]
@xavier-heysch So I think we can close this issue?
