### ISSUE TITLE
sampling: {canvas: 15}  导致生成多个虚拟机实例

### ISSUE THREAD

**Issue by qwe1177** [rrweb-io/rrweb#901]
![image](https://user-images.githubusercontent.com/14831316/169505508-54275c83-2702-4999-9095-6d4e19fafdbf.png)

我采用多实例模式，在同步的业务场景下会停止之前的实例重新生成一个新的，但是好像基于canvas的虚拟机实例不会销毁掉一直常驻内存导致内存泄露。有什么办法销毁掉这个canvas的实例。请看图片
const instance = rrweb.record({
  emit(event) {},
  recordCanvas: true,
  sampling: {
    canvas: 15,
  },
});

**Comment by qwe1177** [comment]
@Juice10 hi，帮忙看看

**Comment by qwe1177** [comment]
@Juice10 help…

**Comment by qwe1177** [comment]
打错字了，在不同的业务场景下

**Comment by Juice10** [comment]
@qwe1177 thanks for reporting this. Just to be sure we know exactly what is going on, what version of rrweb are you using?
This might be solved by fixing https://github.com/rrweb-io/rrweb/issues/883

**Comment by qwe1177** [comment]
@Juice10 用的是master最新版的. 
页面有一些charts图表， 在不设置抽样属性sampling: {canvas: 15}的情况下 没有图片中描述的多开虚拟机实例  但是回放的时候charts图表 乱糟糟的， 设置了抽样属性后 又有图片中描述的问题。

**Comment by qwe1177** [comment]
@Juice10 You can toggle creating a Record instance configured with sampling properties with two button actions, and now look at the javascript virtual machine instance

**Comment by qwe1177** [comment]
已解决，版本问题引起
