### ISSUE TITLE
[Bug]: rrweb is not reverting "crossorigin" attribute changes made to "img" elements

### ISSUE THREAD

**Issue by dkozlovskyi** [rrweb-io/rrweb#904]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/rrweb-io/rrweb/issues) for a bug report that matches the one I want to file, without success.

### What package is this bug report for?

rrweb

### Expected Behavior

rrweb sets the original "crossorigin" attribute value or removes it in case it was empty before the recording

### Actual Behavior

rrweb is referencing to the attribute in CamelCase ("crossOrigin"), as the result it can not preserve and revert the original value.

### Additional Information

**Steps to reproduce:**
1. Go to https://drive.google.com
2. Start recording
3. Check the broken thumbnails.

**Fix suggestion**
reference to the case-sensitive "crossorigin" attribute instead of "crossOrigin".

**Comment by Juice10** [comment]
Hi @dkozlovskyi, thanks for submitting the bug report!
I looked through drive and I could only find this element with crossorigin on it, is this the one you are having issues with?
<img width="533" alt="image" src="https://user-images.githubusercontent.com/4106/170989673-cd7dbc77-7f10-4f38-bf29-851053f1bc79.png">

I looked through the rrweb source code and noticed rrweb isn't changing any of the cases. As far as I know every attribute is automatically lowercased by the browser before it is returned. Example below:

```js
const el = document.createElement('div');
el.setAttribute('MYATTR', 'upcase?')
console.log(el.attributes[0].name) //=> 'myattr'
```

Could you share your `events.json` file so we can see what is going on?
