### ISSUE TITLE
[Bug]: The <use> element support

### ISSUE THREAD

**Issue by pavlogavryliuk** [rrweb-io/rrweb#907]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/rrweb-io/rrweb/issues) for a bug report that matches the one I want to file, without success.

### What package is this bug report for?

rrweb-snapshot

### Expected Behavior

The <use> element takes nodes from within the SVG document, and duplicates them somewhere else.

**Example:**
```
<svg viewBox="0 0 30 10" xmlns="http://www.w3.org/2000/svg">
  <circle id="myCircle" cx="5" cy="5" r="4" stroke="blue"/>
  <use href="#myCircle" x="10" fill="blue"/>
  <use href="#myCircle" x="20" fill="white" stroke="red"/>
</svg>
```

**href** - should not change to absolute path in this case.

### Actual Behavior

RRWeb transform this href attribute to absolute path:

```
 // relative path in attribute
  if (name === 'src' || (name === 'href' && value)) {
    return absoluteToDoc(doc, value);
  }
```

All <svg> elements with <use> is broken in replayer:

```
<use href="https://cas2.pipedrive.com/pipeline/1/user/everyone#icon-sm-cross" xlink:href="#icon-sm-cross"></use>
```

### Additional Information

I've add this changes localy to fix this.

```
// element should ignore href transform
if (tagName === 'use') {
  const element = n as HTMLImageElement;
  const href = element.getAttribute('href');
  if (href) {
    attributes.href = href;
  }
}
```

**Comment by lele0108** [comment]
@Yuyz0112 @Juice10 I have fixed this issue in #938
