### ISSUE TITLE
[Bug]: Safari iframe serialization errors

### ISSUE THREAD

**Issue by DomasB** [rrweb-io/rrweb#908]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/rrweb-io/rrweb/issues) for a bug report that matches the one I want to file, without success.

### What package is this bug report for?

rrweb-snapshot

### Expected Behavior

Rrweb should ignore iframes with different origin when serializing.

### Actual Behavior

Rrweb throws errors in console on Safari when serializing DOM with iframes.
![image](https://user-images.githubusercontent.com/3443371/171127061-d85cbc1c-311b-43aa-9586-bb8f1c8e540d.png)

### Additional Information

Block class cannot be added as iframes are created dynamically buy the libraries.
We are using Rrweb with Sentry integration.

**Comment by Mark-Fenng** [comment]
Similar to #892, this error only occurs on Safari when accessing iframe.conrentDocument. This error can't be try/catched and these errors don't have any influence on the recording process. I think just ignoring these errors is the easiest way.
