### ISSUE TITLE
一个页面运行多个record实例时，input输入事件似乎只会被某一个实例记录

### ISSUE THREAD

**Issue by hughfenghen** [rrweb-io/rrweb#91]
**背景**
我使用WEB RTC + rrweb做了一个类似“直播”[demo](https://github.com/hughfenghen/rtc-live-show)(这个demo可以复现问题)，允许多个用户看“直播”，所以在“房主”端需要需要运行多个recod实例，将记录的数据通过channel发送出去。
**现象**
当一个页面运行多个record实例时，input输入事件似乎只会被某一个实例记录。鼠标移动事件是正常的。
![](https://ws3.sinaimg.cn/large/005BYqpgly1g4ze1lqdu5g30m80dk7wh.jpg)

**Comment by Yuyz0112** [comment]
我抽时间会 debug 一下。不过从实现上来说，每个 audience 接入之后都新建一个 record 实例可能不是最好的方案。

感觉可以考虑“房主”这一侧本地缓存一下快照数据，一个新人接入之后把历史快照也都同步过去。当然这里面有不少优化的空间。

**Comment by Yuyz0112** [comment]
考虑更多功能的迭代依赖全局唯一的能力，不再建议一个页面使用多个 record
