### ISSUE TITLE
[Bug]: Getting this error "cannot read property on null (reading scrollTo)".

### ISSUE THREAD

**Issue by shanptl12** [rrweb-io/rrweb#916]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/rrweb-io/rrweb/issues) for a bug report that matches the one I want to file, without success.

### What package is this bug report for?

rrweb

### Expected Behavior

iFrame.contentWindow was returning null, hence was getting the error. 

` this.iframe.contentWindow!.scrollTo(
          (firstFullsnapshot as fullSnapshotEvent).data.initialOffset,
        );`

### Actual Behavior

Null Check should be added

### Additional Information

PR was created for the issue. 
PR: https://github.com/rrweb-io/rrweb/pull/915

**Comment by shantanup12** [comment]
> 

Did a mistake is writing the issue description. The expected and Actual behaviour are interchanged in the description

**Comment by Soulwail** [comment]
Is this bug fixed?

**Comment by Mark-Fenng** [comment]
This has been fixed by #915

**Comment by js199069** [comment]
![Screenshot from 2022-12-19 10-19-03](https://user-images.githubusercontent.com/11973814/208611162-3ed71a7b-70f3-47f6-a59a-9b6f122b8fea.png)

hi
we use rrweb player we get this error.i think its not fix
we use in reactjs  
how could we handle this error?
