### ISSUE TITLE
dynamic 样式处理疑问

### ISSUE THREAD

**Issue by moweng** [rrweb-io/rrweb#92]
![image](https://user-images.githubusercontent.com/8938428/61208285-a2e62400-a729-11e9-92cd-63f4dd892ca1.png)

//TODO: Currently we only try to get dynamic stylesheet when it is an empty style element
这里为什么需要是空标签的时候才处理呢，如果是空标签的话，这里还有处理的必要吗 @Yuyz0112

**Comment by Yuyz0112** [comment]
以为有 `CSSStyleSheet.insertRule` 这样的 DOM API 可以动态插入样式，很多 CSS in JS 工具使用了这个方式。
