### ISSUE TITLE
Failed to build, "Type 'string' is not assignable to type 'never'."

### ISSUE THREAD

**Issue by 1mehal** [rrweb-io/rrweb#94]
Hello guys,

I'm trying to build RRWeb, I never used TypeScript before, but during compile time I'm getting the following error:

```
src/replay/index.ts:91:7 - error TS2322: Type 'string | number | boolean | string[] | Element' is not assignable to type 'never'.
  Type 'string' is not assignable to type 'never'.

91       this.config[key] = config[key]!;
```

**Comment by Yuyz0112** [comment]
Hi @1mehal, how did you `build` rrweb?
`npm run bundle` looks fine for me.

**Comment by 1mehal** [comment]
@Yuyz0112 thank you for a quick answer! It works :) 
I was trying to use tsc
