### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by GitHubWesley** [rrweb-io/rrweb#948]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/rrweb-io/rrweb/issues) for a bug report that matches the one I want to file, without success.

### What package is this bug report for?

rrweb

### Expected Behavior

在使用过程中发现 rrweb 对于 rrweb.record() 开始录制后动态产生的 web component （custom element）可以正确录制

### Actual Behavior

在使用过程中发现 rrweb 对于 rrweb.record() 开始录制后动态产生的 web component （custom element）无法回放

**Comment by Yuyz0112** [comment]
Have you tried the rrweb@2.0.0-alpha.0

**Comment by Mark-Fenng** [comment]
I think PR #834 has fixed this problem.
