### ISSUE TITLE
mutationObserver 添加节点逻辑

### ISSUE THREAD

**Issue by moweng** [rrweb-io/rrweb#97]
@Yuyz0112 
![image](https://user-images.githubusercontent.com/8938428/61441308-eafa8600-a977-11e9-998f-a4625bed9388.png)
请问源码里面添加节点的逻辑是怎样的？moveSet 记录的是什么类型的节点，为什么需要记录 dropSet????

**Comment by Yuyz0112** [comment]
可以参考：https://github.com/rrweb-io/rrweb/blob/master/docs/observer.zh_CN.md#%E6%96%B0%E5%A2%9E%E8%8A%82%E7%82%B9

drop set 是记录了在一次 callback 中被添加又移除的节点，move set 记录的是移动的节点

**Comment by moweng** [comment]
@Yuyz0112 加个微信？添加节点这里还是有一些逻辑不明白，想请教下~

**Comment by moweng** [comment]
@Yuyz0112 
![image](https://user-images.githubusercontent.com/8938428/61456952-e5ae3300-a999-11e9-8974-6a9c587be5b0.png)

这个逻辑：
1、如果节点还没序列化，则加入带序列化的集合？
2、如果节点已经序列化，则加入移动节点集合？
为啥是这个处理逻辑哇
![image](https://user-images.githubusercontent.com/8938428/61457071-25751a80-a99a-11e9-927b-60224cdb5756.png)
但是移动节点为啥是直接pushAdd

**Comment by Yuyz0112** [comment]
可以邮件我
