### ISSUE TITLE
【literallyCanvas.js】 It doesn't work ，There are some warnings

### ISSUE THREAD

**Issue by liuzhilin123** [rrweb-io/rrweb#978]
![image](https://user-images.githubusercontent.com/23622612/186804941-0694e0fe-dd34-43b9-8478-2559cc318cd8.png)

record({
          emit(event) {
          },
          recordCanvas:true
        });

Replayer([], {
      liveMode: true,
      UNSAFE_replayCanvas:true
    });

**Comment by liuzhilin123** [comment]
@1.1.3 is ok

**Comment by liuzhilin123** [comment]
@1.1.3 is ok

**Comment by Juice10** [comment]
Can you share your events? Preferably in a gist with a rrwebdebug.com link?
