### ISSUE TITLE
[Bug]: Null Showing on the replay

### ISSUE THREAD

**Issue by tomcrofty** [rrweb-io/rrweb#979]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/rrweb-io/rrweb/issues) for a bug report that matches the one I want to file, without success.

### What package is this bug report for?

rrweb

### Version

v1.1.3

### Expected Behavior

Replay should look identical to recorded events

### Actual Behavior

Looks similar however "null" shows everywhere as text
![image](https://user-images.githubusercontent.com/28220951/186912246-373d1906-d6b3-4264-b445-f354fe41f086.png)

### Steps to Reproduce

Recording Code:
```js
rrwebRecord({
    emit(event) {
        // push event into the events array
        events.push(event);
    },
    sampling: {
        // do not record mouse movement
        mousemove: false,
        // do not record mouse interaction
        mouseInteraction: false,
        // set the interval of scrolling event
        scroll: 150, // do not emit twice in 150ms
        // set the interval of media interaction event
        media: 800,
        // set the timing of record input
        input: 'last', // When input mulitple characters, only record the final input
    },
    inlineStylesheet: true,
    blockSelector: 'link[href="https://use.fontawesome.com/ea731dcb6f.css"], style#fa-v4-font-face'
});
````

Replay Code:
```js
const events = {!! $data !!};

const replayer = new rrweb.Replayer(events, {
    root: document.getElementById("player"),
    data: {
        autoPlay: true,
    }
});

replayer.play();
```

### Testcase Gist URL

https://rrwebdebug.com/play/index.html?url=https%3A%2F%2Fgist.github.com%2Ftomcrofty%2F2cca6793752850d3d792e78d9d5ee5f0&version=1.0.0-alpha.1&play=on

### Additional Information

I've tried so many variations of the recording code which is clearly the culprit here, any ideas what I'm doing wrong? You can try the debug URL I posted to see the same result from the recording.

**Comment by tomcrofty** [comment]
Just done a bit more digging into this, after decoding the data stored in the DB, there's no reference to anything such as:
```
textContent: "null"
```
However, there's plenty of references to:
```
textContent: null
```
Which one would assume would mean that when recreating the page based on the events would not output "null" as text. It seems to be placed before and after every element almost behaving like a psuedo element.

**Comment by tomcrofty** [comment]
Interestingly when replacing all ocurrences of:
```
textContent: null
```
with:
```
textContent: ""
```
All the issues go away, for now that's my temporary solution but it's obviously not too ideal

**Comment by tomcrofty** [comment]
![image](https://user-images.githubusercontent.com/28220951/186915780-bf78e09a-d82a-4490-a5ce-dde6f243e59e.png)

**Comment by stevenmyhre** [comment]
I also had to hack the nulls away.

**Comment by Yuyz0112** [comment]
Could you check your backend/transport layer? Looks like that parts add null to undefined fields instead of omitting it.

**Comment by stevenmyhre** [comment]
Before it even hits the server the payload contains empty textContent:

Payload of events returned from .record callback:
```
{"type":5,"textContent":"","rootId":2222,"id":2822},{"type":3,"textContent":" ","rootId":2222,"id":2823},{"type":2,"tagName":"hr","attributes":{},"childN...
```
