### ISSUE TITLE
Cannot read property '__sn' of null

### ISSUE THREAD

**Issue by mewwind** [rrweb-io/rrweb#98]
目前碰到小概率会抛出 `Cannot read property '__sn' of null`的错误
然后从错误堆栈中定位如下
```javascript
getId(n) {
    if (!n.__sn) {
      return -1;
    }
    return n.__sn.id;
  },
-----------------------
const pushAdd = (n: Node) => {
      const parentId = mirror.getId((n.parentNode as Node) as INode);
-----------------------
Array.from(movedSet).forEach(pushAdd);
```
当```pushAdd```中调用```getId```时，这里的n.parentNode是否可能为null，若为null，则getId就会抛出如标题所示的错误。

**Comment by Yuyz0112** [comment]
可以提供一段能复现这个 bug 的 events 数据吗？因为按说新添加的节点不应该没有 parent node

**Comment by Yuyz0112** [comment]
Please feel free to reopen this with any further debug info.

**Comment by IMFIL** [comment]
@Yuyz0112 this is still relevant. Here is a picture with from version 1.31. 
<img width="456" alt="Screen Shot 2020-04-17 at 3 13 34 PM" src="https://user-images.githubusercontent.com/16093847/79605491-038dfd00-80be-11ea-823b-c3f61baee440.png">

I will post a PR to solve it. Do you think you can post a new version to NPM with the pr with the fix ?
