### ISSUE TITLE
[Bug]: Recordings don't render a scroll that doesn't happen on the body. 

### ISSUE THREAD

**Issue by isaiahdahl** [rrweb-io/rrweb#980]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/rrweb-io/rrweb/issues) for a bug report that matches the one I want to file, without success.

### What package is this bug report for?

rrweb

### Version

v1.1.3

### Expected Behavior

My issue initially starts here https://github.com/PostHog/posthog/issues/10021

I'm not sure exactly how to recreate this in this repo for a good issue here so If I could get some feedback on how I could show my error better that'd be appreciated.

From what I can gather using tools that are using this tool. I'm expecting that the screen recording will record my interactions with the website.

### Actual Behavior

If I do a screen recording where i browse this website https://www.praisecharts.com/ 

It wont record any of my scrolling because it's an ionic app which does all the scrolling in an ion-content element.

### Additional Information

I'm pretty sure it's gotta be connected to shadow dom somehow.

If there are steps I can take to better reproduce this issue here, I will gladly do that. Just don't know where to start.

**Comment by wfk007** [comment]
It is caused by that the scrolling into a web-component shadow root can't be captured by `document.addEventListener('scroll')`
@isaiahdahl you can write a rrweb record plugin to listen to the `mousewheel` event and refer to the achievement of **initScrollObserver** in rrweb record

**Comment by Mark-Fenng** [comment]
I confirmed that this bug has been fixed since v2.0.0-alpha.3.
