### ISSUE TITLE
[Bug]: replayer.addEvent(event) 无效，可以帮忙看下吗

### ISSUE THREAD

**Issue by Emmpty** [rrweb-io/rrweb#982]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/rrweb-io/rrweb/issues) for a bug report that matches the one I want to file, without success.

### What package is this bug report for?

rrweb

### Version

2.0.0

### Expected Behavior

`

    rrweb.record({
            emit(event) {
                console.log('>>>>>>>>>>>>>>>send', ws.readyState, event);
                if (timeConnect >= 20) return
                if (ws.readyState !== 1) {
                    return reconnect(wsUrl, event);
                }
               // 发送单个event
                ws.send(JSON.stringify(event))
            }
    })
`
` 

        // 使用直播模式
        const replayer = new rrweb.Replayer([], {
            liveMode: true
        })
        replayer.enableInteract();
        replayer.startLive(500)
       // websocket接收回放日志
        ws.onmessage = (event) => {
            const message = JSON.parse(event.data);
            replayer.addEvent(message);
        };
`

### Actual Behavior

**使用websocket去传输event**

在onmessage里取调用  replayer.addEvent(event) 

但是回放页面只在左上角显示了一个鼠标  没其他反应了

### Steps to Reproduce

初始化时报了这个错误：Blocked script execution in 'about:blank' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.

**Comment by jiangyanghe** [comment]
同样的问题 怎么解决的？

**Comment by pittQ** [comment]
同样的问题 怎么解决的？

**Comment by naihe138** [comment]
同样的问题 怎么解决的？
