### ISSUE TITLE
observer.observe target 设置为 document 会导致浏览器崩溃

### ISSUE THREAD

**Issue by betweens** [rrweb-io/rrweb#99]
rrweb 接入 我们react 项目 发现 在 componentDidMount 执行后监听器回调不停的执行导致浏览器死机，阅读代码返现 监听器 坚挺documen 我改为 documen.body就可以了，具体什么原因暂时还不清楚

**Comment by Yuyz0112** [comment]
有最小化复现的代码可以试一下吗？

**Comment by betweens** [comment]
我用create-react-app创建一个简单的react 项目不会导致浏览器崩溃 因为我们的项目以来我们公司内部的架构 代码比较复杂， 以为公司内部安全问题不便展示出来，具体什么原因 我也在排查，麻烦你们有空也帮忙看下，非常感谢！💕💕💕

**Comment by betweens** [comment]
对了 或者 你在 打开这个链接 https://m.lu.com/user/login 在控制台直接监听ducoment 就会出现这个问题，貌似现在让你们帮我好问题，这个你看有空看看，非常感谢啦
