### ISSUE TITLE
replayer.enableInteract()无效，大佬可以帮忙解答下吗

### ISSUE THREAD

**Issue by Emmpty** [rrweb-io/rrweb#996]
我在直播模式下回放都正常  canvas回放也正常   就是在对端无法进行交互，可否解答一下吗？ 谢谢

**Comment by Emmpty** [comment]
`

        this.replayer = new rrweb.Replayer([], {
            root: document.getElementById('syncit-box'),
            liveMode: true,
            loadTimeout: 100,
            showWarning: true,
            showDebug: true,
            mouseTail: false,
            UNSAFE_replayCanvas: true
        })
        this.replayer.enableInteract()
        var FIRST_EVENT = true
        this.ws.onmessage = (event) => {
            const message = JSON.parse(event.data);
            console.log('>>>>>>>>>>>>>>>>>>>>>message', message);
            if (FIRST_EVENT) {
                this.replayer.startLive(message.timestamp - 1200)
                FIRST_EVENT = false
            }
            this.replayer.addEvent(message);
        };


`

**Comment by Emmpty** [comment]
对端中能看到hover事件可以生效，但是点击事件并没有生效。

**Comment by Yuyz0112** [comment]
使用的版本是？

**Comment by Emmpty** [comment]
> 使用的版本是？

- **使用版本**

> "rrweb": "^2.0.0-alpha.1",
> "rrweb-player": "^1.0.0-alpha.1",

- **问题描述**

> 我在对端控制台打印操作事件，貌似在对端中的操作没能回传到源端。是我初始化有误吗

- **初始化代码**

```ruby
  import * as rrweb from 'rrweb'
  import 'rrweb/dist/rrweb.min.css'
  
  const rrwebObj = {
    wsUrl: 'ws://101.132.112.36:8080/scrs-admin/websocket1/',
    paramsUrl: '',
    ws: '',
    limitConnect: 20,
    timeConnect: 0,
    replayer: '',
    stopRecord: '',

    webSocketInit(paramsUrl) {
        let url = this.wsUrl + paramsUrl
        this.paramsUrl = paramsUrl
        this.ws = new WebSocket(url);
        this.ws.onopen = () => {
            console.log("已连接TCP服务器")
        };
        this.ws.onclose = (e) => {
            console.log('服务器已经断开', e.code + ' ' + e.reason + ' ' + e.wasClean)
            this.reconnect(paramsUrl);
        };
        return this.ws
    },

    reconnect(url, params) {
        // lockReconnect加锁，防止onclose、onerror两次重连
        if (this.limitConnect > 0) {
            this.limitConnect--;
            this.timeConnect++;
            console.log("第" + this.timeConnect + "次重连");
            // 进行重连
            this.webSocketInit(url);
            setTimeout(() => {
                if (this.timeConnect >= 20) return
                if (this.ws.readyState !== 1) {
                    return
                }
                this.ws.send(JSON.stringify(params))
            }, 2000);
        } else {
            console.log("TCP连接已超时");
        }
    },

    // 开始录屏
    crateWeb() {
        let that = this
        const stopRecord = rrweb.record({
            emit(event) {
                console.log('>>>>>>>>>>>>>>>send', that.ws.readyState, event);
                if (that.timeConnect >= 20) return
                if (that.ws.readyState !== 1) {
                    return that.reconnect(that.paramsUrl, event);
                }
                that.ws.send(JSON.stringify(event))
            },
            inlineStylesheet: false,
            recordCanvas: true,
        })
        return stopRecord
    },

    // 回放
    async playback() {
        this.replayer = await new rrweb.Replayer([], {
            root: document.getElementById('syncit-box'),
            liveMode: true,
            loadTimeout: 100,
            showWarning: true,
            showDebug: true,
            mouseTail: false,
            UNSAFE_replayCanvas: true,
        })
        this.replayer.enableInteract()
        var FIRST_EVENT = true
        this.ws.onmessage = (event) => {
            const message = JSON.parse(event.data);
            console.log('>>>>>>>>>>>>>>>>>>>>>message', message);
            if (FIRST_EVENT) {
                this.replayer.startLive(message.timestamp - 1200)
                FIRST_EVENT = false
            }
            this.replayer.addEvent(message);
        };
        return this.replayer
    },
}

 export {
    rrwebObj
 }

```

- 源端代码

```ruby
     await rrwebObj.webSocketInit('222')
     this.stopRecord = rrwebObj.crateWeb()
```

- 对端代码
```ruby
      await rrwebObj.webSocketInit("222");
      this.replayer = rrwebObj.playback();
```

> 就非常苦恼，使用syncit的话，有独有的链接操作ui，但是他所依赖的rrweb版本太低不支持canvas回放。

> 用rrweb的话、canvas能正常回放了，但是replayer.enableInteract()后，是能看到有hover效果，远程控制不知为何失效了。
大佬help help me~~~~~

**Comment by Yuyz0112** [comment]
先看一下对一段已有 events 进行回放（不是实时），enableInteraction 是否正常？

**Comment by Emmpty** [comment]
> 先看一下对一段已有 events 进行回放（不是实时），enableInteraction 是否正常？

好的，我试试

**Comment by wfk007** [comment]
@Emmpty 你这 `webSocketInit` 实现的也有问题吧，返回的不是 Promise，源端和对端代码 await 了个寂寞，也就是说，ws 可能还没 open 的时候，已经开始录制和回放了

**Comment by Emmpty** [comment]
> @Emmpty 你这 `webSocketInit` 实现的也有问题吧，返回的不是 Promise，源端和对端代码 await 了个寂寞，也就是说，ws 可能还没 open 的时候，已经开始录制和回放了

这是个问题  后面我看下怎么优化吧，回放端的操作要同步回录制端才是大问题

**Comment by Emmpty** [comment]
> 先看一下对一段已有 events 进行回放（不是实时），enableInteraction 是否正常？

没效果   如果是对一段已有的events回放，这个仅仅是回放吧？并不能远程操控吧，远程操控的事件通过什么方式回传到源端呢

**Comment by Emmpty** [comment]
方便的话可以加你吗？  有偿解决、这个问题困扰我一周了.....

**Comment by wfk007** [comment]
> > @Emmpty 你这 `webSocketInit` 实现的也有问题吧，返回的不是 Promise，源端和对端代码 await 了个寂寞，也就是说，ws 可能还没 open 的时候，已经开始录制和回放了
> 
> 这是个问题 后面我看下怎么优化吧，回放端的操作要同步回录制端才是大问题

你希望在回放的时候开启 enableInteract，然后一顿操作后，可以把操作同步到录制端？

**Comment by Emmpty** [comment]
> > > @Emmpty 你这 `webSocketInit` 实现的也有问题吧，返回的不是 Promise，源端和对端代码 await 了个寂寞，也就是说，ws 可能还没 open 的时候，已经开始录制和回放了
> > 
> > 
> > 这是个问题 后面我看下怎么优化吧，回放端的操作要同步回录制端才是大问题
> 
> 你希望在回放的时候开启 enableInteract，然后一顿操作后，可以把操作同步到录制端？

> 对的， 就是像作者写的syncit一样（可以在回放端远程操作）， 但是缺了canvas回放的功能。

**Comment by wfk007** [comment]
@Emmpty 你这种写法，录制端肯定无法同步到回放端 enableInteract 后的操作
1. 回放端应该只有 replay，没有 record，enableInteract 后的操作不会产生 Mutation，更不可能通过 ws 把消息同步到录制端
2. 录制端应该只是纯 record，没有 replay，首先接收不到 Mutation，其次，即使接受到了，因为没有 replay 环境，也无法 applyIncremental

enableInteract 只是更新 replay iframe 的样式而已
```js
this.iframe.setAttribute('scrolling', 'auto');
this.iframe.style.pointerEvents = 'auto';
```

**Comment by Emmpty** [comment]
> @Emmpty 你这种写法，录制端肯定无法同步到回放端 enableInteract 后的操作
> 
> 1. 回放端应该只有 replay，没有 record，enableInteract 后的操作不会产生 Mutation，更不可能通过 ws 把消息同步到录制端
> 2. 录制端应该只是纯 record，没有 replay，首先接收不到 Mutation，其次，即使接受到了，因为没有 replay 环境，也无法 applyIncremental
> 
> enableInteract 只是更新 replay iframe 的样式而已
> 
> ```js
> this.iframe.setAttribute('scrolling', 'auto');
> this.iframe.style.pointerEvents = 'auto';
> ```

> 是呀~~我感觉一直没有形成闭环，我看文档中使用场景---回放时与 UI 交互----里说的以为这样开了就能实现两端同步了。
那现在需要怎么改才能实现类似syncit的远程控制的功能呢~~~我太菜了。看不懂syncit源码

**Comment by Emmpty** [comment]
> 先看一下对一段已有 events 进行回放（不是实时），enableInteraction 是否正常？

> 能不能让回放端的canvas，每隔一秒转成图片的形式去做展示呢？

**Comment by Emmpty** [comment]
> 嗯，enableInteraction 的作用只是允许和 iframe 做交互，具体的同步逻辑可以参考 syncit 的代码、文档和介绍视频。

> 这边改用回syncit了 ， 在canvas  mouseUp的时候将canvas转成图片在传过去就可以显示了。非常感谢大家的帮助
