### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by rishabh-soc** [rrweb-io/rrweb#997]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/rrweb-io/rrweb/issues) for a bug report that matches the one I want to file, without success.

### What package is this bug report for?

rrweb

### Version

v1.0.0.

### Expected Behavior

blockclass should replace pre content with the black block.

### Actual Behavior

blockclass is only replacing the non pre content with the black block.

### Steps to Reproduce

By simply adding pre tag in child node of rr-block element.

**Comment by wfk007** [comment]
@rishabh-soc Is the following case? but I can't reproduce your case after trying rrweb@1.0.0

```js
<div class="rr-block">
    <div>div tset</div>
    <pre>pre test</pre>
</div>
```
