### ISSUE TITLE
[Feature Request]: Publish ESM on CDN

### ISSUE THREAD

**Issue by otakustay** [rrweb-io/rrweb#999]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/rrweb-io/rrweb/issues) for a feature request that matches the one I want to file, without success.

### What package is this feature request for?

rrweb

### Problem Description

For pages that asynchronously install rrweb recorder, we currently use `createElement('script')` and `script.onload` to lazy import `rrweb-record.min.js`, but it will be more confortable if we can simply use `await import('rrweb-record.esm.js')`.

### Proposed Solution

Build and publish bundled ESM modules alongside current `dist`

### Alternatives Considered

Using `createElement('script')` works but is a little complicated

**Comment by Mark-Fenng** [comment]
Is this jsDelivr link your wanted feature?
https://www.jsdelivr.com/package/npm/rrweb?path=es%2Frrweb%2Fpackages%2Frrweb%2Fsrc%2Frecord

**Comment by otakustay** [comment]
Since these es files seems to be generated directly from ts files, I'm not sure if they will include some new language features that not work on older (but still supports ESM) browsers, maybe a bundled version can be better

**Comment by Mark-Fenng** [comment]
They are actually bundled with rollup. You can see the bundling configuration here: https://github.com/rrweb-io/rrweb/blob/master/packages/rrweb/rollup.config.js

**Comment by otakustay** [comment]
I still see some `import` statements in [src/record/index.js](https://cdn.jsdelivr.net/npm/rrweb@2.0.0-alpha.1/es/rrweb/packages/rrweb/src/record/index.js), would it be possible that the ES version is exactly like the single file [dist version](https://cdn.jsdelivr.net/npm/rrweb@2.0.0-alpha.1/dist/rrweb.min.js), elliminating multiple network requests?

**Comment by Mark-Fenng** [comment]
I think it's possible but we don't have enough time to create a separate config for this situation.

**Comment by otakustay** [comment]
I'm going to try to create a PR for this

**Comment by Juice10** [comment]
I believe this PR might fix it: https://github.com/rrweb-io/rrweb/pull/1033
It's not finished yet but includes esm in release
